UGENE-6799 Task member becomes invalid during the task execution
ugeneunipro/ugene pull request #101
Opened 2020-05-22 10:58 UTC by DmitriiSukhomlinov

2020-05-22 11:42 UTC, atiunov requested changes

2020-05-22 11:42 UTC, atiunov commented on src/plugins/workflow_designer/src/WorkflowSceneIOTasks.cpp
> +    CHECK(scene != nullptr, ReportResult_Finished);
"scene" pointer should be QPointer to be nullified on the WD closing.

2020-05-22 11:42 UTC, atiunov commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +        ts->cancelTask(loadWorkflowSceneTask);
You can just use Task::cancel() here.

2020-05-22 14:00 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/WorkflowSceneIOTasks.cpp
> +    CHECK(scene != nullptr, ReportResult_Finished);
Поправил

2020-05-22 14:00 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +        ts->cancelTask(loadWorkflowSceneTask);
Fixed

2020-05-25 08:05 UTC, atiunov approved these changes

2020-05-25 08:06 UTC, merged