Fix and improve tests
ugeneunipro/ugene pull request #1051
Opened 2022-12-30 10:56 UTC by EvelinaBiserova

https://github.com/ugeneunipro/ugene/pull/1026#issuecomment-1333164939

2023-01-01 23:09 UTC, yalgaer commented on src/plugins/CoreTests/src/CMDLineTests.cpp
> +    if (hasError()) {
nit: use CHECK() for boilerplate code

2023-01-01 23:13 UTC, yalgaer submitted a review, later dismissed

2023-01-01 23:13 UTC, yalgaer commented on src/plugins/GUITestBase/src/runnables/ugene/plugins/external_tools/BlastDbCmdDialogFiller.cpp
> +    using namespace HI;
nit: move to the upper level. Otherwise you have to repeat it in almost every method in tests

2023-01-01 23:24 UTC, yalgaer requested changes
Please make sure that the fixed tests runs on Windows within 1 minute (but not 3:50)

2023-01-02 10:37 UTC, EvelinaBiserova commented
> Please make sure that the fixed tests runs on Windows within 1 minute (but not 3:50)

How to fix it?

2023-01-10 02:12 UTC, yalgaer commented
> > Please make sure that the fixed tests runs on Windows within 1 minute (but not 3:50)
> 
> How to fix it?

Can we reduce the analyzed data size and still be able to reproduce the issue?

2023-01-13 17:48 UTC, yalgaer commented
Closing as not active. Please reopen with an update

2023-01-13 17:48 UTC, closed without merging