UGENE-7808 update translation
ugeneunipro/ugene pull request #1155
Opened 2023-02-21 05:43 UTC by smlnkcv

2023-02-25 21:55 UTC, yalgaer requested changes

2023-02-25 21:55 UTC, yalgaer commented on src/ugeneui/transl/russian.ts
> +        <translation>Шаблон поиска слишком длинный.  Он будет урезан до 1000 символов.</translation>
Use 1 space, not too after the dot

2023-02-25 21:55 UTC, yalgaer commented on src/ugeneui/transl/russian.ts
> +        <translation type="vanished">Not enough resources for load document, resource name: &apos;%1&apos; available: %2%3 requested: %4%3</translation>
Why do we have 'vanished' in the fixed version. If the translation is vanished it should be removed, right?

2023-02-25 21:55 UTC, yalgaer commented on src/corelibs/U2View/transl/russian.ts
> +        <translation type="vanished">Цвет</translation>
If translation is vanished it should be removed

2023-02-25 21:55 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/sequence_info/SequenceInfo.cpp
> -static const char* CAPTION_SEQ_GC_CONTENT = QT_TR_NOOP("GC content");
What was the reason of moving these constants to the header file?

2023-02-27 07:57 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/sequence_info/SequenceInfo.cpp
> -static const char* CAPTION_SEQ_GC_CONTENT = QT_TR_NOOP("GC content");
Почему константы были перемещены:
Для того, чтобы переменная была транслирована, она должна быть ассоциирована с классом, отнаследованным от QObject. Эти переменные находятся вне класса и поэтому в текущем состоянии не могут быть транслированы.

Почему оно работало раньше:
Точно не могу сказать, веротяно благодаря тому, что трансляция была сделана еще в тот момент, когда эти переменные были разбиты на .h/.cpp файлы. Впоследствии их слили в один файл, но файл с трансляциями остался прежним, поэтому трансляция каким-то образом подтянутась. Тут же пришлось сделать lupdate, он обновил трансляции и отвязал их от переменных, которые на данный момент находятся вне класс.

Можно ли оставить в cpp:
Думаю да, если использовать `QT_TRANSLATE_NOOP`

2023-02-27 16:05 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/sequence_info/SequenceInfo.cpp
> -static const char* CAPTION_SEQ_GC_CONTENT = QT_TR_NOOP("GC content");
The constants should stay in C++, otherwise it looks like a workaround for the problem that has several known correct solutions.

2023-02-27 16:08 UTC, yalgaer commented on src/corelibs/U2View/transl/russian.ts
> +        <translation type="vanished">Цвет</translation>
> If translation is vanished it should be removed

Resolving as we agree that is not related to your patch.

2023-02-27 16:10 UTC, yalgaer requested changes
Please fix the remaining issues. No need to deal with 'vanish'

2023-02-28 23:21 UTC, yalgaer commented
Closing as inactive.
I reworked this PR here: https://github.com/ugeneunipro/ugene/pull/1161/files
Please check how a simple translation PR should look like
1) No vanished elements
2) No unfinished elements
3) No changes in C++ code unless you are sure.

2023-02-28 23:21 UTC, closed without merging