UGENE-7852 Codons show/hide behaves incorrect
ugeneunipro/ugene pull request #1219
Opened 2023-04-17 13:37 UTC by rasputinkirill

По неизвестным мне причинам, на 609 строке, при повторном открытии вкладки `isVisible()` всегда возвращает `false`. Очень долго с этой проблемой разбирался. Я пробовал модифицировать `ShowHideSubgroupWidget` вставлял `setVisible` в методы `void setSubgroupOpened(bool open);` и `void updateSubgroupState(bool isSubgroupOpened);` это не помогло. Пытался добавить `eventFilter` в этот же класс чтобы понять кто скрывает этот виджет, тоже не помогло.
В итоге заменил на эквивалент `activeContext->getAlphabet()->isNucleic()`.

2023-04-17 19:16 UTC, yalgaer requested changes
см комментарий выше.

2023-04-17 19:16 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/sequence_info/SequenceInfo.cpp
> +    getCodonsOccurrenceCache()->sl_invalidate();
Это решение неверное и вот почему:

1) У нас есть кеш с информацией для какого-то секвенса. Этот кеш содержит последнее состояние и пересчитывает его только если последовательность изменилась.

2) У нас есть виджет, который показывает информацию из кеша. В тот момент когда состояние последовательности меняется этот виджет должен запрашивать данные из кеша заново и кеш вернет пересчитанное состояние

Сам виджет менять состояние кеша не должен вовсе (вызывать invalidate) - только запрашивать текущее.

2023-04-19 22:45 UTC, rasputinkirill commented on src/corelibs/U2View/src/ov_sequence/sequence_info/SequenceInfo.cpp
> +    getCodonsOccurrenceCache()->sl_invalidate();
переделал

2023-04-20 16:18 UTC, yalgaer commented
В виджете осталось много мест типа
```
getCodonsOccurrenceCache()->sl_invalidate();
```
Правильно ли я понимаю, что все эти места теперь можно убрать?
Виджет должен слушать сигнал от кеша, что состояние изменилось и перерисовываться, но не инвалидировать кеш самостоятельно.

2023-04-20 16:19 UTC, yalgaer reviewed
см. комментарий про инвалидацию кеша из виджета.

2023-04-21 02:47 UTC, rasputinkirill commented
Если перенести всю инвалидацию кеша в SequenceObjectContext, то получится что кеш инвалидируется по сигналам в этом классе, а пересчет происходит в SequenceInfo по тем же сигналам. Это может спровоцировать гонку данных когда сигнал на пересчет запустил слот вперед слота который инвалидирует кеш. Можно рассмотреть вариант переделки механизма работы SequenceInfo, что пересчет срабатывает только после сигналов от SequenceObjectContext который будет испускаться после инвалидации каждого из четырех кешей. Если считаешь целесообразно так переделывать то я могу попробовать. Либо предложи свой вариант.

Мое мнение, что этот виджет статистики при текущей реализации выполняет свои функции, не имеет проблем с производительностью и делать рефакторинг ради рефакторинга не нужно, с учетом уже затраченного времени на эту задачу. Но решение за тобой, если хочешь, я готов доделать\переделать.

2023-04-21 09:39 UTC, yalgaer commented
> Это может спровоцировать гонку данных когда сигнал на пересчет запустил слот вперед слота который инвалидирует кеш

То есть порядок сигналов будет таким
1) Изменяется последовательность
2) Вызывается инвалидация кеша
3) В конце инвалидации кеша посылается сигнал - кеш изменен
4) Виджеты статистики получают этот сигнал и инициируют отрисовку новых значений
5) Для отрисовки новых значений они просят данные у кеша
6) Кеш считает новые значения

"Гонки" тут не будет, если  в шаге 6 не делать расчет а только запланировать его: запустить таск и следить что существует только 1 такой таск.

Но я согласна что это все уже вырождается в отдельную большую задачу. Текущий код кеша пассивен (не имеет контроллер части) - и это надо доделывать.

Я заапрувлю текущее решение без изменений как пройдут все тесты. 

На описанное же выше, если хочешь, заведи новую задачу: Виджеты не должны управлять кешем так как виджетов может быть много, а кеш один.

2023-04-24 15:26 UTC, yalgaer approved these changes

2023-04-24 17:17 UTC, merged