UGENE-7567 Deleted tool MAAFT is used when reinstalling UGENE
ugeneunipro/ugene pull request #1233
Opened 2023-04-27 02:36 UTC by rasputinkirill

Я сделал упрощение, для того чтобы не заморачиваться со сложным парсингом ключа в ini файле что путь в ключе присутствует если присутствует и версия. Для решения текущей проблемы с путями до внешних инструментах это подходит, у них у всех параметров есть версионность.

2023-04-27 22:48 UTC, yalgaer requested changes
Небольшие замечания.

2023-04-27 22:48 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +QString SettingsImpl::UGENE_WORKING_DIR_PATH = "";
Не нужно дублировать существующий функционал QT:  QCoreApplication::applicationDirPath() и так доступен везде.

2023-04-27 22:48 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/Settings.h
> +     * all path-specific values must use versioneedValue = true and bool pathValue = true
nit: документацию методов начинай с глагола и заглавной буквы.
В слове versioneedValue исправь опечатку

2023-04-27 22:48 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +        if (pathValue) {
nit: используй оператор ?
nit: переиспользуй переменную `key`

2023-04-27 22:48 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +
Добавь SAFE_POINT что versioned = true если pathValue true

2023-04-27 22:48 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +void SettingsImpl::setValue(const QString& pathName, const QVariant& value, bool versionedValue, bool pathValue) {
Добавь SAFE_POINT

2023-04-27 22:48 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +             desiredKey = toVersionKey(key) + "/" + UGENE_WORKING_DIR_PATH;
Используй toPathKey?

2023-04-27 22:48 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +    return key + PATH_KEY_SUFFIX + (key.endsWith("/") ? "/" : "");
Использовать путь в чистом виде небезопасно тк key это тоже путь. Замени реальный путь до UGENE на MD4 hash. Для этого сделай getter метод где этот MD4 хеш вычисляется 1 раз после старта UGENE и кешируется в локальный статик.

2023-05-03 08:26 UTC, rasputinkirill commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +        if (pathValue) {
`key` и `desiredKey` разные вещи, переименовал их

2023-05-03 10:38 UTC, rasputinkirill commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +    return key + PATH_KEY_SUFFIX + (key.endsWith("/") ? "/" : "");
Оставил эту же переменную для хеш-суммы UGENE_WORKING_DIR_PATH

2023-05-03 11:34 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +    static QString PATH_KEY_SUFFIX = "/" + UGENE_WORKING_DIR_PATH_MD4;
UGENE_WORKING_DIR_PATH_MD4 используется только здесь. Не надо заводить для этого дополнительную переменную со сложным циклом инициализации.

2023-05-03 11:35 UTC, yalgaer requested changes
см. комментарий про UGENE_WORKING_DIR_PATH_MD4

2023-05-03 15:04 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +static const QString UGENE_WORKING_DIR_PATH_MD4 = QString(QCryptographicHash::hash(QCoreApplication::applicationDirPath().toUtf8(), QCryptographicHash::Md4).toHex());
Это неправильное решение: статика может запуститься до запуска QT приложения.
Встрой расчёт хеша прямо в эту строку: 
```
static QString PATH_KEY_SUFFIX = "/" + UGENE_WORKING_DIR_PATH_MD4;
```

Она все равно больше нигде не используется.

2023-05-03 15:05 UTC, yalgaer requested changes
см комментарий про UGENE_WORKING_DIR_PATH_MD4

2023-05-03 15:35 UTC, rasputinkirill commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +static const QString UGENE_WORKING_DIR_PATH_MD4 = QString(QCryptographicHash::hash(QCoreApplication::applicationDirPath().toUtf8(), QCryptographicHash::Md4).toHex());
Глобальные статические переменные инициализируются на старте приложения, все должно быть нормально. Засовывать вычисление этого константного хеша в метод которыей более 50 раз точно вызывается думаю нецелесообразно. Может создать вложенный класс-синглтон (вроде так пойдет) да и все, если ты не веришь в статическую переменную.

2023-05-03 15:41 UTC, yalgaer commented on src/corelibs/U2Private/src/SettingsImpl.cpp
> +static const QString UGENE_WORKING_DIR_PATH_MD4 = QString(QCryptographicHash::hash(QCoreApplication::applicationDirPath().toUtf8(), QCryptographicHash::Md4).toHex());
У тебя же написано `static` (локальный статик) - о каких 50 раз речь?

2023-05-03 21:10 UTC, yalgaer commented
Все нормально. Жду прохождения тестов и апрувлю

2023-05-06 19:50 UTC, yalgaer approved these changes

2023-05-06 19:50 UTC, merged