UGENE-7853 SAFE_POINT in Import Primers dialog
ugeneunipro/ugene pull request #1235
Opened 2023-04-28 07:15 UTC by DmitriiSukhomlinov

2023-04-30 12:55 UTC, yalgaer requested changes

2023-04-30 12:55 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +            CHECK_SET_ERR(!GTWidget::findWidget(os, "pbAddObject")->isEnabled(), "Add object(s) shoud be disabled'");
nit: shoud -> should

2023-04-30 12:55 UTC, yalgaer commented on src/plugins/pcr/src/import/ImportPrimersDialog.cpp
> +    pbAddObject->setEnabled(AppContext::getProject() != nullptr);
project can be added dynamically when the dialog is active (if there is a pending load-file task). The complete solution is to add a project listener and dynamically enable/disable this button (I won't ask about GUI test for this).

2023-05-02 06:42 UTC, DmitriiSukhomlinov commented on src/plugins/pcr/src/import/ImportPrimersDialog.cpp
> +    pbAddObject->setEnabled(AppContext::getProject() != nullptr);
Это практически нереально. Я бы даже сказал - абсолютно нереально.

Во первых, нужно понимать, что добавление проекта и загрузка документа - это два разных процесса. Когда ты загружаешь файл (это действие и вправду может оказаться долгим), проект уже давно существует. Поэтому, если ты нажмешь кнопку "Импорт праймеров" в процессе парсинга файла, то кнопка "Add object(s)" уже будет активна и будет права - проект создался уже давно. А для того, чтобы возникла описанная тобой проблема, нажать "Импорт праймеров" нужно до создания проекта.

Во вторых, проект создается с помощью таски "Enable Project", которая даже не имеет `run()` части (настолько быстрая) - а значит, она полностью исполняется в главном потоке за один прогон функции `TaskSchedulerImpl::update()`. А теперь смотрим внимательно:

1. Когда ты открываешь файл, на ближайшем прогоне функции `TaskSchedulerImpl::update()` создается таска `Enable Project`, которая добавляется в очередь.
2. Эта таска полностью исполняется и создает проект на следующем прогоне `TaskSchedulerImpl::update()`. После его завершения проект создан.
3. `TaskSchedulerImpl::update()` - это функция, вызываемая по таймеру каждые 100 миллисекунд.

Таким образом, нужно нажать на кнопку "Импорт праймеров" в момент между пунктами 1 и 2. У тебя есть **100 миллисекунд** на это". Насколько я знаю, даже при двойном щелчке время между нажатиями левой кнопки мыши будет больше. 

Скажу честно - я бы даже не стал строчить этот комментарий, если запрашиваемый тобой фикс было бы сделать быстрее, чем написать этот коммент, но я не увидел готовой инфраструктуры для листенера проекта, а писать эту штуку ради несуществующей проблемы у меня нет ни желания, ни времени.

PS. я не знал, как хорошо выразить идею того, что хочу это написать, поэтому решил сначала сделать это на русском, а потом перевести, но сейчас думаю, что можно оставить так.

2023-05-02 06:44 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +            CHECK_SET_ERR(!GTWidget::findWidget(os, "pbAddObject")->isEnabled(), "Add object(s) shoud be disabled'");
OK

2023-05-02 18:50 UTC, yalgaer commented on src/plugins/pcr/src/import/ImportPrimersDialog.cpp
> +    pbAddObject->setEnabled(AppContext::getProject() != nullptr);
Here is an example when project can be added after the dialog is shown:
1. Run a computational task that as the result will load a document and create a project.
2. Open the dialog. The `pbAddObject` will be disabled.
3. Keep the dialog open. Wait until task from the step 1 completes
4. The project will be added, but the  `pbAddObject` still will be disabled.

How to listen for project:
See `    void si_serviceStateChanged(Service* s, ServiceState oldState);`

If you think this functionality is too much for your dialog, I'm OK if you just skip it and resolve this issue.

2023-05-02 18:51 UTC, yalgaer commented
Looks good. Will approve after tests.

2023-05-03 10:13 UTC, DmitriiSukhomlinov commented on src/plugins/pcr/src/import/ImportPrimersDialog.cpp
> +    pbAddObject->setEnabled(AppContext::getProject() != nullptr);
Oh, yeah, it was really easy to fix. Done.

2023-05-03 21:15 UTC, yalgaer commented
Looks good. Will approve after tests.

2023-05-05 11:00 UTC, DmitriiSukhomlinov commented
BOTH failed GUI test have passed locally. For some reason, **test_7515** failed twice but I don't see why it could happened but some coincidence - this test has not a single related point to the current fix.

2023-05-06 19:50 UTC, yalgaer approved these changes

2023-05-06 19:50 UTC, merged