UGENE-7851 A lot of messages in the log on opening PDB file: QList::insert(): Index out of range.
ugeneunipro/ugene pull request #1237
Opened 2023-04-28 10:25 UTC by rasputinkirill

2023-04-30 12:51 UTC, yalgaer requested changes
Решение неверное: у каждого атома в молекуле есть порядковый номер (индекс) и менять его на случайный нельзя

2023-05-02 18:55 UTC, yalgaer commented
Правильно ли я понимаю что теперь мы не сможем открывать pdb файлы из наших же data samples?
Мне кажется это не совсем серьёзное решение :)

2023-05-02 18:56 UTC, yalgaer requested changes
Правильно ли я понимаю что теперь мы не сможем открывать pdb файлы из наших же data samples?
Мне кажется это не совсем серьёзное решение :)

2023-05-03 06:22 UTC, rasputinkirill commented
Не понял что не так. Все файлы из семплов открываются, 3D структуры выглядят нормально. Если не нравится мое решение предложи свой вариант. Суть моего варианта - собрать заранее все атомы для каждой модели в отдельной структуре данных, проверить что их верное количество и потом вставить в список дял 3d модели.

2023-05-03 09:37 UTC, yalgaer reviewed
> Не понял что не так. Все файлы из семплов открываются, 3D структуры выглядят нормально. 

Я вижу следующий новый код в  парсинге PDB:
```
ti.setError(U2::PDBFormat::tr("One of the atom chains is incomplete. One or more atoms are lost."));
```
То есть парсинг будет прерван с ошибкой.

Далее, я вижу что в тесте ты используешь файл из сэмплов: то есть в нём была ошибка и его парсинг будет прерван?


>Если не нравится мое решение предложи свой вариант. 

Чтобы предложить свой вариант для глобальной переделки мне придется детально разобраться с форматом и пропустить пару сотен файлов из базы PDB, чтобы понять масштаб проблемы.
Ошибки же при review видны сразу.

2023-05-03 10:21 UTC, rasputinkirill commented
Изначальная проблема была в том что индекс по которому атом пытались вставить в список выходил за пределы этого списка - появлялась ошибка в логе, но QList обрабатывал эту попытку как вставку в конец списка.
Я сделал простое решение - что если есть попытка вставить за пределы списка - то сами вставляем в конец, тебе это не понравилось.
Я сделал более безопасный вариант. Мы по мере чтения всего файла создаем структуру в которой храним атомы по индексу модели индексу цепочки и индексу атома. После формирования этой структуры убеждаемся что атомов нужное количество (пропусков в цепочки индексов нет). Потом еще дополнительно сортируем, вдруг индексы атомов были не по порядку (возможно они всегда по-порядку и это оговорено форматом). И после этого заполняем эти наши проблемные списки атомами.

2023-05-03 11:31 UTC, yalgaer commented
> Я сделал простое решение - что если есть попытка вставить за пределы списка - то сами вставляем в конец, тебе это не понравилось.

Конечно мне это не понравилось. Индекс атома в файле должен соответствовать индексу в списке.
Мне кажется это не нужно повторять - это доступно в переписке выше. Давай концентрироваться на правильном решении.

2023-05-03 11:32 UTC, yalgaer commented
> Я сделал более безопасный вариант.

Ответь пожалуйста на вопросы выше: https://github.com/ugeneunipro/ugene/pull/1237#pullrequestreview-1410521692
Что было сделано я вижу в коде, словесное описание излишне.

2023-05-03 11:51 UTC, rasputinkirill commented
>То есть парсинг будет прерван с ошибкой.
По идее да.
>Далее, я вижу что в тесте ты используешь файл из сэмплов: то есть в нём была ошибка и его парсинг будет прерван?
Нет не будет, потому что файл нормальный, индексация в pdb файле начинается с 1, атом пытаются вставить в пустой список по этому индексу - получаем сообщение в логе. Любой из наших pdb файлов имеет начальный индекс атомов с 1.
Ошибка не в файле, а в нашем парсере формата.

2023-05-03 12:00 UTC, yalgaer commented
> > То есть парсинг будет прерван с ошибкой.
> 
> По идее да.
> 

А что было раньше? Этот файл бы открылся? То есть в твоем тесте файл из samples не открывается?

2023-05-03 12:07 UTC, rasputinkirill commented
> А что было раньше? Этот файл бы открылся? То есть в твоем тесте файл из samples не открывается?

Файл открывался, ошибка от QT не препятствовала последующему выполнению.
После моего исправления тоже открывается, так как оно учитывает что индекс атомов начинается с 1 (но ошибки от QT нету в логе, это и проверяется в тесте).

2023-05-03 12:16 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    CHECK_SET_ERR(!lt.hasMessage("QList::insert(): Index out of range."), "'QList::insert(): Index out of range.' present in log, but it shouldn't");
Насколько я знаю QT выдает подобные ошибки только в дебаге. А тесты у нас идут в релизе. 
Падает ли этот тест в релизе если не применять фикс?

2023-05-03 12:17 UTC, yalgaer commented on src/corelibs/U2Formats/src/PDBFormat.cpp
> +            ti.setError(U2::PDBFormat::tr("One of the atom chains is incomplete. One or more atoms are lost."));
Добавь с сообщение об ошибке индекс атома и `return` после ошибки - дальше парсить нет смысла

2023-05-03 12:18 UTC, yalgaer commented on src/corelibs/U2Formats/src/PDBFormat.cpp
> +        if (!atomsInChain.keys().contains(atomsInChain.size())) {
Не нужно создавать промежуточный контейнер чтобы проверить наличие элемента в Map.

2023-05-03 12:28 UTC, yalgaer commented
> > А что было раньше? Этот файл бы открылся? То есть в твоем тесте файл из samples не открывается?
> 
> Файл открывался, ошибка от QT не препятствовала последующему выполнению. После моего исправления тоже открывается, так как оно учитывает что индекс атомов начинается с 1 (но ошибки от QT нету в логе, это и проверяется в тесте).

Если вся изначальная проблема заключается в том, что индексация (atom id) начинается с 1 а не с 0: можно ли решить задачу проще: добавить методы model.getAtom(id), model.setAtom(id, atom) которые будут конвертировать atom id в индекс (вычитать единицу).

Если же id-1 превысит размер массива model.atoms - нужно прерывать парсинг с ошибкой.

2023-05-03 12:42 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    CHECK_SET_ERR(!lt.hasMessage("QList::insert(): Index out of range."), "'QList::insert(): Index out of range.' present in log, but it shouldn't");
Очевидно ошибки нет. Тест ничего не проверяет в релизе.

2023-05-03 13:16 UTC, rasputinkirill commented
Я тут подумал, что твой метод отнимать единицу от индекса не годится, так в методе `parseAtom` есть условие, `if (atomIsInChain) {` что не все атомы попадут в 3d модель, а соответственно будут пропуски в последовательности. А еще моя эта проверка на количество атомов и индекса не имеет смысла. Вообще эта проверка неправильная она осталась с того когда пробовал уместит атомы в структуру QMap<int, QMap<int, SharedAtom>> но потом понял что надо еще и индекс модели сохранять, а не только индекс цепочки.

2023-05-03 13:23 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    CHECK_SET_ERR(!lt.hasMessage("QList::insert(): Index out of range."), "'QList::insert(): Index out of range.' present in log, but it shouldn't");
Тогда надо что-то сделать с этим тестом

2023-05-03 13:25 UTC, yalgaer commented on src/corelibs/U2Formats/src/PDBFormat.cpp
> +        if (atomsMap.find(chainIndex) == atomsMap.end()) {
nit: используй atomsMap.contains()

2023-05-03 13:26 UTC, yalgaer commented on src/corelibs/U2Formats/src/PDBFormat.cpp
> +    for (const QMap<int, QMap<int, SharedAtom>> atomsInChain : qAsConst(atomsMap)) {
nit: здесь правильным именем может быть: atomModelsInChain ?

2023-05-03 13:28 UTC, yalgaer commented on src/corelibs/U2Formats/src/PDBFormat.cpp
> +    QMap<int, QMap<int, QMap<int, SharedAtom>>> atomsMap;  // QMap<chainIndex, QMap<modelId, QMap<atomIndex, Atom>>>
Так как ключи int - можно ли заменить на QHash? Это будет и эффективнее и уберет обратный поиск ключа по значению

2023-05-03 15:34 UTC, rasputinkirill commented
Не понял как QHash пристроить. QMap в отличии от QHash нам дает гарантированно отсортированные по ключу контейнеры. В остальном интерфейс у них один и тот же, по идее у QHash доступ по чтению должен быть быстрее при большом количестве операций чтения по сравнению со вставкой\удалением.

2023-05-03 15:47 UTC, yalgaer commented
> Не понял как QHash пристроить. QMap в отличии от QHash нам дает гарантированно отсортированные по ключу контейнеры. В остальном интерфейс у них один и тот же, по идее у QHash доступ по чтению должен быть быстрее при большом количестве операций чтения по сравнению со вставкой\удалением.

QHash имеет тот же базовый интерфейс как и QMap - заменить должно быть просто.

Получение списка сортированных ключей в данонм случае не является базовым сценарием - можно и запустить сортировку когда нужен этот массив. 
Если это нужно делать много и часто (получать сортированный массив) - Map тут плохой кандидат - надо вытаскивать и кешировать этот массив в отдельную переменную и поддерживать более сложную композитную модель из пары QHash + сортированный массив.

2023-05-03 22:45 UTC, yalgaer requested changes
Кирилл, ты зря не возразил на мое первое утверждение:

```
Решение неверное: у каждого атома в молекуле есть порядковый номер (индекс) и менять его на случайный нельзя
```
Старый код действитально выглядел так, что строил индекс `[atomId]=>atom` но это было лишним. Я изучила код и этот индекс не нужен: везде достаточно простого списка атомов (порядок произвольный).

Поэтому предлагаю вернуться к твоему начальному решению в 1 строку: замены insert на append.

Тесты же оставь - они должны работать: так как от абсолютого значения atomId или его порядка у нас теперь ничего не зависит, а старый код мог бы упасть на большом atomId.

2023-05-06 19:51 UTC, yalgaer approved these changes

2023-05-06 19:51 UTC, merged