UGENE-7834 Add link to database in the "Access remote databases..." dialog
ugeneunipro/ugene pull request #1269
Opened 2023-05-22 06:12 UTC by DmitriiSukhomlinov

2023-05-23 23:43 UTC, yalgaer requested changes
Th
![icon-before](https://github.com/ugeneunipro/ugene/assets/17791039/7aec4860-a474-421a-a409-abf041070813)
e code looks good. The icon color pops out:

Could you please check if the lightened icon works well for Windows too?
![icon-after](https://github.com/ugeneunipro/ugene/assets/17791039/650a398d-f899-4ac1-81b2-cecd26b6fec2)

The lighter file:
![external_link](https://github.com/ugeneunipro/ugene/assets/17791039/4f5ae1cc-b3d4-49b0-885d-22cb37deeca5)

2023-05-23 23:43 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.cpp
> +    externalLinks.insert(ENSEMBL, "http://www.ensembl.org/index.html");
nit: 1) it is better to use 'https' instead of http when possible 2) index.html suffix is not needed.

2023-05-23 23:43 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.cpp
> +    SAFE_POINT(externalLinks.keys().contains(dbName), "No database found", QString());
nit: 1) keys() is not needed, 2) return type can be shortened to "" or {}, 3) Add DB name to the error message.

2023-05-23 23:43 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.cpp
> +    externalLinks.insert(GENBANK_DNA, "https://www.ncbi.nlm.nih.gov/nucleotide/");
nit: slash at the end is not needed in any of the links

2023-05-23 23:43 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.h
> +    // Return the link to the database (to open in browser) by the database name
nit: Return -> Returns (start method names & docs with a verb), end every sentence in comments with a dot (for the consistent style).

2023-05-23 23:43 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/DownloadRemoteFileDialog.cpp
> +static const QString DB_EXTERNAL_LINK = QString(R"(<a href="%1"><img src=":core/images/external_link.png" width="22" height="22";></a>)");
semicolon in the link img tag is typo.

2023-05-24 05:21 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.cpp
> +    externalLinks.insert(ENSEMBL, "http://www.ensembl.org/index.html");
OK

2023-05-24 05:22 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.cpp
> +    SAFE_POINT(externalLinks.keys().contains(dbName), "No database found", QString());
OK

2023-05-24 05:23 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.cpp
> +    externalLinks.insert(GENBANK_DNA, "https://www.ncbi.nlm.nih.gov/nucleotide/");
OK

2023-05-24 05:23 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/LoadRemoteDocumentTask.h
> +    // Return the link to the database (to open in browser) by the database name
OK

2023-05-24 05:27 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/DownloadRemoteFileDialog.cpp
> +static const QString DB_EXTERNAL_LINK = QString(R"(<a href="%1"><img src=":core/images/external_link.png" width="22" height="22";></a>)");
OK

2023-05-24 05:28 UTC, DmitriiSukhomlinov commented
The lighter icon looks good, fixed

2023-05-24 23:06 UTC, yalgaer approved these changes

2023-05-25 02:45 UTC, merged