Kirkinskaya alisa
ugeneunipro/ugene pull request #1277
Opened 2023-06-05 11:31 UTC by alisa667

- Access to AlphaFold Protein Structure Database
- Added the opportunity to calculate Shannon entropy of an alignment and save it to PDB file (avaliable from "Alignment Entropy Calculation" option panel tab of a PDB file). Shannon entropy shows variability of an alignment column
- Added "Alignment Entropy" color scheme in 3D Structure Viewer
- Graphic tests for AlphaFold database and the color scheme
- Added Russian translations

2023-06-05 13:51 UTC, yalgaer requested changes
1. Please update the title of the review.
2. Add `override` to all virtual functions
3. Fix build on Linux

Once the build is fixed I will continue with the testing & the review.

2023-06-05 15:54 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationAndAddToProjectTask.h
> +    void prepare();
override

2023-06-05 15:54 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationAndAddToProjectTask.h
> +    QList<Task*> onSubTaskFinished(Task* subTask);
override

2023-06-06 03:39 UTC, DmitriiSukhomlinov commented
Check [this page](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/project/Experiments_ExternalTests?mode=builds) for build and test info.

2023-06-06 03:55 UTC, alisa667 commented
All remarks corrected

2023-06-06 14:54 UTC, yalgaer requested changes

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +            BaseAlignmentAlgorithmsIds::ALIGN_SEQUENCES_TO_ALIGNMENT_BY_UGENE);
Почему выбран этот алгоритм выравнивания а не другие доступные в UGENE?

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +            counts[row->charAt(i)]++;
В зависимости от особенностей и настроек работы алгоритма выравнивания может получиться ситуация, когда для символа A из PDB последовательности в столбце нет вообще ни одного символа А из выравнивания.

В итоге символу А будет присвоен вес других символов.

Критический пример: в столбце A есть только пропуски.
Текущий алгоритм выдаст одинаковый результат как для пропусков, так и для столбца полностью заполненного символами А

2023-06-06 14:54 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/project/remote_request/GTTestsProjectRemoteRequest.cpp
> +    //    1. Select {File -> Access remote database} menu item in the main menu.
Я попробовала использовать COI.aln для одного из PDB файлов и все сработало.
Нужно добавить проверку, что поданное пользователем выравнивание имеет смысл - алфавит и качество парного выравнивания после добавления в него PDB последовательности.

2023-06-06 14:54 UTC, yalgaer commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +AlignmentEntropyColorScheme::AlignmentEntropyColorScheme(const BioStruct3DObject* biostruct)
для 99.99% PDB файлов эта схема не будет давать обещанный результат:либо будет везде 1.00, либо будет нечто другой записанное в столбец PDB который называется "температура"

Эту схему нужно предлагать для выбора только в том случае, если в текущей модели есть данные с которыми можно работать.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2Gui/src/options_panel/OPWidgetFactory.h
> +    OPFactoryFilterVisitor(ObjectViewType _objectViewType, QList<DNAAlphabetType> _objectListAlphabet, bool _isPdb)
Это слишком грубое внедрение в абстрактную систему фильтрации заточенное на 1 конкретный use-case.
Это лучше сделать иначе:
1) Либо передать сюда список констант: formatId
2) Либо вообще не трогать OPFactoryFilterVisitor и обработать фильтр в `EntropyCalculationWidgetFactory::passFiltration` - там можно сделать любое нужное вычисление контекста.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/AnnotatedDNAView.cpp
> +                    SAFE_POINT(format != nullptr, L10N::nullPointerError("U2DocumentFormat"), nullptr);
Формат у существующего документа не может быть nullptr

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationAndAddToProjectTask.cpp
> +      annotatedDNAView(_annotatedDNAView),
Это очень небезопасный способ кеширования ссылки на view в task. Тк PDB последовательности короткие можно передавать последовательность напрямую

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +        auto context = annotatedDNAView->getActiveSequenceContext();
к этому моменту контекст внутри view может уже переключиться.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +    QTextStream in(&readFile);
Формат PDB может быть и бинарным (gzipped)

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +        } else if ((line.startsWith("ATOM") || line.startsWith("HETATM")) && it != entropyForEveryColumn.constEnd() && currentChainIndex == chainId) {
Нужно добавить дополнительную проверку что имя аминокислоты полученное на входе алгоритма соответствует имени в файле (нет случайного сбоя)

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +    readFile.close();
Эти строки лишние - файлы закроются автоматически при удалении объекта

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.ui
Здесь обязательно нужна кнопка Help на документацию или любой другой способ объяснить что будет сделано дальше, так как мы предлагам пользователю сделать нечто, что не имеет описания в статьях/других тулах.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/AnnotatedDNAView.cpp
> +                    auto curDoc = seqObj->getDocument();
ADV не может содержать объекты без документа.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/AnnotatedDNAView.cpp
> +                    SAFE_POINT(seqObj != nullptr, L10N::nullPointerError("U2SequenceObject"), nullptr);
ADV не может иметь SequenceContext без Sequence

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.h
> +    MultipleSequenceAlignmentObject* alignment;
Нужно добавить значения по умолчанию и тут. Это поможет в случае если в конструкторе (другом месте) эти поля забудут инициализировать.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +        QObject::tr("Additional settings"), QObject::tr("Additional settings"), additionalSettingsWidget, true));
QObject здесь не нужен - нужно использовать контекст текущего виджета для трансляции.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +    QRegularExpression exprBetweenBrackets("\\[(.*)\\]");
Зависимость имени файла от имени view - может привести к некорректному имени файла. Нужно либо удалить из него плохие символы (сделать безопасным) или (лучше) передать имя оригинального файла и использовать уже его для построения нового имени.

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +void EntropyCalculationWidget::connectSlots() {
nit: эти методы создают больше шума чем пользы при чтении. Лучше встроить их код в конструктор виджета

2023-06-06 14:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +    runButton->setEnabled(alignmentLineEdit->text() != "");
nit: Используй isEmpty()

2023-06-06 14:54 UTC, yalgaer commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +                    isEntropy = false;
1) нужно добавить break
2) нужно вынести этот метод (checkMoleculeModelHasEntropy) в отдельный метод - так его можно будет переиспользовать например решая нужно ли вообще показывать опцию этой раскраски
3) Нужно проверить температуру на >=0

2023-06-06 14:54 UTC, yalgaer commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +                if (atom->temperature > 1) {
Что если в столбце temperature в записана не энтропия а нечто другое?

Если в формате PDB этот столбец называется Temperature factor то может и нам называть схему именно так, а не энтропией?

Или, если мы все же мы хотим представить цветовую схему именно как "схему энтропии" - можем ли мы записать дополнительное поле в одну из секций PDB файла и указать, что в поле Temp содержится именно наша энтропия, а не что-то другое

2023-06-07 03:46 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +            BaseAlignmentAlgorithmsIds::ALIGN_SEQUENCES_TO_ALIGNMENT_BY_UGENE);
Изначально планировалось сделать комбобокс с выбором выравнивания (MAFFT и MUSCLE), но на это не хватило времени. Поэтому выбрали наиболее легко интегрируемый алгоритм

2023-06-07 03:48 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.ui
Кнопка Help есть, но страница документации пока пустая. В ближайшем будущем заполним

2023-06-08 02:54 UTC, alisa667 commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +                if (atom->temperature > 1) {
Это стандартный подход, когда в столбце temperature factor записывается что-то другое. Например, AlphaFold записывает метрику уверенности в предсказании, [вот этот инструмент](https://consurf.tau.ac.il/consurf_index.php) считает консервативность выравнивания и тоже записывает в temperature factor.

Если же в temperature factor записан именно temperature factor (который имеет смысл для 3D моделей, полученных экспериментальным путём), то наша схема для него не сработает. В этом случае значения в этом столбце будут варьироваться примерно от 0 до 100. Именно так мы отличаем энтропию от настоящего temperature factor.

Насчёт записать дополнительное поле в PDB файл - не хотелось бы менять формат, так как могут возникнуть проблемы при чтении этого файла другими инструментами.

2023-06-08 18:10 UTC, alisa667 commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +AlignmentEntropyColorScheme::AlignmentEntropyColorScheme(const BioStruct3DObject* biostruct)
OK

2023-06-08 18:11 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/AnnotatedDNAView.cpp
> +                    SAFE_POINT(format != nullptr, L10N::nullPointerError("U2DocumentFormat"), nullptr);
OK

2023-06-08 18:11 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +    readFile.close();
OK

2023-06-08 18:11 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/AnnotatedDNAView.cpp
> +                    auto curDoc = seqObj->getDocument();
OK

2023-06-08 18:11 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/AnnotatedDNAView.cpp
> +                    SAFE_POINT(seqObj != nullptr, L10N::nullPointerError("U2SequenceObject"), nullptr);
OK

2023-06-08 18:11 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.h
> +    MultipleSequenceAlignmentObject* alignment;
OK

2023-06-08 18:13 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +        QObject::tr("Additional settings"), QObject::tr("Additional settings"), additionalSettingsWidget, true));
OK

2023-06-08 18:13 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +void EntropyCalculationWidget::connectSlots() {
OK

2023-06-08 18:13 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +    runButton->setEnabled(alignmentLineEdit->text() != "");
OK

2023-06-08 18:14 UTC, alisa667 commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +                    isEntropy = false;
OK

2023-06-09 11:26 UTC, yalgaer commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +                if (atom->temperature > 1) {
Проблем с чтением не возникнет если не менять формат, а дополнить его аннотацией в рамках правил формата.

Лучшим же решением будет назвать ново-созданный график общим именем: Карта температуры (Temperature map, Heatmap) и показывать этот график для любого PDB у которого есть данные в столбце температурного фактора.

2023-06-09 11:29 UTC, yalgaer commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +        return Color4f(QColor(atom->temperature * 255, green, (1 - atom->temperature) * 255));
Эта формула дает очень невыразительный (визуально) результат.

Нужно взять градиент с "ожидаемым" переходом цветов типа этого (можно дискретный)
![image](https://github.com/ugeneunipro/ugene/assets/17791039/24ddf2e2-0104-4fe4-8cff-59e400e0ff1c)

И выбирать цвета из него.

2023-06-09 11:31 UTC, yalgaer commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.cpp
> +                if (atom->temperature > 1 || atom->temperature < 0) {
Этот метод проверяет столбац "температурный фактор" - лучше назвать его getChainIdsWithVariableTemperature и выбирать любую вариабельность, а не только в диапазоне 0..1

2023-06-09 11:32 UTC, yalgaer commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.h
> +    virtual bool isSchemeValid(const BioStruct3D&) const {
nit: реализация метода должна уйти в cpp

2023-06-10 04:42 UTC, alisa667 commented on src/corelibs/U2Gui/src/options_panel/OPWidgetFactory.h
> +    OPFactoryFilterVisitor(ObjectViewType _objectViewType, QList<DNAAlphabetType> _objectListAlphabet, bool _isPdb)
OK (первый вариант)

2023-06-10 04:42 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationAndAddToProjectTask.cpp
> +      annotatedDNAView(_annotatedDNAView),
ОК

2023-06-10 04:43 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +    QTextStream in(&readFile);
ОК

2023-06-10 04:43 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationWidget.cpp
> +    QRegularExpression exprBetweenBrackets("\\[(.*)\\]");
ОК

2023-06-10 06:13 UTC, alisa667 commented on src/plugins/GUITestBase/src/tests/common_scenarios/project/remote_request/GTTestsProjectRemoteRequest.cpp
> +    //    1. Select {File -> Access remote database} menu item in the main menu.
Проверку на алфавит добавила, с качеством выравнивания не совсем понятно, как сделать

2023-06-10 06:13 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +        auto context = annotatedDNAView->getActiveSequenceContext();
OK

2023-06-10 06:14 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +        } else if ((line.startsWith("ATOM") || line.startsWith("HETATM")) && it != entropyForEveryColumn.constEnd() && currentChainIndex == chainId) {
OK

2023-06-10 09:28 UTC, alisa667 commented on src/plugins/biostruct3d_view/src/BioStruct3DColorScheme.h
> +    virtual bool isSchemeValid(const BioStruct3D&) const {
ОК

2023-06-10 10:24 UTC, alisa667 commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +            counts[row->charAt(i)]++;
Даже если в PDB последовательности на месте А находится замена, то это нормально, так как мы отображаем именно вариабельность выравнивания. Насчёт пропусков - да, это недостаток этого алгоритма подсчёта вариабельности, но тем не менее он широко используется

2023-06-10 12:45 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/AnnotatedDNAView.cpp
> +    bool isPdbFormat = false;
Неиспользуемая переменная

2023-06-10 14:01 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +            counts[row->charAt(i)]++;
>Даже если в PDB последовательности на месте А находится замена, то это нормально, так как мы отображаем именно вариабельность выравнивания

Ситуация когда под A(pdb) стоит консенсусная A(выравнивание) дает 100% стабильность.
При этом ситуация когда под A(pdb) стоит консенсусная B тоже дает 100% стабильность.
Я считаю это недостатоком текущей реализации: нужно учитывать всю информацию в выравнивании - включая и символы из PDB последовательности.

> Насчёт пропусков - да, это недостаток этого алгоритма подсчёта вариабельности, но тем не менее он широко используется

Пропуск это "отсутствие информации" (NaN) и он не равен ничему, и даже самому себе в отличие от простых символов алфавита.

Текущий алгоритм для 100% пропусков в выравнивании дает ответ: 100% стабильность.

Если это широко используется, добавьте, пожалуйста, пару ссылок где описывается расчёт в присутствии пропусков. Мне они будут полезны при review.

2023-06-10 14:05 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/project/remote_request/GTTestsProjectRemoteRequest.cpp
> +    //    1. Select {File -> Access remote database} menu item in the main menu.
Мой следующий тест будет таким: на выбранную PDB последовательность я наложу не имеющее к ней отношение выравнивание и получу бессмысленный результат и статус об успешном выполнении расчёта. Это неправильно.

Расчет должен выдавать ошибку если качество выравнивания не соотвествует критериям получения осмысленного результата.

2023-06-11 06:33 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +        int lineLength = readIO->readLine(byteLine.data(), max_size);
Неиспользуемая переменная

2023-06-11 17:05 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/project/remote_request/GTTestsProjectRemoteRequest.cpp
> +    //    1. Select {File -> Access remote database} menu item in the main menu.
Что такое "качество выравнивания" и как оно считается? В UGENE сейчас не существует такого определения.

2023-06-12 02:30 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/project/remote_request/GTTestsProjectRemoteRequest.cpp
> +    //    1. Select {File -> Access remote database} menu item in the main menu.
Вообще, я не очень согласен с логикой данного замечания. Пример: мы берем множественное выравнивание, содержащее набор эволюционно схожих последовательностей, и еще одну последовательность, не имеющую к ним никакого отношения и пытаемся наравнять последовательность на выравнивание. Ни один из существующих в UGENE алгоритмов не выдаст нам ошибку, а выполнит выравнивание настолько, насколько сможет. Идея всех этих алгоритмов в том, что пользователь понимает данные, с которыми он работает и только тогда получает осмысленный результат. Аналогичная ситуация с огромным количеством иных алгоритмов в UGENE - проверку "на дурака" зачастую трудно сделать, а в некоторых случаях она может случайно отсечь "правильный" вариант.

2023-06-12 03:04 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/project/remote_request/GTTestsProjectRemoteRequest.cpp
> +    //    1. Select {File -> Access remote database} menu item in the main menu.
Я согласна что для научной работы никаких проверок делать не нужно - пользователь сам должен подать на вход правильные данные. 

В данном PR мы обсуждаем не только состоятельность научного подхода, но и подачу нового метода пользователям средствами UGENE.

Мы уже делаем проверку на то, является ли правильным алфавит. То есть валидацию данных "на дурака" выполняем.

Более того: "в других местах" UGENE визуализирует результат выравнивания. Пользователь видит результат визуально и может нажать undo.

В этом же случае, для последовательности из PDB в 500 символов пользователь может подать выравнивание в 50 или 2000 символов и сделать глобальное выравнивание (не локальное!). 

Результат будет бессмысленным, но UGENE покажет карту температуры и даже не предупредит пользователя об ошибке.
Именно эта часть неприемлема для качественного инструмента (UGENE).

Как сделать проверку на совместимость последовательности из PDB и выравнивания:

1) Так как вы делаете глобальное выравнивание то нужно учесть длину (без вставок): не должно быть большой разницы в длине. 
Эту проверку сделать очень просто: она будет происходить еще до запуска выравнивания.

2) Так как алгоритм имеет смысл только когда пользователь подает выравнивание в котором есть вариации текущей PDB последовательности, а не что угодно, то можно дополнительно проверить, что существенная доля символов PDB последовательности получила подтверждение в поданном на вход выравнивании. Это выражается простым числом гэпов вставленных в PDB последовательность, либо чрезмерно большим увеличением длины оригинального выравнивания (с учетом вставок).
Эту проверку тоже сделать очень просто: уже после выравнивания посмотреть насколько изменилась его длина (насколько его "раздули" вставками). Коэффициент можно подобрать достаточно легкий: например 50%. С этим стоит поэксперементировать подавая схожие по длине (см. фильтр 1) но не схожие по составу выравнивания.

Возможно есть и более качественный способ проверки, но для UGENE этих двух простых достаточно.
Их можно сопроводить "неблокирующим предупреждением" для пользователя. Если пользователь понимает что делает то сможет продолжить в любом случае.

Также было бы идеально иметь опцию показа промежуточного выравнивания (открыть MSA) - но это уже понятно не в рамках текущего PR.

2023-06-19 11:39 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +            counts[row->charAt(i)]++;
> Я считаю это недостатоком текущей реализации: нужно учитывать всю информацию в выравнивании - включая и символы из PDB последовательности.

Нужно учитывать, что выравнивание мы задаем сами и оно содержит то, что нам необходимо - соответственно, при необходимости, можно туда просто добавить последовательность 3D структуры и все. Чтобы учесть все пожелания, предлагаю добавить галочку "Учитывать последовательность 3D структуры".

> Если это широко используется, добавьте, пожалуйста, пару ссылок где описывается расчёт в присутствии пропусков. Мне они будут полезны при review.

@alisa667

2023-06-19 14:37 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/alignment_entropy_calculation/EntropyCalculationTask.cpp
> +            counts[row->charAt(i)]++;
Я не против галочки для включения PDB последовательности в учете статистики со включенным по умолчанию состоянием.

Хочу заметить, что если PDB последовательность уже включена в выравнивание (вариант, где реально стоит отжать галочку), то и само выравнивание производить не нужно - достаточно просто найти эту последовательность в выравнивании и сделать расчёт относильно нее.

2023-06-22 16:15 UTC, yalgaer commented
Closing as non-active. 
Please re-open with updates.

2023-07-05 03:40 UTC, closed without merging