UGENE-7866 Error message should be unified for non-latin characters and spaces in the path
ugeneunipro/ugene pull request #1313
Opened 2023-06-26 05:40 UTC by rasputinkirill

Сделал проверки в самом диалоге на правильность путей, использовав недавно написаный функционал для внешних инструментов.

2023-06-27 05:29 UTC, yalgaer requested changes

2023-06-27 05:29 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    6. Set database name with not latin symbols, move cursor to this line edit
Описание шага 6 то же что и шага 4. В чем разница?
В тесте вижу пробелы в стоке "A A O O O A A". Если в этой строке есть не-ascii символы замени их на такие, чтобы сразу было видно (например русскую Ю)

2023-06-27 05:29 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/BlastDBSelectorWidgetController.cpp
> +    static QString pathTooltip = tr("Database path contains spaces or/and not Latin characters.");
not latin -> non-latin

2023-06-27 05:29 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/BlastDBSelectorWidgetController.cpp
> +    static QString nameTooltip = tr("Database name contains spaces or/and not Latin characters.");
Судя по тому, что написано тут: https://www.ncbi.nlm.nih.gov/books/NBK569860/ Blast будет принимать пути с проблелами, если их обернуть в кавычки. 
Если оно работает - стоит поддержать, так как на Windows (самой популярной у нас системе) пробелы встречаются часто (а-ля My Documents).

2023-06-27 05:29 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/BlastDBSelectorWidgetController.cpp
> +    bool isOkay = ExternalToolSupportUtils::checkArgumentPathLatinSymbols({le->text()}).isEmpty() &&
Правила на то, какие символы в путях должен и какие не должен принимать external tool уже записаны в самом туле (см. BlastSupport)
Нужно взять правила из этого места, а не хардкодить их копию тут.

2023-06-27 05:29 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/BlastDBSelectorWidgetController.h
> +    bool checkValidPathLE(QLineEdit *le, const QString& errorTooltip);
Если приватный метод может быть статическим то стоит убрать его в cpp и не засорять header (публичный интерфейс).

Также, функция не просто проверят что-то но и меняет tooltip - это надо отразить в имени функции.

2023-06-28 11:47 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    6. Set database name with not latin symbols, move cursor to this line edit
хотел чтоб был вариант с пробелами

2023-06-28 12:20 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/blast/BlastDBSelectorWidgetController.cpp
> +    static QString nameTooltip = tr("Database name contains spaces or/and not Latin characters.");
Предлагаю, реализацию поддержки пробелов сделать отдельной задачей.

2023-06-28 15:55 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/BlastDBSelectorWidgetController.cpp
> +    static QString nameTooltip = tr("Database name contains spaces or/and not Latin characters.");
Хорошо

2023-06-28 15:57 UTC, yalgaer reviewed
Замечаний нет. Жду тестов и апрувлю.

2023-06-28 23:16 UTC, rasputinkirill commented
Все таки нельзя так делать проверять поля ввода пути и имени файла унифицированной функцией проверки которая проверяет не только пути до входных файлов, но и остальные передаваемые пути для внешнего инструмента.
В итоге os может содержать ошибку не вызванную неверным путем или именем файла для инструмента.
Предлагаю вернуться к предыдущему варианту или в тултипе писать ошибку из os или что-то еще придумать.

2023-06-29 05:39 UTC, yalgaer commented
> Все таки нельзя так делать проверять поля ввода пути и имени файла унифицированной функцией проверки которая проверяет не только пути до входных файлов, но и остальные передаваемые пути для внешнего инструмента. В итоге os может содержать ошибку не вызванную неверным путем или именем файла для инструмента. Предлагаю вернуться к предыдущему варианту или в тултипе писать ошибку из os или что-то еще придумать.

Информация о том, как именно с путями или параметрами работат external tool принадлежит самому тулу, но не диалогу.
Её может вызывать, например, WD worker или диалогов /типов виджетов может быть несколько разных и тп.

Поэтому все клиенты тула должны запрашивать у него информацию: хороший ли путь/параметр или нет. Дублировать эту информацию не надо. Если текущий фреймворк в external tools недостаточно хорош для этого - нужно его доработать.

Вопрос:
```void ExternalTool::checkPaths(const QStringList& arguments, U2OpStatus& os) const;```

принимает аргументы тула. В твоем случае путь к базе данных.
Ты не хочешь позволять пробелы в пути. Эта функция вернет ошибку если есть пробелы в аргументе (в пути).
Вроде все работает.
Можешь описать плохой сценарий?

2023-06-30 03:56 UTC, rasputinkirill commented
Да `void ExternalTool::checkPaths(const QStringList& arguments, U2OpStatus& os) const;` принимает аргументы инструмента, но он так же осуществляет проверку и других параметров которые указаны в конструкторе, собственно в  BLAST:
`pathChecks << ExternalTool::PathChecks::NonLatinArguments 
               << ExternalTool::PathChecks::SpacesArguments;
    if (isOsLinux() || isOsWindows()) {
        pathChecks << ExternalTool::PathChecks::NonLatinTemporaryDirPath
                   << ExternalTool::PathChecks::SpacesTemporaryDirPath;
    }
    if (isOsWindows()) {
        pathChecks << ExternalTool::PathChecks::NonLatinToolPath;
    }`
То есть могут быть проверены еще и путь до временной папки и путь до инструмента, и при проблемах с этими путями в `os` будет ошибка и в диалоге поля ввода станут помеченными как имеющие неверное содержимое ,соответственно будет неправильный тултип.
Поэтому надо делать проврку путей по-другому.

2023-06-30 17:30 UTC, yalgaer commented
Что если мы разделим checkPath на checkToolPath и checkToolArgs ?
Тогда для проверки аргументов можно будет вызвать только `checkToolArgs`?

2023-07-01 17:31 UTC, yalgaer commented
Замечаний нет, апрув после тестов.

2023-07-03 08:11 UTC, yalgaer submitted a review, later dismissed

2023-07-04 04:47 UTC, yalgaer approved these changes

2023-07-04 05:01 UTC, merged