UGENE-7905 Bad crash reports on macOS and Linux
ugeneunipro/ugene pull request #1357
Opened 2023-07-19 06:19 UTC by DmitriiSukhomlinov

@rasputinkirill updated breakpad in [UGENE-7577](https://ugene.dev/tracker/browse/UGENE-7577), but only client code. There are two utilities - dump_syms (generates symbols when release is being build) and minidump_stackwalk (parses dumps when we receive crashes)  - wasn't updated. dump_syms updated for Linux and macOS (everything is fine on Windows about crash reports, I decided not to fix things if it already works). Also I updated minidump_stackwalk on server.

If you want to test use these [Linux](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/repository/download/ReleaseLinuxPortable/265049:id/ugene-48.0-dev-r348-b3774-linux-x86-64.tar.gz) and [macOS](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/repository/download/ReleaseMacIntelDmg/265134:id/ugene-48.0-dev-r627-b5044-mac-x86-64.dmg) builds. [This](http://api.ugene.net/tools/ugenecrashes/index.php?id=25625) and [this](http://api.ugene.net/tools/ugenecrashes/index.php?id=25626) reports were processed with new utilites

2023-07-19 06:21 UTC, DmitriiSukhomlinov commented
Only some unstable XML failed. I re-run testing just in case, but not sure about success

2023-07-19 15:09 UTC, yalgaer requested changes
Looks good, but could you please strip the binaries before merge? So you will have 10x less binary size in the git repository

2023-07-20 09:14 UTC, DmitriiSukhomlinov commented
I stripped Linux and it works, but for "have no idea why" reasons on macOS stripped **dump_syms** failed to generate symbols (see [this build](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/buildConfiguration/ReleaseMacIntelDmg/265392?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true) artifacts). If you don't mind, I'll leave macOS dump_syms not stripped, it is just 1.2 MB

2023-07-20 15:53 UTC, yalgaer approved these changes

2023-07-21 03:04 UTC, merged