UGENE-7923 Crash on project filter operation
ugeneunipro/ugene pull request #1403
Opened 2023-08-21 08:18 UTC by rasputinkirill

На всякий случай уточню - MAXIMUM_EXPRESSION_TREE_DEPTH и BIND_PARAMETERS_LIMIT это разные ограничения для запроса и они не зависят друг от друга.

2023-08-21 17:21 UTC, yalgaer commented
Правильно ли я понимаю, что проблема была в том, что у нас было слишком много `OR` условий для поиска?
В этом случае вопрос: можем ли мы заменить серию `OR` на один `IN`?

2023-08-21 17:22 UTC, yalgaer commented
Еще вопрос: в FASTA файле в тесте нет объектов с аннотациями. Почему у нас было переполнение в этом случае?

2023-08-21 17:28 UTC, rasputinkirill commented
> Правильно ли я понимаю, что проблема была в том, что у нас было слишком много `OR` условий для поиска?
> В этом случае вопрос: можем ли мы заменить серию `OR` на один `IN`?
Я не проверял.
> Еще вопрос: в FASTA файле в тесте нет объектов с аннотациями. Почему у нас было переполнение в этом случае?
В приведенном тесте получаем конструкцию аналогичного запроса который вызывает креш. Если есть идея как просто  сделать файл для теста с 1000+ таблицами аннотаций, то давай перепишем.

2023-08-21 17:49 UTC, rasputinkirill commented
То что пишут про `IN` в документации - это как я понял просто замена для `OR` в итоге запрос во внутреннем представлении будет собран в такую же конструкцию и получим такую же ошибку "Expression tree is too large".

2023-08-21 19:23 UTC, yalgaer commented
> > Правильно ли я понимаю, что проблема была в том, что у нас было слишком много `OR` условий для поиска?
> > В этом случае вопрос: можем ли мы заменить серию `OR` на один `IN`?
> 
> Я не проверял.
> 
> > Еще вопрос: в FASTA файле в тесте нет объектов с аннотациями. Почему у нас было переполнение в этом случае?
> 
> В приведенном тесте получаем конструкцию аналогичного запроса который вызывает креш. Если есть идея как просто сделать файл для теста с 1000+ таблицами аннотаций, то давай перепишем.

Документ с аннотациями можно сгенерировать налету из шаблонного текста: слить в один файл маленький Genbank например.

Тест нужно сделать именно с аннотациями по следующей причине:  вызывается метод getAnnotationTablesByFeatureKey. Этот метод должен вызываться только для аннотаций. То, что он сейчас вызывается для секвенсов это неправильно и как только ты это поправишь то текущий тест с секвенсами перестанет тестировать тот код, который ты исправил.

2023-08-21 19:42 UTC, yalgaer commented
> эт



> То что пишут про `IN` в документации - это как я понял просто замена для `OR` в итоге запрос во внутреннем представлении будет собран в такую же конструкцию и получим такую же ошибку "Expression tree is too large".

Такие вещи нужно проверять.

Текущее решение неверно так как не учитывает сложность запроса вызванную другими аргументами. Если у IN нет такого низкого ограничения в 1000, то решение может быть намного проще: использовать IN и все равно сделать ограничение но уже например на 1 миллион параметров (мы просто не тестируем такие значения и не знаем работают ли они).

Проверь пожалуйста, мне кажется что IN не то же самое что OR в плане "Expression tree"

2023-08-21 19:50 UTC, rasputinkirill commented
> Документ с аннотациями можно сгенерировать налету из шаблонного текста: слить в один файл маленький Genbank например.

Можно поподробней, я не понял как это сделать?

2023-08-22 04:19 UTC, yalgaer commented
> > Документ с аннотациями можно сгенерировать налету из шаблонного текста: слить в один файл маленький Genbank например.
> 
> Можно поподробней, я не понял как это сделать?

Есть много способов. Самый простой: сделай строку в тесте:
```
QString genbankFileContent = "LOCUS...\nFEATURES             Location/Qualifiers\ngene           1..2\....acgt\n";
```
И запиши ее в файл 1000 раз в цикле в sandboxDir. После этого прочитай этот файл.

2023-08-22 21:33 UTC, rasputinkirill commented
переделал

2023-08-23 22:09 UTC, yalgaer reviewed
Патч хороший. Небольшие замечания по тесту

Вопрос: то, что мы подаём sequence object id в функицию которая ждет только annotation object id уже неправильно.

Это тоже надо включить в релиз. Думаешь сделать это отдельным патчем?

2023-08-23 22:09 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    GTUtilsTaskTreeView::waitTaskFinished();
Здесь нужно проверить какой-то результат.
Например в одной из таблиц добавить что-то уникальное к фиче и проверить что число показанных результатов корректно.

2023-08-23 22:27 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    GTUtilsTaskTreeView::waitTaskFinished();
Проверка отсутствия креша в задаче про наличия креша не достаточна?

2023-08-23 22:31 UTC, rasputinkirill commented
> Это тоже надо включить в релиз. Думаешь сделать это отдельным патчем?

Эта задача про производительность, а не про креш и я бы отложил ее в следующий мажорный релиз, а не в исправляющий релиз включил.

2023-08-23 23:58 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    GTUtilsTaskTreeView::waitTaskFinished();
нет надо проверить что результат отработал. Вдруг там неправильно что-то показывается (баг в новом коде)

2023-08-24 00:00 UTC, yalgaer commented
> > Это тоже надо включить в релиз. Думаешь сделать это отдельным патчем?
> 
> Эта задача про производительность, а не про креш и я бы отложил ее в следующий мажорный релиз, а не в исправляющий релиз включил.

Давай ее тоже в этот. 
Если бы не эта проблема с неправильным выбором типа объектов, то креша на файле с секвенсами (реальный сценарий пользователя) не было бы вовсе.
Фикс у нее - 1 строка.

2023-08-24 05:46 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    GTUtilsProjectTreeView::checkFilteredGroup("zzz", {}, features, {});
Это плохая проверка: ты генерируешь 5000 строк а эта проверка проверят только одну из них (случайную)
Лучше сделать следующую проверку: 
1) Ввести имя уникальной фичи, не документа (ты менял поиск на имя фичи), правильно?
2) Проверить что в результирующем дереве есть только 1 нужный результат

2023-08-24 21:47 UTC, yalgaer requested changes
В GUI тесте ты проверяешь что в результате есть хотя бы один элемент с именем `scaffold_4528 features`

Этого недостаточно, как я писала выше.
Нужно добавить еще 2 проверки
1) Число результатов = 1
2) Нужная фича (а не объект фич) найдена: тот алгоритм что ты менял ищет по именам фич, а не только именам объектов

2023-08-27 02:33 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    GTFileDialog::openFileWithDialog(testDir, "_common_data/gff/5k_annotation_tables.gff");
Это надо заменить на GTFileDialog::openFile - тут нет никакого диалога.
В остальном тест нормальный. 
Апрув после тестов.

2023-08-27 18:41 UTC, yalgaer approved these changes

2023-08-27 18:42 UTC, merged