Filter project optimization (2)
ugeneunipro/ugene pull request #1412
Opened 2023-08-29 02:16 UTC by rasputinkirill

2023-08-29 04:35 UTC, yalgaer requested changes
Добавь метод `findGObjectIdsByType` (по типу `findGObjectsByType`) и используй его.

Искать в Map задом-наперед (getIdByObject) не нужно.

2023-08-29 22:20 UTC, yalgaer commented on src/corelibs/U2Core/src/models/DocumentModel.cpp
> +QList<U2DataId> Document::findGObjectsByType(const GObjectType& type) const {
У нас уже есть набор методов типа
```
QList<GObject*> findGObjectByType(GObjectType t, UnloadedObjectFilter f = UOF_LoadedOnly) const;
```
Все они возвращают GObject.

Новый метод нужно именовать иначе (c Id):

```
... findGObjectIdsByType(...) const;
```

2023-08-29 22:24 UTC, rasputinkirill commented on src/corelibs/U2Core/src/models/DocumentModel.cpp
> +QList<U2DataId> Document::findGObjectsByType(const GObjectType& type) const {
сделал

2023-08-30 20:30 UTC, yalgaer commented
Фикс корректный, пожалуйста смержись с мастером и запусти GUI тесты.

2023-08-30 22:01 UTC, rasputinkirill commented
Ты в своем коммите 6ab51d3bd0707232c8c950190cce3092d360cf84 потеряла тест на UGENE-7923, я его добавли снова. Проверь не потерялось ли чего еще.

2023-08-31 22:50 UTC, yalgaer commented
Дифф для патча нереально большой. Почисти пожалуйста и я просмотрю снова. 
Замечаний не было, нужно чтобы прошли тесты и был правильный diff

2023-09-01 20:42 UTC, yalgaer commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteFeatureDbi.cpp
> +    CHECK(!objectIdsToSearch.isEmpty(), result);
Здесь ты поменял оригинальное поведение задокументированное в заголовочном файле: U2FeatureDbi.

```* If @desiredObjectIdsToSearch is not empty search only in that objects.```

Если уверено что оно того стоит - измени комментарий и вынеси проверку выше начала транзакции.
Или оставь как было.

2023-09-01 20:46 UTC, rasputinkirill commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteFeatureDbi.cpp
> +    CHECK(!objectIdsToSearch.isEmpty(), result);
Да оно стоит, это единственное место где используется этот метод. Если не менять предыдущий баг будет снова воспроизводится.

2023-09-01 22:47 UTC, yalgaer commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteFeatureDbi.cpp
> +    CHECK(!objectIdsToSearch.isEmpty(), result);
Почему баг будет воспроизводиться если не менять? Если не будет фильтра по объектам (objectIdsToSearch будет пустым) - то размер запроса не вырастет, правильно?

2023-09-01 23:04 UTC, rasputinkirill commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteFeatureDbi.cpp
> +    CHECK(!objectIdsToSearch.isEmpty(), result);
Вот этот баг будет воспроизводиться https://github.com/ugeneunipro/ugene/pull/1356 , так как будет возвращена не пустая карта объектов. Я кстати там зря параметр по умолчанию убрал, верну.

2023-09-02 19:02 UTC, yalgaer commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteFeatureDbi.cpp
> +    CHECK(!objectIdsToSearch.isEmpty(), result);
Тогда вернемся на шаг назад: в описании метода говорится
```* If @desiredObjectIdsToSearch is not empty search only in that objects.```

то есть параметр опционален. Без него будет поиск во всех объектах

Ты поменял это поведение и это уже не маленькая оптимизация.
 
Возможно этот метод неправильно используется в том коде, на который ты сослался - значит надо править тот код, но никак не этот метод. Реализация метода же должена соответствовать описанию.

Похоже этот патч становится слишком большим для включения в патч релиз - можно его отложить. 
Но чтобы его залить нужно сделать правильно - как написано в документации метода.

2023-09-04 00:20 UTC, rasputinkirill commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteFeatureDbi.cpp
> +    CHECK(!objectIdsToSearch.isEmpty(), result);
Можно поменять и поведение и его описание, этот метод используется только тут.

2023-09-04 02:50 UTC, yalgaer commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteFeatureDbi.cpp
> +    CHECK(!objectIdsToSearch.isEmpty(), result);
Можешь поменять метод и доку для него. Тогда надо будет убрать пустое значение по умолчанию для списка, так как оно будет уже невалидным.

2023-09-04 17:10 UTC, yalgaer commented
На текущее состояние замечаний нет. Пропусти тесты и approve.

2023-09-05 15:47 UTC, yalgaer approved these changes

2023-09-05 19:21 UTC, merged