UGENE-7902 Unclear "wrong output format" when Sanger alignment fails
ugeneunipro/ugene pull request #1427
Opened 2023-09-25 11:02 UTC by rasputinkirill

Пойдет такое исправление?
Если нормально, то приступлю к https://ugene.dev/tracker/browse/UGENE-7901

2023-09-25 11:56 UTC, yalgaer requested changes
Наличие файла с логом на самом деле полезно, чтобы иметь возможность проанализировать детали ошибки, но это не первостепенно.

В первую очередь надо захватить std-error вывод процесса и показать его пользователю. В std-error должна уже быть  конкретная ошибка.

Показывать std-error вывод и считать что задача завершена с ошибкой нужно если дочерний процесс завершился с кодом ошибки. Если кода ошибки нет - все ожидаемые файлы должны быть на месте: иначе это уже внутренняя ошибка UGENE.

2023-09-25 12:37 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        CHECK_EXT(QFile::exists(settings.resultAlignmentFile), setError(tr("There is no result file after align, please, investigate the log file for errors: %1").arg(alignToRefCmdlineConfig.outputFi
Я думаю, что не нужно здесь работать с файловой системой и проверять наличие файла. Аналогичной проверкой является проверка форматов двумя строками ниже. Нужно убрать ничего не значащую фразу "wrong output format" и заменить ее на текущий отчет об ошибке.

2023-09-25 12:39 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        CHECK_EXT(QFile::exists(settings.resultAlignmentFile), setError(tr("There is no result file after align, please, investigate the log file for errors: %1").arg(alignToRefCmdlineConfig.outputFi
There is no result file after **align** - align это глагол "выравнивать", существительное в данном случае будет alignment, но лучше здесь использовать что-то вроде фразы "процесс выравнивания" (the alignment process)

2023-09-25 12:43 UTC, DmitriiSukhomlinov commented
Нужно дописать в отчет об ошибке ту самую ошибку, с которой свалился процесс, который делает вычисления. Сейчас информация о расчете пишется на стадии `run()` у класса `WorkflowRunFromCMDLineBase` и в этом проблема - если до этой стадии не доходит, то никакая информация не записывается. Нужно перенести запись статуса куда-нибудь в `WorkflowRunFromCMDLineBase::report()` и там же писать ошибку, если что-то сломалось

2023-09-25 12:44 UTC, DmitriiSukhomlinov commented
И не хватает файла с трансляцией

2023-09-25 22:53 UTC, rasputinkirill commented
> В первую очередь надо захватить std-error вывод процесса и показать его пользователю. В std-error должна уже быть конкретная ошибка.

`ugenecl` не пишет ничего в поток ошибок приложения, весь лог выполнения WD схемы это стандартный вывод.
То есть то что показываем пользователю в файле. Можем пропарсить его найти все записи начинающиеся с "[ERROR]" и выдавать пользователю в логе GUI-юджина, хочешь так?

> Я думаю, что не нужно здесь работать с файловой системой и проверять наличие файла. Аналогичной проверкой является проверка форматов двумя строками ниже. Нужно убрать ничего не значащую фразу "wrong output format" и заменить ее на текущий отчет об ошибке.

Ну я подумал так логичней будет - типа не получили на выходе файла, чето не так сработало на предыдущем шаге - смотри лог. А если файл есть но не того формата, то уже чето другое случилось. В конкретном сценарии же у нас как раз такая проблема что файл не появился.

> Нужно дописать в отчет об ошибке ту самую ошибку, с которой свалился процесс, который делает вычисления. Сейчас информация о расчете пишется на стадии `run()` у класса `WorkflowRunFromCMDLineBase` и в этом проблема - если до этой стадии не доходит, то никакая информация не записывается. Нужно перенести запись статуса куда-нибудь в `WorkflowRunFromCMDLineBase::report()` и там же писать ошибку, если что-то сломалось

Вот так и попытался переделать. В задаче чето это для меня немного неясно было написано.

2023-09-26 03:36 UTC, DmitriiSukhomlinov commented
Насчет моих замечаний - я написал, что нужно сделать и их нужно все поправить, а именно:

1. Проверку файла убрать. Чекать расположение файла в файловой системе не правильно, у нас есть другие способы проверять, прошла задача успешно или нет.
2. "wrong output format" убрать - это абсолютно бессмысленная фраза, она не говорит о произошедшей проблеме ничего ни пользователю, ни даже нам. Заменить эту фразу на текущую генерацию репорта с путем до лога и ошибкой, которая пришла от дочернего процесса.
3. В `WorkflowRunFromCMDLineBase::run()` пишется файл с определенной информацией о том, что произошло в дочернем процессе. Если таска упала, не дойдя до `run()`, то никакой записи не произойдет. Поэтому, надо перенести ее в `WorkflowRunFromCMDLineBase::report()`, которая вызывается всегда, даже если таска упала.
4. Добавить в файл информацию об ошибке, если таска упала. Эту ошибку выводить в отчет.
5. Обновить трансляции. Мы уже много лет делаем это каждый самостоятельно.

2023-09-26 03:50 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +            writeReport(errorStr);
Твое исправление, конечно, поправит проблему в данном конкретном месте, но не изменит ситуацию в целом. Любая ошибка выполнения может произойти в любом месте, а не только на данной конкретной валидации. Если она произойдет, то мы снова не провалимся в `run()` и снова не получим отчет. Нужно поправить ситуацию в целом. Какое исправление требуется:

1. Избавиться от функции `run()`. В ней не происходит ничего, кроме записи файла с репортом, а мы, как уже стало понятно, не можем рассчитывать на то, что у нас не будет ошибок на предыдущих этапах и, соответственно, что `run()` будет вызвано.
2. Нужно добавить таске соответствующий флаг `NO_RUN` или как-то так он называется.
3. Добавить таске функцию `report()`. Эта функция вызывается **всегда**, вне зависимости от того, прошла таска успешно или нет.
4. Таска имеет свойство `stateInfo`. Если в ходе исполнения произошла ошибка, то эта ошибка будет записана именно туда. Нужно проверить `stateInfo` на наличие ошибки и, если они есть, то записать ее в файл

2023-09-26 20:34 UTC, rasputinkirill commented
Вроде все поправил, только не понял что с этим делать:

> 1. Проверку файла убрать. Чекать расположение файла в файловой системе не правильно, у нас есть другие способы проверять, прошла задача успешно или нет.

Как мы можем проверять из GUI таски  которая запущена во внешнем `ugenecl `который стартует через `CmdlineInOutTaskRunner`, а он выдает ошибку только если запускаемый процесс вернул 1. Собственно для этого в конфиге и передается путь до файла в параметре `"ugene-write-task-report-to-file`, как сейчас и сделано.

2023-09-27 03:45 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        CHECK_EXT(file.open(QIODevice::ReadOnly | QIODevice::Text), setError(tr("No report file after align, please, investigate the output file for errors: %1")
В конце забыл точку с запятой, у тебя Линукс из-за этого не скомпилировался

2023-09-27 03:45 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        CHECK_EXT(file.open(QIODevice::ReadOnly | QIODevice::Text), setError(tr("No report file after align, please, investigate the output file for errors: %1")
У остальных CHECK аналогично

2023-09-27 03:47 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/transl/russian.ts
> +        <translation type="vanished">wrong output format</translation>
Запускти с флагом `-no-obsolete` чтобы убрать трансляции, которые больше не используются

2023-09-27 03:53 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    CHECK(workflowRunTask != nullptr || stateInfo.hasError(), res);
Я сейчас может что-то не понял, но ты выходишь из функции на этом месте, если у тебя `stateInfo` содержит ошибку. Как тогда ты ниже записываешь эту ошибку в файл?

2023-09-27 04:08 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    reportFile.write(!stateInfo.hasError() ? workflowRunTask->generateReport().toLocal8Bit() : "[ERROR] " + stateInfo.getError().toLocal8Bit());
В данном файле отчет имеет определенную структуру и записан в формате XML. Здесь ты просто дописываешь текст с конца, без какой-либо структуры. Так делать не надо, поскольку это может создать проблемы с последующим чтением этого файла - его форматирование может просто не распознаться. Если ты записываешь ошибку в файл, то ты должен поддержать формат XML.

2023-09-27 04:13 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +void WorkflowRunFromCMDLineBase::writeReport(const QString& errorString) {
Пустая функция, можно удалить

2023-09-27 04:18 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
>          DocumentFormat* format = formats.first().format;
Вероятно, еще вот эта строчка является причиной ошибки компиляции на Линуксе - переменная `format` не используется

2023-09-27 04:20 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        QFile file(alignToRefCmdlineConfig.reportFile);
> Вроде все поправил, только не понял что с этим делать:
> 
> > 1. Проверку файла убрать. Чекать расположение файла в файловой системе не правильно, у нас есть другие способы проверять, прошла задача успешно или нет.
> 
> Как мы можем проверять из GUI таски которая запущена во внешнем `ugenecl `который стартует через `CmdlineInOutTaskRunner`, а он выдает ошибку только если запускаемый процесс вернул 1. Собственно для этого в конфиге и передается путь до файла в параметре `"ugene-write-task-report-to-file`, как сейчас и сделано.

Нужно убрать проверку вот этого файла, а не файла с логом или чем там. Вместо нее - detect format

2023-09-27 04:33 UTC, DmitriiSukhomlinov commented
Насчет комментария Юли

Есть две такие функции - `QProcess::readAllStandardOutput()` и `QProcess::readAllStandardError()`. С их помощью родительский процесс может читать лог дочернего и таким образом получать информацию о том, что да как там отработало. Как я понял, Юля хочел, чтобы ты читал возникающие в дочернем процессе ошибки с их помщью. Я не уверен, что оно того стоит, сейчас взаимодействие между процессами налажено через промежуточный файл, использовать две системы взаимодействия одновременно мне кажется избыточным. 

Однако, я был бы непротив полностью перевести взаимодействие на использование указанных выше функций (вместо промежуточного файла) - это нативнее и удобнее. Я точно помню, что текущее взаимодействие через файл делал я и я просто не знал тогда, что можно сделать то же самое через эти две функции. Если делать это, то я бы сказал, что можно вынести в отдельную задачу, но лучше обсуди этот момент с Юлей

2023-09-27 09:58 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        CHECK_EXT(file.open(QIODevice::ReadOnly | QIODevice::Text), setError(tr("No report file after align, please, investigate the output file for errors: %1")
CHECK_EXT довольно длинный, поэтому в несколько строчек, там есть точка с запятой.

2023-09-27 10:08 UTC, rasputinkirill commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    CHECK(workflowRunTask != nullptr || stateInfo.hasError(), res);
Тут все нормально, мы остаемся в функции если `workflowRunTask` нулевой, а `stateInfo` содержит ошибку. В этом случае мы пишем эту ошибку в отчет далее по коду.

2023-09-27 10:46 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        QFile file(alignToRefCmdlineConfig.reportFile);
Здесь мы как раз и смотрим файл отчета и ищем в нем строчку с "[ERROR]" на основании чего и делаем вывод о наличии ошибок во время исполнения. Если файл не открылся - значит чето то пошло не так и ugenecl не запускался даже. Так что эту проверку надо оставить. Проверку формата давай верну.

2023-09-27 11:19 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    CHECK(workflowRunTask != nullptr || stateInfo.hasError(), res);
Да, точно

2023-09-27 11:22 UTC, rasputinkirill commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    reportFile.write(!stateInfo.hasError() ? workflowRunTask->generateReport().toLocal8Bit() : "[ERROR] " + stateInfo.getError().toLocal8Bit());
Ну вообще далеко не во всех `generateReport()` возвращается html, сделаю вот так - `QString res = "<br>[ERROR]: " + stateInfo.getError() + "</br>";`, пойдет?

2023-09-27 11:35 UTC, yalgaer commented
> > В первую очередь надо захватить std-error вывод процесса и показать его пользователю. В std-error должна уже быть конкретная ошибка.
> 
> `ugenecl` не пишет ничего в поток ошибок приложения, весь лог выполнения WD схемы это стандартный вывод. То есть то что показываем пользователю в файле. Можем пропарсить его найти все записи начинающиеся с "[ERROR]" и выдавать пользователю в логе GUI-юджина, хочешь так?

Даже если окажется что файл есть, но процесс завершен с ошибкой - продолжать не нужно.

Ошибку можно взять из лога: если у нас действительно нет различия между stderr и stdout то можно распарсить по префиксу.

Что там произошло внутри дочернего процесса - родительский может и не знать все детали. Поэтому гадать с файлом не нужно. Но правильно передать сообщение об ошибке родительский процесс должен.

Если говорить о минимальном фиксе - достаточно проверить exit-code и показать error-log  в отчете.

2023-09-27 12:16 UTC, rasputinkirill commented
Возможно я не совсем понимаю, какое ты хочешь исправление.
Про exit code - если ugenecl вернет не 0 то таска CmdlineTaskRunner который его запускала завершится с ошибкой которая будет отображена пользователю, так как у нас в `onSubTaskFinished(Task* subTask)` всегда есть такая проверка `CHECK(!subTask->isCanceled() && !subTask->hasError(), result);`

Если в процессе выполнения схемы появилась ошибка она будет в логе, который мы сохраняем.
Соответственно, после того как отработает `ugenecl` мы ищем в логе строку "[ERROR] Task {Workflow run from cmdline} finished with error:", если она есть - то выводим пользователю эту конкретную ошибку и предлагаем ознакомиться с логом.
Если нет - удаляем файл с логом и работаем дальше.
Файл отчета (report) нам тут не нужен и мы его не используем.
Правильно понял?

2023-09-27 12:28 UTC, rasputinkirill commented
Закоммитил покачто исправления замечаний от Димы

2023-09-28 07:46 UTC, DmitriiSukhomlinov commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    QString res = "<br>[ERROR]: " + stateInfo.getError();
Тэг `<br>`, означающий перенос строки в HTML, не имеет никакого отношения к XML. Есликто-то через год-другой посмотрит на этот файл, то вообще не поймет, почему он имеет такой странный невалидный формат и как оно вообще должно работать. Исправление должно быть сделано правильно и качественно.

Данный файл состоит из блоков <div>...</div>, содержащих информацию о прошедших тасках. Он выглядит вот так:
![image](https://github.com/ugeneunipro/ugene/assets/26257527/fc58f37c-7ddf-4b5f-a1c2-733efbc2b593)

Если один блок вложен в другой, то вложенный блок соответствует дочерней таске. Сейчас данный отчет пишется для всех тасок, кроме таски верхнего уровня `WorkflowRunFromCMDLineBase`. Нужно добавить эту таску верхнего уровня в данный отчет и туда писать ошибку, если она возникает. Так же, нужно поправить функцию `splitReports`, которая в файле AlignToReferenceBlastDialog.cpp парсит получившийся репорт, чтобы в ней первым делом проверялось наличие ошибки. Такое решение было бы наиболее правильным.

Но все это я бы посоветовал тебе делать только после того, как ты разберешься, что хочет от тебя Юля. Лично я тебе с этим не могу помочь, т.к. сам не до конца понимаю. Речь идет про какой-то error-code - как я понимаю, под этим кодом подразумевается значение, которое возвращает дочерний процесс ugenecl. Но дело в том, что возвращаемое значение процесса показывает, насколько успешно отработал сам ugenecl, а не его таска. По простому говоря, даже если выравнивание по Сэнгеру завершается с ошибкой, то ugenecl все равно возвращает 0 и я считаю это правильным решением - само выполнение прошло успешно, тот факт, что из-за невалидных данных расчет не завершился не означает, что сам процесс имел какие-то проблемы в выполнении.

Если вообще поставить вопрос ребром, то мне кажется, что запуск выравнивания по Сэнгеру в отдельном процессе в принципе не самое удачное решение и идеальным фиксом было бы перенести этот расчет в главный процесс, но это уже более масштабная задача.

2023-09-28 12:21 UTC, yalgaer requested changes
Я уже два раза писала нужное решение, пишу в третий раз:

1. Проверь exit code запущенного процесса. 
2. Если он не успешен - покажи error log этого процесса в репорте.

Все что нужно - это коротко и четко показать пользователю правильную ошибку.

Если процесс закончился без ошибок, а файла нет - правильная ошибка будет "Файл должен быть а его нет".

2023-09-30 01:58 UTC, rasputinkirill commented
Так, опять все переделал.

Вроде работает - внятная ошибка появляется в логе.
Мне кажется код который я убрал из `CmdlineTaskRunner::sl_onReadStandardOutput()` надо вернуть, по-моему он нужен для тестирования в тимсити, а так он вроде как ваще не нужен (ну это я уже после того как закоммитил подумал).

Дима, я попробовал реализовать отчет в таске в случае ошибки, но это по моему ерунда. Потому что в дефолтном отчете ошибка и так написана см. картинку. Так что мне кажется можно убрать (ну по крайней в этой конкретной таске, так то изменение репортов можно оставить).
![image](https://github.com/ugeneunipro/ugene/assets/17490668/383da906-10d3-4efd-851e-2779b339d159)

Юля, я реализовал завершение ugenecl с кодом ошибки, вроде работает. Но потом переделал чтение вывода и оно и без этого теперь работает. Так что посмотри, если что оставим. Пока не знаю завалит это тесты или нет.

Трансляции обновлю как уже к консенсусу придем.

2023-10-02 15:06 UTC, yalgaer requested changes

2023-10-02 15:06 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +        setError(errorStr);
Так не пойдет:в запускаемом таске может быть любая ошибка с логе: например не загрузился плагин. Из этого не следует что сам таск завершился с ошибкой. Только exit code говорит о том успешно ли завершился процесс.

2023-10-02 15:06 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.cpp
> +    connect(ts, SIGNAL(si_topLevelTaskUnregistered(Task*)), SLOT(startShutdown()));
Используй в новом коде указатели на функции для сигналов. Они приверяются в момент компиляции.

2023-10-02 15:06 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.cpp
> +        connect(ts, &TaskScheduler::si_stateChanged, this, &ConsoleShutdownTask::sl_shutdownOnTaskError);
Любая ошибка для shutdown не подойдет.
CMD-line процесс должен вернуть код ошибки только если его основная задача завершилась с ошибкой.
Об основной задаче знает тот, кто ее запускает - думаю это код парсит параметры запуска

2023-10-04 06:08 UTC, yalgaer requested changes

2023-10-04 06:08 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +    const QString pattern = tr("} finished with error:");
Проносить ошибку так наверх в запускающий таск не нужно: ошибок может быть много и выбирая первую мы можем выбрать неправильную: не связанную с реальным падением.

В запускающем таске достаточно устаносить базовую ошибку: "Запускаемый таск закончился с ошибкой" а уже в отчет вывести все ошибки из лога запущенного таска.

2023-10-04 06:08 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.cpp
> +            QCoreApplication::exit(exitCode);
Может ли здесь exitCode быть 0 (успех) ?

2023-10-04 10:37 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.cpp
> +            QCoreApplication::exit(exitCode);
Да может, если возникла ошибка в запускаемой сабтаске `CancelAllTask()`.

2023-10-04 10:48 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +    const QString pattern = tr("} finished with error:");
То есть возвращаем сюда старый код который был с `ERROR_KEYWORD`. Сохраняем весь лог в файл. Если был выход из консольного приложения с кодом 1 - то уже в таске верхнего уровня  (`AlignToReferenceBlastCmdlineTask`) анализируем лог и пишем в отчете все строчки с "[ERROR]".  Если был выход из консольного приложения с кодом 0 - удаляем файл.
В лог в итоге попадает только то, что напишет метод `CmdlineTaskRunner::writeLog`.
Правильно я понял?

2023-10-05 12:48 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +    const QString pattern = tr("} finished with error:");
Никакого файла не нужно: если дочерний процесс завершился с кодом ошибки покажи error лог в репорте у родителя.

2023-10-06 11:55 UTC, yalgaer requested changes

2023-10-06 11:55 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +            processErrorLog += "[" + logLevelErrorName + "]" + logLine + "\n";
Тут можно не создавать новую строку - достаточно включить огининальную как есть.

2023-10-06 11:55 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +    QStringList combineMultiLines({""});
Какой смысл пустой строки в начале списка?

2023-10-06 11:55 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +        QString logLine = line.mid(closePos + 1);
Этот метод после твоих изменений теперь принимает `logMessages` но не `logLines`

2023-10-06 11:55 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.h
> +    QString getProcessErrorsLog() const;
Все публичные методы должны быть задокументированы

2023-10-06 11:55 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.cpp
> +        coreLog.info("Shutdown because of task error");
info сообщения должны быть переведены

2023-10-06 11:55 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.h
> +    bool exitAppOnTaskError;
Инициализируй значением по умолчанию

2023-10-06 11:55 UTC, yalgaer commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.h
> +    Task::ReportResult report();
Добавь override

2023-10-06 11:55 UTC, yalgaer commented on src/ugenecl/src/Main.cpp
> +    ConsoleShutdownTask watchQuit(&app, true);
Нужна ли эта переменная? Кажется нет другого варианта использования этого таска?

2023-10-06 11:55 UTC, yalgaer commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    reportFile.write(!stateInfo.hasError() ? workflowRunTask->generateReport().toLocal8Bit() : getReportFromError());
Зачем нужно менять это поведение? Ошибка в случае exitCode !=0 парсится из output, правильно?

2023-10-06 11:55 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        reportString = reportFile.readAll();
Есть открытие но нет закрытия файла.
У нас есть утилитный метод чтобы прочитать все содержимое файла в 1 строку безопасно.

2023-10-06 11:55 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        reportString = "<br><table><tr><td><b>" + tr("Error log: ") + "</b></td><td>" + reportString + "</td></tr></table>";
Добавить ссылку на файл с полным логом. 
Или добавить полный лог в конец репорта, чтобы не потерять детали которые были раньше.

2023-10-06 12:10 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +    QStringList combineMultiLines({""});
У меня было при одном из запусков проблема что первая строчка из анализируемых была "                          [TRACE][19:08]..." и из-за того что не было элементов в списке случилось падение.

2023-10-06 12:32 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.h
> +    bool exitAppOnTaskError;
Код на 33 строке не подходит?

2023-10-06 19:47 UTC, rasputinkirill commented on src/ugenecl/src/Main.cpp
> +    ConsoleShutdownTask watchQuit(&app, true);
C:\src\ugene2\src\plugins_checker\src\Main.cpp:148

2023-10-06 19:51 UTC, rasputinkirill commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    reportFile.write(!stateInfo.hasError() ? workflowRunTask->generateReport().toLocal8Bit() : getReportFromError());
workflowRunTask будет нулевым и будет падение Просто выйти из функции в данном случае.?

2023-10-06 20:01 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        reportString = "<br><table><tr><td><b>" + tr("Error log: ") + "</b></td><td>" + reportString + "</td></tr></table>";
Опять ничего не понимаю :rage::rage::rage::rage:, в прошлой итерации ты мне пишешь: `Никакого файла не нужно: если дочерний процесс завершился с кодом ошибки покажи error лог в репорте у родителя.` в reportString у нас сообщения в уровнем [ERROR], А теперь как, тут должен быть весь лог с уровнем [DETAILS] или как? Или какой файл создать?

2023-10-06 20:02 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +        QString logLine = line.mid(closePos + 1);
Это предложение переименовать переменные?

2023-10-06 20:05 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +            processErrorLog += "[" + logLevelErrorName + "]" + logLine + "\n";
Не понял, хочешь так `processErrorLog += logLine + "\n";`, или так `processErrorLog += logLine;`, опять не понял что от меня требуется :tired_face:.

2023-10-07 12:27 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +        QString logLine = line.mid(closePos + 1);
Да. Правильно используемое имя переменной или функции заменяет документацию

2023-10-07 12:30 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +            processErrorLog += "[" + logLevelErrorName + "]" + logLine + "\n";
Ты сначала парсишь а потом конструируешь то же самое что было изначально.
Этот код сделает то же, что и у тебя?
```
processErrorLog += line + "\n";
```
где `line` это твой изначальный logMessage из переданного функции массива сообщений?

2023-10-07 12:32 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +    QStringList combineMultiLines({""});
Имеешь в виду здесь?
```
 combineMultiLines.last()
```
Если да, то тут можно добавить поверку на пустой список.

2023-10-07 12:32 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.cpp
> +    SAFE_POINT(nEnabled == 0, ConsoleShutdownTask::tr("No services must be enabled"), nullptr);
nit: safe points можно не переводить

2023-10-07 12:33 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.cpp
> +            coreLog.trace(tr("Canceling: %1").arg(t->getTaskName()));
nit: trace можно не переводить

2023-10-07 12:35 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/ConsoleShutdownTask.h
> +    bool exitAppOnTaskError;
нет, если я решу добавить новый конструктор я могу забыть об этой переменной. Проблемы должны решаться на месте явно без подразумеваемового "правильного использования во всех других местах".

2023-10-07 12:39 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        reportString = "<br><table><tr><td><b>" + tr("Error log: ") + "</b></td><td>" + reportString + "</td></tr></table>";
Никакой новый файл создавать или читать в базовом CMDLineTask не нужно.

Если файл с отчетом уже был в другом таске (AlignToReferenceBlastCmdlineTask) то его поведение нужно сохранить: если он показывался - продолжай показывать его и дальше.
Если нужно выделить ошибку - можно либо вынести ее в начала отчета (все строки с ошибками тк лучше не умеем)

Здесь ты убрал показ reportFile - это изменение поведения. Если думаешь что так правильно, пожалуйста поясни почему?

2023-10-07 12:42 UTC, yalgaer commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    reportFile.write(!stateInfo.hasError() ? workflowRunTask->generateReport().toLocal8Bit() : getReportFromError());
Раньше этой проблемы/состояния не было:
```
CHECK(workflowRunTask != nullptr, );
```
Поэтому я и спрашиваю зачем ты решишь ее решать?

2023-10-09 02:43 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +            processErrorLog += "[" + logLevelErrorName + "]" + logLine + "\n";
Но я так понял что мы хотим не все сообщения, а только c уровнем ERROR, поэтому парсим и отделяем только то что надо.

2023-10-09 02:54 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +    QStringList combineMultiLines({""});
Можно и так.

2023-10-09 03:03 UTC, rasputinkirill commented on src/plugins/workflow_designer/src/cmdline/WorkflowCMDLineTasks.cpp
> +    reportFile.write(!stateInfo.hasError() ? workflowRunTask->generateReport().toLocal8Bit() : getReportFromError());
Так как мы перенесли этот код из run() в report() этот метод запускается в любом случае после отработки таски, и так как он делает на выходе файл содержащий отчет о запуске я сделал чтобы был файл и в случае неудачного завершения таски. Тем более мы можем в него вписать некую диагностическую информацию. Могу убрать чтобы фйала отчета не было.

2023-10-09 03:36 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        reportString = "<br><table><tr><td><b>" + tr("Error log: ") + "</b></td><td>" + reportString + "</td></tr></table>";
`reportFile `здесь - это файл отчета который генерится в WorkflowCMDLineTasks.cpp который  в прошлом замечании ты предлагаешь не писать если вернуть условие `CHECK(workflowRunTask != nullptr, );`, предположим оставили поведение как в предыдущих правках - получаем такую картину:
![image](https://github.com/ugeneunipro/ugene/assets/17490668/3fd79230-6a57-4df8-bbfb-f3f21c7d86d5)
То есть абсолютно одинаковые сообщения и там и там.
Если сделать как ты пишешь и не писать файл отчета то после "TASK REPORT" будет пусто.
Если оставить как есть то будет просто то что сейчас есть до "TASK REPORT".
Я же еще до этого картинку прилагал что дублирование сообщений вылезает, там правда они были на других уровнях так сказать.

Мне кажется хороший вариант убрать написание файла отчета в случае ошибки в WorkflowCMDLineTasks.cpp как ты и предлагаешь, и не показывать его тут. Показывать только в случае успешной работы.

2023-10-09 16:03 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CmdlineTaskRunner.cpp
> +            processErrorLog += "[" + logLevelErrorName + "]" + logLine + "\n";
Правильно, нужно парсить и проверять. Если проверка положительно добавлять оригинальное сообщение - не нужно конструировать его заново

2023-10-09 16:05 UTC, yalgaer commented on src/plugins/external_tool_support/src/blast/AlignToReferenceBlastDialog.cpp
> +        reportString = "<br><table><tr><td><b>" + tr("Error log: ") + "</b></td><td>" + reportString + "</td></tr></table>";
хорошо

2023-10-09 16:07 UTC, yalgaer reviewed
Жду тестов и апрувлю

2023-10-10 13:05 UTC, yalgaer approved these changes, later dismissed

2023-10-10 13:10 UTC, yalgaer approved these changes

2023-10-10 13:12 UTC, merged