UGENE-7947 Can't select annotation on the zoom view if this annotation is very short, but sequence is very long
ugeneunipro/ugene pull request #1431
Opened 2023-10-03 09:43 UTC by DmitriiSukhomlinov

2023-10-03 09:48 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    U2Region pointRegion(pos - 2 * uncertaintyLength, 1 + 3 * uncertaintyLength);  // A region of sequence covered by the 'QPoint& coord'.
If annotation is very short it has 3 pixels length, not 2.

2023-10-03 09:50 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/view_rendering/SequenceViewRenderer.cpp
> +    return qFloor(res);
The same problem as in https://github.com/ugeneunipro/ugene/pull/1429, but for the backward function

2023-10-05 13:08 UTC, yalgaer requested changes

2023-10-05 13:08 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +const int GSequenceLineViewAnnotated::getClosestAnnRegion2PointIndex(Annotation* ann, qint64 pos) {
1. Do not use slang, use To instead of 2
2. Use full names: Ann->Annotation
3. I do not know what is pointIndex without reading docs: is it an on-screen point or a base position?

2023-10-05 13:08 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    auto minimumDistance = (std::numeric_limits<qint64>::max)();
This should be documented. As a reader of the code I'm stuck reading minDistance = max-int64.... The braces around ::max are also look strange

2023-10-05 13:08 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    U2Region pointRegion(pos - 2 * uncertaintyLength, 1 + 3 * uncertaintyLength);  // A region of sequence covered by the 'QPoint& coord'.
You should change the `uncertaintyLength` itself, but do not introduce some magic scales around it.

2023-10-05 13:08 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/view_rendering/SequenceViewRenderer.cpp
>      double res = (double)(pos - visibleRange.startPos) * getCurrentScale();
nit: looks like we do not need a cast here.

2023-10-06 07:59 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +const int GSequenceLineViewAnnotated::getClosestAnnRegion2PointIndex(Annotation* ann, qint64 pos) {
1. OK
2. OK
3. The description's been added.

2023-10-06 08:09 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    auto minimumDistance = (std::numeric_limits<qint64>::max)();
I added some comments, but from my point of view this code was pretty obvious.

See [here](https://stackoverflow.com/a/2561377/7273346) why do I have this bracers.

2023-10-06 08:09 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/view_rendering/SequenceViewRenderer.cpp
>      double res = (double)(pos - visibleRange.startPos) * getCurrentScale();
OK

2023-10-06 10:14 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    U2Region pointRegion(pos - 2 * uncertaintyLength, 1 + 3 * uncertaintyLength);  // A region of sequence covered by the 'QPoint& coord'.
Oh, that's my favorite place. Someone used wrong constants here when was writing this code and now I need to explain why did I change them to the correct ones.

Короче, что-то сложно и писать походу много, так что продолжу на русском. 

Со значением `uncertaintyLength` никаких проблем нет. Оно показывает, сколько сиволов у нас умещается в один пиксель и его менять не надо, оно всегда вычисляется правильно. 

Проблема тут следующая.

Если аннотация получается слишком мальенькой, то она рисуется в минимальную ширину в три пикселя. Эта ширина вычисляется [вот тут](https://github.com/ugeneunipro/ugene/blob/05e1e09a5c45fb638716721a9b2d3fb2a09411af/src/corelibs/U2View/src/ov_sequence/view_rendering/SequenceViewAnnotatedRenderer.cpp#L159C70-L159C70). `MIN_ANNOTATION_WIDTH` на данной строчке равна трем. Там есть еще одна переменная `MIN_SELECTED_ANNOTATION_WIDTH`, т.е. ширина аннотации, если она выделена, и она уже равна четырем, но если аннотация выделена, то она имеет форму не правильного четырехугольника, а треугольника, где последний пиксель приходится на наименее широкую часть:
![image](https://github.com/ugeneunipro/ugene/assets/26257527/bef7f241-66e0-4ee7-a79b-b959b0d83ecb)

Я думаю, мы можем, на данный момент для упрощения просто посчитать, что она исключается из региона аннотации, по которому надо кликнуть, чтобы аннотация оказалась выделена, поскольку она визуально очень маленькая и пользователь все равно будет пытаться кликнуть именно по широкой части треугольника. Впоследствии это можно поправить, но там, вероятно, придется переписать немалую часть кода, поскольку в функции `GSequenceLineViewGridAnnotationRenderArea::findAnnotationsByCoord` (где мы сейчас находимся) нет информации о том, выделена ли аннотация или нет, а она понадобится для этого определения.

Так вот, получается, что маленькие аннотации отображаются шириной в три пикселя. Так же есть важный момент - если у нас аннотация соответствует, условно, пикселю с номером 100, то отображать свои законные три пикселя ширины она будет **вперед**, то есть на пикселях 100, 101 и 102. С моей стороны, логичнее было бы отображать ее на пискеле с номером 100 и захватить еще по одному с краев, т.е в итоге это должно было быть 99, 100 и 101, но я просто решил оставить как есть и не переделывать, это имеет минимальное значение.

В данной функции (`GSequenceLineViewGridAnnotationRenderArea::findAnnotationsByCoord`) мы вычисляем, кликнули ли мы в район аннотации или нет. В данном случае, мы все переводим уже не в пиксели, а в позиции. И раньше регион аннотации вычислялся следующим образом: 

`U2Region pointRegion(pos - uncertaintyLength, 1 + 2 * uncertaintyLength);`

То есть есть пиксель, на который мы кликнули, он соответствует некой `pos`. мы отсупаем назад регион, соовтетсвующий еще одному пикселю (в символах последовательности это `uncertaintyLength`) и захватываем длину в две `uncertaintyLength`, то есть **два** пикселя. Возникает очевидное несоответствие - чуть выше мы выяснили, что аннотация рисуется в виде прямоугольника, шириной в **три** пикселя, то есть при клике на один пиксель у нас аннотация не выделится. Поскольку, как я уже писал, аннотация у нас рисуется **вперед** по отношению к пикселю, на котором находится, то при расчете региона клика нам наоборот нужно идти **назад**, чтобы захватить аннотированный регион.

Я проверил старые версии - эта проблема была в юджине **всегда**, даже когда выделение коротких аннотаций еще работало, просто никто не обращал на нее внимание. Полагаю, что её сделали еще когда только все это разрабатывалось, но никто не стал заниматься пиксельхантингом и не увидел (или решили что "и так пойдет").

Тут было много и сложно, поэтому если что, то советую просто потестировать и сравнить с предыдущими версиями, сразу будет видно, что раньше выделение коротких анотаций на длинных последовательностей работало плохо, а сейчас я эти проблему поправил

2023-10-06 10:16 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    U2Region pointRegion(pos - 2 * uncertaintyLength, 1 + 3 * uncertaintyLength);  // A region of sequence covered by the 'QPoint& coord'.
Существенной проблемой считаю то, что у нас нет синхронизации между классами, рисующими аннотацию, и текущим классом, где определяется ее позиция, но исправление этого потребует масштабного рефакторинга

2023-10-06 12:51 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    U2Region pointRegion(pos - 2 * uncertaintyLength, 1 + 3 * uncertaintyLength);  // A region of sequence covered by the 'QPoint& coord'.
Решение предложенное выше это workaround. Нужно решать правильно.

1. Добавить метод: `getAnnotationRegionXRange` который будет принимать один регион аннотации и ее состояние (например, выделили ли ее)

2. Использовать этот метод как при отрисовке, так и при поиске аннотаций по клику.

2023-10-06 12:54 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    auto minimumDistance = (std::numeric_limits<qint64>::max)();
Проблемы отдельных API не должны портить читаемость нашего кода. Добавить нужную константу (типа INT_MAX) с комментарием описывающим проблему и используй ее. 

Видеть проблемы и загадки в каждом месте где нам просто нужен INT64_MAX неправильно.

2023-10-09 06:05 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    auto minimumDistance = (std::numeric_limits<qint64>::max)();
Я не очень понял идею и что за проблему с читаемостью ты имеешь ввиду - что такое `std::numeric_limits` понятно даже не читая документацию - но я просто перепишу код, чтобы не использовать максимальное значение в принципе

2023-10-09 06:15 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    U2Region pointRegion(pos - 2 * uncertaintyLength, 1 + 3 * uncertaintyLength);  // A region of sequence covered by the 'QPoint& coord'.
Ну, короче, все-таки рефакторинг. ОК

2023-10-09 16:20 UTC, yalgaer reviewed
Минимальные замечания. Апрув после исправления и тестов

2023-10-09 16:20 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +QList<int> GSequenceLineViewGridAnnotationRenderArea::getAnnotationRegionsContainsXPoint(int x, Annotation* annotation, int locationRegionIndex, const AnnotationSettings* annotationSettings) const {
nit: нужно добавить `indexes` в имя метода: `getAnnotationRegionIndexesByXCoord`

2023-10-09 16:20 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +                CHECK_CONTINUE(annotationSettings->visible && xRegs.contains(yReg));
Проверку на as->visible нужно провести до остальных вычислений.

2023-10-09 16:20 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +const int GSequenceLineViewAnnotated::getClosestAnnotationRegionToPointIndex(Annotation* ann, qint64 baseNumber) {
nit: baseIndex звучит лучше чем baseNumber так как index подразумевает нумерацию с 0

2023-10-09 16:20 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    const auto& firstRegion = annotationRegions[closestAnnotationRegionIndex];
nit: ` const auto& firstRegion = annotationRegions.first();` будет более читаемо

2023-10-09 16:20 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    for (int i = 0; i < annotationRegions.size(); i++) {
нужно начать с единицы

2023-10-09 16:20 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.h
> +    /** Returns numbers of annotation region contains 'x' point. */
nit: numbers -> indexes

2023-10-10 03:18 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +QList<int> GSequenceLineViewGridAnnotationRenderArea::getAnnotationRegionsContainsXPoint(int x, Annotation* annotation, int locationRegionIndex, const AnnotationSettings* annotationSettings) const {
OK

2023-10-10 03:19 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +const int GSequenceLineViewAnnotated::getClosestAnnotationRegionToPointIndex(Annotation* ann, qint64 baseNumber) {
OK

2023-10-10 03:28 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    const auto& firstRegion = annotationRegions[closestAnnotationRegionIndex];
OK

2023-10-10 03:29 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    for (int i = 0; i < annotationRegions.size(); i++) {
Лучше с нуля, там еще идет проверка на то, что регион содержит индекс. Можно его, конечно, тоже вынести из цикла, но тогда получится целая итерация вынесена отдельно, как-то не очень

2023-10-10 03:40 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +                CHECK_CONTINUE(annotationSettings->visible && xRegs.contains(yReg));
OK

2023-10-10 03:40 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.h
> +    /** Returns numbers of annotation region contains 'x' point. */
OK

2023-10-10 11:50 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    auto minimumDistance = (std::numeric_limits<qint64>::max)();
Проблема с читаемостью в том что ты не пишешь
```
std::numeric_limits<qint64>::max()
```

а пишешь

```
(std::numeric_limits<qint64>::max)()
```

Что требует дополнительного пояснения/ссылок.

2023-10-10 12:49 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    for (int i = 0; i < annotationRegions.size(); i++) {
От этой проверки в случае baseIndex=0 ничего не меняется, так как  closestAnnotationRegionIndex = 0 еще до цикла

2023-10-11 02:32 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/GSequenceLineViewAnnotated.cpp
> +    for (int i = 0; i < annotationRegions.size(); i++) {
Формально, немного, но меняется - если мы кликнули на кусок аннотации с индексом 0, то на этой проверке мы выйдем из цикла на первой итерации, а если мы пропустим эту проверку, начав с индекса 1, то прогоним цикл по всем кускам аннотации. 

Там все тесты прошли (за исключением нестабильных), мне бы не хотелось прогонять все тесты еще раз из-за этого минорного коммита. Я могу поправить это в любой другой ближайшей задаче

2023-10-11 02:33 UTC, DmitriiSukhomlinov commented
Все тесты (кроме каких-то нестабильных) прошли

2023-10-11 12:38 UTC, yalgaer approved these changes

2023-10-12 02:42 UTC, merged