UGENE-7909 SAFE_POINT on enzyme disabling/enabling
ugeneunipro/ugene pull request #1434
Opened 2023-10-05 06:33 UTC by rasputinkirill

Были переоткрыты, исправление для обоих
UGENE-7927 SAFE_POINT on "Annotation highlighting" tab when at least one restriction site is visible
UGENE-7909 SAFE_POINT on enzyme disabling/enabling

2023-10-05 13:19 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/PanView.cpp
> +            if (rowsManager->getAnnotationRowIdx(a) != -1 && as->visible) {
Почему если аннотация видима у нее может не быть ряда в PanView?
+ Нужен GUI тест демонстрирующий проблему.

2023-10-06 23:41 UTC, rasputinkirill commented on src/corelibs/U2View/src/ov_sequence/PanView.cpp
> +            if (rowsManager->getAnnotationRowIdx(a) != -1 && as->visible) {
`as->visible` это состояние взятое из настроек, если аннотация уже видима - то мы не можем делать `rowsManager->addAnnotation(a);` так как там внутри CHECK на проверку этого, на котором и происходит падение. Поэтому сздесь и код проверки чтобы не делать видимые аннотации видимыми повторно. А так как это слот срабатывает на любые изменения настроек аннотации (не только на видимость\невидимость) вынуждены проверять. Мне кажется все достаточно понятно и проверяется текущим тестом или все еще требуется GUI тест на нажатие галочек на этой панели опций?

2023-10-07 12:15 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/PanView.cpp
> +            if (rowsManager->getAnnotationRowIdx(a) != -1 && as->visible) {
Если этот баг воспроизводится на текущем мастере и никакой тест при этом не падает, значит нужно добавить такой тест.

2023-10-07 12:26 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/PanView.cpp
> +            if (rowsManager->getAnnotationRowIdx(a) != -1 && as->visible) {
> если аннотация уже видима - то мы не можем делать rowsManager->addAnnotation(a);

Выше в коде у нас есть проверка:
```
if (as->visible == hasRow) {
            continue;
        }
```
То есть если аннотация видима и у нее уж есть row, то дальше не идем
Если же row не было - добавляются все аннотации с нужным именем

Твой код дублирует ту проверку выше, правильно? 
Более логичным было бы оставить проверку выше в качестве оптимизации, а в `rowsManager->addAnnotation(a)` не падать если аннотация уже добавлена - просто игнорировать этот вызов

2023-10-09 02:41 UTC, rasputinkirill commented on src/corelibs/U2View/src/ov_sequence/PanView.cpp
> +            if (rowsManager->getAnnotationRowIdx(a) != -1 && as->visible) {
Я сейчас проверил.
Имя аннотации и имя строчки (row) - разные вещи в данной ситуации.
"Restriction Site" и "Esp3I"
![image](https://github.com/ugeneunipro/ugene/assets/17490668/4e108544-4405-46dc-9b50-2c3ad9d9822a)
А вот например если добавлять аннотации вручную - то будет совпадать.
"misc_feature" и "misc_feature".
![image](https://github.com/ugeneunipro/ugene/assets/17490668/eb0a16b4-aca7-46f9-b78d-0e297e491d63)
Я уберу эту проверку на строках 310-313 так как получается что она не подходит.

2023-10-10 12:20 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/PanView.cpp
> +            if (rowsManager->getAnnotationRowIdx(a) != -1 && as->visible) {
Проверку убирать не нужно. Нужно исправить `hasRowWithName()` метод.
Далее как я писала + GUI тест

2023-10-11 12:46 UTC, yalgaer requested changes
Решение неверно. Все аннотации энзимов вне зависимости от их имени (имени энзима) пакуются в общие ряды RESTRICTION_SITE_NAME. У тебя нет на это проверки.

То что я имела в виду под заменой hasRowWithName->hasRowWithAnnotation должно содержать внутри код который правильно обрабатывает RESTRICTION_SITE_NAME: то есть hasRowWithAnnotation для энзима должно возвращать true если ряд для энзимов уже есть.

2023-10-12 00:06 UTC, yalgaer requested changes
Текущее решение тоже получилось некорректное - оно не будет работать если я создам аннотацию с тем же именем что и энзим: ты проверишь имя ряда по первой найденной аннотации из списка и проигнорируешь другие.

То есть зависишь от того какая аннотация будет первой в списке.

Думаю ты был прав в том, что это проверка не нужна: по одному имени нельзя вывести имя ряда - нужны 2 параметра: имя и тип - то есть вся аннотация.

Давай подумаем какое решение будет правильным.
Что если:
1) Ты уберешь проверку по имени rowsManager->hasRowWithName(name);
2) Найдешь все аннотации с нужным именем и вызовешь для них rowManager->addAnnotation/removeAnnotation
3) Внутри addAnnotation annotation проверишь добавлена ли она уже. Если да - просто выйдешь (noop), иначе добавишь как и раньше

Что думаешь?

2023-10-12 02:42 UTC, rasputinkirill commented
Да я тоже думал что такая неопределенность в поведении будет,  но она и так есть в текущем коде в мастере.  Можно саму эту систему раскрасок аннотаций изменить сначала например их по типу их определять и применять настройки к ним, а потом по имени, тип у нас пока что один "restriction site". Но это думаю в отдельной задаче.

А сейчас, получается, сделаем как было сделано мое прошлое решение?

2023-10-12 16:23 UTC, yalgaer approved these changes

2023-10-12 19:42 UTC, merged