UGENE-7957 Add Primer3 run without sequence
ugeneunipro/ugene pull request #1441
Opened 2023-11-01 06:40 UTC by DmitriiSukhomlinov

Было сделано много что.
Основная задача - запускать Primer3 без таргетной последовательности. Сам Primer3 предусматривает такую возможность, но только при определенных параметрах:

- Задача расчета выставлена на "check_primers""
- Как минимум один праймер (левый, правый или средний) задан
- Так же я потестил веб-тулы и они неявно автоматом выставляют "Pick anyway", который позволяет продолжать расчет, даже если заданные праймеры не подходят по каким-то заданным параметрам (например, не соответствуют заданой температуре плавления, GC-составу или еще там чему), поэтому я тоже по умочанию выставил эту галочку. 

Сам диалог запуска в точности повторяет диалог запуска с таргетной последовательностью, только все ненужные параметры задизейблены.

В результате создается последовательность с праймерами и N-ками между ними (аналогично работает [Primer3 web](https://primer3.ut.ee/)). Праймеры отмечены аннотациями с квалификаторами, аналогичными тем, что появляются при запуске с таргетной последовательностью.

Сам пункт меню находится в Tools -> Primer -> Primer3 (without target sequence)...

Дополнительно:

- Полностью отрефакторил вообще все, что было внутри проекта Primer3. Разделил классы, которые ютились по 3-4 штуки в одном .cpp файле. Переделал структуру тасок, сделав ее понятной - я бы даже сказал, очевидной. Т.е. теперь есть таска верхнего уровня с говорящим названием `Primer3TopLevelTask` и куча тасок, которые она по очереди запускает - сначала таски, которые делают расчет праймеров, потом преобразование результатов в аннотации, потом сохранение аннотаций в файл, затем открытие этого файла (если нужно). Сам `Primer3TopLevelTask` имеет два конструктора - один для случая, когда у нас есть таргетная последовательность, другой - если нет.
- Переделал систему тестирования. Раньше она была не очень хорошая, т.к. тестировала таску нижнего уровня `Primer3Task`, которая запускала непосредственно Primer3. Из-за этого проблемы, которые происходили "выше" (то есть в родительской таске, которая раньше называлась `Primer3ToAnnotationTask`) либо "слева и справа" (т.е. в других дочерних тасках `Primer3ToAnnotationTask`) фактически не отслеживались. Теперь система тестирования запускает непосредственно `Primer3TopLevelTask`. Тесты остались те же самые, пришедшие из самого Primer3, однако теперь последовательность, на которой они запускаются, вынесена в отдельный файл и загружается с помощью инструментов UGENE. Раньше она передавалась просто в виде аргумента самого Primer3 SEQUENCE_TEMPLATE. Из-за того, что это было сделано таким образом, тестирование запуска Primer3 без последовательности было раньше (были тесты, которые запускались без последовательности), но, по факту, ничего не проверяло. Теперь запуск Primer3 без последовательности происходит через таску `Primer3TopLevelTask`, в итоге проверяется созданная последовательность, аннотации, квалификаторы, все, что должно быть. Список тестов напишу ниже.
- Тестов стало чуть больше (1441 -> 1466) в счет того, что я нашел тесты, которые я не заметил, когда переделывал тесты из формата Primer3 в формат UGENE XML в прошлый раз. Однако, мне пришлось замьютить тесты на параметр, который называется Lowercase masking. Его смысл в том, что в последовательности, которая передается через SEQUENCE_TEMPLATE, можно написать маленькими буквами символы, которые должны обязательно входить в рассчитанные праймеры. Поскольку теперь мы не используем этот параметр, а загружаем последовательность средствами UGENE, она всегда передается с большими буквами. Я временно замьютил этот параметр и завел задачу на эту тему UGENE-7972.

2023-11-01 06:48 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/ImportSequenceFromRawDataTask.h
> +class U2GUI_EXPORT ImportSequenceFromRawDataTask : public Task {
Это надо убрать вместе с инклудом ниже

2023-11-01 06:51 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/runnables/ugene/plugins_3rdparty/primer3/Primer3DialogFiller.h
> +    static constexpr const int POSTERIOR_ACTIONS_TAB_NUMBER = 6;
Тут 7. Ни на что не повлияло, т.к. используется только в новом тесте, где проверяется, что вкладка с таким номером задизейблена, а 6 задизейблена тоже.

2023-11-01 23:40 UTC, yalgaer requested changes

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/primer3_core/libprimer3.cc
> +    int ls = -1, le = -1, regionSelector = -1, re = -1;
Так как это не наш файл лучше его не менять

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.h
> +}
Нужно убедиться что в конце каждого нового h файла есть пустая строка

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/PrimerSingle.cpp
> +void PrimerSingle::setSelfAnyStruct(const QString& selfAnyStruct) {
Какой смысл в десятках симметричных get/set методов? 
Нужно сделать переменные публичными, читаемость кода только возрастет.

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    bool openView;
nit: все примитивные параметры должны иметь значение по умолчанию

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    QPointer<Document> document;
Ради этого поля у класса есть деструктор (сложная логика).
Нужно описать смысл этого поля. Можно ли чистить документ раньше деструктора? По завершению таска. Это позволит не держать данные у уже завершившихся тасков.

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +                    .arg(seqObj->getSequenceName()));
Проверка pointer на isNull должна происходить при каждом использовании. Либо сохрани имя в переменну.

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +    } else {
nit: else не нужен

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        findExonsTask = new FindExonRegionsTask(seqObj, settings->getSpanIntronExonBoundarySettings().exonAnnotationName);
Подтаски TopLevelTask некорректно работают со ссылками на объекты (не используют QPointer)

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const int includedRegionOffset = includedRegion.startPos != 0 ? includedRegion.startPos - firstBaseIndex : 0;
неконсистентное использование const на примитивных типах внутри одной функции.
В UGENE мы не используем const на примитивах на внутренних переменных функции.

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const auto& includedRegion = settings->getIncludedRegion();
В данном случае возвращается значение, а не ссылка. С точки зрения стандарта мы тут имеем ссылку на временный объект (я знаю что компиляторы обходят этот баг как фичу, но писать так код все равно нет причин).

`U2Region includedRegion = ` будет и короче и точнее и лучше читаться чем `const auto& includedRegion =`. То есть "новояз" стоит использовать там, где он улучшает читаемость.

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +void Primer3Task::run() {
Этот метод содержит ядро того, как UGENE запускает primer3, но при этом на 80 строк кода нет ни одного комментария о логике внутри метода.

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +        stateInfo.setError(resultPrimers->per_sequence_err.data);
Ошибка перетирает ошибку выше.

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    for (qint64 junctionPos : junctions) {
qAsConst

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +        for (int idx : regionIndexes) {
qAsConst

2023-11-01 23:40 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const QList<U2Region>& regions = settings->getExonRegions();
Нужен комментарий описывающий логику кода в этой сложной функции

2023-11-03 08:19 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/primer3_core/libprimer3.cc
> +    int ls = -1, le = -1, regionSelector = -1, re = -1;
ОК

2023-11-03 08:21 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.h
> +}
OK

2023-11-03 09:52 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/PrimerSingle.cpp
> +void PrimerSingle::setSelfAnyStruct(const QString& selfAnyStruct) {
OK

2023-11-03 09:52 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    bool openView;
OK

2023-11-03 10:38 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    QPointer<Document> document;
Пара объектов `U2SequenceObject` и `AnnotationSequenceObject` хранят последовательность и аннотации соответственно. Они не живут сами по себе и должны быть привязаны к документу `Document`. Раньше у нас запуск всегда осуществлялся из последовательности, поэтому все эти объекты всегда существовали до запуска, мы просто их брали и использовали. Теперь мы сделали запуск **без** последовательности, поэтому мы должны создавать их все самостоятельно. Поскольку `U2SequenceObject` и `AnnotationSequenceObject` привязывются к `Document` и умирают вслед за ним, нам достаточно отследить судьбу только документа.

После того, как мы их создали, записали туда результаты расчета и сохранили всё в файл, мы должны открыть результат в UGENE (я не стал делать галочку "Add to project", считаю, что в данном случае имеет смысл открывать результат всегда). К счастью, существует готовая таска `AddDocumentAndOpenViewTask`, которая берет на вход документ, добавляет его в проект и открывает его вьюшку. После того, как таска отработала, этот самый созданный нами документ уже принадлежит проекту и будет удален когда пользователь закроет проект/закроет UGENE/удалит документ из проекта. Соответственно, в **идеальном сценарии** нам с созданным нами документом ничего делать не надо - он будет передан в проект и очищен пользователем при условном закрытии проекта.

В **неидеальном сценарии** мы можем создать документ, но в проект передан не будет, потому что у нас исполнение свалится с ошибкой или будет отменено пользователем - поэтому его владельцем так и останется сама таска. Именно для этого сценария у нас и есть деструктор.

Можно, конечно, сделать `Document` `QSharedPointer`'ом, а в таску `AddDocumentAndOpenViewTask` передавать его копию, но копирование документа - достаточно трудозатратная задача, я считаю, что ее не нужно добавлять на пустом месте.

2023-11-03 10:41 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +                    .arg(seqObj->getSequenceName()));
Добавил проверку на `nullptr` т.к. это единственное место, где используется ее имя

2023-11-03 10:41 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +    } else {
OK

2023-11-03 10:49 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        findExonsTask = new FindExonRegionsTask(seqObj, settings->getSpanIntronExonBoundarySettings().exonAnnotationName);
Добавил везде `QPointer` и сделал проверку на null перед каждым обращением

2023-11-03 10:50 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const int includedRegionOffset = includedRegion.startPos != 0 ? includedRegion.startPos - firstBaseIndex : 0;
OK

2023-11-03 10:51 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const auto& includedRegion = settings->getIncludedRegion();
ОК, тут я просто почеиу-то подумал,что возвращается именно ссылка

2023-11-03 11:34 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +void Primer3Task::run() {
OK

2023-11-03 11:52 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    for (qint64 junctionPos : junctions) {
OK

2023-11-03 11:52 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +        for (int idx : regionIndexes) {
OK

2023-11-03 11:56 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const QList<U2Region>& regions = settings->getExonRegions();
Без понятия, как она работает. Это часть функции RT-PCR, а я сколько не пытался, даже не смог понять, как это расшифровывается - то ли Real Time PCR, то ли Reverce Transcription PCR, то ли еще как-то. Могу предложить вообще удалить её - все равно никто не значет, что это и зачем нужно

2023-11-03 12:17 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +        stateInfo.setError(resultPrimers->per_sequence_err.data);
Объединил, появятся вместе

2023-11-06 18:45 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    QPointer<Document> document;
Почему бы не удалить документ в методе report()?

2023-11-06 18:48 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        // we need to deete it on our own.
nit: typo

2023-11-06 18:49 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +    // From now, @document will be handeled by the Project, we can just forget aboul it.
nit: typos

2023-11-06 19:02 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    // so it is important to do in in a separate thread
nit: typo

2023-11-06 19:07 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const QList<U2Region>& regions = settings->getExonRegions();
Если у этой функции нет ни использования ни документации ни тестов - ее стоит удалить.

2023-11-06 19:09 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/CheckComplementTask.h
> +    CheckComplementTask(const CheckComplementSettings& settings, const QList<QSharedPointer<PrimerPair>>& results, QPointer<U2SequenceObject> seqObj);
nit: Передавай объекты по константным ссылкам: `const QPointer<U2SequenceObject>& seqObj`

2023-11-06 19:10 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/FindExonRegionsTask.h
> +    FindExonRegionsTask(QPointer<U2SequenceObject> dnaObj,
`const QPointer<U2SequenceObject>& seqObj`

2023-11-06 19:26 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    bestPairs.clear();
Какой смысл в очистке пар здесь? Эту строку можно убрать?

2023-11-06 19:28 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +        singlePrimers.clear();
Тот же вопрос тут: можно ли убрать эту строку или в этом списке уже может быть результат?

2023-11-06 19:31 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        SAFE_POINT_EXT(!seqObj.isNull(), setError(L10N::nullPointerError("U2SequenceObject")), nullptr);
В SAFE_POINT локализация не нужна

2023-11-06 19:36 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/PrimerPair.cpp
> +    if (quality < pair.quality) {
Все проверки ниже могут быть сокращены в 2 раза: 
```c++
if (quality != pair.quality) {
    return quality < pair.quality;
}
```

2023-11-06 19:39 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.cpp
> +        for (const auto& primer : singlePrimers) {
qAsConst

2023-11-06 19:41 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.cpp
> +        return qAbs(reference - val) > 0.1;
Magic constant needs a description: what kind of double values are equal if they are as close as 0.1?

2023-11-06 19:43 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    SAFE_POINT(createAnnotationWidgetController != nullptr, L10N::nullPointerError("CreateAnnotationWidgetController"), CreateAnnotationModel());
nit: в SAFE_POINT не нужна локализация

2023-11-06 19:44 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    auto setPrimerChecboxesState = [&widgetStates, this](bool state) {
nit: typo

2023-11-06 19:48 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Plugin.cpp
> +        CHECK_EXT(!resultFilePath.isEmpty(),
Эту ошибку надо показывать в диалоге до его закрытия, а не после

2023-11-07 03:10 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    QPointer<Document> document;
Это особо ничего не изменит, все равно будет определенная проверка и удаление в зависимости от того, прошла она или нет. Деструктор, с моей точки зрения, больше подходит для очистки памяти, т.к. это его прямое назначение

2023-11-07 03:16 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const QList<U2Region>& regions = settings->getExonRegions();
Вообще, у нее есть [документация](https://doc.ugene.net/wiki/display/UM/RTPCR+Primer+Design) и даже определенные тесты (5898, 5899, 7671), и, вполне вероятно, что кто-то понимает, как она используется и зачем, но у меня не получается провести аналогии с кодом для того, чтобы написать хоть какие-то комментарии. Могу удалить, могу вставить счетчик, спустя релиз глянем, нужна она кому или нет и если нет - удалим

2023-11-07 03:16 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        // we need to deete it on our own.
OK

2023-11-07 03:37 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +    // From now, @document will be handeled by the Project, we can just forget aboul it.
OK

2023-11-07 03:37 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    // so it is important to do in in a separate thread
OK

2023-11-07 03:39 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/CheckComplementTask.h
> +    CheckComplementTask(const CheckComplementSettings& settings, const QList<QSharedPointer<PrimerPair>>& results, QPointer<U2SequenceObject> seqObj);
OK

2023-11-07 03:40 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/FindExonRegionsTask.h
> +    FindExonRegionsTask(QPointer<U2SequenceObject> dnaObj,
OK

2023-11-07 03:41 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    bestPairs.clear();
OK

2023-11-07 03:45 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +        singlePrimers.clear();
Нет, можно удалить

2023-11-07 03:46 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        SAFE_POINT_EXT(!seqObj.isNull(), setError(L10N::nullPointerError("U2SequenceObject")), nullptr);
Это стандартная штука, которую я использую вообще всегда и везде в SP

2023-11-07 03:53 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/PrimerPair.cpp
> +    if (quality < pair.quality) {
OK, правда, как мне кажется, читаемость похуже стала

2023-11-07 03:53 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.cpp
> +        for (const auto& primer : singlePrimers) {
OK

2023-11-07 03:55 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.cpp
> +        return qAbs(reference - val) > 0.1;
OK

2023-11-07 03:56 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    SAFE_POINT(createAnnotationWidgetController != nullptr, L10N::nullPointerError("CreateAnnotationWidgetController"), CreateAnnotationModel());
Уже было выше - это стандартное сообщение об ошибке, если у нас указатель нулевой

2023-11-07 05:29 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    auto setPrimerChecboxesState = [&widgetStates, this](bool state) {
OK

2023-11-07 05:32 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/Primer3Plugin.cpp
> +        CHECK_EXT(!resultFilePath.isEmpty(),
OK, там есть уже такая ошибка, тут заменил на SP

2023-11-07 12:21 UTC, DmitriiSukhomlinov commented
All passed except some unstable tests

2023-11-08 00:08 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    QPointer<Document> document;
Это не совсем так для тасков: представь себе задачу которая объединяет сотни других подзадач (как в workflow - где происходит потоковая обработка файлов). 

В этом случае если подзадача чистит результаты только в момент удаления - она будет тяжеловесная. Для исполнения всего потока задач может не хватить памяти.

Если же задача чистит рабочие данные в методе report() - то далее в памяти от нее остается только легковесная структура таска, которая содержит только статус завершения.

В итоге, если после исполения (вызова report) твой документ никому больше не нужен - его нужно чистить сразу же. 
Также вместо ->deleteLater нужно использовать обычный delete, или задокументировать почему нужен необычный deleteLater

2023-11-08 00:09 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3Task.cpp
> +    const QList<U2Region>& regions = settings->getExonRegions();
Ок, тогда оставляем

2023-11-08 00:10 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        SAFE_POINT_EXT(!seqObj.isNull(), setError(L10N::nullPointerError("U2SequenceObject")), nullptr);
Хорошо я исправлю это в отдельном PR

2023-11-08 00:15 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.cpp
> +        return qAbs(reference - val) > 0.1;
Эпсилон для double это функция от абсолютного значения double.

Большие соседние double могут находится на расстоянии 1000 и более друг от друга. Маленькие, на расстоянии 0.0001 и менее.

Сравнивать близкие double в общем случае нужно специальными функциями типа https://doc.qt.io/qt-5/qtglobal.html#qFuzzyCompare из Qt.

Если это не общий случай и 0.1 имеет какой-то особый смысл - то это magic constant и они должны быть объяснены (задокументированы)

2023-11-08 00:16 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    SAFE_POINT(createAnnotationWidgetController != nullptr, L10N::nullPointerError("CreateAnnotationWidgetController"), CreateAnnotationModel());
ok

2023-11-08 00:17 UTC, yalgaer commented
Остались минимальные замечания по деструктору и epsilon

2023-11-08 02:51 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.h
> +    QPointer<Document> document;
OK

2023-11-08 02:58 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.cpp
> +        return qAbs(reference - val) > 0.1;
Заменил на [qFuzzyCompare](https://doc.qt.io/qt-5/qtglobal.html#qFuzzyCompare). А еще я не правильно назвал функцию, надо было areDoubleValues**NOT**Equal, так что появился `!`

2023-11-10 01:19 UTC, yalgaer approved these changes

2023-11-10 04:19 UTC, merged