UGENE-7971 Crash: divide by zero on Statistics option panel for *.fsa file
ugeneunipro/ugene pull request #1443
Opened 2023-11-02 09:43 UTC by DmitriiSukhomlinov

У нас есть пара крешей, который возникли из-за деления на ноль, которое происходит [здесь](https://github.com/ugeneunipro/ugene/blob/0a205e0d660000d6c3a5638ce2104239baf64098/src/corelibs/U2View/src/ov_sequence/sequence_info/DNAStatisticsTask.cpp#L426). Сама проблема не в делении, а в том, что знаменатель, который является длиной выделенной последовательности, не может быть нулем в этом месте ну просто никак. Я очень долго пытался воспроизвести эту задачу, но не преуспел, поэтому я хочу немного улучшить логирование в некоторых местах, которые могут потенциально подсказать, откуда растет проблема и если подобный креш придет снова, то это может помочь продвинуться в решении.

Хотелось бы, чтобы данный фикс вошел в релиз

2023-11-02 20:42 UTC, yalgaer requested changes
> Хотелось бы, чтобы данный фикс вошел в релиз

К сожалению это не фикс.
Если проблему не удается воспроизвести то нужно попытаться ее локализировать.
Например в DNAStatisticsTask может прийти пустой список регионов и проверки на это нет

В сам таск нужно добавить проверку - он не должен работать поверх пустого Sequence и пустого списка регионов - это будет первый шаг по локализации проблемы.
Далее можно посмотреть кто вызывает этот таск без проверки на пустоту - проблема будет локализована еще лучше. Или, даже можно сказать решена.

2023-11-03 03:49 UTC, DmitriiSukhomlinov commented
> > Хотелось бы, чтобы данный фикс вошел в релиз
> 
> К сожалению это не фикс. Если проблему не удается воспроизвести то нужно попытаться ее локализировать. Например в DNAStatisticsTask может прийти пустой список регионов и проверки на это нет
> 
> В сам таск нужно добавить проверку - он не должен работать поверх пустого Sequence и пустого списка регионов - это будет первый шаг по локализации проблемы. Далее можно посмотреть кто вызывает этот таск без проверки на пустоту - проблема будет локализована еще лучше. Или, даже можно сказать решена.

Говоря "фикс" я не имею ввиду исправление проблемы (как я уже написал, я не могу ее выявить), а просто некий набор кода, связанный с этой фичей.

Добавить в `DNAStatisticsTask` проверку на пустоту - это костыль. Мы, конечно, можем так сделать и данный креш действительно больше не воспроизведется. Но проблема в том, что в UGENE не существует сценариев, когда мы бы могли передать в `DNAStatisticsTask` вектор пустых регионов - при этом, сценарий воспроизведения бага абсолютно точно завязан на том, что у нас в качестве аргумента передается что-то вроде `QVector<U2Region>() << { U2Region(0, 0) }`, т.е. вектор, содержащий регион нулевой длины, а такого не должно происходить никогда.  Таким образом, проблема не в самой `DNAStatisticsTask` - она работает идеально - а где-то в момент определения выделенных регионов. Строки лога, которые я добавил, я поместил в места, которые, по моему мнению, могут потенциально подсказать, что пошло не так. 

Я могу добавить в `DNAStatisticsTask` проверку на пустоту, но тогда в улучшении логирования нет особого смысла - креш больше не воспроизведется.

2023-11-06 13:06 UTC, yalgaer commented
> В итоге, что делаем?

Я уже писала выше.
Могу перефразировать: в самом таске где было падание надо проверять на 0 и выходить без падения.
Также проверки на 0 нужно добавить в места где передаются параметры в этот таск.
То есть сделать падение невозможным.

2023-11-08 00:27 UTC, yalgaer requested changes
1. У нас в этом же методе есть деление без проверки на ungappedLength. Его тоже нужно сделать безопасным - падение могло быть не нем.

2. Вопрос: regions в этот таск могут приходить из selection и из sequenceLength - ты проверил что там точно не получится пустого региона? 

Потому как в selection с точки зрения текущего API можно добавить пустой регион. А в этом методе у нас уже SAFE_POINT. Мне кажется где-то должна быть проверка без SAFE_POINT - иначе эти два API работают несинхронно.

2023-11-08 03:44 UTC, DmitriiSukhomlinov commented
> 1. У нас в этом же методе есть деление без проверки на ungappedLength. Его тоже нужно сделать безопасным - падение могло быть не нем.

Вообще это не обязательно, т.к. там значение присваивается в double, а это вполне законно с точки зрения исполнителя - он просто посчитает, что делит на бесконечно малую и запишет в результат бесконечность (можно даже потестировать и увидеть, что ничего страшного не произойдет). Подобный креш возникает только если результат деления на ноль попытаться записать в `int`, у нас в данном файле такое место только одно.
Но зрелое зерно в замечании все равно есть, считать GC-состав при нулевой длине смысла не имеет, поэтому я оберну его в `if`

> 2. Вопрос: regions в этот таск могут приходить из selection и из sequenceLength - ты проверил что там точно не получится пустого региона?
> 
> Потому как в selection с точки зрения текущего API можно добавить пустой регион. А в этом методе у нас уже SAFE_POINT. Мне кажется где-то должна быть проверка без SAFE_POINT - иначе эти два API работают несинхронно.

Регион (точнее, список регионов, у нас же есть множественное выделение), который приходит в таску вычисляется [здесь](https://github.com/ugeneunipro/ugene/blob/fa5fa80536ee5b4d84f6ca062966a4207eed1587/src/corelibs/U2View/src/ov_sequence/sequence_info/SequenceInfo.cpp#L560) и там все очень прозрачно - либо берем выделение, либо всю последовательность. Я достаточно долго тестировал этот кусочек кода, в надежде получить что-то неожиданное, но у меня не получилос. Насчет пустого региона - я не смог найти сценария, при котором нечто подобное можно сделать. Если подскажешь это поможет

2023-11-10 01:18 UTC, yalgaer approved these changes

2023-11-10 04:19 UTC, merged