UGENE-7979 Sequences syncronisation does not work well
ugeneunipro/ugene pull request #1454
Opened 2023-11-15 13:24 UTC by rasputinkirill

В задаче немного непонятное описание, после обсуждения было решено вот что.
Первая проблема - то что при повторном выборе пункта меню "Связать шкалы..." синхронизация отменяется  (что правильно), но состояние кнопки и меню в ней не меняется.
Вторая проблема - производительность при выделении части последовательности и включенной синхронизации.
С этой проблемой я не смог разобраться.
Предлагаю оформить эту задачу как отдельную и решить позже. А это исправление принять как решение первой описанной проблемы.

2023-11-15 23:43 UTC, yalgaer requested changes
Согласна, можно решать задачу частями. Давай пока решим без исправления производительности.

2023-11-15 23:43 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +        action->setChecked(false);
Добавь проверку после каждого qobject_cast тк может быть nullptr

2023-11-15 23:43 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +        unlock();
unlock() вызывае updateEnabledState() где уже централизовано обовляется состояние кнопок.
Там же, централизовано, нужно выставлять правильное состояние actions. Так получится?

2023-11-15 23:43 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.h
> +    bool lockByStartPrevState = false;
Сложность с дополнительными состояниями добавлять не нужно. Выведи текущее состояние из того, какой именно action enabled/disabled (то есть action уже храннит состояние). Так получится?

2023-11-17 14:38 UTC, rasputinkirill commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.h
> +    bool lockByStartPrevState = false;
Переделал, но все равно мы должны сохранять одно состояние "ни один из пунктов меню не выбран".

2023-11-19 13:54 UTC, rasputinkirill commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +        action->setChecked(false);
Я добавил, но в текущем коде в этот слот мы всегда придем только по сигналу от QAction.

2023-11-19 14:17 UTC, rasputinkirill commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +        unlock();
Сделал путем добавления переменной для сброса в класс, так как посчитал что протаскивать как аргумент через два метода будет не круто.

2023-11-20 02:05 UTC, yalgaer requested changes

2023-11-20 02:05 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +        for (QAction* action : { lockByStartPosAction, lockBySeqSelAction, lockByAnnSelAction }) {
Напиши 3 раза:
```
 action->setChecked(false);
```
будет короче и проще для чтения

2023-11-20 02:05 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +    if (s == lockByStartPosAction && lockByStartPrevState ||
Добавь скобок вокруг блоков разделенных || , чтобы не было warnings

2023-11-20 02:05 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.h
> +    bool lockByStartPrevState = false;
У нас есть enum `SyncMode` - можно ли используя его сделать 1 переменную хранящую предыдущее состояние вместо целых 3? На три переменные приходится 6 возможных состояний. 

На 1 переменную с enum всего 3.
Так как в 1 момент времени у нас возможен только 1 вид лока - то всего нужно сохранять 3 варианта и использование 3 переменных типа bool должно быть излишним.

2023-11-20 02:05 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +        unlock();
Предлагаю убрать поле и пробрасывать через 2 метода.

"Не круто" иметь лишние глобальные состояния на классе. При проносе же переменной через методы будет сразу видна причина зачем нужно именно так. Возможно сразу появится лучшее и еще более короткое решение.

Например, возникает вопрос, почему когда мы делаем unlock() нам нужно сбрасывать check состояние не всегда?

2023-11-20 13:30 UTC, rasputinkirill commented
В процессе тестирования нашел еще одну проблему, которая присутствует в прошлых релизах - при переключении с одного режима на другой теряется синхронизация выделения аннотаций. Заведу отдельную задачу.

2023-11-20 23:37 UTC, yalgaer reviewed
Минимальные замечания. Approve после тестов

2023-11-20 23:37 UTC, yalgaer commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +                CHECK("Unexpected switch", );
если это баг, то тут должен быть SAFE_POINT

2023-11-20 23:37 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    private:
nit: в служебных классах типа этого заморачиваться с областью видимости полей

2023-11-21 00:08 UTC, rasputinkirill commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +                CHECK("Unexpected switch", );
Это не баг, GCC не собирает если все варианты не перечислены. В этот кейс мы не должны никогда прийти.

2023-11-21 03:42 UTC, rasputinkirill commented
В предыдущем решении была ошибка. Я аж запутался в итоге в коде. В итоге переделал попроще. Операции с состоянием кнопки и ее меню я не стал тащить в updateEnabledState() так как мы все их состояния и изменения (setChecked(), toggle()) смотрим и изменяем здесь в этом слоте sl_lock(). updateEnabledState() же нужен только для активации этого контроллера при наличии нескольких вьюшек.

2023-11-21 05:26 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_sequence/ADVSyncViewManager.cpp
> +                CHECK("Unexpected switch", );
Если мы не должны придти в этот кейс никогда, то тут должен быть `SAFE_POINT`, или, в данном случае лучше подойдет его частный случай `FAIL`

2023-11-23 02:18 UTC, yalgaer reviewed
Замечаний нет, approve после GUI тестов

2023-11-23 05:26 UTC, yalgaer approved these changes

2023-11-23 05:38 UTC, merged