UGENE-7958 Append new primers (found by Primer3) if some primer already's been found
ugeneunipro/ugene pull request #1456
Opened 2023-11-16 09:23 UTC by DmitriiSukhomlinov

2023-11-16 09:23 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/GUITestBasePlugin.cpp
> +    REGISTER_TEST(GUITest_common_scenarios_primer3::test_0026);
I forgot to register this test in a previous task

2023-11-17 02:47 UTC, yalgaer requested changes
Минимальные стилистические замечания. Approve после тестов

2023-11-17 02:47 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        SAFE_POINT(rootGroup != nullptr, L10N::nullPointerError("AnnotationGroup"), {});
nit: use SAFE_POINT_NN

2023-11-17 02:47 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Tests.cpp
> +    AnnotationGroup* topPrimersGroup = nullptr;
строки с 641 по 648 могут быть 1 строкой поиска в массиве оператором std::

2023-11-17 02:47 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.h
> +    int pairNumberOffset;
нужно добавить значние по умолчанию для всех переменных инициализируемых случайным образом

2023-11-17 06:26 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/Primer3TopLevelTask.cpp
> +        SAFE_POINT(rootGroup != nullptr, L10N::nullPointerError("AnnotationGroup"), {});
OK

2023-11-17 06:26 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/task/ProcessPrimer3ResultsToAnnotationsTask.h
> +    int pairNumberOffset;
OK

2023-11-18 01:26 UTC, yalgaer reviewed
Замечаний нет, approve после тестов

2023-11-20 01:41 UTC, yalgaer approved these changes

2023-11-20 04:33 UTC, merged