UGENE-7959 Add "BLAST selected primer pairs" option
ugeneunipro/ugene pull request #1458
Opened 2023-11-17 12:20 UTC by DmitriiSukhomlinov

Основной смысл этой задачи в разработке функционала, аналогичного представленному в инструменте [Primer-BLAST](https://www.ncbi.nlm.nih.gov/tools/primer-blast/index.cgi?GROUP_TARGET=on).
Суть этого инструмента следующая - сначала, с помощью Primer3, подбирается пара праймеров, а затем, с помощью BLAST, определяются организмы, которым принадлежит каждый из получившихся праймеров, смотрится пересечение результатов (и взаимное расположение праймеров на этом пересечении) и мы получаем организмы, которые содержат в себе эту пару праймеров.

BLAST в UGENE уже есть, мне надо было только его доработать, чтобы он бластил пару праймеров по очереди, искал их общие организмы, проверял, что в этом организме они располагаются правильно по отношению друг к другу (как пара праймеров, там в коде есть очень длинный комментарий о том, как они могут располагаться) и выдает получившийся результат.

Сейчас BLAST запускается всегда по выделенной последовательности (либо по всей сразу, если выделения нет). Для того, чтобы запустить BLAST не так, а по паре праймеров, нужно выделить все праймеры, по которым они должны запускаться и вызвать диалог бласта (через контекстное меню или шорткат Ctrl + Shift + B который я добавил):
![image](https://github.com/ugeneunipro/ugene/assets/26257527/124c6192-8d29-43d8-b111-e3d85bb8e698)

Диалог бласта будет немного отличаться - настройки аннотаций (куда сохранять) заменились на список праймеров. Это нужно потому, что мы, при таком режиме поиска, не задаем аннотации для сохранения (результат всегда будет сохранен в ту же группу, где и пара праймеров, по которой он искался). Так же я изменил некоторые настройки по-умолчанию у бласта - это связано с тем, что я очень много его тестировал и при текущих настройках поиск идет очень долго:

![image](https://github.com/ugeneunipro/ugene/assets/26257527/5fe4647e-540f-4c0b-88f6-9bfd7e7b753b)

Добавлен GUI и XML тест

2023-11-18 01:58 UTC, yalgaer requested changes

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/sequence_view/GTTestsSequenceView.cpp
> +    GTKeyboardDriver::keyPress(Qt::Key_Control);
Нужно крайне аккуратно использовать keyPress, если после него не будет keyRelease то будет непредсказуемое поведение системы.

Желательно добавить все модификаторы прямо в keyClick

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    SAFE_POINT(av != nullptr, L10N::nullPointerError("AnnotatedDNAView"), );
nit: SAFE_POINT_NN

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    CHECK(QDialog::Accepted == dlg->result(), );
nit: fix yoda style

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    SAFE_POINT(seqObj != nullptr, L10N::nullPointerError("U2SequenceObject"), );
nit: SAFE_POINT_NN

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    DNATranslation* aminoT = (dlg->translateToAmino ? seqCtx->getAminoTT() : 0);
nit: скобки не нужны

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.cpp
> +                } else {
nit: вложенный if может быть объединен с верхним

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.cpp
> +    CHECK_EXT(leftPrimer.data() != nullptr, setError(tr("The left primer is lost, probably, annotation object has been closed")), );
"annotation object has been closed" - странная ошибка. Объекты удаляются из UGENE а не "закрываются".
Нужно сразу в конструкторе принимать аннотации в виде SharedAnnotationData и не бояться что их кто-то удалит.

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.cpp
> +    CHECK_EXT(!ato.isNull(), L10N::nullPointerError("AnnotationTableObject"), {});
L10N::nullPointerError здесь dead-code

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.h
> +                                           const SharedAnnotationData& leftPrimer,
В описании таска нет деталей почему left и right должны быть именно праймерами а не просто случайными аннотациями.

Например должны не перекрываться, иметь определенное расстояние друг от друга или быть прямыми или комплементарными или иметь только 1 регион. 

В самом таске стоит проверить  корректность поданных данных до начала расчета.

2023-11-18 01:58 UTC, yalgaer commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairsToAnnotationsTask.cpp
> +        tasks << t;
Похоже это поле не используется

2023-11-20 04:43 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/sequence_view/GTTestsSequenceView.cpp
> +    GTKeyboardDriver::keyPress(Qt::Key_Control);
Поправил, забыл, что можно по несколько модификаторов добавлять

2023-11-20 04:44 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    SAFE_POINT(av != nullptr, L10N::nullPointerError("AnnotatedDNAView"), );
OK

2023-11-20 04:44 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    CHECK(QDialog::Accepted == dlg->result(), );
OK

2023-11-20 04:44 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    SAFE_POINT(seqObj != nullptr, L10N::nullPointerError("U2SequenceObject"), );
OK

2023-11-20 04:45 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPlugin.cpp
> +    DNATranslation* aminoT = (dlg->translateToAmino ? seqCtx->getAminoTT() : 0);
OK

2023-11-20 04:46 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.cpp
> +                } else {
OK

2023-11-20 04:50 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.cpp
> +    CHECK_EXT(leftPrimer.data() != nullptr, setError(tr("The left primer is lost, probably, annotation object has been closed")), );
Переписл текст ошибки, насчет SharedAnnotationData  - они и так принимаются в этом виде. Проблема тут может возникнуть, если кто-то удалит аннотацию из текущего файл (в смысле, удалит, например, в дереве аннотаций) либо удалит объект аннотаций из проекта (или просто закроет файл)

2023-11-20 04:52 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.cpp
> +    CHECK_EXT(!ato.isNull(), L10N::nullPointerError("AnnotationTableObject"), {});
Точно, добавил `setError`

2023-11-20 05:36 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairToAnnotationsTask.h
> +                                           const SharedAnnotationData& leftPrimer,
Я немного улучшил комментарий и добавил валидацию на разные направления в начало `prepare()`. Валидации на местоположение на последовательности не нужно, праймеры могут располагаться как угодно - мы проверяем их расположение только на результате [здесь](https://github.com/ugeneunipro/ugene/pull/1458/files#diff-ebb80e0f01b078d7d6e7846b73e3c363c01e8122c935df0efd5a78a57669f005R135). Регион может быть или один, или два (если праймер располагается на нуле, а последовательность круговая) - этот сценарий тоже уже обработан [здесь](https://github.com/ugeneunipro/ugene/pull/1458/files#diff-ebb80e0f01b078d7d6e7846b73e3c363c01e8122c935df0efd5a78a57669f005R170).

Вообще, валидация тут особо не нужна, она вся происходит еще до вызова диалога

2023-11-20 05:37 UTC, DmitriiSukhomlinov commented on src/plugins/remote_blast/src/RemoteBLASTPrimerPairsToAnnotationsTask.cpp
> +        tasks << t;
Действительно, удалено

2023-11-20 23:33 UTC, yalgaer approved these changes

2023-11-21 03:17 UTC, merged