UGENE-7746. [Crash, Mac] Open project when UGENE is minimized
ugeneunipro/ugene pull request #1459
Opened 2023-11-19 08:03 UTC by EvelinaBiserova

2023-11-20 01:40 UTC, yalgaer requested changes
В одной зоне могут быть несколько доков. 

Нужно проверить что удаляемый док является активным прежде, чем занулять активный.

2023-11-20 23:32 UTC, yalgaer commented
Замечаний нет, approve после тестов

2023-12-19 08:32 UTC, evelinabis commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +GUI_TEST_CLASS_DEFINITION(test_7746) {
This is a different scenario, but the fixes are in one place.

If I understand correctly, we don't have dock action testing. Should I write some tests as part of this PR?

2023-12-22 10:02 UTC, evelinabis commented
@yalgaer GUI tests on Mac crash randomly. Not relevant to the current PR. I can investigate and try to fix some of them, but that's not within the scope of the current task. Ready for review.

2023-12-23 00:19 UTC, yalgaer commented
Закрываю задачу как неактивну. Переоткрой, пожалуйста, как будут изменения/тесты.

2023-12-23 07:17 UTC, evelinabis commented
What changes do you want?

2023-12-23 17:52 UTC, yalgaer commented
> What changes do you want?

Я писала "Замечаний нет, approve после тестов". 

Были упавшие тесты. Если ты их проверила и подтверждаешь что они не связаны с твоими изменениями я даю approve.

2023-12-23 17:52 UTC, yalgaer approved these changes

2023-12-25 02:51 UTC, merged