UGENE-7986 Levitsky consensus algorithm problems
ugeneunipro/ugene pull request #1470
Opened 2023-12-04 13:32 UTC by DmitriiSukhomlinov

Алгоритм работает следующим образом:

1. Подсчитывается встречаемость всех символов алфавита во всем выравнивании.  
2. Затем идет проверка - подсчитывается встречаемость каждого символа в стобце, она должна быть больше заданного порога. Если нет - символ скипается.   
3. Если символ не скипнут, то берется его встречаемость во всем выравнивании и отображается символ с наименьшей встречаемостью.

Тут и была основная проблема алгоритма - символы перечислялись в алфавитном порядке (алфавитный порядок никакого биологического смысла в себе не несет). Поэтому, фактически, отображался тот символ, который ближе к началу алфавита.  Из-за этого было практически невозможно предугать, какой символ оказывается на том или ином месте - например, очень часто рисовался символ B (потому что он второй), либо в случае, когда символы имеют одинаковую встречаемость, отдавалось предпочтение по совершенно не ясному принципу:
![image](https://github.com/ugeneunipro/ugene/assets/26257527/cbbe7119-d690-4466-9f30-64608f8dcd93)
Всех символов поровну, почему выбрана K (T или G) не понятно

Я изменил алгоритм таким образом, чтобы выбор сначала делался в следующем порядке:

1. Из символов ДНК/РНК (A, C, G, T/U).
2. Из символов расширенного алфавита, которые кодируют два символа.
3. Из символов расширенного алфавита, которые кодируют три символа.
4. N, которая кодирует все четыре символа.

Если есть несколько равнозначных опций (как на картинке выше, например), то выбирается символ, который кодирует их все (в данном случае будет N, например).

Задачу про то, что не обновляются начения встречаемости когда редактируешь последовательность я вынесм отдельно.

2023-12-05 06:41 UTC, yalgaer requested changes
С идеей использовать N если находится несколько равнозначных вариантов из которых мы не можем выбрать я согласна.

Текущий алгоритм уже считает частоты всех опций. Изменения внести следует только в часть, которая отвечает за выбор результата.

Что мне не нравится в текущем PR

1)  Тесты: XML тест тут не нужен - нужны API тесты которые для 1 столбца выберут нужную букву. 
Вместо 4 микротестов на XML нужно проверить существенно большее число комбинаций и вариаций используя API тесты. 

2) Нужно оставить оптимальную версию подсчета вероятностей написанную в С-стиле
Новый алгорим работающий через Map (дерево) это очень плохо: так не нужно писать ни на каком языке.
Мы используем низкоуровневый язык программирования как раз чтобы иметь возможность писать алгоритмы оптимально, и подсчет консенсуса на лету для больших двумерных структур (например 10000x10000 символов) должен оставаться оптимальным.

Итого: идея хорошая. число изменений нужно сократить до минимума, тесты должны иметь лучшее покрытие всех вариантов выбора и быть читаемыми.

2023-12-06 11:49 UTC, DmitriiSukhomlinov commented
Окей, я постарался учесть замечания. Насчет тестов - написал достаточно много кейсов, но, начиная с какого-то момента их становится так много, что все не сделаешь (где-то начиная с момента, когда мешается по три символа). Поэтому, я постарался учесть общую идею того или иного кейса, но только в одной вариации, т.е. для одного набора символов.

2023-12-06 11:59 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Предвидя вопрос "зачем тут такой `for`":

При итерации в обычном порядке, у нас в `selectedChars` могут оказаться два символа из разных групп - например A (нуклеотид) и W (символ расширенного алфавита, обозначающий A или T). Вообще таких комбинаций может быть очень много, я просто привел простейший пример.

В этом случае, предлагается оставить наиболее значимый символ - в данном случае A. Для того, чтобы понять, какой из этих символов относится к какой группе мы все символы можем разбить на группы и проверить текущий символ на вхождение в одну из этих групп. Разбиение на группы уже сделано выше - `SINGLE_NUCL`, `DOUBLE_NUCL`, `TRIPLE_NUCL` ну и отдельно стоящая `N`. Получится код вроде такого:
```
for (int c = 'A'; c <= 'Y'; c++) {
    ...
    if (SINGLE_NUCL.contains(c)) {
        ...
    } else if (DOUBLE_NUCL.contains(c)) {
        ...
    } ...
   ....
}
```

`contains(...)` - это просто `for()` по коллекции. Получается, подобный ход делает у нас вложенный `for`, что сразу увеличивает вычислительную сложность функции с O(N) до O(N^2). Поскольку, в данной функции, скорость вычисления критически важна, подобный подход может сильно сказаться на производительности.

2023-12-06 23:10 UTC, yalgaer commented
> Насчет тестов - написал достаточно много кейсов, но, начиная с какого-то момента их становится так много, что все не сделаешь

Стоит разделить тесты по типу для улучшения читаемости

1) Тест на 1 столблец.  Этому тесту должна подаваться только 1 строка и редко минимальная частота (пусть будет 50 по умолчанию) и он должет выдвать 1 символ в ответ. Таким образом не надо будет подавать большой alignment - запись будет компактна.

2) Тест на >1 столбец для тестирования только эффекта глобальной частоты. Таких тестов может быть мало.

3) Тесты на примеры из описания к алгоритму, чтобы знать что описание соответствует реализации.

2023-12-06 23:10 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Как отработает этот код, если в столбце MSA есть только символы из расширенного алфавита?

2023-12-06 23:10 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
В этом файле много переноса из одного места в другое без изменений - это сильно усложняет ревью
Предлагаю либо оставить где было, либо я я проревьюю перенесенные методы полностью в деталях (тк где diff не видно)

2023-12-06 23:10 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    return MSAConsensusUtils::mergeCharacters(selectedChars);
Данный merge это OR? 
Может стоит назвать этот метод как 'pickRarestCharacter'

Далее, registerHit для A зарегистрирует хиты как для A так и для символов расширенного алфавита (W).
Что в этом случаe выберет mergeCharacters для пары А и W? Есть ли тест для этого случая, когда оба этих символа попали в результат?

2023-12-06 23:10 UTC, yalgaer commented on src/plugins/api_tests/src/core/datatype/msa/MsaConsensusAlgorithmUnitTests.cpp
> +    CHECK_EQUAL("A", QString(MsaConsensusAlgorithmUnitTestsUtils::getLevitskyConsensusBase({"A", "A"}, 50, 0)), "consensus base");
nit: последний параметр в тестах всегда 0 - можно сделать его значением по умолчанию

2023-12-07 08:39 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Выбор из нескольких символов происходит аналогично тому, как происходит выбор для алгоритма "Simple Extended". Проще на примере:

Есть два равнозначных символа:  
- W - A или T
- S - G или T

В консенсусе будет символ, соответствующий всем трем символам A, T и G - это символ D.

2023-12-07 08:55 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    return MSAConsensusUtils::mergeCharacters(selectedChars);
Такого не может произойти из-за того, как написан `for(...)`. Итерация происходит по символам в переменной `ALL_POSSIBLE_NUCL`. В этой переменной символы идут по условным группам:

- одиночные символы ДНК/РНК (A, C, G, T и U).
- символы расширенного алфавита, кодируемые **двумя** символами ДНК/РНК.
- символы расширенного алфавита, кодируемые **тремя** символами ДНК/РНК.
- N (означает, что любой из **четырех** символов может быть на этом месте)

Когда заканчивается одна группа, мы проверяем, есть ли у нас символы, претендующие на право быть консенсусом. Если есть хотя-бы один символ, то мы выходим из цикла.

Таким образом, если мы, например, проверив символы первой группы (A, C, G, T и U) поймем, что у нас есть как минимум один кандидат в консенсус, то мы выйдем из цикла и не будем проверять символы последующих групп. Поэтому, символы разных групп не могут оказаться в списке кандидатов в консенсус.

2023-12-07 09:08 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Я могу унести это обратно, но это немного ухудшит структуру кода. 

На всякий случай я поясню. У нас есть алгоритм расчета консенсуса Simple Extended, который расчитывает консенсус по следующему правилу:
![image](https://github.com/ugeneunipro/ugene/assets/26257527/61b20679-24d3-44ef-866b-8142338b4b9c)

В левом столбце указан символ консенсуса, который будет отображен, если в соответствующем ему столбце выравнивания встречаются все символы из правого столбца.

Для того, чтобы не изобретать велосипед, я решил, что будет логичнее всего применить такое же правило для алгоритма Левицкого в случае, если у нас есть несколько равнозначных кандидатов в консенсус. В UGENE уже есть неплохой код, который делает это, однако он использовался только для алгоритма Simple Extended, но он приватный в соответствующем классе `MaConsensusAlgorithmSimpleExtended`. Если он используется несколькими алгоритмами, логичнее перестать держать его в файлах, соответсвующих только одному алгоритму и перенемсти в общий утилитный класс.

Насчет предложения - если изменения не слишком большие, то я готов их сделать. Если концептуальные - то лучше просто скину обратно.

2023-12-07 09:24 UTC, DmitriiSukhomlinov commented on src/plugins/api_tests/src/core/datatype/msa/MsaConsensusAlgorithmUnitTests.cpp
> +    CHECK_EQUAL("A", QString(MsaConsensusAlgorithmUnitTestsUtils::getLevitskyConsensusBase({"A", "A"}, 50, 0)), "consensus base");
OK

2023-12-07 10:09 UTC, DmitriiSukhomlinov commented
> > Насчет тестов - написал достаточно много кейсов, но, начиная с какого-то момента их становится так много, что все не сделаешь
> 
> Стоит разделить тесты по типу для улучшения читаемости
> 
> 1. Тест на 1 столблец.  Этому тесту должна подаваться только 1 строка и редко минимальная частота (пусть будет 50 по умолчанию) и он должет выдвать 1 символ в ответ. Таким образом не надо будет подавать большой alignment - запись будет компактна.
> 2. Тест на >1 столбец для тестирования только эффекта глобальной частоты. Таких тестов может быть мало.
> 3. Тесты на примеры из описания к алгоритму, чтобы знать что описание соответствует реализации.

Сделал

2023-12-07 19:41 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Мне проще продемонстрировать ошибку на примере:
![image](https://github.com/ugeneunipro/ugene/assets/17791039/0f25d7c7-93ba-4e8a-be15-d4df69cec80e)

Как должен работать алгоритм для порога 50% и первого столбца:
1) Выбрать все символы у которых встречаемость >= 50%: выбираются T и W
2) Выбрать из них самый редкий во всём выравнивании: выбирается W

Далее твой новый алгоритм добавляет новый шаг:
3) Если осталось несколько равнозначных вариантов, то выбирается лучший: объединяющий максимальное количество символов: этот шаг в текущем примере не актуален - только 1 символ.

2023-12-07 19:59 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Замечания будут концептуальными: 
1. Выбрано плохое и неоднозначное имя для флага Character
2. Используется мета-система QT для итерации по enum в hotspot месте - тот же функционал пишется быстрее и проще: например функция `flags2Character` не требует цикла - это просто возврат уже известного значения по индексу нуклеотида.

2023-12-08 04:49 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
1. Переименовал в `DnaExtendedBaseFlag`. Если имя все еще не устраивает - предложи любое свое.
2. Касательно `switch` - это действительно очень неудобный способ трансформации `char` в `enum` и обратно. Фактически, мы перебираем все символы по порядку, что является абсолютным аналогом `for(...)` с его линейной сложностью вычисления. Использование низкоуровневого массива тоже не является оптимальным решением в данном случае, т.к. это опять-таки сведется к итерации всех символов, что тоже имеет вычислительную сложность O(N). Как ни странно, лучшим решением в данном случае я считаю как раз-таки использование высокоуровневых `QHash` либо `QMap`, которые представляют из себя хеш-таблицу либо красно-черное дерево соответственно. В данном случае, они объявляются статическими, поэтому инициализируются на старте юджина (уже существуют в момент подсчета консенсуса, поэтому не замедлят его своим созданием), константными (гарантирует невозможность добавления элемента  - а значит, отсутствие сложных перестроений таблицы/дерева, которые зачастую требуются для данных типов контейнеров) и обеспечивают наиболее быстрый поиск по ключу из возможных (O(1) в среднем и O(N) в худшем случае для `QHash` либо O(logN) для `QMap`). Я выбрал `QMap` потому что в данном случае концептуальной разницы это не принесет, а в Visual Studio есть какая-то проблема с отображением элементов `QHash` в режиме дебага, что бываетg приводит к неудобствам.
3. Я не очень понял, каким образом можно избавиться от цикла - данный способ трансформации мне кажется самым оптимальным. Если тебе кажется, что этот момент можно как-то улучшить, то поясни чуть конкретнее, желательно с примером

2023-12-08 05:28 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Первый указанный тобой тест уже существует и находится [тут](https://github.com/ugeneunipro/ugene/pull/1470/files#diff-2f5f8fc9332e0ac236bc422324e9ea4ba2d8c339fc1fa9db286b4ea286ecee25R224). Там же, следом за ним идет вариация этого же теста, но с более высоким пороговым значением, у которого как раз таки проиходит смешение двух символов (потому что из-за высокого значения порога ни один из этих символов сам по себе в консенсус не попадает). Там огромное количество комбинаций тестов на подобные кейсы (начиная буквально с комбинации трех различных символов в колонке количество всевозможных кейсов становится огромным, поэтому все написать просто нереально, но основные сценарии я постарался учесть).

Касательно миксов групп типа того, как указано во втором сценарии - эти случаи менее интересны, т.к., как я уже подробно описывал, алгоритм, скорее всего, просто остановится на символе ДНК/РНК. Так или иначе, добавил описаный тобой кейс.

2023-12-08 05:43 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
1. Имя OK
2. 
Вместо QMap в подобных алгоритмах нужно использовать массив. 
В случае с массивом данные локализованы в памяти - это серьезный плюс.

O(LogN) с Map отличается от O(1) в случае массива еще и большой (100x?) константой перед O.  Нужно переделать.

3.
```
char MSAConsensusUtils::flags2Character(DnaExtendedBaseFlags flags) {
   return flagToCharacterMapping[flags];
}
```
где массив `flagToCharacterMapping ` содержит всего 32 элемента (gap нужно убрать из enum - это другое измерение не имеющее отношение к расширению алфавита).

2023-12-08 05:50 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Насчёт второго примера: мы не меняет определение алгоритма, а дорабатываем его недостаток - добавляем шаг 3 который убирает случайный выбор.

Второй же случай  не требует шага 3: он должен выбирать самый редкий символ (R) на втором шаге.

2023-12-08 05:56 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Я не понял этот аргумент, можно поподробнее. Как в массиве можно осущствлять поиск за O(1)?

2023-12-08 05:57 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Что за преимущество в виде локализации в памяти для меня тоже не очень понятно, буду рад узнать что-то новое

2023-12-08 06:03 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Мы не выбираем символ расширенного алфавита, если у нас есть кандидат из основного. Мне кажется такое поведение более правильным и я изначально затачивал алгоритм именно под него. Изменение этого поведения может потребовать серьезного изменения в алгоритме, я не уверен, что буду это делать, просто потому, что ты считаешь, что так будет правильнее.

2023-12-08 06:10 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
Я согласна на доработку алгоритма, но не на изменение его сути. Алгоритм придуман не нами.

Далее решай сам. Если не захочешь дорабатывать я могу это сделать сама.

2023-12-08 06:15 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
> Я не понял этот аргумент, можно поподробнее. Как в массиве можно осущствлять поиск за O(1)?

Подробнее:
Есть функция
```
char MSAConsensusUtils::flags2Character(DnaExtendedBaseFlags flags) {
```
преобразующая пространство `flags` в пространство `char`.

В пространстве `flags` есть всего 32 значения: от 0x0000 до 0x1111 в битовом представлении или от 0 до 31 в десятичном.

Достаточно завести массив на 32 элемента чтобы отобразить каждое значение `flags` в `char` верно?

2023-12-08 06:23 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
> Что за преимущество в виде локализации в памяти для меня тоже не очень понятно, буду рад узнать что-то новое

В случае с массивом мы имеем блок памяти размером в 32 байта. Этот блок может поместиться не только в одну кеш-линию или даже в какой-либо из спецрегистров или в пару основных регистров. То есть процессору для вычисления результата, в случае частого использования этого метода, не нужно даже будет обращаться к кешу. А в случае даже обращения к кешу/памяти весь массив будет подгружен в виде кеш-линии за 1 раз при первом обращении.

Этого нельзя сказать о Map - где все значения хранятся не локально в памяти и доступ к ним происходит через серию редирекций и дополнительных проверок.

Об этом преимуществе массивов над деревьями нужно знать не только программистам на C/С++, но и любым программистам. В UGENE же это особенно важно.

2023-12-08 13:05 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Ничего из написанного тобой ты не можешь гарантировать. В теории - возможно, есть крошечная вероятность, что оно сработает именно так. На практике - это неспецифицированное поведение и может сработать как угодно.  Процессор сам решает, что ему кэшировать, а в рамках операционной системы в момент работы нашего алгоритма может возникнуть (и наверняка возникнет) миллион более важных (по мнению процессора) участков памяти, требующих более быстрого доступа. Кэш процессора в принципе настолько незначителен и используется на очень низком уровне (я сильно сомневаюсь, что им можно целенаправленно оперировать на языках, уровнем выше ассемблера). В алгоритмических задачах вроде нашей о нем в принципе задумываться не имеет смысла. А с учетом того, что мы используем крайне высокоуровневый (по меркам C++) Qt, который обрабатывает весь наш код, далеко не факт, что хоть что-то из написанного нами уходит дальше оперативной памяти (вполне подходящей по скорости для наших задач). Если бы писали на ассемблере - это имело бы смысл. А так - ты бы еще на джаве или питоне заговорила об этом, пока виртуальная машина расходует в десять раз больше ресурсов, чем твой собственный код.

С другой стороны, контейнеры и их времена вычисления, о которых я писал выше, очень жестко специфицированы и я могу со стопроцентной вероятностью гарантировать, что они отработают именно так, как я описал. 

А про 32 байта все равно не очень понял. Ты заводишь массив 32 байта для `enum` - допустим, он там как-то обработается на низком уровне и с ним можно будет работать быстро. Но тебе понадобится рядом стоящий массив для `char`, в котором будут хранится буквенные значения символов - 8 байт каждый символ умножить на 14 символов равно 112 байт на весь массив. Кэш процесора вышел из чата.

2023-12-08 15:01 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Можно мне не комментировать то что написано выше и вернуться к работе над патчем?

Писать километры текста суть которых "я не знаю" вместо патча который состоит из 2 строк - это ненормальное использование рабочего времени.

То, что для 4-битного (14 вариаций) отображения нужно 112 байт - это можно сделать тестом на прием в проект. Идеальное решение - 7 байт (1 регистр CPU или int32 переменная в С). Приемлемое: 14 байт - по байту на вариацию чтобы сократить размер кода (размер кода как и данные тоже влияет на скорость исполнения) .

2023-12-11 03:36 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Даже если отвлечься от того, что мне это не очень нравится, я все равно не понимаю предлагаемое тобой решение и каким образом мне нужно изменить код, чтобы оно заработало - частично из-за слишком высокого уровня абстракции написанного тобой, частично из-за того, что редко работаю с такими низкоуровневыми решениями.

2023-12-11 03:52 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Примеров подобного в UGENE множество: подобным образом работает весь код трансляций DNA - битовые маски, массивы - это ядро UGENE.  Никаких деревьев с прыжками по памяти и циклами там, где достаточно прямолинейного доступа в память.

Я могу создать PR где продемонстрирую то, что имею в виду - это займет намного меньше текста и времени чем переписка тут.

То что мы обсуждаем - это не относится к решаемой в PR задаче вообще так как является рефакторингом который можно было и не делать и про который я сразу предупредила - если переделывать - то правильно.

Раз правильно сложно - может оставить как есть? Старый switch намного оптимальнее дерева, так как позволяет компилятору видеть весь контекст для оптимизации.

2023-12-11 09:21 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusUtils.cpp
Изменения откачены

2023-12-11 09:28 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmLevitsky.cpp
> +    for (int i = 0; i < ALL_POSSIBLE_NUCL.size(); i++) {
У меня весь алгоритм заточен на то, что символ выбирается из текущей группы, все тесты проверяют тоже это же состояние, поскольку я посчитал такое поведение наиболее логичным и понятным. До описываемого тобою поведения нужно не дорабатывать, а переделывать. Так что нет, я не захочу

2023-12-12 03:10 UTC, yalgaer commented
Закрываю pull request. 

Правильное решение со всеми тестами из текущего PR и без касания extended consensus алгоритма залито в мастер.

Далее я перепишу утилитные методы из extended consensus алгоритма как и обещала - их стоит трогать только если добавить для него своих тестов - поэтому будет отдельный PR.

2023-12-12 03:10 UTC, closed without merging