UGENE-7956 Can't open ACE file
ugeneunipro/ugene pull request #1471
Opened 2023-12-06 04:19 UTC by rasputinkirill

Проблема в том что cap3 корректно обрабатывает файлы только с концами строк LF.
Исходный файл не модифицируется, меняется только его копия которая создается во время подготовки файлов.
Если создавались дополнительные файлы с качеством ридов `.qual` - то они уже имеют верные концы строк.

2023-12-06 23:21 UTC, yalgaer requested changes

2023-12-06 23:21 UTC, yalgaer commented on src/corelibs/U2Core/src/util/FileAndDirectoryUtils.cpp
> +void FileAndDirectoryUtils::convertToLfLineEndings(const QString& inputFilePath) {
Метод не возвращает результата операции.

2023-12-06 23:21 UTC, yalgaer commented on src/corelibs/U2Core/src/util/FileAndDirectoryUtils.cpp
> +    if (inputFile.open(QIODevice::ReadOnly)) {
Файл перезаписывается на месте: и можно ли это оптимизировать чтобы не считывать его полностью в память?
Что если вообще никаких изменений делать не нужно?

2023-12-06 23:21 UTC, yalgaer commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        FileAndDirectoryUtils::convertToLfLineEndings(inputUrl.getURLString());
В данном случае будет модифицирован `inputUrl`. 

Если этот файл был подан из внешнего контекста - мы не может его модифицировать тут так как он может использоваться где-то еще.

Если же этот файл был создан как промежуточный этап текущего таска - то почему бы его не создать корректно сразу?

2023-12-07 04:33 UTC, rasputinkirill commented on src/corelibs/U2Core/src/util/FileAndDirectoryUtils.cpp
> +    if (inputFile.open(QIODevice::ReadOnly)) {
Я не стал запариваться и писать проверку на то какие концы строк в исходном файле. Это надо открыть файл бинарном режиме искать есть ли там пары символов CRLF или только CR. Плюс файл может содержать разные символы концов строк, так что мы его все равно должны читать весь в память. Тут мы просто открыли файл и прочитали построчно и поменяли концы строк, это не какая-то там мега медленная операция. Я посчитал не целесообразным усложнять.

2023-12-07 04:54 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        FileAndDirectoryUtils::convertToLfLineEndings(inputUrl.getURLString());
Хорошо, давай перенесем в `PrepareInputForCAP3Task`.

2023-12-07 10:22 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +GUI_TEST_CLASS_DEFINITION(test_7956) {
Мне кажется, нам не нужен здесь гуи тест, лучше написать XML. Запуск CAP3 можно сделать с помощью схемы WD (элемент Assembly Sequences with CAP3 присутствует), загрузку с помощью "load-document"

2023-12-07 20:12 UTC, yalgaer commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +    CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
То есть мы сначала сами пишем sequence, а потом ее конвертируем. Почему бы сразу не записать правильно?

2023-12-08 07:09 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +    CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
Проверил код `SeqWriter`, он и так пишет с верными концами строк.

2023-12-08 07:11 UTC, rasputinkirill commented
@yalgaer что скажешь насчет комментария Димы https://github.com/ugeneunipro/ugene/pull/1471#discussion_r1418724654 ?

2023-12-08 15:11 UTC, yalgaer commented
> @yalgaer что скажешь насчет комментария Димы [#1471 (comment)](https://github.com/ugeneunipro/ugene/pull/1471#discussion_r1418724654) ?

Я согласна что если можно обойтись XML тестом то стоит им и обойтись.

2023-12-08 15:20 UTC, yalgaer commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
То есть, у нас есть проблема только с FASTA файлом который содержит неправильные переводы строк.
При этом для CAP3 этот файл является очень большим и явно произведенным не в ручную (в notepad.exe)

Поэтому вопрос: какая вероятность что подобный файл содержит неправильные переводы строк?

Если рабочая вероятность 0 и проблема воспроизводится только на фиктивных файлах созданных пользователем в нотепаде то может стоит выдать ошибку и все?

Что думаешь?

2023-12-12 07:14 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
Да, ситуация редкая. Возникнет только если на входе был единичный корявый fasta файл с неверными концами строк. Во всех остальных случаях подходящие для CAP3 входные файлы будут сгенерированны нами самими.
Я б оставил свое решение с исправлением концов строк по следующим причинам:
- прозрачно для пользователя - он взял запустил и все сработало, никаких задержек из-за ошибки
- если только информировать пользователя об ошибке, то в этом случае мы все равно делаем анализ файла - почему бы сразу не исправлять.

2023-12-12 07:26 UTC, yalgaer commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
Почему решение с конвертацией это плохо:

1) Плохой файл может придти только извне и ты его перезаписываешь. На изменение своих данных пользователь разрешения не давал.

2) Мы не читаем этот файл сами, а просто передаем его другому тулу. Ты предлагаешь начать читать и перезаписывать данные, которые иначе бы мы не читали вообще.

3) Мы уже договорились что этот сценарий не должен возникать на реальных данных: для ассемблера входные данные это сотни мегабайт или гигабайты - в notepad (как тест) их не составишь.

Лучшее решение - показать пользователю ошибку внешнего тула и предложить (в тексте ошибки) сконвертировать этот файл одной из наших схем, которая уже произведет корректный файл.

Предложенное изначально решение, когда из-за чисто синтетического теста мы наворачиваем и замедляем реальные сценарии некорректное.

2023-12-12 07:37 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
> 1. Плохой файл может придти только извне и ты его перезаписываешь. На изменение своих данных пользователь разрешения не давал.

Мы не переписываем исходный, только его копию.

> 2\. Мы не читаем этот файл сами, а просто передаем его другому тулу. Ты предлагаешь начать читать и перезаписывать данные, которые иначе бы мы не читали вообще.
> Лучшее решение - показать пользователю ошибку внешнего тула и предложить (в тексте ошибки) сконвертировать этот файл одной из наших схем, которая уже произведет корректный файл.
Тул отрабатывает без ошибок в этой ситуации, просто мы не можем нормально прочитать результырующий ACE файл так как там концы строк разные, юджин не может в итоге нормально парсить файл, так как там некоторые строки оказываются разбыты на две.

Поэтому мы сами должны читать входной файл и править его, либо писать что в нем неверные концы строк.
Либо убрать эту стремную ветку алгоритма поготовки файлов
`if (inputUrls.size() == 1) {
    const QString& inputFileUrl = inputUrls.first();

    QList<FormatDetectionResult> results = DocumentUtils::detectFormat(inputFileUrl);

    if (!results.isEmpty()) {
        DocumentFormat* format = results.first().format;
        if (format->getFormatId() == BaseDocumentFormats::FASTA) {
            onlyCopyFiles = true;
        }
    }
}`

И тогда все файлы будут перезаписываться через `StreamShortReadWriter` и будут хорошие концы строк, я думаю тут нет какого-то невераятного выигрыша по производительности.

2023-12-13 00:55 UTC, yalgaer commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
Если мы с любом случае копируем этот fasta файл - то предложенное тобой решение заменить копирование на конвертацию может и сработать.

Можешь прямо здесь и вставить свою фунцию конвертации, нам же не надо читать файл как fasta в данном случае.

Важно учесть что мы не должны втягивать конвертируемый файл в память - он может быть очень большим (это данные ассемблера).

2023-12-13 07:04 UTC, rasputinkirill commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
Чето я не понял что ты имеешь в виду. Я предлагал выкинуть полностью переменную onlyCopyFiles и ветку алгоритма if (onlyCopyFiles). Делаем так?

Так же я понял что текущее решение неверное, нельзя оставлять смену концов строк в run() так как копирование происходит в сабтаске и может произойти гонка данных, когда файл еще не скопирован, а run() уже исполняется.

2023-12-14 00:46 UTC, yalgaer commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
Внутри onlyCopyFiles нужно проверить (например первый мегабайт) на предмет наличия плохих переводов строк и 1) либо скопировать как раньше (без изменений) 2) либо новым способом.

Проверки первого мегабайта достаточно, так как этот ассемлер работает на коротких ридах (<1000) и для Fasta обязательно будут новые строки.

Читать при конвертации нужно потоком: читаем N (1Mb) символов -> меняем переводы строк -> пишем
Так, чтобы весь файл не находился в памяти один момент времени.

Этот способ копирования не зависит от формата файла - главное чтобы он был текстовый и правильно определилась кодировка.

Протаскивать данные через память (внутреннюю fasta или plain text) не нужно - данные для ассемблера обычно очень большие - легко превышают гигабайт.

2023-12-14 00:49 UTC, yalgaer commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +        CHECK_EXT(FileAndDirectoryUtils::convertToLfLineEndings(preparedPath),
> Так же я понял что текущее решение неверное, нельзя оставлять смену концов строк в run() так как копирование происходит в сабтаске и может произойти гонка данных, когда файл еще не скопирован, а run() уже исполняется.

У тасков есть различные флаги/способы синхронизации.
Думаю этих их достаточно чтобы решить проблему копирования (подождать его), если эта проблема есть.

2023-12-14 23:52 UTC, yalgaer requested changes
Я не дам апрув на код который втягивает полный файл с шортридами для ассемблера в память. Речь может идти о гигабайтах Нужно исправить на поточный режим.
Иначе этот фикс приносит больше вреда, чем пользы.

Проверку на наличие плохих переводов строк тоже добавить надо.
Смотри TextDocumentFormat::checkRawData - может помочь.

2023-12-23 00:19 UTC, yalgaer commented
Закрываю задачу как неактивну. Переоткрой, пожалуйста, как будут изменения.

2024-01-08 23:31 UTC, rasputinkirill commented
Переделал как обсуждали: добавил в таску копирования опцию замены концов строк.

2024-01-09 10:14 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    CHECK(ioFrom != nullptr && ioTo != nullptr, );
Аналогом `assert` является `SAFE_POINT`, не `CHECK`

2024-01-09 10:18 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +            const char currentChar = *it;
Можно заменить на более современную и простую для понимания запись:
`    for (char currentChar : qAsConst(line)) {`

2024-01-09 10:21 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
>      qint64 count_w = 0;
Не относится к твоей задаче, но, вроде, эта переменная вообще никак не используется. Если будешь делать изменения в этом файле - удали, пожалуйста

2024-01-09 10:28 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/cap3/CAP3SupportTask.cpp
> +            CopyDataTask* copyTask = new CopyDataTask(iof, fileName, iof, outputDir + "/" + GUrl(fileName).fileName(), CopyDataTask::ReplaceLineEndings::LF);
Погоди, т.е. мы делаем какие-то правки в файле только в том случае, если он является результатом работы CAP3, запущенным из UGENE? Но ведь ACE файл мог придти вообще откуда угодно. В том числе, пользователь мог запустить CAP3 независимо от UGENE, получить результат и попытаться открыть его в UGENE.

2024-01-09 10:31 UTC, DmitriiSukhomlinov submitted a review, later dismissed
Я прошу прощения, если это уже обсуждалось и я пропустил, но, с моей точки зрения, данный подход не верный. Мы не должны пытаться поправить файл в промежутке между запуском CAP3 и открытием ACE файла, поскольку некорректный ACE файл может придти откуда угодно. Пользователь может запустить CAP3 независимо от UGENE, а, затем, попытаться открыть результат в UGENE. Мое мнение - нужно править процесс парсинга ACE файла.

2024-01-09 18:53 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        replaceLineEndings(newLineEndings, lineEndsWithCR, buff, count);
Что есть граница прочитанного блока лежит внутри CRLF: CR в одном блоке а LF в другом?
Я вижу что в твоем алгоритме ниже есть привязка на 2 последовательно идущих символа, правильно?

2024-01-09 22:44 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        replaceLineEndings(newLineEndings, lineEndsWithCR, buff, count);
Да этот случай должен обрабатываться корректно, я проверил когда граница чтения лежит между CR и LF.

2024-01-09 22:55 UTC, rasputinkirill commented
@DmitriiSukhomlinov CAP3 выдает корявый эйс файл если в файлах с ридами не линуксовые концы строк. Юджин корректно парсит и корректно отрабатывает ошибки в неверном эйс файле. Поэтому мы обрабатываем входные файлы для CAP3 чтобы он выдал правильный файл (вроде ж все это в описании ревью было).
Да некорректный эйс может прийти откуда угодно, но ведь мы его парсим и выдаем диагностику, разве этого недостаточно?

2024-01-10 02:25 UTC, DmitriiSukhomlinov commented
> @DmitriiSukhomlinov CAP3 выдает корявый эйс файл если в файлах с ридами не линуксовые концы строк. Юджин корректно парсит и корректно отрабатывает ошибки в неверном эйс файле. Поэтому мы обрабатываем входные файлы для CAP3 чтобы он выдал правильный файл (вроде ж все это в описании ревью было). Да некорректный эйс может прийти откуда угодно, но ведь мы его парсим и выдаем диагностику, разве этого недостаточно?

Посмотри на это с точки зрения пользователя. У него есть вполне нормальный, с его точки зрения, ACE-файл, который не открывается и он не понимает, почему. Диагностика, в данный момент, плохая, и никаких ошибок, которые ему могли бы подсказать о том, в чем проблема, не выдает. Пользователь сам не сможет решить эту проблему. Мы, собственно, узнали про неё только потому, что нам пользователь и написал.

Да, твое решение исправляет сценарий, возникший у конкретно этого пользователя, но проблема в общем случае остается. Проблема нам известна - существует биоинформатический инструмент CAP3, который используют и который плохо работает с входными файлами и генерирует не совсем верный результат. Да, мы можем сказать, что это не с нашей стороны проблема, но пользователя-то это не волнует, у него CAP3 во время исполнения ошибок не выдавал, так что там все было в порядке. Он пытается открыть ACE в юджине, у него не получается, пользователь удаляет юджин и вот мы потеряли пользователя.

Я считаю, что раз мы знаем про то, что на данном этапе существует проблема, то нужно ее фиксить для всех случаев использования, а не только для одного частного сценария.

2024-01-10 10:59 UTC, rasputinkirill commented
@DmitriiSukhomlinov не увидел от тебя конкретного предложения как решать проблему.
Если ты предлагаешь научить юджин правильно различать и правильно парсить неправильный файл сделанный инструментом CAP3, считаю этот подход абсурдным. Форматы файлов именно для того и сделаны чтобы им соответствовать.

2024-01-11 02:28 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    if (newLineEndings == ReplaceLineEndings::LF) {
Почему мы здесь не можем просто убрать все CR из буфера? 
Мы же работаем здесь с текстом и случайных контрольных символов быть не может.

2024-01-11 02:28 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    ReplaceLineEndings newLineEndings;
Нужно инициализировать значением по умолчанию

2024-01-11 02:29 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    void replaceLineEndings(ReplaceLineEndings newLineEndings, bool prevLineEndsWithCR, QByteArray& line, qint64& symbolsCount) const;
Используй `const &` для всех нестантартный типов. Когда читаешь код сразу не видно enum этот или что-то еще.

2024-01-11 02:30 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    void replaceLineEndings(ReplaceLineEndings newLineEndings, bool prevLineEndsWithCR, QByteArray& line, qint64& symbolsCount) const;
Добавь документацию для метода что происходит с line & symbolCount

symbolCount поменяй на int& так как в QByteArray больше не поместится.

2024-01-11 02:31 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    SAFE_POINT(ioFrom != nullptr && ioTo != nullptr, "One of io adapters is null!", );
Используй SAFE_POINT_NN

2024-01-11 02:31 UTC, yalgaer reviewed
Минимальные замечания. 

Апрув после исправления и тестов.

2024-01-12 05:45 UTC, DmitriiSukhomlinov commented
> @DmitriiSukhomlinov не увидел от тебя конкретного предложения как решать проблему.
Если ты предлагаешь научить юджин правильно различать и правильно парсить неправильный файл сделанный инструментом CAP3, считаю этот подход абсурдным. Форматы файлов именно для того и сделаны чтобы им соответствовать.

Я уже написал конкретно - не исправлять файл, а подправить парсинг. Ты правишь определенный кейс, а не проблему в общем случае.

Так же нужно удалить GUI тест и заменить его XML, который в данном случае прекрасно пишется.

2024-01-12 05:52 UTC, DmitriiSukhomlinov commented
> @DmitriiSukhomlinov не увидел от тебя конкретного предложения как решать проблему.
Если ты предлагаешь научить юджин правильно различать и правильно парсить неправильный файл сделанный инструментом CAP3, считаю этот подход абсурдным. Форматы файлов именно для того и сделаны чтобы им соответствовать.

Короче, я не вижу смысла спорить, минимально используемый кейс. Единственное - мне кажется, что тут вполне можно написать XML тест, GUI излишен.

2024-01-12 13:30 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    if (newLineEndings == ReplaceLineEndings::LF) {
Я анализирую строку посимвольно и если встречаю CR заменяю его на LF, если потом за ним следует LF - он игнорируется, чтобы не было двух переводов строки вместо одного. Просто делать `QByteArray::replace` по всей строке не получится правильная строка.

2024-01-12 13:31 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    ReplaceLineEndings newLineEndings;
уже и так в конструктор вписано, но окей добавлю и тут

2024-01-12 13:35 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    void replaceLineEndings(ReplaceLineEndings newLineEndings, bool prevLineEndsWithCR, QByteArray& line, qint64& symbolsCount) const;
окей, но как я помню обычно документировали только публичные методы

2024-01-12 22:20 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    if (newLineEndings == ReplaceLineEndings::LF) {
Я  вижу что для того, что может быть сделано 1 строкой тут написал достаточно сложный алгоритм на 20 строк.

Смотри, если все, что нам нужно это заменить в текстовом файле \r\n на \n достаточно удалить все \r
Вариантов когда \r идет без привязки к \n просто не бывает - иначе это неправильный текстовый файл.


>Просто делать QByteArray::replace по всей строке не получится правильная строка.

Можешь ли привести вариант строки с которой произойдет плохое?

2024-01-15 22:25 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    * Replace existing line endings with desired
Ни из декларации ни из описания метода мне непонятно что далается с массивом line и что пишется в symbols count.

2024-01-16 22:22 UTC, yalgaer requested changes
Остался открытым вопрос выше:
https://github.com/ugeneunipro/ugene/pull/1471#discussion_r1450977383

2024-01-16 23:57 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    if (newLineEndings == ReplaceLineEndings::LF) {
1. На маке концы строк в текстовых файлах CR.
2. Маловероятно, но могут быть намешаны концы строк в файле, тогда CR+LF расцениваем как конец строки и отдельно стоящий CR как конец строки

2024-01-18 00:56 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    if (newLineEndings == ReplaceLineEndings::LF) {
1. На маке уже 15 лет как переводы строк такие же как и на Linux.
2. Намешать концы строк так, чтобы простая замена, о которой я писала выше, не получится - файлы с переводами в виде одиночных \r можно считать битыми и не работать с ними.

2024-01-24 21:56 UTC, yalgaer requested changes
Выношу сюда оставшиеся замечания, так как ты видно потерял их выше (не отвечаешь)

1) Для замены \r\n на \n в корректном текстовом файле достаточно удалить \r
Переводов строк с \r на маке нет уже лет 15. Поэтому весь твой сложный метод может быть заменён на 1 стоку с replace.

2) Метод replaceLineEndings содержит избыточный параметр: symbolsCount. Если ты решил изменить массив line in-place - то его финальная длина и будет symbols count.

2024-01-24 22:32 UTC, rasputinkirill commented
В предыдущем коммите как раз сделал как ты и просила.
Так же добавил проверку что в файле не намешаны разные концы строк, в этом случае предупреждаю пользователя что могут быть дальнейшие проблемы. Опять же в соответствии с твоим замечанием, что мы не работаем с файлами если в них намешаны разные концы строк.
Про второе замечание не понял, если мы меняем CRLF на LF длинна же массива меняется, и соответственно далее в функцию которая пишет в файл мы передаем QByteArray и скорректированную длину.

2024-01-25 16:30 UTC, yalgaer commented
> Про второе замечание не понял, если мы меняем CRLF на LF длинна же массива меняется, и соответственно далее в функцию которая пишет в файл мы передаем QByteArray и скорректированную длину.

Измененная длина массива это QByteArray().length - зачем нужна дополнительная переменная к уже имеющейся в QByteArray ?

2024-01-26 08:49 UTC, rasputinkirill commented
> Измененная длина массива это QByteArray().length - зачем нужна дополнительная переменная к уже имеющейся в QByteArray ?

Ели глянешь по коду, как там сделано в `IOAdapter` чтение\запись они используют `char*` как буфер и количество символов прочитанных записанных. В  `CopyDataTask` `char*` зачем-то обернули в `QByteArray` (может чтобы автоматически чистился `char*`). Но этот `QByteArray` будет всегда длинны `BUFFSIZE`, а в его `data*` читается содержимое файла, но оно очевидно будет меньше чем `BUFFSIZE` на последней итерации, для этого и переменная с количеством прочитанных символов.

2024-01-28 00:35 UTC, yalgaer requested changes
Нужно из массива
```
QByteArray buff(BUFFSIZE, 0);
```
удалить все \r перед записью в файл.
Далее вернуть его длину обратно: buff.resize(BUFFSIZE)

2024-01-29 13:00 UTC, rasputinkirill commented
Переделал. Так ты хотела?

2024-01-30 02:12 UTC, yalgaer commented
> Переделал. Так ты хотела?

Нет я уже говорила выше что сложность в виде `replaceLineEndings` должна уложиться в одну строчку - удалить все \r из строки если это нужно.

2024-01-30 08:10 UTC, rasputinkirill commented
Так?

2024-01-31 03:01 UTC, yalgaer commented
> Так?

Нет, вся функция replaceLineEndings должна исчезнуть и остаться только строка byteArray.replace()

2024-02-02 07:49 UTC, rasputinkirill commented
А теперь?

2024-02-03 17:06 UTC, yalgaer requested changes
Минимальные заменчания. Approve после исправления и GUI тестов

2024-02-03 17:06 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
Считать все эти символы не нужно. Достаточно одного boolean который выставляется в true если у буффера изменился размер после удаления '\r'

2024-02-03 17:06 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    static const char CHAR_CR = '\r';
Все эти private константы нужно унести в C++.

2024-02-03 17:06 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    lt.assertNoErrors();
Нужно проверить сообщение в логе что task сделал то что ты писал в нем: заменил и выдал warning

2024-02-10 20:59 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
Не понял, почему так надо сделать?
Я сделал что мы подсчитываем /r и /n чтобы убедиться что их равное количество, что будет означать то что переводы строк не намиксованы.

2024-02-10 21:01 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    static const char CHAR_CR = '\r';
Тут я тоже не понял, почему так.
В других файлах static const нормально объявляются в заголовочных файлах.

2024-02-10 21:03 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    lt.assertNoErrors();
warning выдается если концы строк смешаны, то есть присутствуют и \r, и \r\n .

2024-02-12 20:47 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    static const char CHAR_CR = '\r';
Не нужно объявлять приватные статические константы в заголовочных файлах.
В старых файлах это может встречаться, в новых так делать уже не нужно.

2024-02-12 20:51 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
Если переводы строк "намиксированы" в текстовом файла  - то текстовый файл битый и это не наша проблема.

Насколько я понимаю мы тут решаем очень простую задачу: в корректном текстовом файле с переводами строке  \r\n заменить все переводы строк на \n.
Это делается удалением \r.

Если это почему-то не далается - файл битый изначально. С битыми файлами UGENE работать не обязан - ошибка это нормальный результат в этом случае.

2024-02-12 20:52 UTC, yalgaer requested changes
см. комментарии

2024-02-13 07:21 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
> Если это почему-то не далается - файл битый изначально. С битыми файлами UGENE работать не обязан - ошибка это нормальный результат в этом случае.

Так я для этого и сделал эту проверку чтобы пользователь получил диагностику про свой исходный файл и увидел предупреждение.

2024-02-13 08:01 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    static const char CHAR_CR = '\r';
Мне не жалко поменять, я просто не понимаю в чем преимущество предлагаемого тобой варианта.

2024-02-14 22:00 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    lt.assertNoErrors();
Мы знаем что в этом случае CAP3 упадет - он не умеет работать с \r\n?
Ты хочешь сказать что он умеет работать со \r? Тогда warning не нужен.
Если он не умеет работать с \r - тогда тоже warning не нужен - это уже не warning а ошибка.

2024-02-14 22:02 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    static const char CHAR_CR = '\r';
Заголовочные файлы в первую очередь описывают публичный интерфейс.

Если что-то приватное можно утащить в С++ (как статики) - их нужно класть туда. Это ускорить перекомпиляцию в случае их модификации: не будут перекомпилироваться зависимые от публичного интерфейса файлы.

В итоге компиляция будет быстрее и ты зафиксишь больше багов :)

2024-02-14 22:04 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
Если файл битый - то это не предупреждение а ошибка. CAP3 все равно упадет.
Проверка на "битость" делается в 1 строку:
1) Заменяем \r\n на \n
2) Делаем проверку: остались ли еще \r

2024-02-16 02:07 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
Так нельзя делать, вдруг конец буфера чтения будет между CR и LF. Поэтому я и сделал replace одного символа на пустой. И подсчет всех видов переносов строк.

2024-02-16 02:09 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    static const char CHAR_CR = '\r';
То есть constexpr в заголовочных файлах теперь не используем?

2024-02-16 02:14 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    lt.assertNoErrors();
Хорошо, сначала разберемся как на определять "битый" и "обработаный" файлы из другог комментария.

2024-02-16 06:08 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
Оно плохо следующим:

1) Влияет на обычный режим когда замена не нужна. Мы считаем CRLF всегда, даже когда не просят.

2) Код который обрабатывает CRLF, на мой взгляд неоправданно сложен. Простое решение о котором я писала: просто убери все CR из буфера. Эти символы управляющие и бинарные (не имеют текстового представления). Если убирание CR из текстового файла делает его по каким-то причинам 'битым' - этот файл изначально был битым для (наших нужд)- можно и отказаться работать с ним.

3) Когда ты делаешь `buff.replace(CHAR_CR, "");` хотелось бы знать эффективно ли работает эта операция. Здесь мы копируем большие файлы и если из 1Гб нам надо удалить каждый сотый символ и это потребует 10М  релокаций внутри массива 4Мб - это будет нехорошо - тогда надо использовать другой алгоритм замены, который релоцирует данные только раз в момент прохода по буферу.

2024-02-19 03:36 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
ты не ответила  что делать если

> вдруг конец буфера чтения будет между CR и LF.

попробовал решить это самостоятельно

2024-02-19 03:37 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    lt.assertNoErrors();
Поправил

2024-02-19 16:17 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.h
> +    static const char CHAR_CR = '\r';
Если приватные данные можно положить в *.cpp вместо .* без усложнения кода - нужно их класть в *.cpp

2024-02-19 16:18 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +    cRCount += buff.count(CHAR_CR);
Если просто удалять все CR из буфера то не важно на какой символ приходится граница буфера

2024-02-19 16:22 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        isCRLastSymbol = buff.endsWith(QB_CR);
Алгоритм повторен 2 раза в этой функции. Это нормально если алгоритм банален, иначе это не хорошо.
Так как все что нам нужно знать после buff.replace() это были ли удалены символы то считать их не надо. Достаточно сравнить длину буфера до и после. А такую короткую логику можно уже и повторить

2024-02-19 16:23 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        buff.replace(QB_CRLF, QB_LF);
Здесь стоит заменить \r просто на пустой символ.

2024-02-19 16:24 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +            buff.replace(QB_CRLF, QB_LF);
Какая сложность метода buff.replace? Если в буфере размером 1мб каждый сотый символ будет \r - будет ли сделано 10k перемещений в буфере или только одно?

2024-02-19 16:24 UTC, yalgaer requested changes
см. комментарии

2024-02-20 02:20 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +            buff.replace(QB_CRLF, QB_LF);
Документация не дает ответ на этот вопрос

2024-02-20 02:42 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        buff.replace(QB_CRLF, QB_LF);
В прошлом коммите решение было `buff.replace(CHAR_CR, "");` тебе не понравилось ты сказала сделай `buff.replace(QB_CRLF, QB_LF);`, я сделал, теперь ты просишь обратно. Я продолжаю ничего не понимать.

2024-02-20 03:09 UTC, rasputinkirill commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        isCRLastSymbol = buff.endsWith(QB_CR);
Алгоритм повторен так как ты сама писала чтобы я убрал отдельную функцию которая это делала.
С длинной буфера лучше вообще тут не работать она не всегда меняется правильно коггда в не читают, потому что как я уже писал местный `QByteArray` просто выступает тут как обертка для `char*` чтобы память при выходе из метода сама почистилась. А все методы чтения записи работают с `char *QByteArray::data()` и длинной `count`. Я и написал код используя эти механизмы чтобы не делать всякие лишние ресайзы и потом передавать длину в count.
Считаем мы все символы \r после `buff.replace(QB_CRLF, QB_LF);` чтобы увидеть остались ли после этого одиночные \r в буфере. Если символ был последним в буфере и за ним следовал \n то мы уменьшаем счетчик на единицу. В итоге если `singleCRCount` больше нуля после прочтения файла то мы определяем был ли файл с намешаными концами строк.
Тут подумал что надо еще и одиночные LF посчитать если оны были то тоже определять это как ошибку.

2024-02-20 15:30 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +            buff.replace(QB_CRLF, QB_LF);
Без знания того как работает этот метод ты не можешь его использовать, так как это может привести к N/100 копированиям большого массива, где N для задач ассемблирования может измеряться гигабайтами.

Варианты:
- Узнай как работает этот метод посмотрев исходник
- Напиши и протестируй наш метод в TextUtils который удаляет из строки заданный символ.

2024-02-20 15:33 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        buff.replace(QB_CRLF, QB_LF);
Ты же правильно заметил что \r\n может попасть на границу блока. Значит остается только вариант с удалением \r - мы обсуждали оба эти варианта.

2024-02-20 15:35 UTC, yalgaer commented on src/corelibs/U2Core/src/tasks/CopyDataTask.cpp
> +        isCRLastSymbol = buff.endsWith(QB_CR);
Убрать отдельную функцию нужно было потому что она уже есть: QByteArray.replace('\r', '')
Если эта операция меняет длину буфера - то не нужно вызывать count().

2024-02-24 00:52 UTC, yalgaer commented
В этом PR осталось сделать очень немного:

1) Удалить все \r из считываемого буфера

2) Сделать это эффективо - избегая многоразового копирования используй метод TextUtils::remove() или напиши подобный метод который принимает не битовую маску удаляемых символов а сам символ.

Итого: это можно сделать минут за 20-30.

2024-02-24 00:53 UTC, yalgaer requested changes
См. комментарий с решением выше

2024-02-28 02:46 UTC, yalgaer reviewed
По патчу замечаний нет, пожалуйста смержись с master и запусти тесты

2024-02-29 18:41 UTC, yalgaer commented
Если по тестам нет падений связанных с этим PR даю approve

2024-03-03 19:58 UTC, yalgaer approved these changes

2024-03-04 03:57 UTC, merged