UGENE-8001 SAFE_POINT if you add document with the name of already opened one
ugeneunipro/ugene pull request #1473
Opened 2023-12-08 13:40 UTC by DmitriiSukhomlinov

2023-12-08 15:11 UTC, yalgaer requested changes

2023-12-08 15:11 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/CreateDocumentFromTextDialogController.cpp
> +        const auto& documents = project->getDocuments();
Нужно использовать findDocumentByURL() вместо цикла

2023-12-08 15:11 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/CreateSequenceFromTextAndOpenViewTask.cpp
> +    const auto& documents = project->getDocuments();
Не нужно удалять текущий документ таким образом. У нас уже есть функционал который предлагает пользователю перезагрузить существующий документ in-place если он был изменен извне UGENE.

Этот сценарий будет общим и для случая если запущено несколько копий UGENE и каждая из них уже имеет открытым данный перезаписываемый документ.

2023-12-11 03:17 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/CreateSequenceFromTextAndOpenViewTask.cpp
> +    const auto& documents = project->getDocuments();
Очень многое не понятно. Во-первых, касательно нескольких копий UGENE. В данном сценарии последовательность не сохраняется в файл (галочка "Save immediately" в диалоге создания последовательности не установлена, также мы нигде не жмем отдельно кнопку "Сохранить"), поэтому эта последовательность существует только в сессионной базе UGENE, но не существует на диске. Разные инстансы UGENE используют разные сессионные базы, не знающие о существовании друг друга, поэтому спроецировать этот сценарий на случай с несколькими одновременно открытыми копиями UGENE проблематично. 

Во вторых - удаление/модификация документа, уже открытого в UGENE, относится к сценариям совсем другого типа (да-да, сейчас будет то самое "вы не понимаете, это другое"). Поскольку мы можем контролировать только события, происходящие внутри UGENE, а любой открытый файл может быть модифицирован на уровне операционной системы (через обычный текстовик, например - чего мы уже не можем контролировать) мы должны постоянно отслеживать изменения файла извне и если оно случилось - информировать об этом пользователя. В описанном же в данной задаче сценарии все действия происходят внутри UGENE - то есть внутри пространства, которое у нас под контролем. Поэтому, мы вполне можем предупредить пользователя **заранее** о том, что его действия могут првести к перезаписыванию того или иного файла (как мы делаем во многих других случаях) и, если он проигнорирует это предупреждение, со спокойной душой сделать эту модификацию. В случае модификации файла извне UGENE мы уведомляем пользователя о произошедшей модификации уже **постфактум** - просто потому, что мы заранее об этом знать никак не могли.

В третьих, не очень понятно предлагаемое тобою решение. Сценарий текущей задачи можно модифицировать и отпочковать от него второй случай - когда перезаписываемый файл уже существует на диске. Это не очень хорошо - мое текущее решение не требудет деления на микрокейсы - однако, пускай. После этого он будет выглядеть как-то так:

1. Откройте "human_T1.fa"
2. Нажмите File -> New document from text..
3. Напечатайте "ACGT" в качестве последовательности и введите путь к "human_T1.fa" в качестве пути к файлу.
4. Нажмите "Create"

И - очевидный вопрос - что дальше должно происходить? У нас уже есть открытый в UGENE документ, привязанный к "human_T1.fa". Добавить в проект еще один документ, приязаный к тому же файлу, мы не можем - UGENE так не умеет (не писать же массивную инфраструктуру, которая научит так делать, для такого маленького бага). Куда деть этот новый открытый файл?

Короче, описываемая тобой функция тут не совсем к месту и ее использование создает целую массу вопросов и непоняток.

2023-12-11 03:28 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/CreateDocumentFromTextDialogController.cpp
> +        const auto& documents = project->getDocuments();
Это хороший совет, поправил

2023-12-11 03:43 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/CreateSequenceFromTextAndOpenViewTask.cpp
> +    const auto& documents = project->getDocuments();
Мой сценарий совместим со всеми другими сценариями которые уже есть в UGENE: любые export диалоги, генерация данных или множество вызовов Save-To-File диалога:

1) Если пользователь перезаписывает файл который уже есть в проекте - его стоит предупредить: хочет ли он только перезаписать существующий файл.

2) Если пользователь хочет перезаписать файл - перезаписать его. UGENE сам увидит эти изменения и запустит их обработку единым способом.

Данный случай ("create document from text") не отличается от "save selected sequence/alignment/etc to document" или "generate  document". Функционал, когда могут потеряться данные из памяти и замениться новыми данными с диска должен обрабатываться и развиваться в едином ключе, а не в каждом месте разрабатываться заново.

На счет галочки "Save file immediately": ее нужно убрать так как она больше запутывает пользователя и в ней нет практического смысла. Пользователь указывает файл куда записать сразу, может вставить через наш GUI в него только относительно небольшой текст и его нужно сохранить тоже сразу.

2023-12-11 04:14 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/CreateSequenceFromTextAndOpenViewTask.cpp
> +    const auto& documents = project->getDocuments();
Все равно не понимаю, что требуется. Будем говорить в рамках сценариев (допустим, я убераю галочку "Save immediatly"):

1. Нажмите File -> New document from text..
2. Напечатайте "AAAA" в качестве последовательности и введите путь к "123.fa" в качестве пути к файлу.
3. Нажмите "Create"  
Ожидается: файл сохранен на диск.
4. Снова нажмите File -> New document from text..
5. Снова напечатайте "GGGG" в качестве последовательности и введите путь к "123.fa" в качестве пути к файлу.
6. Нажмите "Create".  
Текущее поведение: SAFE_POINT.
Ожидаемое поведение: 

Что должно быть в графе "Ожидаемое поведение"?

2023-12-11 05:00 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/CreateSequenceFromTextAndOpenViewTask.cpp
> +    const auto& documents = project->getDocuments();
Должно произойти следующее:

1) Пользователь должен подтвердить что он действительно хочет перезаписать существующий файл.
2) UGENE должен перезаписать этот файл
3) Должен включиться общий для подобного типа сценариев обработчик на случай когда модифицирован файл добавленный в проект.

Далее обсуждаем уже дизайн этого обработчика (общего для всех подобных сценариев)
1) Обработчик должен работать быстро (для этого есть системный file-watch API)
2) Обработчик должен посмотреть нет ли новых данных которые могут быть потеряны в результате перезагрузки (например аннотации к файлу, модификации и тп)
3) Обработчик должен предложить пользователю оптимальный способ разрулить ситуацию для разных типов модификаций.

Рассмотрим самый простой случай: перегружается файл который не имеет модификаций, открытых view и ссылкок (GObjectReference). В этом случае можно перегрузить файл не спрашивая пользователя.

В рамках этого бага не обязательно доделывать/улучшать этот обработчик - достаточно иметь его в виду - он уже есть и как-то (хоть и не идеально) работает.

2023-12-11 06:49 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/CreateSequenceFromTextAndOpenViewTask.cpp
> +    const auto& documents = project->getDocuments();
OK, попробуем так

2023-12-12 03:13 UTC, yalgaer approved these changes

2023-12-12 03:21 UTC, merged