UGENE-8024 SAFE POINT on opening 2 files together
ugeneunipro/ugene pull request #1482
Opened 2023-12-14 04:39 UTC by rasputinkirill

2023-12-14 23:57 UTC, yalgaer requested changes
Фикс плохой: Наличие warnings в subtask не является причой считать что он не сработал как нужно.

Нужен нормальный документированный API на конкретном типе таска описывающий ситуацию.

2023-12-15 12:36 UTC, rasputinkirill commented
> Фикс плохой: Наличие warnings в subtask не является причой считать что он не сработал как нужно.
> 
> Нужен нормальный документированный API на конкретном типе таска описывающий ситуацию.

Это изначально логика которое я не менял. Я только сделал чтобы наличие warnings из subtask корректно были переданы родительской таске.
Как по твоему мнению должна правильно отрабатываться ситуация из сценария?

2023-12-15 19:07 UTC, yalgaer commented
> Это изначально логика которое я не менял. Я только сделал чтобы наличие warnings из subtask корректно были переданы родительской таске. Как по твоему мнению должна правильно отрабатываться ситуация из сценария?

Старый код может быть плохим. Новый нет.
Я не знаю как это исправлять - мне нужно время чтобы разобраться (это 90% работы).
У меня будет время на следующей неделе. Или предлагай свое решение раньше.

2023-12-23 17:50 UTC, yalgaer commented
Закрываю PR как неактивный. Будет что-то новое - открывай.

2023-12-23 17:50 UTC, closed without merging