Fix test_0010.xml
ugeneunipro/ugene pull request #1494
Opened 2023-12-20 15:36 UTC by EvelinaBiserova

2023-12-20 17:58 UTC, yalgaer requested changes
Нужно хоть какое-то пояснение почему это нужно именно для этого теста, но не для десятка подобных.

2023-12-21 04:57 UTC, evelinabis commented
> Нужно хоть какое-то пояснение почему это нужно именно для этого теста, но не для десятка подобных.

Fails on Linux because it runs in multiple threads. The 9th test writes an error to the log, which is indifferent to it. The 10th test reads this error from the log, since the log is common to all tests. If the 10th test was started before the 9th test ran, then this error will appear; if the 9th test runs first, then the 10th test log listener will start later than the unexpected message from the 9th file, and there will be no problems.

Messages from the 9th test are highlighted in black, messages from the 10th are highlighted in red. This is part of the log of run #4054.
![Screenshot 2023-12-21 114800](https://github.com/ugeneunipro/ugene/assets/39720063/5918024a-8a15-4fea-89b4-05d326545d12)

See the 10th test history http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/test/-8813027912133869155?currentBuildTypeId=XmlLinux&currentProjectId=UgeneCommitBuilds&expandTestHistoryChartSection=true

You can reproduce the problem by running all 10 tests from the genbank folder locally several times with and without these changes.

2023-12-21 17:13 UTC, yalgaer commented
Что делать с остальными тестами которые имеют `no-message=` но не имеют `lockForLogListening`?

Самый простой способ поправить их все и навсегда это
1. Удалить lockForLogListening из XML
2. В multi-test проверять элементы внутри и если хоть один из них зависит от того, что написано в лог, автоматически ставить `lockForLogListening`

Таким образом будут исправлены все текущие проблемы и не ошибется тот кто будет писать новые тесты.

2023-12-22 04:23 UTC, evelinabis commented
> Что делать с остальными тестами которые имеют `no-message=` но не имеют `lockForLogListening`?

What about the "message" attribute?
What about attributes that don't contain the word "message" but are log listeners?
What about implicit log listeners that are not marked with any attribute?
Are all `XmlTest`s written and will be written without log listeners?

In general, the idea is good, we need to see it through to the end. We may have to inherit all listeners not from `XmlTest`, but from `XmlTestWithLogListener`, where this tag will be written by default.

2023-12-22 23:46 UTC, yalgaer commented
Нужно выделить 1-2 аттрибута которые отвечают за проверку лога как шаблонные и проверять на их наличие.

Если какой-то из тестов нарушает этот шаблон (вводит свои аттрибуты) - этот тест описан неправильно и нужно исправить шаблон этого теста.

Наследований и новых классов вводить не нужно - достаточно композиции. Все возможные трейты тестов с С++ не отнаследуешь.

Итого, правки в С++ будут минимальными, поле `lockForLogListening` пропадёт из всех тестов вовсе.

2023-12-23 07:30 UTC, evelinabis commented
> Нужно выделить 1-2 аттрибута которые отвечают за проверку лога как шаблонные и проверять на их наличие.
> 
> Если какой-то из тестов нарушает этот шаблон (вводит свои аттрибуты) - этот тест описан неправильно и нужно исправить шаблон этого теста.
> 
> Наследований и новых классов вводить не нужно - достаточно композиции. Все возможные трейты тестов с С++ не отнаследуешь.
> 
> Итого, правки в С++ будут минимальными, поле `lockForLogListening` пропадёт из всех тестов вовсе.

Well, add the proposed editing so that the current testing does not fall, and then correct the test, as you usually do.

Changes in each other do not contradict, but the decision you have proposed is significantly more complicated and should be made in a separate PR.

2023-12-23 17:49 UTC, yalgaer commented
Хорошо, делай в другом PR. Этот я закрываю - он не нужен.

2023-12-23 17:49 UTC, closed without merging