UGENE-8033 Update Plasmid features database
ugeneunipro/ugene pull request #1498
Opened 2023-12-22 12:59 UTC by DmitriiSukhomlinov

Данная функция была создана в аналогии с инструментом PlasMapper2.0, который вышел в 2004 году (что делает его слегка устаревшим). Совсем недавно (в 22 году, вроде), появилась новая версия этого инструмента [PlasMapper3.0](https://plasmapper.wishartlab.com/). Из наиболее интересных для нас вещей - там обновили базу данных добавили больше последовательностей для поиска и т.д. Репозиторий инструмента хранится в битбакете, сам файл с базой - [здесь](https://bitbucket.org/wishartlab/plasmapper3/src/master/PlasMapper_API/plasmapperAPI/fsdSearch/featureDB/features.fasta.nt). Я переработал его в тот вид, в котором он представлен в UGENE. Если честно, его бы и можно было оставить в FASTA, но это потребовало бы достаточно большого рефакторинга, который я не готов делать для далеко не самой популярной функции (порядка 500 запусков за последние полгода, я проверил статистику). 

Еще насчет базы - в оригинальном файле **471** плазмид фич (собственно, это же и усвержается в [статье](https://watermark.silverchair.com/gkad276.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA04wggNKBgkqhkiG9w0BBwagggM7MIIDNwIBADCCAzAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMF8FWcI5TfoNXZTYJAgEQgIIDAVjuBQyXHV9q4QCdem-rCB8ZnUTWyUtkGAp2M4VZmDNie0B7S310Zp2zuW94mGg1OVQQj5iIEQv-PID3LEpGlhtPc75ERFJQpWlI8OYCcunT8wE92OX_kySJfzztGVVq4sfkCiaIkKUTVJSj3HUahpBoxgN9EMLjarlrVUhZHsEbEMhY3zKMRUxmQub6tiIjP5Se-ChLVKYNq-Vkghcfi27RWE067FRAcR-tGthUBneh0zuj2H4hhIpwlHtYbCQU5GQ_VUwtNHcaFz-rbeugmhpDD6toK3q9b5Yre2ddKQDFBz5yXezsWCE0rUfKfeC0Nt0pbiPEiQLflBqyQddj07lYvhAvhzNVk-N79pqSnTBn2hEP6DFzSwx2Qifvta5g-AzRhdv0tjrs83rVfOFHUqN2Jy8cfvEjBEPSFP6fMtQY254tCHbqAT2Y9fDuXdxep70SjEg1O0-eTOtw7iPMvSdgksO6v2likxr87qs3_al1UUsEt6dlRNI5ztafps6-wj2-ksgNU4tGYJa5koSFC_PRNd4Jc9Xo27ZWn78sxMTEr84lwEfJoOT7bfNHGjQ3mZbmNIIOlCvJqrKGsYQ2_1fEynYmzx3fzjvv5oCXkPW83qxh86F-rCMf5EY_UwERz0f_h7jKHrDQkrKwFCgwvX5sB68M4HxyzyqD3grMy89wJIvXV1Zbz44UaC2cvMZ5_E8ixhAcP2RlrRd11CJFtXZYlvEtWun5iXsioi5-uzF6ZjiYVc7HqJ0MmyC8RZYmOV3mBzqUASRLUh_-yVnT2gke7SOEGg3i804tGqizYNfdJDm2lKEnZC0LW-aGLZ2AoG8kRsL3YICjMXVhh4EGcXymfzXHCD6bWIUp6zHW_8v85XZVwbAqEgMlsrvDh-pRY_x0wSFpXgDW1XiXIadc4odbWPQYpzni1m3fDq5KcHoi8Ai2itfgBvlKupIj6TxjGb2KdUlLGKbamf9YfYRofbfDQxZ5uRlvp89mDNETQgxhhxqk_y8NaGClYkT64Taf0yY)). Однако, на практике, их получилось меньше, по какой-то причине **семь** следующих фич дублируются полностью (у них одинаковые имена, последовательности и группы, к которым они относятся):
```
T7_promoter
T3_promoter
Sp6_promoter
SV40_intron
attB1
attB2
CAP_binding_site
```

Так же у нас есть еще **одна** фича, добавленная в отдельной задаче (см [UGENE-4394](https://ugene.dev/tracker/browse/UGENE-4394)). Уж не знаю, что в ней такого важного, но решил все-таки оставить.

Итого, получается 471 - 7 + 1 = 465. Всего 465 фич. 

Это только первый шаг в улучшении этой функции, остальные расписаны в [эпике](https://ugene.dev/tracker/browse/UGENE-8032).

2023-12-22 13:06 UTC, DmitriiSukhomlinov commented on tests/annotator/custom_auto_annotation/test_0004.xml
> +    <custom-auto-annotation-search doc="doc" seq="clipboard_3" result="plasmid_annotations" circular="false" expected_results="457"/>
Как я уже сказал, у нас 465 фич, но фичи `central_polypurine_tract` и `U3_polypurine_tract` встречаются по пять раз (имя одно, последовательности разные). В тесте я решил не усложнять и считаю только уникальные имена. Четыре дубликата у двух фич = восемь. 465 - 8 = 457.

2023-12-22 13:06 UTC, DmitriiSukhomlinov commented on src/plugins/annotator/src/CustomPatternAnnotationTask.cpp
> -    char unknownChar = 'N';
Теперь у нас есть фичи с N, поэтому мы должны ее учитывать

2023-12-22 23:52 UTC, yalgaer commented
> остальные расписаны в [эпике](https://ugene.dev/tracker/browse/UGENE-8032).

Там пусто

2023-12-23 00:18 UTC, yalgaer requested changes

2023-12-23 00:18 UTC, yalgaer commented on src/plugins/annotator/src/AnnotatorTests.cpp
> +    if (strCircular == "true") {
nit: Это можно было сократить и до 1 строки

2023-12-23 00:18 UTC, yalgaer commented on src/plugins/annotator/src/CustomPatternAnnotationTask.h
> +    static const QString REGULATORY_SEQUENCE;
Символы объявленные в CustomPatternAnnotationTask.h должны быть определены в CustomPatternAnnotationTask.cpp а не в файле диалога

2023-12-23 00:18 UTC, yalgaer commented on tests/annotator/custom_auto_annotation/test_0001.xml
> +    <find-annotation-by-name index="ann1" obj="plasmid_annotations" name="T7 promoter"/>
Это изменение вводит несовместимость с форматом genbank. Так делать не нужно.
https://www.insdc.org/submitting-standards/feature-table/#3.1

2023-12-23 00:18 UTC, yalgaer commented on src/plugins/annotator/src/CustomPatternAnnotationTask.cpp
> -    char unknownChar = 'N';
В связи с этим изменением нужно добавить двусторонние тесты: 
1) как новые фичи с unknown char матчатся с последовательностью в которой их нет
2) как последовательность с unknown char матчится с фичами в которых их нет.

2023-12-25 03:40 UTC, DmitriiSukhomlinov commented
> > остальные расписаны в [эпике](https://ugene.dev/tracker/browse/UGENE-8032).
> 
> Там пусто

Авторизуйся в джире, чтоб видеть приатаченные задачи

2023-12-25 03:48 UTC, DmitriiSukhomlinov commented on src/plugins/annotator/src/CustomPatternAnnotationTask.h
> +    static const QString REGULATORY_SEQUENCE;
Да, точно. Хотел порефакторить немного, но, в итоге, отложил на отдельную задачу и забыл откатить изменения

2023-12-25 04:12 UTC, DmitriiSukhomlinov commented on tests/annotator/custom_auto_annotation/test_0001.xml
> +    <find-annotation-by-name index="ann1" obj="plasmid_annotations" name="T7 promoter"/>
Вообще, это не совсем так. У формата генбанк в принципе нет такого понятия как **имя аннотации**. У аннотации есть только тип (`misc_feature` и т.д.) и квалификаторы. То, что мы используем в виде имени аннотации мы условились сохранять в виде значения квалификатора `ugene_name`. Ключ квалификатора не может содержать проблелы, а вот использовать пробелы в виде значения квалификатора уже можно, для улучшения читаемости - об этом написано в [том же документе](https://www.insdc.org/submitting-standards/feature-table/#4.4). Откровенно говоря, мы так делаем постоянно - сценарий "создать аннотацию с именем, содержащим пробелы, и сохранить это в файл" не вызовет никаких проблем, поскольку именем будет являться всего лишь значение квалификатора.

Если ты настаиваешь, то я заменю пробелы на нижние подчеркивания, но, как я вижу, проблем с этим не должно быть, а читать названия действительно проще с пробелами

2023-12-25 04:19 UTC, DmitriiSukhomlinov commented on src/plugins/annotator/src/AnnotatorTests.cpp
> +    if (strCircular == "true") {
OK

2023-12-25 05:15 UTC, DmitriiSukhomlinov commented on src/plugins/annotator/src/CustomPatternAnnotationTask.cpp
> -    char unknownChar = 'N';
Я немного потестил, текущее решение и сравнил его с тем, что делает сам PlasMapper. Оказалось, что у нас получилось не совсем правильно - находятся только фичи, у которых в месте, где указано N в самой последовательности стоит прям именно N, хотя это должно означать A, C, G или T. 

На практике, у нас есть всего одна фича, содержащая `N` - она называется **Ad5 left arm homology**. Чтобы не трогать алгоритм, я плавно обойду эту проблему, добавив в файл `plasmid_features.txt` четыре версии этой фичи с разными буквами - благо, это ничему не противоречит и у нас уже есть примеры таких фич (см. [коммент](https://github.com/ugeneunipro/ugene/pull/1498#discussion_r1435040322)).

Остается вопрос, что делать, если у нас встречается либо N, либо символ расширенного алфавита. Очевидным решением кажется посмотреть, что делает оригинальный инструмент, но, как оказалось, он не умеет отображать символы, отличные от ACGT. Если попытаться дать ему на вход, например, N, то он заменит его одним из четырех символов (выбирает он символ по одному ему известно какому принципу). Поэтому подобное поведение выбивается из рамок UGENE и, формально, данный момент получается не специфированным, то я предлагаю вернуться к варианту с `unknownChar = 'N'`.

2023-12-25 15:57 UTC, yalgaer commented on tests/annotator/custom_auto_annotation/test_0001.xml
> +    <find-annotation-by-name index="ann1" obj="plasmid_annotations" name="T7 promoter"/>
Да нужно оставить так как было и не менять эту часть: с Genbank/EMBL форматом мы стремимся работать по принцип минимума сюрпризов: что видишь на экране то есть и в файле.

Имена фич имеют семантику и менять их на произвольные и наши изобретения не надо.

2023-12-25 16:08 UTC, yalgaer commented on src/plugins/annotator/src/CustomPatternAnnotationTask.cpp
> -    char unknownChar = 'N';
Добавление в файл одной фичи с одной N 4 раза с заменой N на ACTG выглядит нормальным решением если это "учетверение" после этого нигде не всплывет в UI: например, не будет повторяться 4 раза в каких-либо списках.

Если же учетверение сделает неоднозначным UI то можно либо вообще убрать эту фичу из файла (сказать что мы такое не поддерживаем), либо исправить алгоритм (это требует тесты).

В случае UGENE N в последовательности это 25% от A,C,G T. Поэтому, по умолчанию, при сравнении с любым символом N не считается за совпадение: 25% против 75% (даже с самим собой).

Если в этой базе для N нужно считать за точное совпадение - надо поддержать эту несимметричность в алгоритме который работает с этой базой.

Дальше решай сам. Я бы просто выкинула этот элемент если он будет мешать (пока не попросят).

2023-12-26 08:30 UTC, DmitriiSukhomlinov commented on tests/annotator/custom_auto_annotation/test_0001.xml
> +    <find-annotation-by-name index="ann1" obj="plasmid_annotations" name="T7 promoter"/>
OK

2023-12-26 08:32 UTC, DmitriiSukhomlinov commented on src/plugins/annotator/src/CustomPatternAnnotationTask.cpp
> -    char unknownChar = 'N';
Я потестировал - никаких дубликатов не возникает, даже сделал тест на это. Решил оставить с четырьмя версиями этой фичи, оно хорошо работает, так же как и в оригинальном инстурменте

2023-12-26 23:19 UTC, yalgaer approved these changes
Да

2023-12-26 23:19 UTC, yalgaer commented on src/plugins/annotator/src/CustomPatternAnnotationTask.cpp
> +        //Each line has four elements - name, feature type and sequence
nit: fix comment

2023-12-27 05:29 UTC, merged