UGENE-7990 Smith-Waterman should have the same parameters in SV and AE
ugeneunipro/ugene pull request #1510
Opened 2023-12-29 10:02 UTC by DmitriiSukhomlinov

На панель опций парного выравнивания для алгоритма Smith-Waterman в AE добавлена кнопка "View...", при нажатии на которую появляется диалоговое окно с матрицей, используемой в алгоритме (аналогично тому, как это происходит в соответствующем диалоге в SV).

Пришлось немного подправить класс `SubstMatrixDialog`. Этот класс отнаследован от класса, определенного в автогенерируемом файле, что не очень удобно протаскивать между проектам. Поэтому мне пришлось изменить `Ui_SubstMatrixDialogBase` c предка на поле класса. Подробнее [здесь](https://forum.qt.io/topic/130566/cannot-open-include-file-ui_-h-when-using-multiple-qt-projects-in-the-same-visual-studios-solution/4).

2023-12-29 18:18 UTC, yalgaer requested changes

2023-12-29 18:18 UTC, yalgaer commented on src/plugins/smith_waterman/src/PairwiseAlignmentSmithWatermanGUIExtension.cpp
> +    smDialog.exec();
Мы больше не создаем диалоги на стеке: объект диалога может удалиться до выхода из текущего контекста стека. 
Пример правильного использования:
```
QObjectScopedPointer<EditPrimerDialog> dlg = new EditPrimerDialog(this);
dlg->exec()
```

2024-01-09 10:31 UTC, DmitriiSukhomlinov commented on src/plugins/smith_waterman/src/PairwiseAlignmentSmithWatermanGUIExtension.cpp
> +    smDialog.exec();
OK

2024-01-09 18:47 UTC, yalgaer approved these changes

2024-01-10 02:06 UTC, merged