UGENE-6485 Crash when remove custom cmdline element
ugeneunipro/ugene pull request #1525
Opened 2024-01-17 12:01 UTC by rasputinkirill

2024-01-18 01:00 UTC, yalgaer requested changes
Замечания по тесту минимальные.
Апрув после исправления и зеленых GUI тестов

2024-01-18 01:00 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_6001_7000.cpp
> +    CHECK_SET_ERR(treeItem != nullptr, "Element not found");
Метод выше не вернет nullptr

2024-01-21 10:30 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_6001_7000.cpp
> +    CHECK_SET_ERR(treeItem != nullptr, "Element not found");
Ты не права.
Удали кастомный воркер "el_6485" создаваемый тестом и проверь еще раз, пожалуйста.

2024-01-21 10:39 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_6001_7000.cpp
> +    CHECK_SET_ERR(treeItem != nullptr, "Element not found");
![image](https://github.com/ugeneunipro/ugene/assets/17490668/515ac8e9-36c0-4ebf-97e2-7ae9cd396fc1)

2024-01-23 13:51 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_6001_7000.cpp
> +    CHECK_SET_ERR(treeItem != nullptr, "Element not found");
Ok

2024-01-24 21:57 UTC, yalgaer commented
Пока не вижу зеленых GUI тестов. Если те падения что есть не связаны с твоим кодом - дай знать (напиши тут)

2024-01-29 02:53 UTC, rasputinkirill commented
Авто именование элементов работало криво, даже если не было элемента с именем "el_6485", но были "el_6485 1", el_6485 2", "el_6485 3" новый элемент создавался с именем "el_6485 4".
`GTUtilsWorkflowDesigner::findTreeItem` находил все эти элементы вида "el_6485 %x" по поиску даже с `exactMatch`.
Добавил опцию чтобы выдавал первый из нескольких результатов.

2024-02-06 18:03 UTC, yalgaer commented
Все еще жду зеленых/анализа красных тестов

2024-03-14 02:59 UTC, yalgaer commented
Закрываю как неактивный. Переоткрой на зеленых тестах пожалуйста

2024-03-14 02:59 UTC, closed without merging