UGENE-6330 A file selection dialog should be opened if "Set reference…
ugeneunipro/ugene pull request #1526
Opened 2024-01-17 23:34 UTC by rasputinkirill

…" button is clicked and an amino acid sequence is selected in the Project View

2024-01-18 01:02 UTC, yalgaer requested changes
Замечания минимальные, апрув после исправления и тестов

2024-01-18 01:02 UTC, yalgaer commented on src/corelibs/U2View/src/ov_assembly/AssemblyBrowser.cpp
> +            QMessageBox::critical(ui, tr("Error!"), err);
У нас есть что-то типа L10N:errorTitle() - так не нужно переводить каждый раз одно и то же

2024-01-24 21:58 UTC, yalgaer commented
Жду зеленых GUI тестов или подтверждения что падения не связаны с твоими изменениями

2024-01-26 08:58 UTC, rasputinkirill commented
Вроде в порядке, упали не связанные тесты.

2024-01-28 00:35 UTC, yalgaer approved these changes

2024-01-28 10:34 UTC, merged