UGENE-8038 Add Primer3 presets
ugeneunipro/ugene pull request #1532
Opened 2024-01-24 09:50 UTC by DmitriiSukhomlinov

Добавил еще пресеты для Primer3, а то эта функция выглядит какой-то обрезанной. Позаимствовал большую часть из [Primer3Plus](https://www.primer3plus.com/index.html). Не стал добавлять три последних, т.к. они какие-то странные и, вероятно, отсылают к каким-то настройкам Primer3 по-умолчанию, которые были когда-то давно (скорее всего, для обратной совместимости). Так же добавил набор настроек "Default2", т.к. у самого Primer3 два набора настроек по умолчанию (в зависимости от подаваемого аргумента).

2024-01-24 22:18 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +        SAFE_POINT(QFile::exists(presetFilePath), "Unexpected preset", );
Что если файл не читается или это вообще не файл, или не совпадает формат?

Ошибку нужно репортить по результатам работы loadSettings. В коде ниже проверки корректности отработки loadSettings нет, но действия подразумевающие успешный результат после вызова loadSettings есть.

Если пользователь имеет доступ в этим файлам - то ошибка не может быть SAFE_POINT - ошибка должна быть ожидаемой.

2024-01-24 22:18 UTC, yalgaer requested changes
Нужно корректно реализовать обработку ошибки загрузки пресета.

2024-01-25 06:23 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +        SAFE_POINT(QFile::exists(presetFilePath), "Unexpected preset", );
ОК, добавил проверку на случай отсутствия файла. Еще пришлось немного переделать код, т.к. я не подумал насчет других языков. Чтобы не было проблем, заменил текст на индексы

2024-01-25 16:26 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    } else if (presetIndex == INDEX_FILE_NAME_MAP.lastKey()) {
Здесь происходит какая-то магия, которая дополнительно еще и не безопасная на случай пересортировки массива (например по имени).
Старый код который проверял по реальному имени (семантике элемента) был лучше.

2024-01-26 05:27 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    } else if (presetIndex == INDEX_FILE_NAME_MAP.lastKey()) {
OK

2024-01-28 00:43 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    } else if (presetIndex == INDEX_FILE_NAME_MAP.lastKey()) {
Магия все еще осталась:
` } else if (text == presetNamesMap.last().first) {`

Раньше было понятно: текст сравнивался с "Default". Сейчас с каким-то абстрактным последним элементом в визуальном списке.

2024-01-28 02:40 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/Primer3Dialog.cpp
> +    } else if (presetIndex == INDEX_FILE_NAME_MAP.lastKey()) {
OK

2024-01-29 03:46 UTC, yalgaer commented
По патчу замечаний нет. Апрув после тестов. Пока вижу что упал какой-то primer3 тест

2024-01-30 05:32 UTC, DmitriiSukhomlinov commented
@yalgaer тесты прошли, остались случайные падения

2024-01-30 05:36 UTC, DmitriiSukhomlinov commented
На втором виндовом агенте попадало много тестов из-за того, что появилось окошко обновления системы. Я уж не стал перезапускать, на линуксе и маке аналогичные тесты прошли

2024-01-31 03:02 UTC, yalgaer approved these changes

2024-01-31 03:16 UTC, merged