UGENE-7784 Debug crash "database is locked" if open in master the file already opened in another release UGENE
ugeneunipro/ugene pull request #1534
Opened 2024-01-26 16:22 UTC by rasputinkirill

Тест не написать, так как требуется два инстанса юджина

2024-01-28 00:48 UTC, yalgaer reviewed
Возможно получится написать тест, если UGENE будет запускать другой UGENE : через workflow и подавать ему залоканую базу, и потом проверять код ошибки?

2024-01-28 00:48 UTC, yalgaer commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteDbi.cpp
> +    SQLiteWriteQuery("DROP TABLE IF EXISTS TestLock;", db, os).execute();
Для проверки на эксклюзивный лок должно быть достаточно выполнить "SELECT 1"

2024-01-28 10:18 UTC, rasputinkirill commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteDbi.cpp
> +    SQLiteWriteQuery("DROP TABLE IF EXISTS TestLock;", db, os).execute();
Нет, не достаточно, надо сделать запрос на изменение.
На чтение срабатывает корректно.

2024-01-29 04:09 UTC, yalgaer commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteDbi.cpp
> +    SQLiteWriteQuery("DROP TABLE IF EXISTS TestLock;", db, os).execute();
Для эксклюзивного лока который мы используем для сессий это так:
![image](https://github.com/ugeneunipro/ugene/assets/17791039/dbd4945a-e45d-4b6a-ad04-f9df4905c69b)

На внешние ugenedb файлы мы ставим обычный normal (write) lock - он работает только для разделения записей. Если записи в данный момент в базу не происходит - то он не блокирует ни чтение ни запись.

Можешь ли подробнее описать свое решение? Можно на примере просто SQL для файла sqlite: как его открыть в 2 процессах чтобы воспроизвести проблему?

2024-01-29 09:06 UTC, rasputinkirill commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteDbi.cpp
> +    SQLiteWriteQuery("DROP TABLE IF EXISTS TestLock;", db, os).execute();
Проблема:
Проблема в том что сваливается на этом методе `rDbi->removeReferencesForObject(entityRef.entityId, os);`, который очевидно пишет в базу.
Решение такое:
Во время открытия базы проверить можно ли в нее писать. Что я и делаю.
Сначала хотел ограничиться проверкой на чтение - то есть делать просто SELECT, однако выяснилось что этого недостаточно и база на чтение доступна.
Возможно у сессионной и базы которую мы открываем как файл различные локи на открытие, я не проверял.

2024-01-30 02:36 UTC, yalgaer commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteDbi.cpp
> +    SQLiteWriteQuery("DROP TABLE IF EXISTS TestLock;", db, os).execute();
Попробуй тогда этот вариант
BEGIN EXCLUSIVE
COMMIT

Для залоканной базы эти команды не должны пройти.
![image](https://github.com/ugeneunipro/ugene/assets/17791039/84bbb620-8b92-4410-9045-b24720df4ef8)

Это лучше чем создавать состояние в базе.

2024-01-30 05:46 UTC, DmitriiSukhomlinov commented
> Возможно получится написать тест, если UGENE будет запускать другой UGENE : через workflow и подавать ему залоканую базу, и потом проверять код ошибки?

Расчеты в WD не запускаются в другом процессе, только в отдельном потоке. Только Сэнгер запускает другой процес со схемой WD (если запускать его через диалоговое окно)

2024-01-30 06:55 UTC, rasputinkirill commented on src/corelibs/U2Formats/src/sqlite_dbi/SQLiteDbi.cpp
> +    SQLiteWriteQuery("DROP TABLE IF EXISTS TestLock;", db, os).execute();
Да так работает.

2024-01-31 03:06 UTC, yalgaer commented
> > Возможно получится написать тест, если UGENE будет запускать другой UGENE : через workflow и подавать ему залоканую базу, и потом проверять код ошибки?
> 
> Расчеты в WD не запускаются в другом процессе, только в отдельном потоке. Только Сэнгер запускает другой процес со схемой WD (если запускать его через диалоговое окно)

Под "workflow" имеется в виду запуск другого UGENE на исполнение WD схемы где будет присутствовать текущий открытый файл. Именно WD схемы из папки data/cmdline являются основным функциональным интерфейсом UGENE.

2024-01-31 03:08 UTC, yalgaer requested changes
Нужно убрать ненужные include из 2 файлов и добавить тест

2024-01-31 15:05 UTC, rasputinkirill commented
Можно, пожалуйста, поподробней про тест.

2024-02-01 02:13 UTC, yalgaer commented
> Можно, пожалуйста, поподробней про тест.

Открой ugenedb файл в тестируемом UGENE и запусти из его cmdline UGENE который попробует прочитать из этого же файла. Например extract-sequence команду - по идее должна вытащить все sequences из ugenedb. Или convert.
Посмотри что у нас есть в папке data/cmdline

2024-02-13 13:26 UTC, rasputinkirill commented
Я попробовал поэкспериментировать с воркфлоу как ты написала.
Воркер read sequence читает только сиквенсы, надо использовать Read NGS Reads Assembly для ugenedb.
Сделал такую схему 
![image](https://github.com/ugeneunipro/ugene/assets/17490668/b3963347-eaab-4ce6-bbd7-ba8d4f3c011f)
Если открывать анализируемый ugenedb файл в проекте и запускать схему все работает нормально.
Если открывать анализируемый ugenedb файл в проекте и запускать отдельно из cmd-line юджина, то будет ошибка `Nothing to write`.
Опять же запустить вместе обычный юджин и из командной строки мы не можем.

2024-02-14 22:11 UTC, yalgaer commented
>  Если открывать анализируемый ugenedb файл в проекте и запускать схему все работает нормально. Если открывать анализируемый ugenedb файл в проекте и запускать отдельно из cmd-line юджина, то будет ошибка `Nothing to write`. Опять же запустить вместе обычный юджин и из командной строки мы не можем.

А почему нельзя запустить ugenecl(d) из текущего теста? Все же настроено (environment) и лежит рядом с ugeneui(d)?

2024-02-19 17:36 UTC, rasputinkirill commented
Добавил тест, запустил гуи тестирование.

2024-02-20 15:38 UTC, yalgaer commented
Замечаний нет, ждем результатов теста

2024-02-24 00:53 UTC, yalgaer approved these changes

2024-02-24 22:06 UTC, merged