UGENE-7979
ugeneunipro/ugene pull request #1547
Opened 2024-02-12 12:30 UTC by rasputinkirill

Sequences syncronisation does not work well

2024-02-12 20:58 UTC, yalgaer requested changes

2024-02-12 20:58 UTC, yalgaer commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.cpp
> +    for (int time = 0; time < 2000 && action == nullptr; time += GT_OP_CHECK_MILLIS) {
Используй GT_OP_WAIT_MILLIS а не 2000

2024-02-12 20:58 UTC, yalgaer commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.cpp
> +    QAction* action = nullptr;
Зачем здесь action?

2024-02-12 20:58 UTC, yalgaer commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.h
> +    //returnall checked menu items
Исправь комментарий. 
Добавь комментарий о том что этот метод будет что-то ждать

2024-02-12 20:58 UTC, yalgaer commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.cpp
> +    return result;
Непонятно чего именно ждет этот метод
Возможно нужно ждать checked state только у нужной menu-item а не у любой случайной?

2024-02-13 08:16 UTC, rasputinkirill commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.cpp
> +    return result;
Ждет потому что это копипаста из ` GTMenu::getMenuItem`, написал это в комментарии к методу.
Мне в тесте понадобилось проверка что никакой пункт не отмечен.
А делать метод `isNoCheckedItems` я не захотел так как это совсем какой-то узкоспециализированый метод.

2024-02-13 08:29 UTC, rasputinkirill commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.cpp
> +    for (int time = 0; time < 2000 && action == nullptr; time += GT_OP_CHECK_MILLIS) {
Зачем? 
Откроется меню и будем смотреть на его пункты не 2 сек, а 30.

2024-02-14 22:15 UTC, yalgaer commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.cpp
> +    return result;
В текущем состоянии метод всегда будет ждать 2 секунды и это не хорошо.

В GUI тестах нужно всегда ждать конкретного состояния. В данном случае ты ждешь что конкретное меню не имеет ни одного checked item.

Если ты считаешь что метод isNoCheckedItems больше нигде не нужен просто напиши его код в своем тесте: жди (не 2 секунды а до GT_OP_WAIT_MILLIS) на нужном меню что там нет ни одного checked item.

2024-02-14 22:16 UTC, yalgaer requested changes
см комментарий

2024-02-16 00:54 UTC, rasputinkirill commented on src/libs_3rdparty/QSpec/src/primitives/GTMenu.cpp
> +    return result;
Перенес метод в тест

2024-02-16 06:27 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +                CHECK_SET_ERR(checkedActions.isEmpty(), "There should be no checked items!");
Собирать actions в список нет смысла - просто проверяй их прямо в цикле.

2024-02-16 06:27 UTC, yalgaer reviewed
Минимальные замечания. Апрув после тестов

2024-02-19 10:08 UTC, rasputinkirill commented
По тестам вроде нормально

2024-02-19 16:16 UTC, yalgaer approved these changes

2024-02-19 16:19 UTC, merged