UGENE-7257 ACE and APR formats couldn't be opened in Assembly Browser if you want to save ".ugenedb" into the default folder
ugeneunipro/ugene pull request #1550
Opened 2024-02-20 22:44 UTC by rasputinkirill

ACE and APR formats couldn't be opened in Assembly Browser if you want to save ".ugenedb" into the default folder

2024-02-21 15:35 UTC, yalgaer requested changes
Замечания

1) Проверка на возможность записи и ошибка записи проверяется не в момент записи, а только в момент построения UI (создания widget)

2) Проверка работает только для  fi.absolutePath, но не для следующего варианта который выбирается если проверка для fi.absolutePath не прошла. Что если и второй путь read-only?

3) Непонятно как о проблеме с записью сообщается пользователю.

2024-02-21 15:35 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +#if defined(Q_OS_WIN)
используй isOsWindows()

2024-02-26 00:50 UTC, rasputinkirill commented
> 1. Проверка на возможность записи и ошибка записи проверяется не в момент записи, а только в момент построения UI (создания widget)

А что не так, в этот момент и выбирается возможный путь для записи?

> 2. Проверка работает только для  fi.absolutePath, но не для следующего варианта который выбирается если проверка для fi.absolutePath не прошла. Что если и второй путь read-only?

В папку UGENE_Data всегда  можно писать см `UserAppsSettings::getDefaultDataDirPath().`.

> 3. Непонятно как о проблеме с записью сообщается пользователю.
Как я написал, в пункте 2 не будет проблемы с записью ни в каком случае.

2024-02-26 01:05 UTC, yalgaer commented
Ок, давай тогда посмотрим что тесты не падают и я дам апрув

2024-03-06 03:35 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/GUITestBasePlugin.cpp
> +    REGISTER_TEST(GUITest_regression_scenarios::test_7257);
Снова такая же штука. Зачем ты в принципе так делаешь, если не секрет?

2024-03-07 00:11 UTC, yalgaer commented
В экспериментах у нас есть билды где можно в настройках билда указать какой именно тест/список тестов нужно запустить:

Пример:
http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/admin/editBuildRunners.html?id=buildType:Experiments_WindowsGuiTestList

2024-03-14 02:59 UTC, yalgaer commented
Закрываю как неактивный. Переоткрой на зеленых тестах пожалуйста

2024-03-14 02:59 UTC, closed without merging