UGENE-7901 Sanger alignment fails if path to files contains commas
ugeneunipro/ugene pull request #1562
Opened 2024-03-05 06:47 UTC by DmitriiSukhomlinov

Данная проблема возникала, если для выравнивания по Сэнгеру использовался ровно один рид и в пути к этому риду были запятые. Путь к рефенсу не важен, с ним проблем нет.

При запуске Сэнгера через диалоговое окно запускается ugenecl со схемой выравнивания по Сэнгеру. При этом, риды передаются в качестве аргумента и разделены точкой с запятой. Когда дело доходит до обработки входного аргумента, то разделитель определяется с помощью функции [WorkflowUtils::getDatasetSplitter()](https://github.com/ugeneunipro/ugene/blob/82f11c4230fbdd9433eafa1a8127691f916b5c4a/src/corelibs/U2Lang/src/support/WorkflowUtils.cpp#L1248). Эта функция проверяет на наличие точки с запятой в строке. Если есть, то разделитель - точка с запятой. Если нет, то разделитель просто запятая.

Разделитель в виде точки с запятой появляется в случаях, когда есть что разделять - т.е. если ридов больше одного. Если рид только один, то путь к риду передается как есть. Если в пути к этому единственному риду есть запятая, то она будет воспринята как разделитель, что приведет к багу. Самый простой способ исправить это - это дописывать точку с запятой в конец списка ридов в любом случае. При разделении пустой элемент будет игнорироваться (см. [здесь](https://github.com/ugeneunipro/ugene/blob/82f11c4230fbdd9433eafa1a8127691f916b5c4a/src/corelibs/U2Lang/src/library/BaseTypes.cpp#L327C9-L327C78)).

Так же я добавил небольшое логирование в место, где, возникала ошибка. У меня ушло немало времени, чтобы найти его и разобраться в причинах - в случае возникновения подобной проблемы снова, этот кусочек лога поможет легко до него добраться.

2024-03-06 01:07 UTC, yalgaer requested changes
Данную проблему в нашем коде надо чинить, а не шпатлевать.

Что и как починить:

Способ сериализации списка файлов в строку должен всегда работать через 2 функции: convertListOfFilesToDatasetString/parseListOfFilesFromDatasetString

Вне этих функций не должно быть ни скрытых магических констант разделителей ни знания об алгоритме, как объединяются имена файлов (join/split).

Какие дополнителные издержки/доработки повлечет такая починка - с этим нужно разобраться тому,  кто правит этот баг и предложить свои варианты.

Я могу предложить следующие, но пока не анализировала их практическую применимость для всех мест использования:

1) Разделять имена файлов исключительно используя ;
2) Разделять имена файлов используя перевод строки.

2024-03-06 03:03 UTC, DmitriiSukhomlinov commented
> Данную проблему в нашем коде надо чинить, а не шпатлевать.
> 
> Что и как починить:
> 
> Способ сериализации списка файлов в строку должен всегда работать через 2 функции: convertListOfFilesToDatasetString/parseListOfFilesFromDatasetString
> 
> Вне этих функций не должно быть ни скрытых магических констант разделителей ни знания об алгоритме, как объединяются имена файлов (join/split).
> 
> Какие дополнителные издержки/доработки повлечет такая починка - с этим нужно разобраться тому, кто правит этот баг и предложить свои варианты.
> 
> Я могу предложить следующие, но пока не анализировала их практическую применимость для всех мест использования:
> 
> 1. Разделять имена файлов исключительно используя ;
> 2. Разделять имена файлов используя перевод строки.

Согласен, действительно, проблема выглядит куда более глобально, однако, я на данный момент просто не готов ей заняться в том объеме, который ты подразумеваешь, т.к. это подразумевает достаточно маленький выхлоп для достаточно большого объема работы, а у меня на примете есть много задач, вызывающих более явные проблемы в UGENE. Я бы предложил поправить этот баг текущим методом - просто дла того, чтобы этот баг не мог вылезти у пользователя -  а на то, что ты написала, завести отдельную задачу.

2024-03-07 00:08 UTC, yalgaer commented
Мы согласились, что решение банально и функция работы с сепаратором вызывается только из одного места.
Осталось найти все остальные места, где может использоваться эта логика без явного вызова функции.

Твой фикс уже нашел одно такое место. Если есть другие подобные места - там тоже нужен фикс: хоть твой текущий, хоть правильный. 

Итог: нам нужно найти все места (полчаса работы) и вставить в них простой и правильный фикс.
Возможно найдется что-то неожиданное, но это быстро станет понятно.

Если есть другая, более приоритетная, загрузка - перепиши этот баг на меня.

2024-03-07 08:31 UTC, DmitriiSukhomlinov commented
> Мы согласились, что решение банально и функция работы с сепаратором вызывается только из одного места. Осталось найти все остальные места, где может использоваться эта логика без явного вызова функции.
> 
> Твой фикс уже нашел одно такое место. Если есть другие подобные места - там тоже нужен фикс: хоть твой текущий, хоть правильный.
> 
> Итог: нам нужно найти все места (полчаса работы) и вставить в них простой и правильный фикс. Возможно найдется что-то неожиданное, но это быстро станет понятно.
> 
> Если есть другая, более приоритетная, загрузка - перепиши этот баг на меня.

Наверное, я все-таки перенесу эту задачу на тебя, т.к. я не совсем согласен с тем, что задача быстрая (`";"` встречается порядка 150 раз в коде, так же есть `Constants::SEMICOLON` с 25 встречаемостями, плюс все места, где вызывается [WorkflowUtils::getDatasetSplitter()](https://github.com/ugeneunipro/ugene/blob/82f11c4230fbdd9433eafa1a8127691f916b5c4a/src/corelibs/U2Lang/src/support/WorkflowUtils.cpp#L1248) и подобные функции, неявно использующие точку с запятой); во многих местах, где используется точка с запятой, не очень понятно, в каком контексте она используется и это нужно тестировать прям с дебаггером, чтобы это понять; мне не нравится идея отмены запятой, т.к. это вполне естественный разделитель, который пользователь может использовать и, откровенно говоря, мне не кажется это особо имеющим смысл - даже если мы заведем такую функцию, то мы не можем защититься от того, что кто-то разделит список путей без её использования. Короче, где именно проблема возникает я нашел и указал, предлагаю тебе применить любое решение, которое ты посчитаешь нужным, коль ты не согласна с моим

2024-03-07 08:31 UTC, closed without merging