UGENE-8052 Crash on copy big annotation sequence
ugeneunipro/ugene pull request #1567
Opened 2024-03-07 10:11 UTC by DmitriiSukhomlinov

2024-03-07 18:23 UTC, yalgaer requested changes
Если мы не можем отреагировать на действие пользователя так как он ожидает (скопировать)  - нужно ему сообщить об этом способом, чтобы у него не осталось вопросов. Сообщение в лог здесь вторично: нужен message box или notification.

2024-03-08 03:29 UTC, DmitriiSukhomlinov commented
Сделал общую функцию, проверяющую размер буфера обмена. Если больше - то ваставляет ошибку через `os`. Максимальный размер в режиме гуи тестирования уменьшен, чтобы тест не тратил 95% времени на загрузку файла. Добавил нотификации, если размер буфера больше лимита. Поправил все связанные случаи.

2024-03-08 22:50 UTC, yalgaer requested changes
Минимальные замечания: нужно переместить тело функции из h в cpp.
Апрув после исправления и тестов

2024-03-08 22:50 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/ClipboardController.h
> +            os.setError(QObject::tr("Block size is too big and can't be copied into the clipboard"));
Реализацию метода нужно перенести в C++
Для контекста перевода можно попробовать найти более подходящий класс

2024-03-08 22:50 UTC, yalgaer commented on src/corelibs/U2View/src/ov_msa/MsaEditorSequenceArea.cpp
> +        NotificationStack::addNotification(os.getError(), NotificationType::Error_Not);
Copy paste с нотификацийе можно вложить прямо в функцию проверки в которую также добавить опциональный параметр: showNotificationOnError = true.

2024-03-09 01:09 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/ClipboardController.h
> +            os.setError(QObject::tr("Block size is too big and can't be copied into the clipboard"));
> Реализацию метода нужно перенести в C++

OK

> Для контекста перевода можно попробовать найти более подходящий класс

Какой конкретно? Все непрекаянные трансляции в `U2Core` привязаны к `QObject`

2024-03-09 01:20 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_msa/MsaEditorSequenceArea.cpp
> +        NotificationStack::addNotification(os.getError(), NotificationType::Error_Not);
Идея, хорошая, но с ней есть сложность - нотификации являются частю проекта `U2Gui`, `U2Core` (где функция лежит сейчас) от него не зависит (зависимость как раз обратная), поэтому рисовать нотификацию прям в текущем месте не получится. Я просмотрел `U2Gui` и `U2View`, но не смог найти там какого-либо хорошо подходящего класса для такой утилитной функции, а идея создавать отдельный утилитный класс для одной единственной функции мне не нравится, поэтому я сделал так, как сделал. 

Я могу перенести, если предложишь, куда именно.

2024-03-10 02:21 UTC, DmitriiSukhomlinov commented
Все тесты прошли за исключение пары нестабильных

2024-03-11 01:34 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/ClipboardController.h
> +            os.setError(QObject::tr("Block size is too big and can't be copied into the clipboard"));
Можно завести класс с именем ClipboardController  прямо в этом же .h файле или сделать U2Clipboard QObject

2024-03-11 01:36 UTC, yalgaer commented on src/corelibs/U2View/src/ov_msa/MsaEditorSequenceArea.cpp
> +        NotificationStack::addNotification(os.getError(), NotificationType::Error_Not);
Что если весь файл ClipboardController перенести в U2Gui?
Для ugenecl он не должен быть нужен по идее.

2024-03-11 02:33 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_msa/MsaEditorSequenceArea.cpp
> +        NotificationStack::addNotification(os.getError(), NotificationType::Error_Not);
Сделав по верхам поиск я увидел, что в `U2Core` есть класс, зависящий от `ClipboardController`. Я бы предпочел не проверять зависимости всех классов чтобы понять, что нужно унести в GUI, а что нет в этой задаче

2024-03-11 02:33 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/ClipboardController.h
> +            os.setError(QObject::tr("Block size is too big and can't be copied into the clipboard"));
Можно, это критично? С моей точки рения, это изменение ради изменения. Сейчас все тесты прошли, я бы не хотел откладывать эту задачу еще на сутки

2024-03-11 04:32 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/ClipboardController.h
> +            os.setError(QObject::tr("Block size is too big and can't be copied into the clipboard"));
ok

2024-03-11 04:33 UTC, yalgaer commented on src/corelibs/U2View/src/ov_msa/MsaEditorSequenceArea.cpp
> +        NotificationStack::addNotification(os.getError(), NotificationType::Error_Not);
ok

2024-03-11 04:33 UTC, yalgaer approved these changes

2024-03-11 04:35 UTC, merged