UGENE-7236 SAFE_POINT on extracting consenus from assembly in GFF format
ugeneunipro/ugene pull request #1575
Opened 2024-03-13 06:08 UTC by DmitriiSukhomlinov

Нетривиальный баг, долго разбирался, будет простыня описания, иначе не понятно, что и почему я сделал. Проблема возникала при экспорте консенсуса из сборки через WD.

Когда консенсус экспортируется не через WD, а через открытое окно Assembly Browser'а, то экспорт производится из базы данных (sam/bam ведь предварительно экспортируются в ugenedb). Перед экспортом, UGENE пробегает все риды в базе данных `.ugenedb` и выясняет максимальный правый символ самого правого рида. Этот символ считается длиной сборки. Зная длину, алгоритм экспорта разбивает сборку на куски не длинее 1'000'000 символов и рассчитывает консенсус для каждого куска по отдельности. Это было добавлено в [UGENE-899](https://ugene.dev/tracker/browse/UGENE-899) для оптимизации, т.к. сборка может большой (нам попадались экземпляры 130+ Гб) и извлечение всего консенсуса за раз может потребовать много памяти - лучше разбить на мелки кусочки.

Когда экспорт ведется через WD, то SAM/BAM в `.ugenedb` не экспортируется. Это резонное решение, т.к. файл  `.ugenedb` занимает примерно столько же места на диске, сколько и SAM файл - это может быть много и, в данном случае, экспорт в базу не нужен, т.к. нам не нужно визуализировать сборку. Общий подход экспорта, при этом, не меняется - берется длина сборки, разбивается на куски по миллиону символов и каждый обрабатывается по отдельности. Проблема возникает с тем, чтобы выяснить длину сборки.

SAM файл, помимо набора ридов, так же должен содержать header, в котором будет общая информация о сборке - в частности, её длина. Но header может отсутствовать в SAM файле (за примером далеко ходить не надо, у `samples/Assembly/chrM.sam` header'а нет). До этого фикса, UGENE ориентировался только на значение длины сборки из header'а, при этом, не учитывалась ситуация, когда header отсутсвовал. Из-за этого выставлялась нулевая длина сборки и возникал этот баг.

Фикс заключается в том же подходе, что и с базой данных. Если в header'е нет информации о длине последовательности, то нам нужно перебрать все риды и выяснить порядковый номер самого правого символа. Для этого я написал отдельный итератер по ридам, который может прогнать все риды сразу (а не риды только какого-то конкретного региона), но, при этом, не дает пользователю сохранить их все (чтобы избежать перегрузки). Мне это показалось более удобным, чем вставлять в текущий итератор кучу `if-else`

2024-03-14 02:58 UTC, yalgaer requested changes
Слишком сложная и перегруженная архитектура нового итератора. См комментарии выше о том как это сделать проще и короче используя старый итератор.

Если по какой-то причине так сделать нельзя, пожалуйста, поясни.

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.h
> +    qint64 calculateMaxEndPos();
nit: make const

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +    int readsSize = reads.size();
nit: если я правильно понимаю здесь можно не инициализировать переменную (результат этой операции не используется)

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +    } while (readsSize != reads.size());
Алгоритм выглядит не явным. Нужно добавить комментарий почему условием выхода из цикла является любое изменение длины массива ридов

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +        applyNameFilter();
Если данный итератор читает все риды - зачем в нем name filter?

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +qint64 SamtoolsBasedAllReadsIterator::calculateMaxEndPos() {
какое отношение эта функция имеет к итератору?
iterator это utility класс для прохода по всем ридам.

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +    return U2AssemblyRead();
почему бы просто не вызвать базовый метод?

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.h
> + * without caching more than one read at the time.
Из текста класса не ясно как реализуется 'one read at the time.'

2024-03-14 02:58 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +        SamtoolsBasedAllReadsIterator sbri(id, dbi);
Здесь нужно создать обычный (уже существующий) итератор, пройтись по всем ридам и вычислить макс. длину.
Ну нужно создавать новый класс итератора который делаешь дополнительную (не касающуюся) итератора магию - это не дело итератора.

2024-03-14 10:05 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +        SamtoolsBasedAllReadsIterator sbri(id, dbi);
Можно использовать уже существующий итератор, в первой реализации я так и сделал, но мне не понравилось, как в итоге выглядит код. Текущий итератор работает с каким-то конкретным регионом сборки, который, в нашем случае, мы не знаем. Поэтому, итератору надо будет каким-то образом просигнализировать о том, что мы не знаем регион - либо через новую переменную типа `bool`, либо, например, передав  в конструктор пустой регион (второй вариант мне нравится больше, т.к. не вижу смысла плодить переменные). После этого, нужно будет адаптировать код под использование пустого региона, добавив в некоторые места строки такого типа:

```
if (region.isEmpty()) {
    //  Делаем что-то одно
} else {
    // Делаем что-то другое
}
```

Я добавил наследный класс как-раз потому, что он помогает более изящно решить подобную проблему путем перегрузки виртуальных функций, нежели эта проблема решается путем использования набора `if-else` (который, с моей точки зрения, выглядит больше каким-то костылем). Я не буду упираться и сделаю все в уже существующем классе - общая идея все равно остается одинаковой

2024-03-14 10:21 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.h
> +    qint64 calculateMaxEndPos();
Функция удалена, поэтому, неактуально

2024-03-14 10:22 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +    int readsSize = reads.size();
Не используется, но я не люблю оставлять переменные неиниализированными. Убрал инициалиацию размером, но проинициализировал нулем

2024-03-14 10:22 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +        applyNameFilter();
Не подумал, удалено

2024-03-14 10:22 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +qint64 SamtoolsBasedAllReadsIterator::calculateMaxEndPos() {
Функция удалена

2024-03-14 10:22 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +    return U2AssemblyRead();
Этого места тоже больше нет

2024-03-14 10:23 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.h
> + * without caching more than one read at the time.
Класс удален, описание тоже

2024-03-14 10:49 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +    } while (readsSize != reads.size());
Да, я тут излишне усложнил. Достаточно просто вытягивать чанк до тех пор, пока можно

2024-03-18 02:16 UTC, yalgaer requested changes

2024-03-18 02:16 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +    int assemblyId,
nit: несимметричное именование переменных, нужно: _assemblyId

2024-03-18 02:16 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +    qint64 assemblyLength = getMaxEndPos(assemblyId, os);
Непонятно это изменение. maxEndPos это `length  -1`. Например для header->target_len[id] равным "1" `getMaxEndPos` вернет 0, верно?

2024-03-18 02:17 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedAllReadsIterator.cpp
> +    int readsSize = reads.size();
В данном случае компилятор не даст использоват неинициализированную переменную

2024-03-18 03:51 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +    int assemblyId,
OK

2024-03-18 03:54 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +    qint64 assemblyLength = getMaxEndPos(assemblyId, os);
`getMaxEndPos()` возвращала значение -1, а, затем, прибавляла единицу тут. Я убрал и минус в самой функции и плюс тут, нигде никаких проблем не увидел, ничего не свалилось. Почему так было сделано не знаю

2024-03-19 02:32 UTC, yalgaer requested changes

2024-03-19 02:32 UTC, yalgaer commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +    qint64 assemblyLength = getMaxEndPos(assemblyId, os);
Исходя из названия функции она возвращает индекс а не длину. Если теперь она возвращает определенную длину то нужно переименовать метод и проревьюить и исправить все места использования

2024-03-20 09:43 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +    qint64 assemblyLength = getMaxEndPos(assemblyId, os);
Да, я посмотрел, оно действительно так и етсь. Более того, эта функция вызывается в большом количестве мест, поэтому, я решил оставить как есть, а не править их все, т.к. там достаточно сложно потом тестировать, воспроизводя использование в каждом из этих мест. Так же добавил `-1` в функцию, где этого не делалось и `+1` в место вызова

Кроме того, есть класс `AssemblyAdapter`, у которого есть функция с таким же именем и она уже возвращает длину - я переименовал её в `getAssemblyLength` для того, чтобы убрать путаницу.

2024-03-21 01:57 UTC, yalgaer reviewed
Замечаний нет, апрув после тестов

2024-03-24 01:23 UTC, DmitriiSukhomlinov commented
Не прошло три теста на маке (все помечены как flaky) и один тест на винде, никак не связаный с этой задачей. На всех остальных сюитах все прошло

2024-03-25 00:47 UTC, yalgaer approved these changes

2024-03-25 01:14 UTC, merged