UGENE-7787 [Pcr, wd] Improve logging when using too small primers
ugeneunipro/ugene pull request #1580
Opened 2024-03-15 13:15 UTC by DmitriiSukhomlinov

У проблемы слишком длинный/короткий праймер в WD было как-то очень много не связанных друг с другом обработчиков, я их все удалил и оставил один со стандартным сообщением, которое мы используем в GUI интерфейсе на вкладке OP в SV

2024-03-18 02:03 UTC, yalgaer requested changes

2024-03-18 02:03 UTC, yalgaer commented on src/plugins/pcr/src/InSilicoPcrWorker.cpp
> +        primers.removeOne(primerPair);
Удаление элементов из коллекции во время итерации по ней может привести к непредвиденным последствиям, включая пропуск элементов или ошибки доступа к памяти. Результат завсисит от деталей реализации коллекции.

2024-03-18 03:48 UTC, DmitriiSukhomlinov commented on src/plugins/pcr/src/InSilicoPcrWorker.cpp
> +        primers.removeOne(primerPair);
OK

2024-03-19 02:47 UTC, yalgaer commented
Замечаний нет, апрув после тестов

2024-03-22 03:01 UTC, DmitriiSukhomlinov commented
Пара случайных падений на маке и винде

2024-03-25 00:48 UTC, yalgaer approved these changes

2024-03-25 01:14 UTC, merged