UGENE-5291 WD can't work with files with ; in name
ugeneunipro/ugene pull request #1588
Opened 2024-03-19 00:13 UTC by rasputinkirill

Устроит такое решение, если да дополню тестом и трансляциями.

2024-03-19 03:03 UTC, yalgaer commented
Я бы попробовала корректно поддержать файлы с допустимыми символами.
У нас есть код, который объединяет списки имен файлов используя ';' и после восстанавливает оригинальные имена из списков (WorkflowUtils::unpackListOfDatasets).

Нужно сделать 2 модификации в этих методах:  энкодить и декодить "плохие" имена файлов по примеру того как это делается в веб:  https://doc.qt.io/qt-6/qurl.html#toEncoded.

Можно выбрать любой свой вид энкодинга (энкодить только ';' ), так чтобы при этом максимально сохранялось визуальное представление файла в закодированном виде.

2024-03-19 07:52 UTC, rasputinkirill commented
Решение с энкодингом не универсально.
Дело в том, что URLLineEdit и в кастомные поля воркеров пользователь может ввести данные руками, и мы не сможем определить где пользователь имел ввиду точку с запятой в имени файла, а где как разделитель файлов.
Поэтому остается абсолютно такая же ситуация как в текущем решении, тут мы можем гарантированно определить когда пользователь подразумевает несколько файлов, а когда имя с точкой с запятой только в случае с диалогами. А в случае ручного ввода мы не сможем определить и корректно заэнкодить.
Так что все же предлагаем оставить мое решение:
- проверять корректность имен файлов в случае ввода через диалог и информировать пользователя
- проверять на на этапе валидации схемы входные url (сюда попадут все которые были введены вручную)

2024-03-19 16:27 UTC, yalgaer commented
Если файл с таким именем возможно иметь в файловой системе, то UGENE должен уметь его открывать. Давай обсуждать решение в этом контексте.

2024-03-19 17:36 UTC, yalgaer commented
Если такой файл может быть в файловой системе, то UGENE должен уметь его открывать. Давай решать задачу в этом контексте.

2024-03-19 19:05 UTC, rasputinkirill commented
> Если такой файл может быть в файловой системе, то UGENE должен уметь его открывать. Давай решать задачу в этом контексте.

У меня есть только такой вариант решения:
В WorkflowUtils::validateInputFiles когда полученый на вход список url засплитили в список, валидатор в цикле начинает проверять их наличие на файловой системе. Если файла нету - он пытается конструирует url из текущего элемента, точки с запятой и следующего элемента списка, и снова проверяет наличие файла на файловой системе и так пока не найдет файл или не закончится список.
Если список закончился, а файл не обнаружен пишет ошибку "Не могу найти один из файлов из этого списка: " и выводит список с того элемента на котором застрял.

Если честно мне не сильно нравится эта идея, не нравится этот "элемент угадывания", мне кажется программа так не должна работать. Вариант с информированием пользователя об ограничении мне больше нравится.

Ну или предложи свое решение.

2024-03-20 01:24 UTC, yalgaer commented
Решение простое: изучить и выбрать какой вид encoding в данном случае будет наиболее приемлем.

Кодирование/декодирование URL- это именно то что используют как командные шелы в операционных системах, так и строки с параметрами в интернет.

Примеры: 
1. Имя файла может содержать пробел, но в командной строке это разделитель параметров. Как-то это проблема решается как на Windows так и на Linux
2. Значение параметра в URL может содержать знак =. Но знак = это разделитель ключ/значение для параметров. И тут проблема решена.

Так же и в UGENE это проблема может быть решена во всех местах где мы сериализируем/парсим список имен файлов.

К самой файловой системе при этом обращаться не нужно - список имен файлов должен однозначно кодироваться и декодироваться без внешнего контекста.

Проанализируй и выбери наиболее приемлемый нам вариант решения. Например:
1) Эскейпить ';'  если это часть имени файла
2) Заключать имя файла в кавычки если в нем есть "плохие" символы и эскейпить кавычки.
3) Энкодить плохие символы как URL параметры в интернет.
4) Что-то еще более крутое и интересное.

2024-03-27 03:47 UTC, rasputinkirill commented
Попробовал поэкспериментировать с экранированием кавычками, но столкнулся с проблемой.
QFileInfo и QFile в принципе не работают нормально с путями в которых есть ";" и путь юникс-стайл. 
Вызовы функций вернут false
```
    QFileInfo ffff("C:/ugene_issue_files/5291/A;nnota;tio;ns.txt");
    ffff.exists();
    QFile::exists("C:/ugene_issue_files/5291/A;nnota;tio;ns.txt");    
```

На линуксе сам юджин (не WD) даже не открывает файлы по таким путям.
![image](https://github.com/ugeneunipro/ugene/assets/17490668/6e798799-701f-4a13-a3b1-4a9bdb99cd9f)

2024-04-01 02:05 UTC, yalgaer commented
> Попробовал поэкспериментировать с экранированием кавычками, но столкнулся с проблемой. QFileInfo и QFile в принципе не работают нормально с путями в которых есть ";" и путь юникс-стайл. Вызовы функций вернут false
> 
> ```
>     QFileInfo ffff("C:/ugene_issue_files/5291/A;nnota;tio;ns.txt");
>     ffff.exists();
>     QFile::exists("C:/ugene_issue_files/5291/A;nnota;tio;ns.txt");    
> ```
> 
> На линуксе сам юджин (не WD) даже не открывает файлы по таким путям. ![image](https://private-user-images.githubusercontent.com/17490668/317117072-6e798799-701f-4a13-a3b1-4a9bdb99cd9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzczNDQsIm5iZiI6MTcxMTkzNzA0NCwicGF0aCI6Ii8xNzQ5MDY2OC8zMTcxMTcwNzItNmU3OTg3OTktNzAxZi00YTEzLWEzYjEtNGE5YmRiOTljZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAyMDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZjQ0NDQ3NTFmOTgyMzhiMzY4ODAwNGM3YjE3N2M5MWVmZDFhODA3NWQ5MTEyMTMwY2JjN2I3ZWI2YTllNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iEYXulBIYunTvj7T3kQS_FQrRzN7rYap33WLwn1M3zM)

Попробуй заескейпить плохие символы. Что если у QT спросить список файлов в каталоге среди которых будет "плохие"?
Мне кажется не может такого быть чтобы на Linux были файлы которые QT вообще не может открыть.

2024-04-01 20:53 UTC, rasputinkirill commented
```
QFileInfo ffff("C:/ugene_issue_files/5291/A\;nnota\;tio\;ns.txt");
ffff.exists();
QFile::exists("C:/ugene_issue_files/5291/A\;nnota\;tio\;ns.txt");
```
Заэскейпленые не воспринимает.
```
QDir dir("C:/ugene_issue_files/5291/");
QStringList entries = dir.entryList();
```
Тут в списке все файлы присутствуют.
На линуксе так же. Причем при сборке ворнинги на `\;` Unknown escape sequence.

Если что то, скриншот выше это месседж бокса с ошибкой - это я просто через File->Open попробовал открыть файл с проблемным именем. Это я к тому что если делать поддержку точки с запятой в путях, то это надо будет по всему приложению в итоге делать, а не только в дизайнере.

2024-04-02 02:54 UTC, yalgaer commented
Qt нормально работает с файлами у которых в имени есть точка с запятой:
![image](https://github.com/ugeneunipro/ugene/assets/17791039/a184f1bd-5e5e-4840-89e7-dba61c03059d)
![image](https://github.com/ugeneunipro/ugene/assets/17791039/f3f144a2-d3c1-42bb-ae05-95e2dcb04ae0)

В рамках этого бага достаточно исправить описанную проблему - не нужно переделывать весь UGENE. На остальные места можно завести другие баги.

2024-04-09 12:31 UTC, rasputinkirill commented
Попробовал сделать с экранированием всей строки заключением в двойные кавычки.
Но столкнулся с проблемой, что в самом формате uwl файла который создается и потом запускается присутствуют кавычки, а если при сериализации файла он встречает двойные кавычки то меняет их на одинарные.
Экранировать пути в одинарными кавычками тоже не выйдет - так как это допустимый в путях файлов.
Так же а принципе при любом типе экранирования, хоть символа, хоть всей строки в кодле придется обрабатывать все места где мы этот файл пытаемся открыть.
А еще тут не видно сразу масштаба необходимых работ, исправляешь одну проблему - появляяются еще места где это не работает.

Пока я все это пытался делать обнаружил что датасеты должны нормально работать с путями с ";" так как там файлы всегда передаются для обработки по одному и неопределенности не возникает.
Поэтому предлагаю такие исправления: 
- проверить что датасеты корректно обрабатывют проблемные пути и убрать проверку для них
- в URLLineEdit при вводе проблемного пути выдавать пользователю предупреждение

2024-04-10 03:41 UTC, yalgaer commented
А что именно будет в предупреждении? 
Если мы скажем что в результате будет неопределенное поведение - то это нехорошо.

Можно ли при сохранении в UWL экранировать и переводы строк и кавычки по примеру URL encoding?
Это может быть расширением возможностей формата UWL: например так:

files: urls("url1", "url2"...) где url в кавычках уже безопасный (encoded)
?

2024-04-11 08:22 UTC, rasputinkirill commented
> А что именно будет в предупреждении? Если мы скажем что в результате будет неопределенное поведение - то это нехорошо.

В предупреждении будет написано "путь до файла ';', такие пути не поддерживаются этим элементом, переименуйте и/или положите файл в другую папку.".
 
> Можно ли при сохранении в UWL экранировать и переводы строк и кавычки по примеру URL encoding? Это может быть расширением возможностей формата UWL: например так:
> 
> files: urls("url1", "url2"...) где url в кавычках уже безопасный (encoded) ?

Думаю, если делать "по-красоте" то для данных из URLLineEdit обертку как для dataset и показывать пользователю в воркере пути как он их ввел - с ";" в путях, а внутри юджина гонять эти данные в заэнкоженном виде. Так же и в схему писать в заэнкоженном виде, а при загрузке и показе схемы пользователю приводить к "человеческому" виду.

Я бы ограничился с вариантом с проверкой работоспособности датасетов и предупреждением в URLLineEdit. Мне кажется поддержка такого вида имен файлов не стоит уже потраченного времени на эту задачу.

2024-04-12 04:08 UTC, yalgaer commented
В качестве временного/быстрого решения можно сделать так, чтобы UGENE вообще не давал записывать/запускать то, в результате чего он не уверен.

Можно ли вместо "предупреждения" сделать блокировку на запуск?

2024-04-12 12:23 UTC, rasputinkirill commented
Не совсем понял что имеешь в виду, ведь сейчас так и есть. Пытаемся запустить схему - валидатор говорит что в схеме ошибки тоько они выглядят коряво из-за попытки распаристь путь по кускам разделенными ";", например для пути "c:\ugene_issue_files\5291\A;;nnota;;tio;n_names.txt" будет так:
![image](https://github.com/ugeneunipro/ugene/assets/17490668/8d1ab503-3a79-4a47-8f28-7a966bd3fe81)
Схема запущена не будет.

2024-04-14 00:19 UTC, yalgaer commented
То есть если мы идем по пути отказа от полноценного фикса, получается что мы не можем отличить ситуацию где ; это символ в имени файла или ; это символ разделитель разных имен.

Если мы не можем различить - не нужно ни warning, ни ошибки - мы должны работать с ; как с разделителем.

Если же мы знаем, что ; каким-то образом пришел в элемент как символ в имени файла - тут мы должны отказать в исполнении/записи этого имени, так как при чтении мы будем трактовать его как разделитель. Правильно?

2024-04-14 02:54 UTC, rasputinkirill commented
> То есть если мы идем по пути отказа от полноценного фикса, получается что мы не можем отличить ситуацию где ; это символ в имени файла или ; это символ разделитель разных имен.
> 
> Если мы не можем различить - не нужно ни warning, ни ошибки - мы должны работать с ; как с разделителем.
> 

Сейчас работает так -  во время валидации когда проверяется что все входные пути существуют ; интерпретируется как разделитель. Появляются ошибки валидации и все прерывается, предлагаешь убрать эту проверку в валидаторе схемы?

> Если же мы знаем, что ; каким-то образом пришел в элемент как символ в имени файла - тут мы должны отказать в исполнении/записи этого имени, так как при чтении мы будем трактовать его как разделитель. Правильно?

Ну не совсем, я предлагал что если пользователь ввел в URLLineEdit путь с ; то не принимать его ввод и выдавать MessageBox с просьбой переименовать/поменять путь.
При этом так же проверить и отредактировать проверку для путей пришедших из датасетов так как пути из них обрабатываются  по одной штуке и ; в них никогда не бывает разделителем.

Так же мне тут еще идея пришла, сделать класс URLLineEdit для мест где ожидается ввод одного пути и для мест где вводится список. Тогда, если из URLLineEdit в котором ожидается ввод одного пути пришел url то не пытаться парсить его как список файлов и тогда будет однозначность насчет данных пришедших из него.  А проверку и предупреждение делать только в тех где список вводим.
У меня если честно ощущение, что у нас даже нет (или их буквально единицы) воркеров где мы ожидаем ввод списка файлов.
Тогда получится что в датасетах проблемные пути допустимы, в большей части воркеров допустимы и только в некоторых будет предупреждение при вводе.

2024-04-15 02:26 UTC, yalgaer commented
Мне было бы интересно сделать поддержку multiple URLS в UWL таким образом, что не возникает неопределенности.
Но если это перебор - давай сделаем минимум твоим способом. Напиши как тот простой и лучший с твоей точки зрения способ готов для review

2024-04-16 00:41 UTC, rasputinkirill commented
Поменял проверку путей для датасетов, так как там всегда единственный url приходит для проверки.
Директории тоже всегда по одной проверяются, поэтому переименовал и поменял метод.
В URLLineEdit добавил отображение предупреждения

2024-04-17 01:39 UTC, yalgaer commented on src/corelibs/U2Designer/src/WorkflowGUIUtils.h
> +    static void semicolonWarning();
1) Add docs, 2) start method names with a verb

2024-04-17 01:39 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +    emit si_finished();
nit: нужно вынести si_finished() за пределы этого метода. Если метод только проверяет/оповещает об ошибке то завершать весь процесс не его задача.

2024-04-17 01:39 UTC, yalgaer commented on src/corelibs/U2Lang/src/support/WorkflowUtils.cpp
>      }
Есть ли смысл тут продолжать проверять файлы после первой ошибки? Ошибок может быть тысячи?

2024-04-17 05:29 UTC, rasputinkirill commented on src/corelibs/U2Lang/src/support/WorkflowUtils.cpp
>      }
Тоже думал так сделать, но оставил старое поведение. 
Если пользователь получит ошибку на пачку файлов он их пачкой и исправит, а не по одной будет. Можно ввести лимит на количество ошибок, например. IDE так же делают. Что думаешь?

2024-04-17 05:30 UTC, rasputinkirill commented
Исправление устраивает, пишу тесты?

2024-04-19 03:47 UTC, yalgaer commented
> Исправление устраивает, пишу тесты?

Да

2024-05-05 01:49 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
Замечания:
1. Если файл не найден - достаточно сказать что он не найден. Говорить о semicolon в каждом случае когда файл не найден не нужно. Думаю соотношение "файл не найден" в "файл не найден по причине что в его имени semicolin" стремиться к бесконечности.

2024-05-05 09:21 UTC, rasputinkirill commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
Я тут исходил из такой логики:
Это проверка если пользователь делал ввод пути руками, а не через кнопку "browse" то мы должны проверить этот ввод.
Если пользователь должен был указывать входной файл - значит он должен существовать. 
Но если делегат подразумевает ввод нескольких файлов с разделителем ";" ? Мы это не можем определить.

Тогда если встретили  ";" во введенной строке то сделаем сплит по ";" и проверим каждый путь на наличие файла. Если файлы найдены - то тогда мы понимаем что тут имелся ввиду множественный ввод путей и принимаем введенные данные. Если же один из файлов не был найден - то выдаем предупреждение "либо один из файлов не найден, либо вы ввели путь до файла содержащий   ";" ".

Или можно написать немного другое предупреждение если думаешь что текущее плохое, что-то типа: "В этом поле ввода ";" интерпретируется как разделитель путей до файлов при множественном вводе. Файл по пути %путь до файла% не был найден. Проверьте что путь до файла не содержит ";" либо убедитесь что файл существует по этому пути или переместите/переименуйте файл чтобы его путь\имя не содержали ";""

2024-05-06 14:32 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
Будет ли эта ошибка выдаваться если пользователь ничего не вводил, а просто открыл uwl file?

Если в списке 100 файлов будет ли эта ошибка выдаваться 100 раз?

2024-05-07 08:55 UTC, rasputinkirill commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
Нет не будет, эта проверка привязана к сигналу `QLineEdit::editingFinished()`, это было добавлено чтобы при ручном вводе в URLLineEdit предупреждение было показано, а не только когда в нем через кнопуку "..." файл вводят.

2024-05-07 14:25 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
1. setText("") делать не нужно - это перетирает то, что пользователь ввел руками и это неправильно (возможно он ошибся в 1  символе)

2. Все имена функций надо начинать с глагола: semicolonWarning -> showSemicolonWarning

3. Warning должен быть не про semicolon, а про то что файл не найден: showFileNotFoundWarning(fileName)

4. Чем отличается file-not-found от can't-read-file или not-file-but-directory? Это все ошибки одного типа.

2024-05-07 14:29 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +        filePathIsOk = checkNameForSemicolon(name);
Зачем здесь эта проверка?

2024-05-07 14:31 UTC, yalgaer commented on src/corelibs/U2Lang/src/support/WorkflowUtils.cpp
> +    CHECK_EXT(fi.exists(), notificationList << WorkflowNotification(L10N::errorFileNotFound(url)), false);
QString url -> const QString& url

2024-05-07 14:33 UTC, rasputinkirill commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
> * setText("") делать не нужно - это перетирает то, что пользователь ввел руками и это неправильно (возможно он ошибся в 1  символе)
При выборе кнопкой "..." выбранный пользователем файл тоже не попадает в поле вводе в случае неподходящего имени файла.
> * Warning должен быть не про semicolon, а про то что файл не найден: showFileNotFoundWarning(fileName)
Тут же мы не знаем что имел ввиду пользователь, если он вводил несколько файлов используя разделитель илбо если он вводил имя файла с ";" то мы говорим что такие имена не поддерживаются
> * Чем отличается file-not-found от can't-read-file или not-file-but-directory? Это все ошибки одного типа.
В этом месте только file-not-found и "плохое имя"

2024-05-07 14:35 UTC, yalgaer commented on src/corelibs/U2Lang/src/support/WorkflowUtils.cpp
>      }
Нужно выдавать только одну ошибку. Если хочешь можешь в ее текст включить первые N файлов

2024-05-07 14:35 UTC, rasputinkirill commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +        filePathIsOk = checkNameForSemicolon(name);
Проверяем после ввода через кнопку, так изначально сделал.
Предлагаешь это убрать и оставить только проверку на sl_editingFinished()?

2024-05-07 14:38 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
Если пользователь ввел имя файла которое мы не можем открыть по любой причине - должно быть сообщение об ошибке. Либо проверяем все ошибки доступа здесь, либо ни одной. 

Выделять и проверять только 1 определенный тип ошибок (file not found) и игнорировать другие (типа file is a directory) неправильно.

2024-05-07 14:39 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +        filePathIsOk = checkNameForSemicolon(name);
Чему равно name в этом месте?

2024-05-07 14:42 UTC, rasputinkirill commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +        filePathIsOk = checkNameForSemicolon(name);
да, ошибка, надо содержимое lst смотреть

2024-05-07 15:03 UTC, rasputinkirill commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
Я так понял предлагаешь дополнить проверками "can't-read-file" или "not-file-but-directory".

2024-05-07 15:23 UTC, yalgaer commented on src/corelibs/U2Designer/src/support/URLLineEdit.cpp
> +            DesignerGUIUtils::semicolonWarning(true);
Либо все, либо ни одной. Оба варианта разумны

2024-05-07 15:25 UTC, yalgaer requested changes
Меняю статус requested review -> request changes. Причина: часть комментариев не исправлена

2024-05-15 15:31 UTC, yalgaer requested changes
Ну нужно говорить в сообщении об ошибке о символе ;

Вероятность имено этой исчезающе мала по сравнению с обычной: файл не найден по каким-то другим причинам. В этом случае мы только запутаем пользователя своей рекомендацией. Можешь добавить это в доку если хочешь и сослаться из ошибки на доку. 

Достаточно показать пользователю имя файла как мы его понимаем - дальше он поймет сам что не так

2024-05-20 09:21 UTC, rasputinkirill commented
Хорошо, поменял в случае ручного ввода. Если пользователь выбирал через гуи оставил текущее сообщение - тут вполне однозначно что выбран файл с плохим путем\именем.

2024-05-21 06:51 UTC, yalgaer requested changes
Тест должен быть без workarounds и извинений: если иначе не работает, надо исправлять или просто писать тест иначе (так как текущие проблемы в тесте не относятся к тестируемуму исправлению)

Если мы оставили 2 варианта поведения: c и без ручнного ввода: можно ли протестировать оба варианта?

2024-05-21 15:52 UTC, rasputinkirill commented
Не понял что не так с тестом, мы тут тестируем и ручной ввод, и ввод через gui и то что в датасетах можно любой путь задать.
То что перекликиваем элемент я написал, проблема возникает из-за потери фокуса ввода после появления месседж бокса.

2024-05-22 12:39 UTC, yalgaer commented
> То что перекликиваем элемент я написал, проблема возникает из-за потери фокуса после появления месседж бокса.

Перекликивание говорит о баге в WD - либо элемент в фокусе и на него не нужно кликать чтобы увидеть его детали, либо не в фокусе - тогда достаточно кликнуть только на него.

Кликать на другой элемент и потом возвращаться к текущему - это workaround для бага.

> Не понял что не так с тестом, мы тут тестируем и ручной ввод, и ввод через gui и то что в датасетах можно любой путь задать.

Не вижу где тестируется текст нового сообщения об ошибке

2024-05-22 13:39 UTC, rasputinkirill commented
Так устроит?

2024-05-23 19:32 UTC, yalgaer commented
Замечаний нет, жду зеленые тесты

2024-05-29 04:20 UTC, rasputinkirill commented
На маке несвязанный тест упал, считаем что успех?

2024-05-29 17:59 UTC, yalgaer approved these changes

2024-05-30 05:12 UTC, merged