UGENE-7290 [ET] Determine vcf-consensus version
ugeneunipro/ugene pull request #1590
Opened 2024-03-21 04:12 UTC by rasputinkirill

Инструмент не выводит свою версию при запуске ни с каким параметром.
Но в папке с инструментом находится соответствующий файл, читаю версию из него.

2024-03-22 01:39 UTC, yalgaer requested changes
Минимальные замечания. Апрув после исправления и тестов.

2024-03-22 01:39 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/ExternalToolRegistry.h
> +    virtual const QString getVersionFromToolPath(const QString& toolPath) const;
Добавь документацию пожалуйста
/** Returns the tool version for the tool located by the specified path without running the tool. Returns an empty string if can't derive the tool version by the path. */

2024-03-22 01:39 UTC, yalgaer commented on src/plugins/external_tool_support/src/vcftools/VcfConsensusSupport.cpp
> +    QFile f(versionPath);
У нас есть однострочный метод который читает содержимое файла.

2024-03-25 00:50 UTC, yalgaer commented on src/plugins/external_tool_support/src/vcftools/VcfConsensusSupport.h
> +    virtual const QString getVersionFromToolPath(const QString& toolPath) const override;
virtual не нужен если уже несть override

2024-03-25 09:51 UTC, rasputinkirill commented
На линуксе гуи сейчас прошли, на маке и линуксе в предыдущей итерации. Думаю можно мержить.

2024-03-26 00:25 UTC, yalgaer approved these changes

2024-03-26 04:20 UTC, merged