Ugene 6485 gui test
ugeneunipro/ugene pull request #1592
Opened 2024-03-23 07:04 UTC by rasputinkirill

Ну сейчас все четко должно быть

2024-03-25 02:47 UTC, rasputinkirill commented
Зависимых тестов не упало.

2024-03-26 00:37 UTC, yalgaer requested changes

2024-03-26 00:37 UTC, yalgaer commented on src/corelibs/U2Lang/src/support/WorkflowUtils.cpp
> +                if (str == left && uniqueStrs.contains(str)) {
Это изменение лишнее. Проверка уже сделана в строке 774.

2024-03-26 05:47 UTC, rasputinkirill commented on src/corelibs/U2Lang/src/support/WorkflowUtils.cpp
> +                if (str == left && uniqueStrs.contains(str)) {
Не смог вспомнить зачем было нужно это изменение, цбрал

2024-03-26 05:48 UTC, rasputinkirill commented
Мержим, или снова ганяем тест?

2024-04-01 02:08 UTC, yalgaer commented on src/plugins/GUITestBase/src/GTUtilsWorkflowDesigner.cpp
> +QTreeWidgetItem* GTUtilsWorkflowDesigner::findTreeItem(const QString& itemName, tab t, bool exactMatch, bool failIfNULL, bool returnFirst) {
Это изменение добавляет неопределенность в тесты.
Ты уверен что тебе все равно с каким из нескольких элементов работать? Может добавить скрин где это будет видно: что выбор элемента для работы/проверки не имеет значения?

2024-04-01 18:18 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/GTUtilsWorkflowDesigner.cpp
> +QTreeWidgetItem* GTUtilsWorkflowDesigner::findTreeItem(const QString& itemName, tab t, bool exactMatch, bool failIfNULL, bool returnFirst) {
Было сделано чтобы удалились все элементы имена которых начинаются с "el_6485" чтобы если остались созданные элементы от предыдущих незавршенных тестов или ручных запусков то они бы и все удалились и тест пошел работать. Эти элементы не хранятся в ини файле и поэтому удаление ини файла их не уберет.
Так же, я вспомнил зачем было предыдущее изменение.
Было такое если создаем три элемента с именем `el` то получаем `el, el 1, el 2`, удаляем `el` и снова пробуем создать элемент с именем `el` получаем `el 1, el 2, el 3` вместо `el, el 1, el 2`.

2024-04-02 02:11 UTC, yalgaer commented on src/plugins/GUITestBase/src/GTUtilsWorkflowDesigner.cpp
> +QTreeWidgetItem* GTUtilsWorkflowDesigner::findTreeItem(const QString& itemName, tab t, bool exactMatch, bool failIfNULL, bool returnFirst) {
Нужно сделать так, чтобы ни один из тестов не давал наводку на другой тест.
То есть, если текущего механизма очистки не хватает, чистить прямо в тесте перед тем как что-то проверять.

2024-04-02 07:22 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/GTUtilsWorkflowDesigner.cpp
> +QTreeWidgetItem* GTUtilsWorkflowDesigner::findTreeItem(const QString& itemName, tab t, bool exactMatch, bool failIfNULL, bool returnFirst) {
Так и делается мы в цикле удаляем все элементы имя которых начинается с "el_6485".

2024-04-03 03:08 UTC, yalgaer commented on src/plugins/GUITestBase/src/GTUtilsWorkflowDesigner.cpp
> +QTreeWidgetItem* GTUtilsWorkflowDesigner::findTreeItem(const QString& itemName, tab t, bool exactMatch, bool failIfNULL, bool returnFirst) {
Тогда почему бы не найти все treeItem (вернуть список)?
С точки зрения переиспользуемого утилитного метода этот вариант лучше чем "найди один случайный из нескольких"

2024-04-03 11:19 UTC, rasputinkirill commented on src/plugins/GUITestBase/src/GTUtilsWorkflowDesigner.cpp
> +QTreeWidgetItem* GTUtilsWorkflowDesigner::findTreeItem(const QString& itemName, tab t, bool exactMatch, bool failIfNULL, bool returnFirst) {
Посчитал нецелесообразным писать метод который необходим в одном месте и будет частичной копипастой существующего. Решил внести дополнительный параметр со значением по умолчанию в текущий метод.

2024-04-03 17:45 UTC, yalgaer commented on src/plugins/GUITestBase/src/GTUtilsWorkflowDesigner.cpp
> +QTreeWidgetItem* GTUtilsWorkflowDesigner::findTreeItem(const QString& itemName, tab t, bool exactMatch, bool failIfNULL, bool returnFirst) {
Правильно, ради одного места не стоит вводить неопределенность (и послабления) в существующий API метод который используется в других местах. Писать тесты с неопределенностью это плохая практика.

Я бы предложила добавить метод который возвращает список - это определенное поведение, но если думаешь что он не нужен то можешь написать его реализацию прямо в тесте

2024-04-07 22:46 UTC, rasputinkirill commented
Нельзя взять список элементов с похожим именем и потом их удалять, так как после удаления  одного эти элементы меняются и надо будет опять искать их. Сделал очистку кастомных элементов через пост экшен.

2024-04-08 08:25 UTC, rasputinkirill commented
Сделал в итоге через метод в тесте. Удалять списком элементы нельзя, так как при удалении список меняется и найденные элементы становятся не валидными.

2024-04-09 03:08 UTC, yalgaer requested changes
Минимальные замечания про лишний код со внутренними циклами

2024-04-09 03:08 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_6001_7000.cpp
> +        QList<QTreeWidgetItem*> outerList = treeWidget->findItems("", Qt::MatchContains);
nit:
Я правильно понимаю что тут мы просто берем все items внутри treeWidget?
Тогда без всякого find("") можно использовать итератор: QTreeWidgetItemIterator

2024-04-09 03:08 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_6001_7000.cpp
> +            QList<QTreeWidgetItem*> innerList;
Структура innerList не нужна. Можно сразу в одном внутреннем цикле сделать то, что ты делаешь в двух

2024-04-09 03:08 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_6001_7000.cpp
> +    for (findEl_6485(); el != nullptr; findEl_6485()) {
nit: можно было бы сделать проще: `while (findEl_6485())`

2024-04-10 03:42 UTC, yalgaer commented
Замечаний нет, если GUI тесты проходят - апрув

2024-04-12 04:08 UTC, yalgaer approved these changes

2024-04-12 15:30 UTC, merged