UGENE-7783 The "ACE" format "A name is duplicated" error
ugeneunipro/ugene pull request #1601
Opened 2024-04-05 09:58 UTC by DmitriiSukhomlinov

Сделал так, что ACE может спокойно работать, если в нем попались риды с одинаковыми именами (это не помеха ни для редактора множестенного выравнивания, ни для браузера сброк).

Удалил один негативный XML тест, который проверял как раз ошибку при загрузке ACE файла с ридами, имеющими одинаковые имена. Добавил два позитивных.

Обнаружил, что для обоих способов открытия используется разный код, что не очень хорошо, потому что парсят файл они по одному и тому же сценарию, т.е., по факту, дублирование кода. Сделаю в [UGENE-8066](https://ugene.dev/tracker/browse/UGENE-8066)

2024-04-07 02:51 UTC, DmitriiSukhomlinov commented
Упало несколько несвязанных тестов

2024-04-07 17:43 UTC, yalgaer requested changes

2024-04-07 17:43 UTC, yalgaer commented on src/corelibs/U2Formats/src/ace/AceFormat.h
> +    static void parseAFTag(U2::IOAdapter* io, U2OpStatus& ti, char* buff, int count, QList<Assembly::Sequence>& reads, QList<QString>& names);
Функция имеет довольно сложную сигнатуру из которой непонятно что происходит. Нужен комментарий со спецификацией

2024-04-07 17:43 UTC, yalgaer commented on src/corelibs/U2Formats/src/ace/AceImportUtils.h
> +        bool operator==(const Sequence& second) {
Тела функций надо писать в cpp.

2024-04-07 17:43 UTC, yalgaer commented on src/corelibs/U2Formats/src/ace/AceImportUtils.cpp
> +    QList<QByteArray> names;
Похоже `names ` больше вообще не нужны.
Предлагаю либо убрать либо сделать более точными проверки основанные на содержимом `names`

2024-04-07 17:43 UTC, yalgaer commented on src/corelibs/U2Formats/src/ace/AceFormat.h
> +    static int getSmallestOffset(const QList<Assembly::Sequence>& reads);
предлагаю изменить на qint64. Если для MSA работа в 32-битном пространстве допустима, то для assembly координат уже нужно 64 бита

2024-04-08 05:42 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/ace/AceImportUtils.cpp
> +    QList<QByteArray> names;
> Похоже names  больше вообще не нужны.
Предлагаю либо убрать либо сделать более точными проверки основанные на содержимом names

Нужны - с их помощью проверяется, что у каждый рид, объявленный в тэге AF, имеет свой тэг RD (можно сказать, что в AF идет объявление рида, а в RD - реализация). До этого, помимо контролирования неповторяющихся имен ридов, это поле так же использовалось для этого.

2024-04-08 05:56 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/ace/AceFormat.h
> +    static int getSmallestOffset(const QList<Assembly::Sequence>& reads);
ОК. Правда, это послекло за собой достаточно много изменений `int` на `qint64`.

2024-04-08 05:58 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/ace/AceImportUtils.h
> +        bool operator==(const Sequence& second) {
OK

2024-04-08 05:58 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/ace/AceFormat.h
> +    static void parseAFTag(U2::IOAdapter* io, U2OpStatus& ti, char* buff, int count, QList<Assembly::Sequence>& reads, QList<QString>& names);
OK

2024-04-08 06:09 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/ace/AceFormat.h
> +    static int getSmallestOffset(const QList<Assembly::Sequence>& reads);
При этом, из-за дублирования кода, аналогичный `int`сохранился в AceImportUtils. Я планирую объединить два процесса парсинга в [UGENE-8066](https://ugene.dev/tracker/browse/UGENE-8066) и там же могу удалить версию с `int`

2024-04-09 03:14 UTC, yalgaer commented on src/corelibs/U2Formats/src/ace/AceImportUtils.cpp
> +    QList<QByteArray> names;
В методе `AceReader::parseConsensus`  есть строки:
```
  consensus.name = getName(headerLine);
    CHECK_EXT(!names.contains(consensus.name), os->setError(DocumentFormatUtils::tr("A name is duplicated")), );

    names << consensus.name;
```
Значит ли это что дупликаты по именам все еще запрещены?

2024-04-09 03:20 UTC, yalgaer commented on src/corelibs/U2Formats/src/ace/AceImportUtils.cpp
> +    QList<QByteArray> names;
В методе `AceReader::parseRdAndQaTag`
для каждого рида удаляется его имя из списка `names`, но `names` содержит больше элементов чем просто имена ридов: в него добаляется также результат `parseConsensus`

В итоге проверка в `parseRdAndQaTag` проверяет риды на множестве имен большем чем имена ридов и это неверно. Правильно?

2024-04-09 06:50 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/ace/AceImportUtils.cpp
> +    QList<QByteArray> names;
Да, верно, я тут не заметил. Я убрал код, добавляющий имена консенсуса в данный список. Он действительно не имеет смысла, т.к. UGENE  в состоянии самостоятельно обработать ситуацию, когда у консенсусов одинаковые имена (он им припишет " 1"). Проверку для ридов я бы все таки убирать не стал, т.к. она имеет смысл и проверяет соответствие тэгов у каждого из ридов (консенсус, в отличии от ридов, пишется в одном тэге, информация по ридам же размазана на два).

2024-04-10 03:57 UTC, yalgaer commented on src/corelibs/U2Formats/src/ace/AceImportUtils.cpp
> +    QList<QByteArray> names;
Список `reads` содержит те же имена что и список `names`. Зачем тогда нужен `names`?

2024-04-10 06:53 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/ace/AceImportUtils.cpp
> +    QList<QByteArray> names;
Это крайне минорная проверка, я просто удалю ее, раз уж она тебе так не нравится. В конце концов, да, с помощью `reads` проверяется нечто подобное.

2024-04-11 02:32 UTC, yalgaer commented
Замечаний нет, апрув после тестов

2024-04-11 06:17 UTC, DmitriiSukhomlinov commented
Один тест проверял, что файл, у которого консенсусы имеют одинаковые имена, не открывается - я заменил его на аналогичный, который проверяет, что все в порядке с этим.

2024-04-12 04:09 UTC, yalgaer approved these changes

2024-04-12 04:45 UTC, merged