UGENE-7267 Can't save sequence name change
ugeneunipro/ugene pull request #1602
Opened 2024-04-05 12:25 UTC by DmitriiSukhomlinov

2024-04-07 17:34 UTC, yalgaer requested changes
Почему такое поведение при переименовывании сделано только для Sequence object? Другие типы (MSA/Assembly/Tree) в Project view должны вести себя аналогичным образом.

2024-04-08 05:19 UTC, DmitriiSukhomlinov commented
> Почему такое поведение при переименовывании сделано только для Sequence object? Другие типы (MSA/Assembly/Tree) в Project view должны вести себя аналогичным образом.

Это уже сделано для всех объектов, которые соотносятся к форматам, как минимум один из которых умеет писать свое имя. По каким-то причинам, этого не было сделано только для последовательностей. У `MSA` отслетивается модификация; у `Assembly` (и у любого другого объекта, который пишется в ugenedb) любая модификация пишется в файл на лету, поэтому у него в принципе этот флаг не работает; Tree/аннотации не умееют писать данные своего имени в файл, поэтому им выставлять модификацию не имеет смысла. Вообще, текущий механизм имеет проблему, ниже я описываю ее подробно.

После небольшого исследования, я понимаю, что в UGENE механизм сохранения имени объекта сделан не очень правильно. В данный момент, за отслеживание модификации имени файла отвечает именно объект. С точки зрения кода, это какой-то наследник `GObject` - `U2SequenceObject` для последовательностей (добавлено в этой задаче), `MsaObject` для выравниваний и так далее. Принцип используется простой - если хотя бы один формат, данные которого перегоняются в объект данного типа, **умеет писать свое имя**, то для данного типа объекта мы отслеживаем модификацию имени. Из-за этого у некоторых форматов озникает проблема - мы отслеживаем модификацию имени, однако эту модификацию попросту некуда записать. Пример - `MsaObject`. UGENE поддерживает запись в следующие форматы, которые могут содержать в себе данные, представляемые в виде `MsaObject`:

- CLUSTALW
- FASTA
- MEGA
- MSF
- NEXUS
- PHYLIP (два типа)
- Stockholm

Однако, из всего этого обширного списка, только **Stockholm** умеет хранить внутри своего представления имя, которое, в случае UGENE, можно соотнести с именем объекта выравнивания. Остальные форматы в качестве имени объекта берут имя файла, отбросив расширение. То есть для всех форматов, кроме `Stockholm`, сколько бы мы не модифицировали имя объекта, сам формат попросту не имеет никаких специальных полей, куда бы это имя можно было записать. Поэтому, фактически, для все форматов, кроме `Stockholm`, отслеживать модификацию имени объекта не имеет смысла - это только вводит пользователя в заблуждение (мы меняем имя объекта у условного CLUSTALW, видим модфикацию, сохраняем файл, переоткрываем файл - а имя не изменилось).

С последовательностями ситуация аналогичная, за исключением, пожалуй, того, что у них большая часть форматов все-таки имеет некоторое внутреннее представление, которое можно ассоциировать с именем файла. Однако, и тут есть исключение - например, формат `.seq`.

Мне кажется, что очевидным решением является переделать отслеживание модификации имени объекта так, чтобы за это отвечал каждый формат по отдельности, а не объект (наследник `GObject`) в целом. Предлагаю решить этот вопрос лжнгим из двух способов: **я закрываю эту задачу с текущим фиксом** либо **закрываю ее как won't fix**. После этого завожу задачу на реализацию описанного выше (изменение отслживание модификации с объекта на формат). Сразу делать не буду, т.к. это может быть не быстро, а я планировал сначала посмотреть другие задачи. Я бы предпочел первый все-таки влить этот фикс, т.к. я не знаю, когда я продолжу заниматься этой задачей, а проблема так или иначе есть.

2024-04-09 03:24 UTC, yalgaer commented
Задачу нужно решить правильно. В качестве места хранения имени можно рассмотреть "проект". Файл при изменении имени можно и вовсе не модифицировать.

2024-04-09 03:32 UTC, DmitriiSukhomlinov commented
> Задачу нужно решить правильно. В качестве места хранения имени можно рассмотреть "проект". Файл при изменении имени можно и вовсе не модифицировать.

Не согласен с предложенным решением от слова вообще. При чем здесь вообще проект? В том, чтобы сделать так, чтобы хранил логики не много. А если и сделать так, то что, если файл открыт в новом проекте? Или что если имя объекта у файла редактируется, а потом файл используется в WD или CMD версии UGENE, где проекта нет? Нет, такое решение я реализовывать не буду.

2024-04-09 03:50 UTC, yalgaer commented
> > Задачу нужно решить правильно. В качестве места хранения имени можно рассмотреть "проект". Файл при изменении имени можно и вовсе не модифицировать.
> 
> Не согласен с предложенным решением от слова вообще. При чем здесь вообще проект? В том, чтобы сделать так, чтобы хранил логики не много. А если и сделать так, то что, если файл открыт в новом проекте? Или что если имя объекта у файла редактируется, а потом файл используется в WD или CMD версии UGENE, где проекта нет? Нет, такое решение я реализовывать не буду.

Это был лишь вариант для рассмотрения: fallback который может работать абсолютно для всех типов файлов. Есть и другие варианты: сохранять прямо в файл, сохранять "рядом с файлом" и тп.

Что такое "визуальное имя" в UGENE и как оно отображается в формат - это может быть индивидуально для каждого формата (сложное решение) или обще для всех (fallback решение).

Правильное решение проблемы - это выработка общего решения сохранения визуального имени для всех форматов.

2024-04-09 06:21 UTC, DmitriiSukhomlinov commented
> > > Задачу нужно решить правильно. В качестве места хранения имени можно рассмотреть "проект". Файл при изменении имени можно и вовсе не модифицировать.
> > 
> > 
> > Не согласен с предложенным решением от слова вообще. При чем здесь вообще проект? В том, чтобы сделать так, чтобы хранил логики не много. А если и сделать так, то что, если файл открыт в новом проекте? Или что если имя объекта у файла редактируется, а потом файл используется в WD или CMD версии UGENE, где проекта нет? Нет, такое решение я реализовывать не буду.
> 
> Это был лишь вариант для рассмотрения: fallback который может работать абсолютно для всех типов файлов. Есть и другие варианты: сохранять прямо в файл, сохранять "рядом с файлом" и тп.
> 
> Что такое "визуальное имя" в UGENE и как оно отображается в формат - это может быть индивидуально для каждого формата (сложное решение) или обще для всех (fallback решение).
> 
> Правильное решение проблемы - это выработка общего решения сохранения визуального имени для всех форматов. Оно может содержать и частные части для каждого формата и общий fallback.

Формат может содержать или не содержать внутри себя некоторое представление, которое может быть интерпретировано как имя объекта. Это зависит от конкретного формата. С моей точки зрения, правильным решением было бы разделить этот момент для каждого формата по отдельности. Это решение наиболее объемное, но, по факту. не такое уж и сложное, поскольку нас интересуют только те форматы, которые мы умеем писать, а они составляют только некоторую часть от всех форматов, которые UGENE поддерживает (большая часть read-only).

2024-04-10 04:05 UTC, yalgaer commented
Если на визуальное имя которое мы показываем в UGENE налагает ограничения формат и состояние файла (типа  readonly) - эти детали должны быть включены в диалог rename (валидатор), чтобы пользователь однозначно понимал что происходит.

Предложенное в этом PR решение общее для Sequence из любого формата не подходит.

2024-04-10 05:51 UTC, DmitriiSukhomlinov commented
> Если на визуальное имя которое мы показываем в UGENE налагает ограничения формат и состояние файла (типа readonly) - эти детали должны быть включены в диалог rename (валидатор), чтобы пользователь однозначно понимал что происходит.

Ситуацию, когда файл read only, мы можем не учитывать - в этом случае UGENE не позволяет в принцпе редактировать имя объекта. Что за валидатор имеется ввиду я не понял. Предлагается прикрутить какой-то валидатор, который будет проверять валидность имени? Окей, это просто вариация оформления изменения имени, но основной вопрос "от чего этот валидатор будет зависеть?" остался открытым. От формата файла? От типа объекта (`MSAObject`, `U2SequenceObject` и т.д.)?

И да, имя объекта редактируется не через отдельный диалог, а нативно прямо в дереве.

> Предложенное в этом PR решение общее для Sequence из любого формата не подходит.

Я не понимаю, что не подходит и почему не подходит. Просьба четче описывать свои идеи - в данный момент ни первая, ни вторая не имеют законченной формулировки и я ума не приложу, как мне продолжить работу над этой задачей.

2024-04-11 02:35 UTC, yalgaer commented
Нужно чтобы возможность менять имя спрашивалась у формата: поддеоживает ли запись и есть ли в формате место где сохранить имя.

Далее, если формат позволяет менять имя нужно чтобы он валидировал новое имя: если будут символы которые формат не может принять и сохранить - то об этом нужно сказать пользователю

Это уже будет достаточно чтобы закрыть задачу.

2024-04-11 06:21 UTC, DmitriiSukhomlinov commented
> Нужно чтобы возможность менять имя спрашивалась у формата: поддеоживает ли запись и есть ли в формате место где сохранить имя.
> 
> Далее, если формат позволяет менять имя нужно чтобы он валидировал новое имя: если будут символы которые формат не может принять и сохранить - то об этом нужно сказать пользователю
> 
> Это уже будет достаточно чтобы закрыть задачу.

Так, хорошо, то есть решение то же самое, что я предлагал в начале, за исключением того, что я предлагал вынести это в отдельную задачу, а ты предлагаешь сделать в этой. Окей, потребуется чуть больше времени, но я сделаю.

2024-04-12 04:09 UTC, yalgaer commented
Хорошо.

2024-04-16 07:07 UTC, DmitriiSukhomlinov commented
Временно закрою PR, т.к. в данный момент занят другой задачей, продолжу, как будет время

2024-04-16 07:07 UTC, closed without merging