UGENE-8067 UGENE can't open GTF that it wrote itself
ugeneunipro/ugene pull request #1603
Opened 2024-04-08 09:09 UTC by DmitriiSukhomlinov

В генбанк формате коммент может писаться в несколько строк, если длинный. По каким причинам перенос строки сохранили при парсинге не очень ясно, заменил на пробел

2024-04-09 03:32 UTC, yalgaer requested changes

2024-04-09 03:32 UTC, yalgaer commented on tests/cmdline/common/annotations/export_annotations_03.xml
> +            out="!tmp_data_dir!export_annotations_03.gbk"/>
расширение выходного файла должно быть gtf?

2024-04-09 03:32 UTC, yalgaer commented on src/corelibs/U2Formats/src/GenbankPlainTextFormat.cpp
> +                st->entry->tags[DNAInfo::COMMENT] = st->entry->tags[DNAInfo::COMMENT].toStringList() << commentSection.join(" ");
Почему то, как читается DNAInfo::COMMENT в формате Genbank влияет на правильность записи в GTF?

Если GTF не поддерживает multi-line comments нужно проверять/исправлять это прямо в формате GTF, так как источником комментариев может быть не только формат Genbank.

2024-04-09 06:04 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/GenbankPlainTextFormat.cpp
> +                st->entry->tags[DNAInfo::COMMENT] = st->entry->tags[DNAInfo::COMMENT].toStringList() << commentSection.join(" ");
Квалификаторы тоже не поддерживают мульти-лайн комменты, почему мы тут тогда их сохраняем? С моей точки зрения, корень ошибки здесь, в записьс GTF уже последствия. Я могу, конечно, подправить это на уровне GTF. если считаешь, что так правильнее

2024-04-09 07:26 UTC, DmitriiSukhomlinov commented on tests/cmdline/common/annotations/export_annotations_03.xml
> +            out="!tmp_data_dir!export_annotations_03.gbk"/>
Опечатка, поправил

2024-04-10 04:06 UTC, yalgaer commented on src/corelibs/U2Formats/src/GenbankPlainTextFormat.cpp
> +                st->entry->tags[DNAInfo::COMMENT] = st->entry->tags[DNAInfo::COMMENT].toStringList() << commentSection.join(" ");
Да если в GTF пришел multi-line комментарий из любого источника - нужно чтобы GTF сам с этим справлялся.

Надо ли в Genbank объединять multiline комментарии в одну строку - это другой вопрос, но я не против того чтобы объединить в 1 строку.

2024-04-10 06:36 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/GenbankPlainTextFormat.cpp
> +                st->entry->tags[DNAInfo::COMMENT] = st->entry->tags[DNAInfo::COMMENT].toStringList() << commentSection.join(" ");
OK

2024-04-11 02:35 UTC, yalgaer commented
Замечаний нет, апрув после тестов.

2024-04-11 12:23 UTC, DmitriiSukhomlinov commented
Все тесты прошли, несколько случайных падений

2024-04-12 04:10 UTC, yalgaer approved these changes

2024-04-12 04:45 UTC, merged