Ugene 7747
ugeneunipro/ugene pull request #1619
Opened 2024-05-02 03:20 UTC by DmitriiSukhomlinov

Пока что не готово, в PR удобнее изменения смотреть

2024-05-08 07:18 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/GUITestBasePlugin.cpp
> -    REGISTER_TEST(GUITest_regression_scenarios::test_2375);
Тест удален, т.к. новый samtools спокойно съедает файл с некорректным cigar

2024-05-08 07:20 UTC, DmitriiSukhomlinov commented on tests/genome_aligner/workflow/test_0007.xml
> -<multi-test>
В данном тесте проверялось равенство длин сборок в то время как входные файлы были пустые. Алгоритм открытия SAM файла был немного изменен и теперь в случае, если на вход приходит пустой файл появляется соответствующая ошибка, поэтому, в данном тесте больше нет смысла.

2024-05-08 10:48 UTC, DmitriiSukhomlinov commented on tests/cmdline/common/filter_bam/test_0004.xml
> -    <compare-sam-by-length file1="bam_filter_test_0004.sam" file2="cmdline/filter_bam/out4.sam"/>
Этот тест и тест ниже были некорректными. SAM и BAM файлы содержат состоят из двух частей - заголовок и набор ридов. У BAM файла всегда есть обе эти части, SAM файл может не содержать заголовок. В UGENE есть некоторый механизм автоматической генерации заголовка, если он отсутствует у SAM файла. В этой задаче я его существенно допилил и теперь он работает хорошо, однако, до этого он работал плохо и, зачастую, выделял память под объект заголовка, но не заполнял её никакими данными. Здесь происходит как раз это и в итоге сравниваются два пустых указателя. После того, как я научил UGENE правильно генерировать заголовок SAM файла, оказалось, что у этого теста и теста ниже вообще некорректный результат для сравлнения (длины сборок не равны).

2024-05-08 10:52 UTC, DmitriiSukhomlinov commented on tests/cmdline/common/simple/conversion/test_0005.xml
> +    <compare-docs doc1="cmdline/conversion/scerevisiae.sam_2.bam"
При преобразовании SAM в BAM новая версия Samtools генерирует BAM, немного отличающийся от того, что генерился раньше (с точки зрения побайтового сравнения). При открытии в UGENE разницы между получившимися файлами нет.

2024-05-08 10:59 UTC, DmitriiSukhomlinov commented on tests/regression/6802/test_0001.xml
> -<multi-test>
Этот тест написан на неверно выполненнную задачу. В UGENE-6802 вылазил `SAFE_POINT` при экспорте покрытия из-за того, что длина  вполне корректной сборки в какой-то момент в коде получалась равной нулю. Правильным решением было разобраться, почему так происходит и сделать так, чтобы выставлялась реальная длина сборки вместо нулевой. В решении задачи `SAFE_POINT` просто заменили на `CHECK`. При этом, результатом экспорта становился пустой файл, т.е. экспорт покрытия в дальнейшем просто прерывался и никто не обратил на это внимания.

В данной задаче было исправлено корректное определение длины сборки во всех случаях, поэтому, я вернул исходный `SAFE_POINT`, проверяющий факт того, что эта длина больше нуля. Данный тест удаляется за некактуальностью

2024-05-08 11:04 UTC, DmitriiSukhomlinov commented on tests/unit_tests/ApiTest/util/BAMUtils.xml
> +    + convertBamToSam
Все тесты на данную задачу написаны здесь и представляют из себя Unit-тесты на утилитный класс `BAMUtils`. Исправления в остальных местах несущественны, т.к. в подавляющем большинстве случаев они представляют из себя просто синтаксические изменения (та или иная структура теперь называется по-другому).

2024-05-08 11:25 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_assembly/CalculateCoveragePerBaseTask.cpp
> +    SAFE_POINT_EXT(lengthAttribute.value > 0, setError(tr("Assembly length must be greater than zero")), );
См [этот](https://github.com/ugeneunipro/ugene/pull/1619/commits/0b40d792b7fff1bad362fe75f7e6230b37c51810#r1593842834) комментарий

2024-05-08 11:28 UTC, DmitriiSukhomlinov commented on src/libs_3rdparty/samtools/samtools.pri
> +unix : DEFINES += HAVE_DRAND48
Samtools использует какие-то функции рандомизации, которые в unix присутствуют, а в винде отсутствуют и реализованы в `rand.c`

2024-05-08 11:51 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Formats/src/BAMUtils.cpp
> -    if (!result) {
В новой версии это поправили

2024-05-13 07:59 UTC, DmitriiSukhomlinov commented on tests/cmdline/common/filter_bam/test_0005.xml
> -<multi-test>
В данном тесте проверялось равенство длин сборок в то время как входные файлы были пустые. Алгоритм открытия SAM файла был немного изменен и теперь в случае, если на вход приходит пустой файл появляется соответствующая ошибка, поэтому, в данном тесте больше нет смысла.

2024-05-13 08:28 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_assembly_consensus/AssemblyConsensusAlgorithmSamtools.cpp
> +            qsum[i] = (int)bcr.qsum[i] << 2 | i;
Здесь действительно просто кастуется к `int`, см [оригинал](https://github.com/samtools/samtools/blob/95f542664b73060d81c8b6f424e6d9243d41a191/bam_tview.c#L197)

2024-05-13 08:37 UTC, DmitriiSukhomlinov commented on src/libs_3rdparty/samtools/src/SamtoolsAdapter.cpp
> -    resRead.l_aux = aux.length();
Такого поля больше нет, но это значение теперь умеет вычисляться на месте, так что хранить его больше не нужно

2024-05-13 10:44 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/BAMDbiPlugin.cpp
> +        if (useGui) {
Баг, который я обнаружил и который долго был в UGENE. Когда мы импортируем SAM/BAM в базу, мы можем выбрать, какие именно скаффолды импортировать. Эта информация запишется в определенный объект `bamInfo`. Если у нас будет несортированый файл, то он проссортируется (т.к. проиндексировать можно только сортированый BAM/SAM) и у него при экспорте появляется уже свой `bamInfo`, который не знает, что мы выбрали в диалоге и имеет настройки по-умолчанию со всеми скаффолдами. Добавил гуи тест на это.

2024-05-13 10:47 UTC, DmitriiSukhomlinov commented on src/plugins/dbi_bam/src/SamtoolsBasedDbi.cpp
> +static int bam_fetch(samFile* fp, const hts_idx_t* idx, int tid, int beg, int end, void* data, bam_fetch_f func) {
Этой функции в samtools больше нет и аналога я найти не смог, поэтому, просто добавил ее.

2024-05-16 01:47 UTC, DmitriiSukhomlinov commented
@yalgaer на всякий случай дополнительно напишу, что ревью можно смотреть

2024-05-16 23:36 UTC, yalgaer requested changes
Начала тестировать. Файл _common_data/bam/scerevisiae.bam3.sam в мастере открывается в твоей ветке нет. Возможно регрессия.

2024-05-17 07:35 UTC, DmitriiSukhomlinov commented
> Начала тестировать. Файл _common_data/bam/scerevisiae.bam3.sam в мастере открывается в твоей ветке нет. Возможно регрессия.

Я полагаю, что ты не обновила тестовый репозиторий. Это стоит сделать, т.к. мне пришлось обновить некоторые файлы, т.к. они отказывались обрабатываться новой версией samtools из-за того, что не соответствовали спецификации формата.

Конкретно - SAM/BAM файлы делятся на две часть - заголовок и риды. Если ты откроешь `_common_data/bam/scerevisiae.bam3.sam` в текстовом редакторе, то ты это легко увидишь (зеленый - заголовок, красный - риды):
![image](https://github.com/ugeneunipro/ugene/assets/26257527/47a2eea1-119a-489f-b0f9-3f5d15f8a211)

Проблема возникала в заголовке.  Каждая строка заголовка, содержит в себе несколько тегов типа **ключ:значение**, а сами тэги разделяются табами. В третьей строке заголовка есть команда запуска, в которой аргументы, в старой версии этого файла, тоже были разделены табами, хотя в значениях тэга табы использовать нельзя, только пробелы. Это четко описано в [спецификации формата](https://samtools.github.io/hts-specs/SAMv1.pdf). В пункте **1.3 The header section** в самом первом абзаце прописаны два регулярных выражения и каждая из строк заголовка должна соответствовать одному из них. В нашем случае нас интересует первое регулярное выражение:

`/^@(HD|SQ|RG|PG)(\t[A-Za-z][A-Za-z0-9]:[ -~]+)+$/`

Старая версия samtools проглатывала этот косяк в файле, однако, у новой исполнение прерывается с соответствующей ошибкой "Malformed key:value pair" вот [в этом месте](https://github.com/ugeneunipro/ugene/blob/21955e16967c2c35ceea44fa0cca69bd23ac8d0c/src/libs_3rdparty/samtools/src/samtools_core/header.c#L876C54-L876C62). Я считаю, что будет правильным согласится с новой версией samtools, т.к. это правильный формат, не противоречащий спецификации, а исправления в значимой части кода могут привести к непредсказуемым последствиям. 

Единственное - я когда заменял табы на пробелы в этих местах сделал это только для файлов, используемых в тестировании. Если в тестовом репозитории есть файлы, не учавстующие в тестировании, но содержащие подобную проблему, то они могут быть не поправлены.

2024-05-17 13:04 UTC, yalgaer commented
Есть другая большая проблема с патчем: чтобы поддержать регулярные выражения на windows ты включил в наш исходный код большую бибилиотеку, которая превышает размер всех samtools и содержит полноценный JIT компилятор (сравни: старый samtools ~10k строк, новый ~200k - различие в 20 раз!).

Это перебор, так как QT уже поддерживает perl-compatible regular expressions да и сам samtools использует их очень ограниченно в выделенном месте.

Нужно убрать эту гигансткую зависимость из нашего будущего и попробовать использовать регулярные выражения из QT. 

Наследние подобных гигантских зависимостей крайне нежелательно для UGENE: их придется поддерживать и решать их проблемы. Сам же samtools не имеет этой зависимости - это наша врезка в его код.

Возможно в рамках нашего использования samtools нам нужно очень ограниченное использование reg-exp: на уровне одной или двух функций работы со строками.

2024-05-20 09:15 UTC, DmitriiSukhomlinov commented
> Есть другая большая проблема с патчем: чтобы поддержать регулярные выражения на windows ты включил в наш исходный код большую бибилиотеку, которая превышает размер всех samtools и содержит полноценный JIT компилятор (сравни: старый samtools ~10k строк, новый ~200k - различие в 20 раз!).
> 
> Это перебор, так как QT уже поддерживает perl-compatible regular expressions да и сам samtools использует их очень ограниченно в выделенном месте.
> 
> Нужно убрать эту гигансткую зависимость из нашего будущего и попробовать использовать регулярные выражения из QT.
> 
> Наследние подобных гигантских зависимостей крайне нежелательно для UGENE: их придется поддерживать и решать их проблемы. Сам же samtools не имеет этой зависимости - это наша врезка в его код.
> 
> Возможно в рамках нашего использования samtools нам нужно очень ограниченное использование reg-exp: на уровне одной или двух функций работы со строками.

Я не уверен, что сделать samtools, написанный на C, зависимым от Qt, написанном на C++,  в принципе возможно, но это, в целом, не так уж и важно в нашем случае. Я поисследовал код и пришел к выводу, что регулярные выражения в samtools используются только для проверки того, что те или иных данные входного рида соответствуют определенному регулярному выражению. Мы не используем этот функционал и, однозначно, не планируем, поэтому я аккуратно вырезал регулярные выражения и все с ними связанное.

2024-05-20 10:08 UTC, DmitriiSukhomlinov commented on tests/regression/6802/test_0001.xml
> -<multi-test>
Я вернул этот тест, подправив его, чтобы он исполнялся, получал корректный реультат и сравнивал его с результатом из репозитория

2024-05-21 07:00 UTC, yalgaer commented
Хорошо, патч в итоге сократился в 2 раза.
Еще пару вопросов/замечаний:

1) Предлагаю не смешивать код htslib и samtools. htslib может лежать в подпапке и повторять оригинальный набор файлов - будет сразу видно что и откуда. Код для этого менять не придется - достаточно расширить INCDIR

2) Код все еще в 10 раз больше того, что был. Можно ли сохранив оригинальную структуру проектов samtools убрать все ненужные файлы/зависимости?

2024-05-21 09:04 UTC, DmitriiSukhomlinov commented
> Хорошо, патч в итоге сократился в 2 раза. Еще пару вопросов/замечаний:
> 
> 1. Предлагаю не смешивать код htslib и samtools. htslib может лежать в подпапке и повторять оригинальный набор файлов - будет сразу видно что и откуда. Код для этого менять не придется - достаточно расширить INCDIR

ОК

> 2. Код все еще в 10 раз больше того, что был. Можно ли сохранив оригинальную структуру проектов samtools убрать все ненужные файлы/зависимости?

Можно попробовать выкинуть pthread, но это потребует существенных изменений в исходном коде samtools, Я не даю гарантий, что не добавлю скрытых багов, делая это.

2024-05-22 07:42 UTC, DmitriiSukhomlinov commented
Тесты на винде попадали из-за того, что там вылез диалог "Указать время для рестарта для обновления"

2024-05-22 13:47 UTC, yalgaer commented
Давай перезапустим винду и как будет зеленая я дам апрув

2024-05-24 06:39 UTC, DmitriiSukhomlinov commented
@yalgaer все тесты пройдены

2024-05-25 06:00 UTC, yalgaer approved these changes

2024-05-27 00:17 UTC, merged