UGENE-7267 Can't save sequence name change
ugeneunipro/ugene pull request #1625
Opened 2024-05-20 12:46 UTC by DmitriiSukhomlinov

Проверил все форматы и все типы объектов. Если у объекта есть возможность модифицировать имя и это можно сохранить внутрь файла, соответствующего данному объекту, то объект можно переименовать (после переименования объект будет подсвечен синим) и сохранить. Если нет - то имя объекта все равно будет изменено (но не подсвечено синим), а внизу появится нотификация с ворнингом и сообщением типа "Мы переименовали обьект, но данный формат не поддерживает запись этих данных".

Какие форматы можно сохранить:

- FASTA
- Genbank
- GFF
- GTF
- BED
- FASTQ

Какие нельзя:

- SEQ
- Все форматы выравнивания
- VCF
- TEXT
- Newick

Остальные форматы read-only, у них имя вообще нельзя поменять.

2024-05-21 07:15 UTC, yalgaer requested changes

2024-05-21 07:15 UTC, yalgaer commented on src/corelibs/U2Core/src/gobjects/PhyTreeObject.cpp
> +    emit si_failedModifyObjectName();
Почему здесь сразу fail? fail или не fail зависит от формата записи но не от типа объекта

2024-05-21 07:15 UTC, yalgaer commented on src/corelibs/U2Core/src/gobjects/AnnotationTableObject.cpp
> +    // but it is not connected to document yet
Все строки кода ниже должны пойти в общее место в GObject.
Возможно это расширит сигнатуру setGObjectName, но это является общим поведением для всех типов объектов

2024-05-21 07:50 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/gobjects/PhyTreeObject.cpp
> +    emit si_failedModifyObjectName();
У нас дерево хранится только в одном формате. Я могу сюда добавить развязку, аналогичную той, что у нас используется для `U2SequenceObject`:
    
```
    if (doc->getDocumentFormat( )->hasModifiableName()) {
        setModified(true);
    } else {
        emit si_failedModifyObjectName();
    }
```

Но ветка `setModified(true);` никогда не отработает

2024-05-21 09:34 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/gobjects/AnnotationTableObject.cpp
> +    // but it is not connected to document yet
Ок

2024-05-21 09:44 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/gobjects/MsaObject.cpp
> -    } else {
Не очень понял логику старого кода - если документ залочен, то изменить ему имя нельзя в принципе. А если не залочен, то не ясно, почему у него не меняется имя.

2024-05-22 13:58 UTC, yalgaer commented on src/corelibs/U2Core/src/gobjects/PhyTreeObject.cpp
> +    emit si_failedModifyObjectName();
Если завтра добавится новый формат хранения деревьев? 
Более того, даже сейчас деревья могут храниться в разных форматах

2024-05-22 14:02 UTC, yalgaer requested changes

2024-05-22 14:02 UTC, yalgaer commented on src/corelibs/U2Core/src/gobjects/MsaObject.cpp
> +        if (type == GObjectTypes::MULTIPLE_SEQUENCE_ALIGNMENT) {
Проверка не должна зависеть от типа объекта - это свойство формата записи.

2024-05-22 14:02 UTC, yalgaer commented on src/corelibs/U2Core/src/models/DocumentModel.h
> +    virtual bool hasModifiableName() const;
Не нужно добавлять новый метод который нужно будет реализовывать много раз. Достаточно ввести новый флаг: DocumentFormatFlags

2024-05-22 14:02 UTC, yalgaer commented on src/corelibs/U2Core/src/models/GObject.h
> +    void si_failedModifyObjectName();
Нужна документация когда это происходит

2024-05-23 08:59 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/gobjects/PhyTreeObject.cpp
> +    emit si_failedModifyObjectName();
Ок, в любом случае, я перенс это в базовый класс

2024-05-23 09:12 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/gobjects/MsaObject.cpp
> +        if (type == GObjectTypes::MULTIPLE_SEQUENCE_ALIGNMENT) {
По хорошему - да, но, по факту, у нас множественное выравнивание не ведет себя как обычный `GObject`, когда мы собираемся менять имя объекта. В данной ветке у нас в принципе не отрабатывает `GObject::setGObjectName(...)`, а используется некий кастомный механизм переименования. Откровенно говоря, сделано кривовато - это как если базовый класс **транспортное средство на колесах**, наследник **автомобиль**, а мы отрезали базовый класс и получили в итоге это:
![image](https://github.com/ugeneunipro/ugene/assets/26257527/e6e86ab9-426d-4ae1-ac0f-63949406842a)


По хорошему, нужно каким-то образом рефакторить этот кусок, чтобы оно встроилось в общий механизм изменения имени. Я попатался, но с наскока у меня не вышло. Делать в этой задаче или унести в отдельную? В этой может оказаться заковыристо.

2024-05-23 10:05 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/models/GObject.h
> +    void si_failedModifyObjectName();
OK

2024-05-23 10:05 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/models/DocumentModel.h
> +    virtual bool hasModifiableName() const;
OK

2024-05-23 19:41 UTC, yalgaer commented on src/corelibs/U2Core/src/gobjects/MsaObject.cpp
> +        if (type == GObjectTypes::MULTIPLE_SEQUENCE_ALIGNMENT) {
Можно добавить TODO и описать проблему в баге если сделать это влет и сразу не выходит

2024-05-23 19:43 UTC, yalgaer commented
Замечаний нет, апрув после тестов

2024-05-24 07:01 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/gobjects/MsaObject.cpp
> +        if (type == GObjectTypes::MULTIPLE_SEQUENCE_ALIGNMENT) {
Унес в отдельную задачу, постараюсь заняться ей в ближайшее время

2024-05-27 02:37 UTC, DmitriiSukhomlinov commented
Все тесты прошли кроме нестабильного 6802

2024-05-27 07:49 UTC, yalgaer commented
Если после заливки samtools он стал стабильным надо смержится и перезапустить

2024-05-29 07:59 UTC, DmitriiSukhomlinov commented
Все прошло, кроме одного не связанного с данной фичей теста на винде (полагаю, случайное падение).

2024-05-29 18:09 UTC, yalgaer approved these changes

2024-05-29 20:50 UTC, yalgaer requested changes
У этого теста всего два падения в истории и одно из них текущее. Прогони ещё раз тесты на винде, чтобы убедиться, что падение случайное.

2024-05-31 01:41 UTC, DmitriiSukhomlinov commented
Все тесты прошли, предыдущее падение было вызвано нестабильностью

2024-06-02 18:58 UTC, yalgaer approved these changes

2024-06-03 01:24 UTC, merged