Ugene 6929
ugeneunipro/ugene pull request #163
Opened 2020-12-23 11:38 UTC by rasputinkirill

2020-12-23 12:18 UTC, DmitriiSukhomlinov requested changes
The most part of the breakpad has been written by Google so I  have check code very briefly. I'm more interested in the compatibility of the new breakpad and our scripts. Please, build the release version of the current brunch, crash it, send a report and leave the comment with the corresponding report number here. Do it for all OS.

2020-12-23 12:20 UTC, rasputinkirill commented
> Do it for all OS.

Already done. Everything seems to be in order.

2020-12-23 23:16 UTC, yalgaer approved these changes

2020-12-24 04:16 UTC, DmitriiSukhomlinov approved these changes

2020-12-24 04:37 UTC, merged