UGENE-8101 Add "Exclude enzymes found in the exclude region" feature
ugeneunipro/ugene pull request #1632
Opened 2024-06-05 20:42 UTC by rasputinkirill

2024-06-06 06:17 UTC, yalgaer commented
Это плохое техническое решение и вот почему.

На данный момент диалог работы с энзимами и так переусложнен: на первый план вынесен редко нужный функционал, который заслоняет то, что нужно всегда.

То, как в этом диалоге развивается выбор региона - это хороший пример, когда делается минимальное изменение вместо правильного (возможно большего по размеру), что приводит в итоге к плохому результату типа "Exclude enzymes found in exclude region".

![image](https://github.com/ugeneunipro/ugene/assets/17791039/d04a17e8-9a61-4c90-a1b9-b006c87518a3)

Как сделать правильно: вместо того, чтобы добавлять все новые и новые одноразовые (используемые только здесь) опции выбора региона нужно правильно использовать идею region selector widget: 

В region selector есть опции:
1 Вся последовательность
2 Custom region
3 Selected region

Selected регион в данном случае может быть сложным (список регионов) так как он может браться из покрытия любой аннотации: выделил аннотацию -> получил selected region.

Более того, selected region опцию в region selector можно развить, когда диапазон задается руками: в виде location string - это тоже будет multi-region, уже без необходимости использования аннотации.

Итого: 
1. Направление решение выбрано плохо с точки зрения UI (биологическую часть я не критикую) 
2. Нужно правильно использовать/доразвить region selector и от этого будет выгода всем местам где он используется в UGENE.

2024-06-18 15:15 UTC, yalgaer commented
Закрываю до обновления

2024-06-28 07:22 UTC, rasputinkirill commented
@yalgaer  Переделал гуи, посмотри устраивает или нет.
Есть еще проблемы которые попаравлю - трансляции, гуи тест, возможно xml тесты придется переписать.
Вопрос: должно ли наличие селекшена в сиквенсе как то учитываться создании диалога, то есть должен ли автоматически координаты селекшена заполнить регион поиска. Потому что сейчас мы заполняем настройки запомненными данными из прошлого запуска таски дял этого сиквенс обджекта (либо значениями по умолчанию). Должны ли координаты селекшена "перебить" эти координаты или нет? Либо вообще игнорируем наличие селекшена на сиквенсе?

2024-06-30 01:19 UTC, yalgaer commented
> Вопрос: должно ли наличие селекшена в сиквенсе как то учитываться создании диалога, то есть должен ли автоматически координаты селекшена заполнить регион поиска. 

Я бы сделала это одной из опций регион-селектора: если есть selection то показывать опцию "Selection" которая не модифицируется пользователем напрямую

2024-06-30 01:40 UTC, yalgaer requested changes
Это не то что нужно:
![image](https://github.com/ugeneunipro/ugene/assets/17791039/13db6bf0-71f7-4e4c-a456-a5121095224d)


Вот что нужно:
1. Удалить класс RegionSelectorWithExcludedRegion вовсе
2. Расширить RegionSelectorGui
 - Добавить в него новый preset: location в формате genbank
 - Сделать этот пресет выключенным по умолчанию - так мы не потревожим другие места использования
 - Когда он включен то startLineEdit и endLineEdit должны заменяться на новый lineEdit в котором будет location.
 - RegionSelectorController должен распознавать этот режим и правильно доставать location из него

2024-07-03 10:41 UTC, rasputinkirill commented
Переделал. Добавил опцию LOCATION в текущий виджет. Пойдет так?
Как поступаем теперь с новым функционалом, добавляем еще один такой виджет с чекбоксом Excleded?

2024-07-04 00:56 UTC, yalgaer commented
> Переделал. Добавил опцию LOCATION в текущий виджет. Пойдет так? 

Начинаю смотреть, добавлю ревью в течение дня.

> Как поступаем теперь с новым функционалом, добавляем еще один такой виджет с чекбоксом Excleded?

А почему одного виджета не хватит: пусть выберут формат с ручным вводом location и напишут там любой join?

2024-07-04 03:37 UTC, rasputinkirill commented
>А почему одного виджета не хватит: пусть выберут формат с ручным вводом location и напишут там любой join?

Ох вроде ж раза два уже обсуждали. Нужно поле в котором задается регион(ы) в найденные в котором(ых) энзимы будут исключены из результатов. Это собственно и есть реализованная фича. В одном поле поиска ты это никак не закодируешь.

2024-07-04 16:55 UTC, yalgaer commented
> Ох вроде ж раза два уже обсуждали. Нужно поле в котором задается регион(ы) в найденные в котором(ых) энзимы будут исключены из результатов. Это собственно и есть реализованная фича. В одном поле поиска ты это никак не закодируешь.

Именно, что обсуждали: если в последовательности 1..1000 надо исключить энзимы располагающиеся в регионе 100.200 то достаточно используя region selector задать location: 1..100,200..1000

Возможно, я не помню какой-то другой вариант, который на самом деле не возможен, так как задача сильно затянулась по времени. Напомни, пожалуйста.

2024-07-05 02:07 UTC, yalgaer reviewed
По коду замечаний нет, кроме того, что надо доделать все TODO

Excluderegion нужно убреть как из селектора так и из FindEnzymesTask

2024-07-05 03:57 UTC, rasputinkirill commented
> Именно, что обсуждали: если в последовательности 1..1000 надо исключить энзимы располагающиеся в регионе 100.200 то достаточно используя region selector задать location: 1..100,200..1000

Например если у нас одно поле ввода формата genbank location и мы хотим поискать энзимы в двух регионах  1..100,200..300, но исключить из результатов энзимы найденные в 50..70 то мы не сможем закодировать это в одной строке. А если регионы указаны не с начала последовательности и не до конца последовательности как поступать с этими кусками? Мы не можем в таком случае указать хотим мы исключать найденные там энзимы или это области где вообще не производить поиск.

Если делать по твоему то область поиска энзимов всегда один непрерывный отрезок, а если в нем разрывы - то это области всегда области исключения.
Мне кажется это не так задумывалось. @DmitriiSukhomlinov прокомментируй пожалуйста.
Плюс если так делать то всеравно мы должны ввести какойто чекбокс или радиокнопку чтобы указать области пропусков это области пропуска поиска или области исключений найденных результатов.

Опять же повторю, если бы у нас не было нового функционала "исключить энзимы найденные в указанном(ых) регионе(ах)". Мы могли бы использовать всего лишь одно поле ввода в котором в формате genbank location можно указать раздробленную область поиска. То теперь в случае применения новой фичи мы должны указать область(и) исключения энзимов найденных в них.

2024-07-05 05:39 UTC, DmitriiSukhomlinov commented
Прочитал, чтот тут было. Если честно, я не очень понял, как предполагаемое изменение графического интерфейса помогает адаптировать графический интерфейс под цели данной задачи. Дальше я постараюсь описать суть - что мы вообще делаем - т.к. у меня есть ощущение того, что именно эта суть осталась не совсем понятной, из-за чего лезут не самые удачные предложения. Просьба разобраться в написаном, прежде чем продолжать обсуждение, я постарался описать все максимально простым языком, но коротко тут никак.

Основная идея региона Exclude состоит в том, чтобы подбирать сайты рестрикции вне некоего фрагмента. Это нужно, если у нас есть некая последовательность, которую мы хотим проклонировать (назовем её целевой - собственно, так её обычно и называют), которая является частью другой, большой последовательности и для проведения реакции нам нужно целевую последовательность вырезать из большой. Поскольку настолько маленьких ножниц еще не изобрели, для решения этой задачи пользуются сайтами рестрикции. Сайт рестрикции представляет из себя короткую последовательность, на которую налипают определенные ферменты и режут сайт в заранее известном месте.

Таким образом, чтобы вырезать целевую последовательность, мы берем небольшие области слева и справа от целевой последовательности и ищем в них подходящие нам сайты рестрикции (подходящие - это, условно, те, которые есть на складе), по которым можно осуществить разрез. В UGENE мы находим подходящий нам сайт в подходящем месте (как можно ближе к целевой последовательности), а потом проводим реацию IRL.

Таким образом, в рамках нашего текущего графического интерфейса, в область Exclude необходимо задать именно регион целевой последовательности, что достаточно удобно. А общий регион должен влючать небольшие кусочки по краям, где мы и ищем сайты, чтобы осуществить разрез.

И тут, нам ткнули пальцем на самый настоящий баг - только не програмистский, а биологический. А что если сайт рестрикции, который мы решим использовать для разреза, будет содержаться не только в краевых облоастях, но и в самой целевой последовательности? Тогда, во время реакции фермент прилипнет где-то внутри неё и в итоге мы уже получим не одну длинную целевую последовательнось, которая нам необходима, а несколько кусочков. Соответственно, данная задача направлена на решение данной проблемы.

Каким образом я планировал решить эту проблему - добавить галочку, при выделении которой поиск будет осуществляться новым алгоритмом, которые не отображает сайты рестрикции, если они есть в Exclude регионе (то бишь, в регионе целевой последовательности). Поскольку текущий поиск, когда регион Exclude просто не участвует в поиске, априори может привести к ошибкам, то мне изначально посоветовали вообще его убрать и при использовании Exclude региона **всегда** проводить поиск, исключая сайты, найденные в Exclude. Поскольку я всегда стараюсь сохранять совместимость с уже существующим функционалом, я решил все-таки оставить его, а новый алгоритм вынести на отдельную галочку.

Теперь, когда нам всем понятно, что и зачем происходит, первым делом стоит задать вопрос - зачем вообще мы изменяем графический интерфейс? 

Во первых, текущий селектор региона достаточно функционален и, более того, каждое его поле имеет определенный смысл, который можно трактовать именно с биологической точки зрения. Замена данного интерфейса уберет это преимущество. Появится возможность выделять сколько угодно регионов, но но она не имеет никакого смысла в контексте данной функци.

Во-вторых, изменение графического интерфейса никаким образом не улучшает его с точки зрения данной задачи, а наоборот, ухудшает.  Допустим, у нас есть последлвательность длиной 100 нукледотидов, мы выбираем в качестве региона поиска 20-80, а в качестве региона Exclude - 30-70. Текущий интерфес подразумевает, что, в контекстве данной функции, у нас есть три типа регионов:

1. вообще не участвующие в поиске (0-20 и 80-100); 
2. те, где мы ищем сайты рестрикции (20-30 и 70-80);
3. и Exclude регион, то бишь целевая последовательность, где мы ищем сайты, которые мы исключим из результата (30-70).

Изменение графического интерфеса объединяет группы 1 и 3 и становится не понятно, каким образом их отличить.

Поэтому, я предлагаю следующее:

- мы не трогаем графический интерфейс диалога сайтов рестрикций в этой задаче вообще,
- если выбран регион Exclude, то мы **всегда** используем новый алгоритм, который исключает не регион, а найденные в нем сайты рестрикции.

2024-07-05 14:34 UTC, yalgaer commented
Краткость сестра таланта. А наоборот как будет?

>Допустим, у нас есть последлвательность длиной 100 нукледотидов, мы выбираем в качестве региона поиска 20-80, а в качестве региона Exclude - 30-70

Достаточно выбрать регион поиска 20-30..70.80 - четко и понятно что это 2 края.

Но с новым функционалом можно вообще не печатать цифры:

Можно выделить функциональные регионы мышкой и тогда текущее выделение будет автоматически подставлено в регион поиска.

Выделение может быть основано на выделенных аннотациях: если есть логически осмыслленный регион пользователю стоит начать с его аннотирования: gene, orf, cdf, target-region-for-enzymes: после этого кликнуть на аннотацию и искать энзимы выбрав регион поиска  = selection.

Именно так надо учить пользоваться UGENE - используя имеющийся функционал, а не создавая одноразовые решения в каждом виджете.

2024-07-05 15:30 UTC, rasputinkirill commented
Делаю такую логику: если выбрана опция задания региона поиска genbank location и она содержит несколько регионов, то не включенные между самой левой и самой правой координатой рассматриваем как места энзимы из которых исключаются.
Старую опцию Exclude выкидываем из алгоритма, работаем только с новой.
Я правильно понял?

2024-07-05 15:39 UTC, yalgaer commented
> Делаю такую логику: если выбрана опция задания региона поиска genbank location и она содержит несколько регионов, то не включенные между самой левой и самой правой координатой рассматриваем как места энзимы из которых исключаются. 

Я бы сказала проще: запускаем поиск энзимов только на выбранных регионах.


> Старую опцию Exclude выкидываем из алгоритма, работаем только с новой. Я правильно понял?
Да, она избыточна

2024-07-05 16:58 UTC, yalgaer commented
> Делаю такую логику: если выбрана опция задания региона поиска genbank location и она содержит несколько регионов, то не включенные между самой левой и самой правой координатой рассматриваем как места энзимы из которых исключаются. Старую опцию Exclude выкидываем из алгоритма, работаем только с новой. Я правильно понял?

Я кажется поняла, что было проблемой моего понимания текущего UI.

Если мы нашли на промежутке 1...100 энзимы A (1), B(2), B(50), A(98) и B(99) и хотим быть уверенны что у нас в результате разреза сохранится регион 10..90 то в результатах не должно быть B, так как он может отрезать по позиции 50.

Думаю та же проблема с пониманием UI есть и у пользователей и нужно придумать как сделать UI прозрачным.

Поэтому соглашусь, что второй region selector нужен.

Его стоит назвать [x] Uncut Region  и добавить тултип о том что это значит:

"A region that will not be cut by any of the found enzymes. If an enzyme is present in this region, it will be excluded from the flank results."

Что делать с алгоритмом: поменять его так, чтобы он работал в соотвествии с описанием в диалоге (если нужно).

2024-07-21 02:28 UTC, yalgaer requested changes

2024-07-21 02:28 UTC, yalgaer commented on src/corelibs/U2Core/src/datatype/U2Location.h
> +        data()->regions = regionList;
Реализация должна быть в CPP

2024-07-21 02:28 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/RegionSelector.cpp
> +      locationLineEdit(nullptr),
инициализируй в header (конструкторов может быть много)

2024-07-21 02:28 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/RegionSelectorController.cpp
> +    return QApplication::translate("RegionSelectorController", "Location");
Почему не RegionSelectorController:tr("...") ?

2024-07-21 02:28 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/RegionSelectorController.cpp
> +        qint64 circLen = settings.circular ? settings.maxLen : -1;
nit: пиши имена переремнных полностью

2024-07-21 02:28 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/RegionSelectorController.h
> +    static QString LOCATION();
nit: называй методы понятно: getLocationModeDisplayName или типа того.

2024-07-21 02:28 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/RegionSelectorController.h
> +    //void si_presetChanged(int index);
nit: если не нужно - удали

2024-07-21 02:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    for (const U2Region region : qAsConst(searchLocation.data()->regions)) {
добавь & ?

2024-07-21 02:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    QList<RegionPreset> searchPresets = {RegionPreset(RegionPreset::RegionPreset::LOCATION(), searchLocation)};
nit: зачем фигурные скобки? более короткая запись A a(); уже не работает?

2024-07-21 02:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    if (!advSequenceContext->getSequenceSelection()->getSelectedRegions().isEmpty()) {
nit: закешируй длинные вызовы функций в переменну и не повторяй их много раз чтобы код лучше читался.

2024-07-21 02:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    for (const U2Region region : qAsConst(excludeLocation.data()->regions)) {
копипаста цикла - стоит переиспользовать и дать имя коду (функции)

2024-07-21 02:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    bool ok2 = false;
одного 'ok' не хватит?

2024-07-21 02:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (cfg.excludeMode) {
исключать надо не здесь, а прямо FindEnzymesTask - те кто вызывает этот таск должны получать уже фильтрованный результат а не фильтровать сами

2024-07-21 02:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    for (const U2Region region : qAsConst(savedSearchRegions)) {
&

2024-07-23 11:30 UTC, rasputinkirill commented on src/corelibs/U2Core/src/datatype/U2Location.h
> +        data()->regions = regionList;
Там нет СРР, предалгаешь сделать и перенести туда все реализации включая инлайны?

2024-07-23 11:35 UTC, rasputinkirill commented on src/corelibs/U2Gui/src/util/RegionSelectorController.cpp
> +    return QApplication::translate("RegionSelectorController", "Location");
Чтобы сохранить единообразие оформления файла, еще и так не получится.
RegionPreset структура не наследова от QObject. 
Сделать ее классом, отнаследовать и внедрить tr?

2024-07-23 11:38 UTC, rasputinkirill commented on src/corelibs/U2Gui/src/util/RegionSelectorController.h
> +    static QString LOCATION();
Для сохранения единообразия оформления следует переименовать другие аналогичные методы этого класса?

2024-07-23 11:49 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    QList<RegionPreset> searchPresets = {RegionPreset(RegionPreset::RegionPreset::LOCATION(), searchLocation)};
Это ж контейнер QList, фигурные скобки показывают объект в контейнере.
Или я не понял что ты имеешь в виду.

2024-07-23 16:55 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    bool ok2 = false;
Хватит, если у нас экономия размерности булевской переменной на стеке приоритетней чем более читаемый код.

2024-07-23 17:04 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (cfg.excludeMode) {
Нет. Сначала найдя все энзимы в указанных регионах поиска.
Потом смотрим какой регион(ы) исключен(ы) и выкидываем все найденные там энзимы из результатов.

И собственно в этом месте и есть баг: когда задано несколько регионов поиска, так как этот код выполняется после каждой сабтаски, а должен выполняться после завершения всех сабтасок.

2024-07-24 08:53 UTC, rasputinkirill commented
Часть замечаний поправил, часть откомментировал.
Найденную проблему с поиском поправил.
Пишу тесты.

2024-07-25 01:20 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (cfg.excludeMode) {
Логика алгоритма должна быть следующая:

1. Если есть исключенные регионы то ищем в них уникальные имена энзимов (координаты не нужны)
2. Запускаем обычный поиск энзимов на регионе поиска только для тех энзимов, чьи имена не были найдены в пункте 1

Логика должена быть скрыта в таске который ищет энзимы, а не в таске который создает аннотации по результатам поиска.

2024-07-25 01:22 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    bool ok2 = false;
Пара имен `ok` и `ok2` - это не читаемый код, или у нас экономия размера файла в git приоритетней чем более читаемый код?

2024-07-25 01:22 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/RegionSelectorController.h
> +    static QString LOCATION();
Старый код можешь улучшать или оставить как есть. Новый нужно писать правильно

2024-07-25 01:23 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/RegionSelectorController.cpp
> +    return QApplication::translate("RegionSelectorController", "Location");
Наследовать RegionPreset от QObject не надо. Вопрос был:
```Почему не RegionSelectorController:tr(```

2024-07-25 01:24 UTC, yalgaer commented on src/corelibs/U2Core/src/datatype/U2Location.h
> +        data()->regions = regionList;
Да новые методы нужно реализовывать в С++. Нужно ли туда убирать старые которые не трогаешь - на твое усмотрение.

2024-07-25 01:24 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesDialog.cpp
> +    QList<RegionPreset> searchPresets = {RegionPreset(RegionPreset::RegionPreset::LOCATION(), searchLocation)};
ok

2024-07-25 07:24 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (cfg.excludeMode) {
Ты предлагаешь запускать в итоге большее количество тасок по поиску - количество включенных в поиск регионов + количество исключенных. В моем варианте количество тасок - только количество включенных регионов, а потом фильтрация итерируясь уже по результатам поиска. Мне кажется мой вариант с меньшим количеством тасок будет попроизводительней.

2024-07-25 14:47 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (cfg.excludeMode) {
И в твоем и в моем варианте последовательность проходится алгоритмом поиска только 1 раз.

Но, в моем варианте в exclude зоне мы ищем и сохраняем только имена, и останавливаем поиск как только имя нашли. Это и быстрее (так как останавливаемся) и выгоднее по памяти - так как храним только true или false напротив имени а не все результаты.

В include зоне же в моем варианте мы ищем только часть энзимов - те что не были excluded.

Количество Task (распараллеливания) и в твоем и моем варианте не является требованием алгоритма  - можно использовать и один на все. Это можно обсудить отдельно от деталей алгоритма.

Ты все еще думаешь твой алгоритм будет производительнее?

2024-07-27 01:23 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (cfg.excludeMode) {
Я считаю что пройти разок по контейнеру с результатами и определить какие из них включать в результат будет быстрей чем создать и обслужить сабтаски которые это сделают, тут разве что за счет параллельности быстрей будет. У меня такой аргумент.
Мне разницы нету, я сделаю как скажешь.

2024-07-27 02:04 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (cfg.excludeMode) {
Логику алгоритма я описала выше и она не имеет отношения к тому, как делить задачу на сабтаски.

На сабтаски же, чтобы было минимум изменений можно не разделять по новому, а оставить как есть.

Вот как выглядит минимальное полное решение в итоге:

1) На вход подается список энзимов, регион поиска и exclude regions
2) Для каждого из энзимов создается FindSingleEnzymeTask (как и сейчас) и ему передается регион поиска и набор exclude регионов.
3) Если есть exclude регионы то FindSingleEnzymeTask ищет есть ли этот энзим там - если есть хоть одно вхождение то дальше он не ищет
4) Если вхождения в exclude region нет, то FindSingleEnzymeTask ищет в оставшемся (разница полного и exclude) регионов.


Выше описано неоптимальное, но приемлемое решение, так как именно так оно работает сейчас.

Намного лучшим решением была бы замена FindSingleEnzymeTask на FindMultipleEnzymesTask, который в одном потоке и при помощи одного SeqeunceWalker ищет сразу N (от 10 до 100) энзимов одновременно на текущем (загруженным sequence walker) участке последовательности.

Это  улучшило бы производительность для небольших участков (где обычно и работают с энзимами), так как не нужно было бы плодить сотни потоков для обработки всего 1kb последовательности каждым.

Можешь сделать любое из этих решений. Например можно начать с первого, чтобы исправить баг, а потом улучшить его до второго, чтобы убрать сотки тасков.

2024-07-29 02:25 UTC, rasputinkirill commented
Вроде все замечания поправил.
Только у меня почемуто трансляции не сработали хотя в лингвисте все зеленое, номера строчек вроде верные.

2024-07-29 03:40 UTC, yalgaer commented
> Вроде все замечания поправил. Только у меня почемуто трансляции не сработали хотя в лингвисте все зеленое, номера строчек вроде верные.

У тебя фильтрацией exclude энзимов занимается FindEnzymesToAnnotationsTask. А все что он должен делать - это перекладывать результаты поиска энзимов в форму аннотаций.

Внеси фильтрацию согласно exclude правилам в FindSingle/MultipleEnzymeTask. Как это сделать подробнее описано выше.

2024-07-31 03:42 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            Task* task = new FindSingleEnzymeTask(seqRef, excludeRegion, enzyme, listener, isCircular);
Добавь здесь параметр maxResult = 1

2024-07-31 03:45 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            SingleEnzymeHitListener* listener = new SingleEnzymeHitListener(&excludedEnzymes);
Этот класс не нужен, так как в уже существующем onResult ты можешь по ряду признаков (например location) понять что именно нашлось и добавить имя энзима exclude set (убрать его из дальнейшего поиска)

2024-07-31 03:47 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (searchExcludedEnzymesTasks.isEmpty()) {
Не нужно дожидаться завершения всех exclude тасков. Как только завершился один из них для одного из энзимов можно сразу же принимать решение запускать ли поиск.

2024-08-01 02:25 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (searchExcludedEnzymesTasks.isEmpty()) {
Всех не нужно, а если несколько регионов пропуска, то мы должны убедиться что энзим не найден во все, чтобы принять решение о запуске поиска энзима в сиквенсе.

2024-08-01 02:26 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            SingleEnzymeHitListener* listener = new SingleEnzymeHitListener(&excludedEnzymes);
Думаю, мой onResult из трех строчек отработает быстрей чем дефолтный с дополнительной логикой которая тут не нужна. Тебе видней конечно.

2024-08-02 03:13 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            SingleEnzymeHitListener* listener = new SingleEnzymeHitListener(&excludedEnzymes);
Ты создаешь новое состояние, новое требование очистки памяти и тп. То есть твои 3 строчки это реально намного больше чем 3 строчки - это протянутое во времени состояние.

2024-08-02 03:19 UTC, yalgaer commented
> Вроде все замечания поправил. Только у меня почемуто трансляции не сработали хотя в лингвисте все зеленое, номера строчек вроде верные.

Внешне выглядит все правильно. Можно попробовать продебажить и посмотреть почему строка которая пристутствует в qm файле в итоге не заменяется на нужную (переведенную)

2024-08-02 03:22 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.h
> +    QMap<QString, int> exludedEnzymesHits;
Может ли `exludedEnzymesHits` быть прость QSet<QString>? Если энзим найден в эксклюд регионе - зачем ему счетчик?

2024-08-02 03:23 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +        for (Task* t : onSubTaskFinished(nullptr)) {
nit: qAsConst

2024-08-02 03:25 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +        for (Task* t : onSubTaskFinished(nullptr)) {
Вызов onSubTaskFinished() таска внутри конструктора таска вызывает столько вопросов, что легче сразу написать это иначе (использовать специальную функцию с понятным именем и тп).
Это надо переделать. 
Более того onSubtaskFinished это виртуальная функция (их не стоит вызывать из конструкторов)

2024-08-02 03:26 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.h
> +    QMap<QString, int> exludedEnzymesHits;
exludedEnzymesHits -> excludedEnzymesHits

2024-08-02 03:28 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (!exludedEnzymesHits.isEmpty()) {
Что означает эта проверка? Ощущение что нужно разгадать сложную загадку.

2024-08-02 03:29 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +        CHECK_EXT(findSingleEnzymeTask != nullptr, setError(L10N::nullPointerError("FindSingleEnzymeTask")), result);
Если других типов subtask нет  нужно заменить CHECK на SAFEPONT

2024-08-02 03:37 UTC, yalgaer requested changes
Код FindEnzymesTask написан возможно и коротко, но запутано. 

Нужно распутать и разложить все шаги (всю логику) по полочкам - тогда будет хоть и длиннее  "четко".

2024-08-02 05:20 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.h
> +    QMap<QString, int> exludedEnzymesHits;
Счетчик нужен чтобы понять что все ассоциированные таски поиска завершены, мы не можем запускать для энзима поиск пока не убедимся что он отсутствует во всех эксклюд регионах.

2024-08-02 06:00 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    if (!exludedEnzymesHits.isEmpty()) {
Немного переписал код по компактней, но смысл остался такой же.
`exludedEnzymesHits` хранит состояние по таскам поиска для каждого энзима, если создается таска на поиск в экслюд регионе - +1 к счетчику, если таска на поиск завершилась без результата -1 к счетчику.
Если `exludedEnzymesHits`  пустая - то экслюд регионов нету, все сабтаски уже запущены в конструкторе, делать больше ничего не надо.
В onSubTaskFinished когда таска поиска завершается - если у энзима который искали в `exludedEnzymesHits` счетчик на нуле - в экслюд регионах ничего не найдено, запускаем обычный поиск, если больше нуля - то значит либо энзим найден, либо еще не завершилась таска по поиску в эксклюд регионе.
Если после обычного поиска ничего не нашлось, знаечние счетчика будет -1 и повторно таска не запустится.

2024-08-06 03:00 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    CHECK(!excludedEnzymesHits.isEmpty(), result);
Можно напрямую сказать CHECK(!excludeRegions.isEmpty(), {})

2024-08-06 03:03 UTC, yalgaer reviewed
Апрув после мержа с мастером и тестов

2024-08-07 07:02 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    CHECK(!excludedEnzymesHits.isEmpty(), result);
Да ладно уж, у нас же прям специально для этого result во всех onSubTaskFinished заводится, не нарушаем единообразие.

2024-08-08 22:03 UTC, yalgaer commented
Можно перезапустить XML мак и винду чтобы были зелеными?

2024-08-13 05:30 UTC, yalgaer approved these changes

2024-08-13 05:31 UTC, merged