UGENE-8079. [Crash, wd, debug] Double opening sample and setting brea…
ugeneunipro/ugene pull request #1645
Opened 2024-06-28 08:08 UTC by EvelinaBiserova

…kpoint

2024-06-29 01:03 UTC, yalgaer commented
Предлагаю вернуться к этому PR после https://github.com/ugeneunipro/ugene/pull/1643 - возможно есть общий код

2024-07-10 09:18 UTC, EvelinaBiserova commented
Упавшие тесты с правками не связаны и рассматриваются в #1651

2024-07-11 08:59 UTC, EvelinaBiserova commented
Как упомянуто в #1651, перезапускаю вин тесты

2024-07-12 00:23 UTC, yalgaer requested changes

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +namespace {
лучше не использоать анонимные namespace а просто испольщовать static для функций. Причина простая 1) не нажно искать контекст где объявлена функция - а он может быть на 3 странице выше. 2) так просто короче запись.

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +WorkflowProcessItem* createProcess(Actor* actor, const Workflow::Metadata& meta) {
Такие сложные методы нужно документировать чтобы понимать что в нем есть правильное поведение а что баг.

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    foreach (WorkflowPortItem* portItem, procItem->getPortItems()) {
не используй deprecated foreach в новом коде

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +            QColor c = visual.getColor(contains);
Нужно добавить SAFE_POINT что стили не нулевые

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QPointF p = visual.getPos(contains);
далее contains является константой - не нужно его использовать как переменную

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    WorkflowBusItem* busItem = scene->addFlow(src, dst, link);
Любой доступ к Map/Hash где может вернуться nullptr должнен экранироваться проверкой (SAFE_POINT)

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    disconnect(scene, SIGNAL(selectionChanged()), this, SLOT(sl_editItem()));
Использую указатели на функции в новом коде для connect/disconnect тк они проверяются на момент компиляции

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
Используй читаемые имена переменных.

2024-07-12 00:23 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
Вопрос: pasteText может содержать не latin1 символы?

2024-07-12 08:03 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +namespace {
Это для `namespace SceneCreatorHelper`

2024-07-12 08:03 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +WorkflowProcessItem* createProcess(Actor* actor, const Workflow::Metadata& meta) {
Это рефакторинг

2024-07-12 08:05 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QPointF p = visual.getPos(contains);
Это чужой код, перемещённый в новое место. По возможности я старалась его не менять, чтобы можно было потом найти корни.

Ладно, перепишу его на новый стиль

2024-07-12 08:10 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
Типа русских букв? Да, в релизе работает корректно

2024-07-12 08:36 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QPointF p = visual.getPos(contains);
Во все функции принимается по неконстантной ссылке, не могу убрать переменную

2024-07-12 10:05 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +namespace {
Убрала

2024-07-12 10:08 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +WorkflowProcessItem* createProcess(Actor* actor, const Workflow::Metadata& meta) {
Методы из SceneCreatorHelper прокомментированы, методы sl_paste* уже были прокомментированы

2024-07-12 10:09 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    foreach (WorkflowPortItem* portItem, procItem->getPortItems()) {
В своих изменениях убрала

2024-07-12 10:24 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +            QColor c = visual.getColor(contains);
Добавлены с дублированием в нескольких местах. Я не уверена, что можно вынести в одну общую проверку; кмк код не будет эквивалентен

2024-07-12 10:25 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    WorkflowBusItem* busItem = scene->addFlow(src, dst, link);
Добавила

2024-07-12 10:26 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    disconnect(scene, SIGNAL(selectionChanged()), this, SLOT(sl_editItem()));
В моих изменениях сделано

2024-07-12 10:27 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
lpt->dataToPaste

2024-07-12 10:28 UTC, EvelinaBiserova commented
GUI тесты не перезапускала. Перезапустить?

2024-07-13 03:06 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
русских букв в latin1 нет, почему не toLocal8Bit?

2024-07-13 03:06 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    for (auto portItem : procItem->getPortItems()) {
qAsConst

2024-07-13 03:07 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    if (wf->checkRawData(s.toLatin1()).score != FormatDetection_Matched) {
toLocal8Bit?

2024-07-13 03:08 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray dataToPaste = lastPaste.toLatin1();
toLocal8Bit?

2024-07-13 03:08 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    for (auto link : pastedS.getFlows()) {
qAsConst

2024-07-15 04:58 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
Какие символы юникода проверить?

2024-07-15 05:50 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
Кит. трад., залго, эмодзи проверила, работает и latin1, и toLocal8Bit

2024-07-15 05:51 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    for (auto portItem : procItem->getPortItems()) {
Ошибка компиляции

2024-07-15 05:55 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    for (auto link : pastedS.getFlows()) {
Ошибка компиляции

2024-07-15 06:05 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray lpt = lastPaste.toLatin1();
latin1->toLocal8Bit

2024-07-15 06:05 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    if (wf->checkRawData(s.toLatin1()).score != FormatDetection_Matched) {
latin1->toLocal8Bit

2024-07-15 06:05 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    QByteArray dataToPaste = lastPaste.toLatin1();
latin1->toLocal8Bit

2024-07-15 06:05 UTC, EvelinaBiserova commented
Перезапуск тестов

2024-07-16 00:53 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    for (auto portItem : procItem->getPortItems()) {
Ошибка не спроста. Получи локальную shallow копию

2024-07-16 00:54 UTC, yalgaer commented
> GUI тесты не перезапускала. Перезапустить?

Да, нужно чтобы тесты прошли

2024-07-16 03:13 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    for (auto portItem : procItem->getPortItems()) {
> Ошибка неспроста

Есть идеи, зачем _специально_ удалили такую перегрузку?

2024-07-16 04:13 UTC, EvelinaBiserova commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +    for (auto portItem : procItem->getPortItems()) {
Добавила qAsConst здесь и в другом замечании

2024-07-17 03:10 UTC, yalgaer commented
На винде только флаки?

2024-07-17 09:16 UTC, EvelinaBiserova commented
> На винде только флаки?

Да. WD открывался дольше 30 сек, локально всё работает

2024-07-18 04:54 UTC, yalgaer approved these changes

2024-07-18 12:59 UTC, merged