Ugene 7610
ugeneunipro/ugene pull request #1652
Opened 2024-07-15 11:17 UTC by DmitriiSukhomlinov

Пока смотреть рано, PR исключительно ради моего удобства

2025-05-12 07:56 UTC, DmitriiSukhomlinov commented
@yalgaer запрос ревью

2025-05-16 11:02 UTC, yalgaer requested changes
Я начала смотреть PR с того, что изменилось в Light теме. Здесь мне бы хотелось увидеть либо улучшения, либо что все осталось как есть.
К сожалению новые иконки в светлой теме выглядят реально плохо.
Я прилагаю скриншоты ниже. Это большой даунгрейд для UGENE. Все иконки что используются в UGENE сейчас выбирались из профессиональных icon-packs с обшим стилем.
Предлагаю оставить внешний вид Light темы без изменений.

По размеру и формату иконок: действительно в различных Icon Packs иконки могут иметь большой размер. Это нужно для использования в различных Laucher приложениях, где иконка приложения/сайта может занимать значительную часть даже на 4k экране.

В случае UGENE подобный размер иконок избыточен: для нас более чем достаточно 32x32 или, в крайнем случае, 64x64.

При разработке новых иконок рекомендую использовать векторный формат SVG. В этом случае иконку будет легко перекрасить CSS стилем из light в dark режим без 

До:
![before1](https://github.com/user-attachments/assets/9656241b-55b9-4bdb-997a-40dba8f204ca)
После:
![after1](https://github.com/user-attachments/assets/28dc3a92-ebad-4729-9a24-54760e0ff540)

До:
![before2](https://github.com/user-attachments/assets/464beb3e-b80c-4ab3-ba6f-4247b6a061c5)
После:
![after2](https://github.com/user-attachments/assets/ead67ffb-2add-403d-a658-d44ae827d6cf)

До:
![before3](https://github.com/user-attachments/assets/af620ddb-6c9e-48b4-8c90-b17dc519c74e)
После:
![after3](https://github.com/user-attachments/assets/cd8243d9-fd76-499f-b517-830e5144ec65)

изменений внутри самой иконки, она не будет иметь большой размер (а наши иконки копилируются в C++ массивы) и будет масштабироваться на любой размер.

2025-05-27 10:48 UTC, DmitriiSukhomlinov commented
Вернул назад все иконки Light схемы, Dark по максимуму использует их же. В случаях, когда это плохо выглядит (например, если Light-иконка содержит темные элементы), используется отдельная Dark-иконка, созданная по подобию Light. 

Размер всех новых иконок уменьшен с 512х512 до 32х32. Перерисовывать в векторную графику не стал по следующим причинам - растровые иконки уже готовы; никогда не работал с векторной графикой, поэтому, может занять много времени; некоторые иконки достаточно замысловаты, сделать векторный аналог может быть проблематично в принципе. В будущем учту это пожелание.

2025-05-28 11:49 UTC, yalgaer commented
Уже выглядит лучше.
Нашла такую проблему с меню. Проявляется только в темной теме.
![Menu_001](https://github.com/user-attachments/assets/6f6b6ff8-f040-4024-b382-b23e011c1cd4)
Иконки прижаты к краю и между ними и текстом слишком большое расстояние


Также я бы посоветовала бы переименовать Color Mode в Color Theme или просто Theme

2025-05-28 11:49 UTC, yalgaer requested changes
см комментарий выше

2025-05-28 11:50 UTC, yalgaer commented on CMakeLists.txt
> +message(STATUS "Deployment target: ${CMAKE_OSX_DEPLOYMENT_TARGET}")
Это нужно печатать только для мака

2025-06-02 07:33 UTC, DmitriiSukhomlinov commented on CMakeLists.txt
> +message(STATUS "Deployment target: ${CMAKE_OSX_DEPLOYMENT_TARGET}")
ОК

2025-06-02 07:35 UTC, DmitriiSukhomlinov commented
Сдвиг иконок поправлен, фраза "Color mode" переименована в "Color theme" во всех местах, где эта она встречается. Не стал переименовывать только `DarkStyle`, т.к. это класс наследуется от `QStyle` и имя указывает на принадлежность к Qt-шным стилям.

Дополнительно добавил трансляции.

2025-06-03 16:53 UTC, yalgaer requested changes
Проревьюила часть файлов, комментарии выше. 

Нашла краш:

Открыть humanT1
Открыть 3INS.pdb
Открыть COI.nwk
Открыть COI.aln

Меняем тему на темную -> crash

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/misc/EnzymeModel.cpp
> +            ch = QString("<span style=\"color: %1; \">%2</span>").arg(AppContext::getMainWindow()->isDarkTheme() ? "#FF7F7F" : "#FF0000").arg(ch);
Подобные константы надо вынести в константы

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msaedit/color_schemes/MsaColorScheme.cpp
> +    Q_UNUSED(colorsPerChar);
Q_UNUSED использовать не нужно - достаточно прочто не давать имя переменной

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msaedit/color_schemes/MsaColorScheme.cpp
> +    Q_UNUSED(colorsPerChar);
Q_UNSUED

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Core/src/datatype/AnnotationSettings.h
> +    // Change color in Light theme to @lightColor
В целом это очень неэффективное решение - оно добавляет состояние dark/light и не дает легко добавить новые темы.

Правильным решением было бы сделать поддержку N тем, при этом у каждой темы были бы свои постоянные и динамические настройки. Когда пользователь менял бы цвет аннотации - он просто менял бы их в текущей теме.

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/ExternalToolRegistry.h
> +    // Set icon parameters for normal icon
Подобный массивный no-op рефакторинг стоило бы вынести в отдельный PR. Это бы сильно уменьшило scope текущего ревью

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/IconParameters.cpp
> +IconParameters::IconParameters(const QString& _iconCathegory, const QString& _iconName, bool _hasColorCathegory)
category

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/UserApplicationsSettings.cpp
> +int UserAppsSettings::getColorThemeIndex() const {
Слово index здесь плохое. Это должен быть ID темы - может быть как строкой так и числом

2025-06-03 16:53 UTC, yalgaer commented on src/corelibs/U2Designer/src/DatasetWidget.cpp
> +    ui->addFileButton->setIcon(GUIUtils::getIconResource("U2Designer", "add_file.png", false));
Клиент темы не должен знать о том шарится ли иконка у light и dark или нет.
Если не хочется добавлять файлы одной и той же иконки 2 раза можно просто использовать light тему в качестве fall-back - если иконка не найдена в dark - брать из light

2025-06-04 01:56 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/datatype/AnnotationSettings.h
> +    // Change color in Light theme to @lightColor
Я думал на этот счет, но посчитал, что мы вряд ли будем добавлять какие-то еще темы в UGENE, поэтому решил остановиться на наборе "светлая/темная/автоматическая". Что-то конкретное ты хочешь, чтобы я исправил в рамках этого комментария?

2025-06-04 02:04 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/ExternalToolRegistry.h
> +    // Set icon parameters for normal icon
Я согласен с этим, необходимость этого `IconParameters` возникла, что называется, на лету и сначала изменения были маленькие, а потом их уже стало трудно отделить от других изменений, поэтому я продолжил как есть. Я могу постараться отделить это в отдельный коммит, чтобы было проще смотреть, но это приведет к изменению истории коммитов, из-за чего моет быть рудно соориентироваться касательно того, что уже ыбло просмотрено, а что еще нет. Если не нужно, то пометь данный комментарий как Resolved

2025-06-04 07:38 UTC, DmitriiSukhomlinov commented
> Проревьюила часть файлов, комментарии выше.
> 
> Нашла краш:
> 
> Открыть humanT1 Открыть 3INS.pdb Открыть COI.nwk Открыть COI.aln
> 
> Меняем тему на темную -> crash

Исправлено

2025-06-04 07:44 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/misc/EnzymeModel.cpp
> +            ch = QString("<span style=\"color: %1; \">%2</span>").arg(AppContext::getMainWindow()->isDarkTheme() ? "#FF7F7F" : "#FF0000").arg(ch);
ОК

2025-06-04 07:47 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msaedit/color_schemes/MsaColorScheme.cpp
> +    Q_UNUSED(colorsPerChar);
Убрал `Q_UNUSED(colorsPerChar);`, но имя переменной оставил т.к. она используется внутри макроса, что я не заметил изначально

2025-06-04 07:47 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msaedit/color_schemes/MsaColorScheme.cpp
> +    Q_UNUSED(colorsPerChar);
Аналогично

2025-06-04 07:49 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/IconParameters.cpp
> +IconParameters::IconParameters(const QString& _iconCathegory, const QString& _iconName, bool _hasColorCathegory)
Исправлено

2025-06-04 08:20 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/UserApplicationsSettings.cpp
> +int UserAppsSettings::getColorThemeIndex() const {
Переименовал в `getColorThemeId`/`setColorThemeId`

2025-06-04 12:12 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Designer/src/DatasetWidget.cpp
> +    ui->addFileButton->setIcon(GUIUtils::getIconResource("U2Designer", "add_file.png", false));
Поправил

2025-06-05 05:29 UTC, yalgaer commented
Мне придется начать ревьють заново так как каждое исправление перечеркивает историю:
![image](https://github.com/user-attachments/assets/ddf46f97-53af-45c8-be42-4a758b1169c3)

Просьба: научиться работать с git правильно. Каждый commit/merge должен включать только относящуюся к нему дельту.

2025-06-05 05:35 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msaedit/color_schemes/MsaColorScheme.cpp
> +    Q_UNUSED(colorsPerChar);
Я не вижу этого исправления после обновления бранча.
Метод нужно сделать статическим (локальным)

2025-06-05 05:44 UTC, DmitriiSukhomlinov commented
> Мне придется начать ревьють заново так как каждое исправление перечеркивает историю: ![image](https://private-user-images.githubusercontent.com/17791039/451710534-ddf46f97-53af-45c8-be42-4a758b1169c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDkxMDE3OTMsIm5iZiI6MTc0OTEwMTQ5MywicGF0aCI6Ii8xNzc5MTAzOS80NTE3MTA1MzQtZGRmNDZmOTctNTNhZi00NWM4LWJlNDItNGE3NThiMTE2OWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjA1VDA1MzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYTFjNzdkZTk4ZDE0NGM5ZTllZDFhMTc5MmY0MmIxMTgzNjM4MmFhNTIzN2E3NGMyMTZmYzhkOTFiMjYzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n5i8DgXwdO4rE_pRsamJcUGiCtlehBePcjAPAYVY2nk)
> 
> Просьба: научиться работать с git правильно. Каждый commit/merge должен включать только относящуюся к нему дельту.

Я не изменял историю коммитов, код в них остался тот же самый, ты можешь просто начать с того же места. Есть, конечно, вариант, что ты мне не веришь и считаешь, что я втихую подсовываю какие-то изменения в начало истории, чтобы они избежали ревью, но я этого не делаю.

Коммиты получили новые хеши, т.к. я сделал rebase для того, чтобы влить master в мою текущую ветку. Я использую rebase, а не merge, для этой цели по ряду причин:
1. Привычка - я работаю в другом проекте, где для этой процедуры требуют именно rebase.
2. Использование merge ломает историю коммитов твоей ветки, т.к. в неё начинают вкрапляться мерж-коммиты. Это может вызвать проблемы в интерактивном rebase или ручном squash'е, если они, по каким-то причинам, понадобятся. Я спотыкался об это как-то и с тех пор стараюсь избегать.

Насколько мне известно, у нас нет и никогда не было какой-то четкой спецификации касательно того, как вливать master в ветку разработки, но я учту замечание и впредь буду делать именно merge.

2025-06-05 05:49 UTC, yalgaer commented on src/corelibs/U2Core/src/datatype/AnnotationSettings.h
> +    // Change color in Light theme to @lightColor
Мы можем иметь только 2 темы и ограничится этим. 
Что важно здесь: не усложнять код которому просто нужен цвет/иконка выбором темы.

То есть в любом месте цвет должен браться примерно так: 
theme->getNamedColor(namedColorKey)
и ставится так:
theme->setNamedColor(namedColorKey)

слова dark/light не должны выходить наружу темы и загрязнять логику внешнего кода
Если цвета в текущей теме нет - он должен браться из базовой (light)

Конкретно в этом месте мы видим что аннотации имеют 2 набора цвета: для темной темы и для светлой.
Поэтому при инициализации этого логического модуля (цвета аннотаций) этот модуль должен сохранить свои кастомные named-color в обе темы (максимум) или только в light тему (так было раньше, минимум).

Именно эти цвета будут перегружаться пользовательскими, если пользователь меняет цвет.

Кроме этого здесь могут быть динамически высчитываемые цвета. Для них в теме нужно регистрировать namedColorProvider - функтор который по ключу вернет цвет (посчитает динамически) или null. 

Логика этой динамичкской функции может выглядеть так:
1) Смотрим если ключ должен обрабатываться этой функцией: имеет правильный prefix
2) Если нет - возращаем null. Если да - возвращаем цвет.


Вся эта описанная логика займет 100 строчек в реализации и уберет if(dark/light) из всех остальных мест в коде

2025-06-05 05:50 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/ExternalToolRegistry.h
> +    // Set icon parameters for normal icon
Да лучше отделить - у меня нет замечаний к этой части, но она сильно загрязняет текущий PR

2025-06-05 05:51 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/IconParameters.cpp
> +IconParameters::IconParameters(const QString& _iconCathegory, const QString& _iconName, bool _hasColorCathegory)
Осталось во многих других местах diff

2025-06-05 05:54 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msaedit/color_schemes/MsaColorScheme.cpp
> +    Q_UNUSED(colorsPerChar);
Я проверил и ты действительно не можешь видеть этого изменения, т.к. я его не сделал, это моя ошибка. В этом классе больше двух методов, содержащих подобное `Q_UNUSED(colorsPerChar);`, а я удалил только в двух, т.к. увидел только два комментария - один из которых, как оказалось, удалил вообще не там, где ты прокомментировала. Чуть позже я еще раз все внимательно посмотрю и почищу

2025-06-05 05:56 UTC, yalgaer commented
> Коммиты получили новые хеши, т.к. я сделал rebase для того, чтобы влить master в мою текущую ветку. Я использую rebase, а не merge, для этой цели по ряду причин:
> 
> 1. Привычка - я работаю в другом проекте, где для этой процедуры требуют именно rebase.

Я не берусь критиковать другие проекты, но так с гитом не работают.

Если я не могу после твоих изменений сделать простой git pull на своей копии твоей ветки которую я не меняла - это неправильно.

Возможность сделать git pull без необходимости пересоздания локальной ветки это единственное что я прошу.
Нигде больше у меня таких проблем не возникало. 
Думаю стоит разобраться и никогда так больше не работать с Git.

2025-06-05 06:01 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/IconParameters.cpp
> +IconParameters::IconParameters(const QString& _iconCathegory, const QString& _iconName, bool _hasColorCathegory)
Да, увидел. Опять же моя ошибка, в строку поиска написал русскую С вместо английской. Даже закоммитил это и пришлось исправлять. Исправлю.

2025-06-05 06:12 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/ExternalToolRegistry.h
> +    // Set icon parameters for normal icon
Я могу отделить это в отдельный коммит, но, возвращаясь к дискусси ниже - без rebase, который изменит историю коммитов, это сделать не получится, т.к. `IconParameters` уже является частью истории коммитов данной ветки. Можно вынести изменения в другую ветку, проревьюить отдельно, влить в мастер, а сверху этой ветки наложить мерж-коммит, котрый синхронизует изменения, но в истории текущей ветки `IconParameters` никуда не денется и, если ты смотришь именно по коммитам от старого к новому, то это никак не поможет. Какой вариант сделать?

2025-06-06 08:30 UTC, yalgaer commented on src/corelibs/U2Core/src/globals/ExternalToolRegistry.h
> +    // Set icon parameters for normal icon
Пусть будет еще раз полное пересоздание и полное перестроение если так легче в этот раз, главное чтобы однажды закончилось.

Но технически это не должно быть нужно - простой мерж все это разрешит: идентичный код из 2 веток мержится без проблем.

То есть, если в абсолютно новую ветку ты скопируешь файлы где есть просто refactoring не касающийся темы и зальешь его после этого в main, то в ветке UGENE-7610 команда 'git merge origin/main' пройдет без проблем. "Проблемы" в виде ручного мержа возникнут только если в main будут "несовместимые" изменения внутри одних и тех же файлов.

2025-06-11 06:29 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/ExternalToolRegistry.h
> +    // Set icon parameters for normal icon
Рефакторинг `IconParameters` перенесен в в другую ветку. Создан отдельный MR https://github.com/ugeneunipro/ugene/pull/1753. На текущую ветку наложен мерж коммит для синхронизации изменений. Для того, чтобы изменения рефакторинга не отображались в текущем MR, была изменена базовая ветка (насколько мне известно, она автоматически переключится на мастер после вливания рефакторинга). Во избежание недоразумений, я больше не буду использовать rebase (либо другие методы слияния веток, подразумевающие изменение истории коммитов) в UGENE после того, как ветка выставлена на ревью.

2025-06-11 07:41 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/globals/IconParameters.cpp
> +IconParameters::IconParameters(const QString& _iconCathegory, const QString& _iconName, bool _hasColorCathegory)
Поправлено

2025-06-11 08:32 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/datatype/AnnotationSettings.h
> +    // Change color in Light theme to @lightColor
Насколько я понял, ты предлагаешь убрать из `AnnotationSettings` заранее определенные dark/light цвета, убрать поля `lightColor`/`darkColor` и, вместо этого, высчитывать цвет аннотации в момент, когда он нужны. Это вызовет следующие проблемы:

- Текущая реализация позволяет кешировать цвета при загрузке UGENE, не высчитывая их кажый раз. Это сделано специально как раз для того, чтобы избежат фризов (на всякий случай уточню, что эта штука была в UGENE всегда, а не добавлена в рамках этой задачи). Удаление кеширования существенно замедлит Sequence View.
- Пользователь имеет возможность менять цвета аннотаций. Сейчас цвета темной и светлой темы разделены, т.е. если пользователь поменяет цвет аннотации в светлой теме, то в темной теме все еще останется цвет по-умолчанию. Это сделано исходя из той логики, что цвет, выставленный в светлой теме, не обязательно будет хорошо смотреться в темной теме (более того, скорее всего, он будет смотреться плохо). Выставленные цвета хранятся в полях `lightColor`/`darkColor`. Если избавиться от этих полей, то мы потеряем функцию смены цвета, т.к. цвет всегда будет высчитываться из имени. Если объединить `lightColor`/`darkColor` в одно поле `color`, то пользователь будет менять цвет для обоих цветовых схем сразу.

Исходя из того, что я написал, как-то меняется желаемый фикс?

2025-08-27 01:30 UTC, DmitriiSukhomlinov commented
@yalgaer на Windows и Linux тесты прошли, с маком разбираюсь, думаю, можно смотреть

2025-08-28 01:24 UTC, yalgaer commented
ок начинаю смотреть

2025-08-28 01:38 UTC, yalgaer requested changes

2025-08-28 01:38 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/GUIUtils.cpp
> +    if (!QFile::exists(iconPath)) {
Тут логика должна быть перевернута по приоритету: если есть тематическая иконка - использовать ее.

Далее, если у нас есть "общие иконки" - стоит использовать в качестве них light состояние - в этом случае не нужно перемещать сотни иконок в папку /light - иначе в ревью порядка 1000 файлов изменились - GitHub интерфейс падает.

Если же есть причины жестко разделить на dark/light папки - то хотелось бы понять нужна ли общая папка вообще? Какой процент иконок переиспользуется обеих темах? Если процент небольшой - стоит разложить их в dark/light (копией) и избежать общее состояние вовсе.
В этом (разделенном) виде нужен какой-то простейший билд-тайм тест что добавив иконку в один сет мы не забыли о другом.

2025-08-28 10:40 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/GUIUtils.cpp
> +    if (!QFile::exists(iconPath)) {
> Тут логика должна быть перевернута по приоритету: если есть тематическая иконка - использовать ее.

Я не увидел никаких преимуществ такого подхода, но окей.

> Если же есть причины жестко разделить на dark/light подпапки - то хотелось бы понять нужна ли общая папка вообще? Какой процент иконок переиспользуется обеих темах? Если процент небольшой - стоит разложить их в dark/light (копией) и избежать общее состояние вовсе.


У нас есть несколько подходов решения этой задачи:
- Сделать общие иконки, а так же dark/light (симметричное разделение, но но уже сущствующие иконки просто перемещаются в light, следовательно, отмечаются измененными). **Реализовано сейчас.**
- Оставить общие иконки как были, добавить новые в подпапку dark (существующие не двигаются, следовательно, меньше файлов будут изменены, но появляется "однобокость", light режим выглядит основным, dark - второстепенным, хотя, по факту, они равны).
- Убрать общую папку, оставив только dark и light подпапки (было бы хорошо, не будь у нас общих иконок, а так будут дубликаты).

Варианты, по факту, плюс-минус эквивалентны друг другу, имеют и положительые и отрицательные стороны. Я выбрал тот, который считал наиболее правильным. Сейчас мне нужно либо согласие с ним, либо конкретика касательно того, какой использовать. Я не буду спорить, просто реализую. Могу только дополнить, что сейчас у нас 144 общих иконок и 190 тематических (элементы Start Page не считаю).

> В этом (разделенном) виде нужен какой-то простейший билд-тайм тест что добавив иконку в один сет мы не забыли о другом.

Не понял, что имеется ввиду. Время билда можно посмотреть в тимсити, оно у данной ветки вообще не отличается от мастера.

2025-08-29 05:11 UTC, yalgaer commented on src/corelibs/U2Gui/src/util/GUIUtils.cpp
> +    if (!QFile::exists(iconPath)) {
Хорошо, цифры понятны.
Тогда стоит оставить разделение иконок как оно есть сейчас в этом PR, но функцию выбора заменить - идти от частного к общему: сначала частное, потом общее.

2025-08-29 06:06 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/util/GUIUtils.cpp
> +    if (!QFile::exists(iconPath)) {
Проверь [последний коммит](https://github.com/ugeneunipro/ugene/pull/1652/commits/eb38440fe5289e4f0176a6c983b723381c9ac4e6), я там уже реализовал это

2025-08-29 06:09 UTC, yalgaer reviewed
Продолжаю review. Принципиальных замечаний нет, вопросы есть

2025-08-29 06:09 UTC, yalgaer commented on src/plugins/GUITestBase/src/GUITestBasePlugin.cpp
> +    //REGISTER_TEST(GUITest_regression_scenarios::test_8001);
Что не так с этим тестом?

2025-08-29 06:09 UTC, yalgaer commented on src/corelibs/U2Core/src/datatype/FeatureColors.h
> +    static QColor transformLightToDark(QColor color);
nit: const Type&

2025-08-29 06:09 UTC, yalgaer commented on src/corelibs/U2Core/src/datatype/U2FeatureType.cpp
> +            darkColor = FeatureColors::transformLightToDark(darkColor);
Выглядит как ошибка. Нужно либо исправить либо документировать

2025-08-29 06:09 UTC, yalgaer commented on src/corelibs/U2Core/src/datatype/U2FeatureType.cpp
> +        SAFE_POINT(darkColor.isValid(), "Got invalid light dark for feature: " + name, );
nit: typo

2025-08-29 06:09 UTC, yalgaer commented on src/ugeneui/dark/darkstyle/darkstyle.qss
> +QToolTip{
Вопрос: откуда этот стиль?
Вот тут народ серьезно занимался темной темой для QT5 - у них есть и стили и графика. Почему этот стиль и а не их?
https://qdarkstylesheet.readthedocs.io/en/latest/screenshots.html#id1

2025-08-29 06:09 UTC, yalgaer commented on src/ugeneui/src/main_window/styles/StyleFactory.cpp
> +    FAIL("Auto color theme is not avalible on Linux", false);
Что случится тут в дебаге? В Linux 90% систем это гном - там можно попробовать достать через gsettings или как-то еще?

2025-08-29 06:09 UTC, yalgaer commented on src/ugeneui/src/main_window/MainWindowImpl.cpp
> +#ifdef Q_OS_DARWIN
Все эти системные ifdef связанные с темой стоит выделить в 1 файл, иначе они расползлись по коду - это уже не первое место.

2025-08-29 06:09 UTC, yalgaer commented on src/ugeneui/src/main_window/MainWindowImpl.cpp
> +#ifdef Q_OS_WIN
Выглядит как workaround - а для них нужно подробное описание проблемы в комменте

2025-08-29 06:09 UTC, yalgaer commented on src/ugeneui/src/main_window/SplashScreen.cpp
> +    if (isDark) {
непонятно почему тут повторен код выбора ресурса. Если нужно чтобы был именно QImage а не QIcon или QPixmap - можно добавить метод в общее место рядом с другими: суть общая.

2025-08-29 06:09 UTC, yalgaer commented on src/ugeneui/src/plugin_viewer/PluginViewerController.cpp
> +    auto textColor = QPalette().text().color();
Почему раньше этого было не нужно делать? Может недостаток проработки qss?

2025-08-29 10:46 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/GUITestBasePlugin.cpp
> +    //REGISTER_TEST(GUITest_regression_scenarios::test_8001);
Не помню, раскомментировал, буду смотреть, как проходит и, если падает, искать причину.

2025-08-29 10:55 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/datatype/FeatureColors.h
> +    static QColor transformLightToDark(QColor color);
Не имеет особого смысла, если обратить внимание на реализацию:
```
QColor FeatureColors::transformLightToDark(QColor color) {
    color.setHsv(color.hue(), color.saturation(), color.value() / 2);
    return color;
}
```

Идет мофицикация цвета, если `color` будет константным, то `setHsv()` нельзя будет применить и все равно надо будет копировать.

Предвидя вопрос, почему тогда не передаю по ссылке -  во многих местах проще работать именно с возвращаемым значением, потому что само значение, передающееся в функцию, rvalue. Для **идеальной** оптимизации тут move-семантику можно прикрутить, но мы её нигде не используем, да и выхлоп будет +0,01 сек.

2025-08-29 11:09 UTC, DmitriiSukhomlinov commented on src/ugeneui/dark/darkstyle/darkstyle.qss
> +QToolTip{
Я тестировал эту штуку (вообще, перед тем, как делать, я все готовые пресеты протестировал, которые нашел). У них не dark theme, а blue theme какая-то получилась. Все синюшним оттенком отдавало, это даже из скриншотов видно. Короче, мне не понравилось, как выглядит. 

Мое решение основано на этом https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle и оно выглядело намного лучше на старте

2025-09-01 04:47 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/datatype/FeatureColors.h
> +    static QColor transformLightToDark(QColor color);
Добавил. Помимо этого, изменил алгоритм, по которому из цвета для светлой темы получается цвет для темной темы, т.к. предыдущий был слишком простым и, зачастую, генерировал не самые лучшие цвета.

2025-09-01 04:48 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/datatype/U2FeatureType.cpp
> +            darkColor = FeatureColors::transformLightToDark(darkColor);
Исправил

2025-09-01 04:48 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/datatype/U2FeatureType.cpp
> +        SAFE_POINT(darkColor.isValid(), "Got invalid light dark for feature: " + name, );
ОК

2025-09-01 05:44 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/main_window/MainWindowImpl.cpp
> +#ifdef Q_OS_WIN
Добавил описание. Дублирую сюда. Qt 5 умеет автоматически определять изменение системной цветовой схемы только на macOS - там можно установить `eventFilter` и `QEvent::PaletteChange` сработает при изменении системной цветовой схемы. На Windows это не отработает, единственный обнаруженный мною способ проверить, изменена ли цветовая схема - это периодически (в моем случае раз в 5 секунд) проверять регистр, в котором есть запись о текущей системной цветовой схеме.

Начиная с Qt 6.5 появился специальный сигнал `QStyleHints::colorSchemeChanged`, но мы пока на Qt 5 и не можем его использовать.

2025-09-01 09:36 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/main_window/SplashScreen.cpp
> +    if (isDark) {
Там Splash Screen создается до `MainWIndow`, а в `GUIUtils` dark или нет mode узнается как раз через главное окно.  Поэтому, я ручками до всего тянулся. Но я щас потестил - даже если создать Splash Screen сильно раньше всего остального, он начинает отрисовываться только когда приложение начнет исполняться, т.е. после вызова `GApplication::exec()`, так что текущее решение имеет мало смысла. Поэтому, я создание `SpashScreen` подвинул на чуть попозже, когда `MainWindow` уже создан и везде тут переписал на использование `GUIUtils`.

2025-09-01 09:47 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/plugin_viewer/PluginViewerController.cpp
> +    auto textColor = QPalette().text().color();
Если честно, не понял, что имеется ввиду. Функция была добавлена т.к. цвет текста по-умолчанию черный и раньше не менялся, а теперь он может смениться, вот мы и появилась новая функция. Т.е. в случае, если у нас светлая тема и мы открываем Pkugin View, то текст черный и эту функцию, в принципе, было бы не обязательно вызывать, но код у нас общий для обоих тем, поэтому она все равно вызовется.

2025-09-02 08:16 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/main_window/MainWindowImpl.cpp
> +#ifdef Q_OS_DARWIN
Я все унес в `StyleFactory`, но этот класс перестал был статическим, а стал реальным объектом, создаваемым в `MainWindow` и обрабатывающим смену классов. Я это сделал по нескольким причинам:

1. У `MainWIndow` есть `QTimer`, который создается только для версии на Windows и каждые пять секунд лезет в регистр, чтобы проверить, была ли изменена тема (единственный, на данный момент, способ определить смену темы для Auto режима на винде, event, который отрабатывает на macOS Тут не работает). Этот таймер должен быть присоединен к реальному объекту. 
2. `StyleFactory` создается имея `MainWindowImpl` в качестве родителя. Это, во первых, способ взаимодействия с  графическим интерфейсом (я унес в `StyleFactory` только расчеты, а саму смену и испускание сигнала смены темы все так же оставил на `MainWIndow`), а, во-вторых, блок, который гарантирует, что у нас будет всего одна `StyleFactory`.

Название `StyleFactory` лично меня устраивает, но может быть изменено на любое предложенное

2025-09-02 09:13 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/main_window/styles/StyleFactory.cpp
> +    FAIL("Auto color theme is not avalible on Linux", false);
Я исследовал этот вопрос и результаты крайне неоднозначные. Сначала по второстепенным изменениям:

1. Функция `isDarkStyleAvaliable` переименована в `isAutoStyleAvaliable`, поскольку она вызывается в местах, где нам надо знать, добавлять ли Auto или нет в комбо бокс выбора темы. Похожую функцию `isDarkStyleEnabled` я переименовывать не стал, т.к. у нее смысл соответствует названию.
2.  `FAIL` удален, в нем нет смысла, гораздо проще убрать обвязку в виде `#if defined(Q_OS_WIN) | defined(Q_OS_DARWIN)`, а тут оставить только `return false;`.

Теперь основное, касательно твоего замечания. Я очень долго исследовал этот вопрос и он достаточно сложный. Да, то, что ты предлагаешь, можно сделать, но это крайне нетривиально. Основная сложность в том, чтобы определить, какая схема выставлена в данный момент и определение момента, когда она сменилась. Я смог найти два способа определения схемы:
1. Через терминал. Команда `gsettings get org.gnome.desktop.interface color-scheme` должна выдать `prefer-dark`, если у системы выставлена темная цветовая схема.
2. Через gsettings (то, что упоминала ты). Можно написать некоторый код с использованием `gio`, который распарсит GNOM'ный бинарь с настройками и вытащит из него необходимое значение.

Первый метод мне очень не понравился, потому что для запуска команды нужно создавать новый процесс, а этого нельзя делать в главном потоке, нужно выносить в таску. Тут сразу две проблемы - во первых, вся та инфраструктура, которую я написал, завязана на использование в главном потоке, я не предвидел сценария использования в таске и переписать может оказаться очень непросто, я бы не хотел этого делать; во вторых, способа трекать изменение системной цветовой схемы я не смог найти, а это значит, что делать надо будет как в Windows, т.е. каждые пять секунд по таймеру смотреть системное значение - т.е. у нас UGENE будет каждые пять секунд создавать в фоне новую таску, что мне показалось вообще не приемлимым вариантом. По совокупности этих причин, я счел этот метод неподходящим и перешел ко второму.

Второй метод так же оказался проблемным. Для работы с `gsettings` нужно подключить системную либу `gio`. Я это сделал и обнаружил неприятную вещь - `gio` содержит ключевое слово `signals`, которое вступает в конфликт с аналогичным ключевым словом из Qt. Решить эту проблему можно с помощью макроса `QT_NO_KEYWORDS`, который есть в Qt и который, к счастью, можно прилепить на этапе `CMake` к отдельному файлу. Я прикрепил его к `StyleFactory.cpp`, но он все равно "просочился" во все, что делает `#include "StyleFactory.h"`. Я уменьшил количество таких файлов по максимуму, но они все равно не исчезли полностью и единственным способом было замена `signals` на `Q_SIGNALS` (а так же `slots` на `Q_SLOTS`, т.к. переменная `QT_NO_KEYWORDS` деактвирует все слова), что мне пришлось проделать в ряде файлов. К счастью, это решило проблемы с зависимостями и сборка прошла успешно.

Однако, само использование gsettings не заработало так, как нужно. Я протестировал взятие необходимого ключа на версии GNOME, где поддержки dark scheme еще нет и исполнение попросту валится на строчке, где я беру пытаюсь взять значение вот таким образом:
```
gchar *val = g_settings_get_string(settings, "color-scheme");
```
Разумеется, у пользователя может оказаться любая версия GNOME и он точно так же может словить креш. Я не смог найти никакого способа определить заранее, присутствует ли ключ "color-scheme" через код с использованием `gio`. Единственный вариант - вызов команды `gnome-shell --version` через терминал и проверки версии (должна быть 42 и больше), но это опять возвращает нас к вопросу использования `QProcess`.

Возможно, тебе известны какие-то еще способы реализации необходимого. Если озвучишь их - но только с хорошей конкретикой - я могу попробовать. Иначе, я предлагаю не тратить более времени на это. После обновления Qt на версию 6.5+ мы сможем вернуться к этому вопросу, т.к. там есть удобные функции для просмотра системных цветовых схем.

2025-09-02 10:01 UTC, DmitriiSukhomlinov commented
Я сделал что-то по всем замечаниям, какие-то требуют дальнейшего обсуждения, но так или иначе, можно смотреть

2025-09-03 17:17 UTC, yalgaer commented on src/ugeneui/src/main_window/styles/StyleFactory.cpp
> +    FAIL("Auto color theme is not avalible on Linux", false);
OK на Linux просто не должно быть FAIL. Если на системе нет автоопределения - пусть просто возращает false

2025-09-03 17:22 UTC, yalgaer commented on src/ugeneui/src/plugin_viewer/PluginViewerController.cpp
> +    auto textColor = QPalette().text().color();
В данном случае мы начали выставлять цвет для стандартного Qt элемента: QTreeWidgetItem
Ранее этого не делали - полагались на тему (QSS).

Вопрос: почему начали это делать? Может что-то не так в QSS?

2025-09-03 17:25 UTC, yalgaer commented on src/ugeneui/dark/darkstyle/darkstyle.qss
> +QToolTip{
Ок, тогда можно использовать их тему 
1. В качестве примера на случай если у нас будет что-то не работать а у них будет работать (QSS раскраска какого-либо элемента)
2. В качестве источника для GUI элементов - рамки/иконки если что-то будет нехватать или что-то будет плохо выглядеть.

2025-09-03 17:49 UTC, yalgaer commented on src/ugeneui/src/main_window/styles/StyleFactory.cpp
> +void StyleFactory::applyAutomaticallyChangedColorScheme() {
Этот метод лучше назвать syncColorSchemeWithSystem().

Далее внутри него не нужно делать setNewStyle если ничего не поменялось

2025-09-03 17:49 UTC, yalgaer commented on src/ugeneui/src/main_window/styles/StyleFactory.cpp
> +    connect(&colorThemeTimer, &QTimer::timeout, this, [this]() {
Проверялся ли вариант с подпиской на WM_SETTINGCHANGE вместо таймера в
qApp->installNativeEventFilter(this); ?

2025-09-04 10:17 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/plugin_viewer/PluginViewerController.cpp
> +    auto textColor = QPalette().text().color();
Понял, нашел проблему. При создании `PlugViewPluginItem` для него вызывается `GUIUtils::setMutedLnF(this, false);`, которая задает Foreground всем итемам и они больше не меняют цвет foreground'а автоматически. Эта функция осталась со времен, когда плагины можно было отключать и при отключении текст становился disabled. Когда [удаляли этот функционал](https://github.com/ugeneunipro/ugene/commit/440520ce9e16a12f3eb7cd440fea18c8eb57eb04#diff-b58d9ed5fab3d671a5a1e0ce834a2d92195a9d30ddc1877652b17b3d5c07b5fdR400) вместо того, чтобы просто удалить вызов `GUIUtils::setMutedLnF(...)` задали ему вечный `false` в качестве второго аргумента. Удалил строчку, `sl_colorThemeSwithced()` и обновление текста.

2025-09-05 03:04 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/main_window/styles/StyleFactory.cpp
> +void StyleFactory::applyAutomaticallyChangedColorScheme() {
ОК

2025-09-05 04:01 UTC, DmitriiSukhomlinov commented on src/ugeneui/src/main_window/styles/StyleFactory.cpp
> +    connect(&colorThemeTimer, &QTimer::timeout, this, [this]() {
Сейчас я его попробовал и оно работает, но:
- Идея решения не поменялась - event filter периодически смотрит состояние некоторой системной переменной. Мы делали то же самое, только могли регулировать периодичность - 5 секунд было достаточно, для быстрого обновления, но не слишком часто, event filter же работает в цикле без пауз.
- `WM_SETTINGCHANGE` срабатывает при смене темы с десяток раз. Мы, конечно, обрабатываем это корректно и меняем тему только раз, но все равно лишний триггер присутствует.
- Чтобы установить native event filter пришлось отнаследоваться от QAbstractNativeEventFilter, что излишне на других системах. Я аккуратно выделил наследование и связанный с ним код в `#ifdef Q_OS_WIN ... #endif`, но получилось больше и не так красиво, как с таймером.

Короче говоря, суть решения осталась плюс-минус такой же, но код получился сложнее. Уношу это в отдельный коммит, далее решение за тобой - или остаемся на этом решении, или возвращаемся к таймеру и тогда я просто сделаю `git revert`.

2025-09-05 04:06 UTC, DmitriiSukhomlinov commented
@yalgaer все замечания поправлены

2025-09-07 23:09 UTC, yalgaer commented
По коду осталось вот это замечание: StyleFactory имеет слишком сложный интерфейс: разный на разных платформах.

Ревьюить код на Linux который должен работать на Windows крайне сложно, так как в интерфейсе класса появляются различные функции которые есть на одной системе и которых нет на другой. Класс даже имеет разную иерархию наследования на разных системах.

Как это исправить: 

1) Класс должен иметь один и тот же интерфейс на всех системах

2) Если можно развести платформозависимую логику через C++ (isOsLinux(), isOsMac()..) - надо использовать эту возможность, ifdef только в крайнем случае и только внутри общих функций.

3) Наследоваться для того чтобы получать события не нужно - композиция в данном случае лучше наследования (слишком разные по сути сущности)

4) Если окажется что на какой-то системе функция не нужна - это можно указать комментарием внутри нее. Например: "Эта функция будет вызываться как коллбек только на MacOS" и просто ничего не делать для других систем или добавить SAFE_POINT или FAIL что будет работать только в дебаге

2025-09-08 09:50 UTC, DmitriiSukhomlinov commented
> Класс должен иметь один и тот же интерфейс на всех системах

Имеет. Я улучшил, убрав forMacOs функцию, переместив эту логику внутрь самой функции.

> Если можно развести платформозависимую логику через C++ (isOsLinux(), isOsMac()..) - надо использовать эту возможность, ifdef только в крайнем случае и только внутри общих функций.

Это трудно реализуемое требование. Практически во всех местах единственный вариант обойтись без `#ifdef` - это выносить в общий код то, что необходимо только на одной платформе:

- `#include` - я разнес мак- и вин- функции по `MacStyleFactory` и `WinStyleFactory` соответственно. Они инклудятся в зависимости от системы. `MacStyleFactory` требуется унести в отдельный файл в любом случае, т.к. там Objective-C, `WinStyleFactory` 
- Вызовы функций из инклудов предыдущего пункта. Если я напишу так:
```
    if (isOsMac()) {
        return MacStyleFactory::macIsInDarkTheme();
    } else if (isOsWindows()) {
        return WinStyleFactory::windowsIsInDarkTheme();
    } else {
        return false;
    }
```
То компилятор на Windows не поймет, что `MacStyleFactory::macIsInDarkTheme()` должно компилироваться только на macOS.
- Есть еще такой код:
```
#ifdef Q_OS_DARWIN
    // On macOS this function is triggered on changing color scheme by user too
    CHECK(!colorIsChangedByUser, );
#endif
```
Переменная `colorIsChangedByUser` нужна только на маке и она обвязывается `ifdef`'ом, т.к. это переменная класса и объявлена в `.h`. Если обвязать код `CHECK(!colorIsChangedByUser, );` в `isOsMac()`, то компилятор, опять же, не поймет, что такое `colorIsChangedByUser`. Единственный вариант - уносить в общие переменные для всех систем.
- В функции `StyleFactory::createNewStyle()` та же самая проблема.

> Наследоваться для того чтобы получать события не нужно - композиция в данном случае лучше наследования (слишком разные по сути сущности)

С выражением согласен, но как его тут реализовать, если для того, чтобы прикрутить native filter, нужно использовать `QAbstractNativeEventFilter`, а это абстрактный класс, от которого надо наследоваться? Либо наследуемся на всех системах (хотя, на маке и линуксе это не нужно), либо `ifdef`, третьего не дано.

> Если окажется что на какой-то системе функция не нужна - это можно указать комментарием внутри нее. Например: "Эта функция будет вызываться как коллбек только на MacOS" и просто ничего не делать для других систем или добавить SAFE_POINT или FAIL что будет работать только в дебаге

Вообще все, относящееся к `QAbstractNativeEventFilter`,  в таких комментах и будет, если без `Ifdef`.

2025-09-09 03:30 UTC, yalgaer commented
ifdef не хватило на Linux вылезли Windows типы в 
```
bool StyleFactory::nativeEventFilter(const QByteArray& eventType, void* message, long* result) {
```

Далее, системных событий может быть много. 
Нам нужен только  lParam с  "ImmersiveColorSet"  если не ошибаюсь.

2025-09-09 07:44 UTC, DmitriiSukhomlinov commented
> ifdef не хватило на Linux вылезли Windows типы в `bool StyleFactory::nativeEventFilter(const QByteArray& eventType, void* message, long* result) {`

Поправил.

> Далее, системных событий может быть много. Нам нужен только lParam с "ImmersiveColorSet" если не ошибаюсь.

Добавил ограничение, но все равно много раз прилетает. В целом, насколько я понял, это нормально, да и мы со своей стороны фильтруем, так что не страшно.

2025-09-10 02:17 UTC, yalgaer commented
> Добавил ограничение, но все равно много раз прилетает. В целом, насколько я понял, это нормально, да и мы со своей стороны фильтруем, так что не страшно.

Если интересно можно посмотреть как сделано в Qt6.

2025-09-10 02:18 UTC, yalgaer approved these changes

2025-09-10 03:02 UTC, DmitriiSukhomlinov commented
@yalgaer я рад, что ты заапрувила, но нам нужно разобраться с последним моментом - на [iMac x64 10.12.5 agent 1](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/agent/96) macOS строиться не будет, т.к. темный режим на маке и связанное с ним API появилось только в 10.14. В данный момент, я использую [MacBook-Pro-1-agent-1](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/agent/167) для билда, но, т.к. в основной конфигурации для билда macOS этого агента нет, то мне пришлось сделать отдельный проект для XML/GUI тестирования на маке в Experiments. До мержа в мастер надо решить эту проблему. Опций две:


- Переводим основной билд на маке на [MacBook-Pro-1-agent-1](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/agent/167). **Плюсы**: 
    - Билд не будет мешать GUI тестированию. 
    **Минусы**: 
    - Я часто работаю на этом маке, а билд его сильно тормозит; 
    - У этого мака какая-то проблема с подключением к Ethernet кабелю и он часто отсоединяется, приходится вытыкать и втыкать. Проблема именно физического характера, т.е. можно поставить мак отдельно и не прикасаться к нему, но работать с ним по VNC будет труднее
    - Рано или поздно мы будем делать нативный билд под ARM и билд все равно переедет на M1.
- Переводим основной билд на macOS M1. **Плюсы**:
    - Не задействуем новую машину.
**Минусы**:
    - На маке может быть не больше пяти одновременно авторизованных пользователей, aka агентов. Три уже используюся под GUI тестирование, завести четвертого будет проблемно т.к. тогда на М1 больше одного человека за раз работать не смогут. Поэтому, GUI тестирование немного пострадает в счет времени, которое будет тратиться на билды.

Я бы предложил перевести билд на М1, но окончательное решение за тобой.

2025-09-10 22:47 UTC, yalgaer commented
Сегодня мы поставляем x86_64 билд на маке и строим его на родной системе. На arm он работает в режиме бинарной трансляции.

В варианте перехода на M1 предалагается
1.Работать  в режиме кросс-компиляции:  cобирать билд x86 на саматеме arm? 
2. Или полностью отказаться от x86 и перейти на arm?

Я бы предложила в релизе/тестах перейти полностью на "новую" архитектуру arm и отказаться от поддержки x86 на маке в следующем релизе. Причина: это "новая" архитектура уже довольно "старая". Кажется с 20 или даже 19 года все новые маки идут на arm.

Но это потребует доработки билда/отключение ряда функционала типа SW SSE.

Итого:
1. Если сможешь сделать переход на arm релиз - предлагаю сделать так
2. Если проще поддержать кросс-компиляцию а 1. сложно - пусть будет кросс-компиляция.

Про машину:
Предлагаю билд настроить на обеих машинах. Когда будешь работать на первом маке можешь просто паузить тимсити агента.

2025-09-11 10:00 UTC, DmitriiSukhomlinov commented
> Я бы предложила в релизе/тестах перейти полностью на "новую" архитектуру arm и отказаться от поддержки x86 на маке в следующем релизе.

Если зайти в БД статистики в таблицу `users` и ввести следующую команду:
```
select count(*) from users where os_name="Mac" and cpuArchitecture='x86_64' and gmt >=DATE('2025-09-01');
```

То я получу вот что:

```
+----------+
| count(*) |
+----------+
|     816  |
+----------+
```

Т.е., согласно статистике, у нас было 816 пользвотелей на Mac x86 только с начала месяца. Я не до конца уверен в том, что статистика собирается правильно, но пока не доказано обратное и пока нет четкого представления о том, сколько у нас сидят на x86, а сколько на ARM, убирать x86 нельзя. В конце концов, x86 запускается на ARM, а вот ARM на x86 - нет. Если будет необходим ARM, то я бы предложил либо собирать два пакета (x86 и ARM), либо Universal, который запускается и там и там.

Статистику я проверю и, если там что-то не так, то налажу к ближайшему релизу. Затем, по истечении нескольких месяцев, мы сможем увидеть распределение x86/ARM на macOS и сделать соответствующие выводы. В целом, вопрос перехода на ARM я бы предложилл решать отдельно от этой задачи и после перехода на Qt6, это будет технически проще, т.к. Qt6 уже поставляется под ARM, а Qt5 есть только под x86 и его надо самим собирать.

> Предлагаю билд настроить на обеих машинах. Когда будешь работать на первом маке можешь просто паузить тимсити агента.

Это не очень удобно, поскольку билд уже может идти, а мне нужно что-то сделать, но можно попробовать. Если мне будет сильно мешать, то я всегда могу отключить агента.

Я реализовал это, сейчас все четыре агента доступно для билда. x86 на M1 строится, после билда протестил бандл на маке x86 и все работает.

2025-09-12 01:14 UTC, merged