UGENE-8136 "Exclude enzymes found in the exclude region" incorrect behaviour
ugeneunipro/ugene pull request #1662
Opened 2024-08-21 21:54 UTC by rasputinkirill

@DmitriiSukhomlinov Сделал исправления проблемы из первого сценария.
Во втором там файл неверный похоже, проверь пожалуйста.

2024-08-21 23:09 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    for (const U2Region& excluded : qAsConst(excludeRegions)) {
Вопрос: 

Дано:
если у нас есть exclude regions то мы не включаем в результат ни один энзим с тем же именем который был найден в exclude region.

Что я вижу здесь: 
Ты добавил дополнительную фильтрацию что, найденный энзим не в exclude region по location.

Вопрос:
Почему недостаточно фильтрации чисто по имени? Ведь этот же энзим найдут таски которые создаются в конструкторе для exclude regions и запишут имя этого энзима как "запрещенное"?

2024-08-22 04:44 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    for (const U2Region& excluded : qAsConst(excludeRegions)) {
Если энзим только частично находится в exclude region, то он не найдется в нем.

2024-08-22 20:37 UTC, rasputinkirill commented
Дополнил в соответствии со сценарием 2.
@yalgaer @DmitriiSukhomlinov  
Предлагаю обсудить ожидаемое поведение в сценарии 3 в задаче.
Мне кажется нелогичным выносить управление валидацией полей вовне класса `RegionSelector`, так как он имеет свой валидатор внутри и относительно этого элемента у него данные верны. 
Я бы предложил сделать в самом виджете "Search in" лейбл и в него писать ворнинг, как в FindPattern например.
Если же все таки реализуем первый вариант, то там предлагаю подсвечивать оба поля ввода, так как они оба "неподходящие" относительно друг друга.
Что скажете?

2024-08-23 02:42 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +    for (const U2Region& excluded : qAsConst(excludeRegions)) {
Понятно, тогда ошибка может состоять в том, что ты уже добавил в результат часть энзимов с данным именем и теперь тебе нужно 1) удалить старые 2) не добавлять новые с таким именем.

Далее, энзимы фильтруются ради того, чтобы они резрезали кодирующий (excluded) регион. Точка разреза у каждого энзима это точка - не весь размер энзима.

Если говорить о 100% правильном решении, возможно нужно для каждого энзина расширять/cужать интересующий регион таким образом, чтобы он не делал разреза exclude региона.

2024-08-23 02:47 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            if (it->second != 0) {
Подобный код не читаем без анализа контекста: что значит it->second != 0? 
Нужно дать имя это переменной как тут, так и там где ты пишешь `-1` в эту коллекцию (спец-значение)

2024-08-23 02:49 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            algoLog.info(tr("The following enzymes were found, but skipped because they are presented inside of the \"Uncut area\": %1.")
they are presented -> they were found

2024-08-23 03:04 UTC, yalgaer commented
> Мне кажется нелогичным выносить управление валидацией полей вовне класса `RegionSelector`, так как он имеет свой валидатор внутри и относительно этого элемента у него данные верны.

В данном случае валидация одного региона (региона поиска) зависит от валидации другого региона (exclude региона) и наоборот. 

В итоге валидация должна быть вне этих виджетов, так как выходит за контекст данных каждого из них.

Если это делать реактивную валидацию сложно - просто валидируй разово финальное состояние уже после нажатия кнопки OK и не запускай расчет и не закрывай диалог если настройки в диалоге получились некорректные (выдавай ошибку в message box)

2024-08-23 09:21 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            if (it->second != 0) {
да "-1" неудачное значение, сделал инкремент при нахождении энзима, и теперь excludedEnzymesHits отражает смысл. И вроде теперь ясно без дополнительных комментариев.

2024-08-23 12:48 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +            if (it->second != 0) {
Немного переделал, чтобы эта мапа не использовалась двояко. Теперь эта мапа используется по тому назначению, как и называется. Думаю теперь без комментариев все читаемо и ясно что код делает.

2024-08-27 03:46 UTC, yalgaer requested changes

2024-08-27 03:46 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +int getLeftCutLength(const SEnzymeData& enzyme) {
Добавь static

2024-08-27 03:46 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +int getLeftCutLength(const SEnzymeData& enzyme) {
Плохое имя метода. Лучше назвать getDirectCutOffset и добавить комментарий что это максимальное смещение от начала энзима где может случиться разрез.

2024-08-27 03:46 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +int getRightCutLength(const SEnzymeData& enzyme) {
добавь static

2024-08-27 03:46 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +int getRightCutLength(const SEnzymeData& enzyme) {
То же замечания про имя метода. Нужно добавить от offset в данном случае считается от начала энзима на комплементарном стренде (в обратную сторону)

2024-08-27 03:46 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +                if (excludeRegion.endPos() + rightExtension > seqLength) {
Ты уверен что rightExtension здесь считается с правильным знаком?
В доках написано:
```// starts from the first char in complement strand, negative->right offset```

2024-08-27 03:46 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +                if (excludeRegion.endPos() + rightExtension > seqLength) {
Теоретически при длине круговой последовательности 100 и exclude регионе 10..90 start может уменьшиться на 20 от 10 и стать 90, а end увеличиться на 20 от 90 и стать равным 10 и ты будешь искать в регионе: 90...10  длиной 20 символов что совсем не соответствует начальным 10..90 заданным пользователем.

В приведенном мной примере надо искать во всей последовательности.

2024-08-27 03:46 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.h
> +    QStringList enzymesFoundInExcludedRegion;
Эта штука должна быть Set, иначе имя энзима может повториться

2024-08-27 06:47 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +                if (excludeRegion.endPos() + rightExtension > seqLength) {
> Ты уверен что rightExtension здесь считается с правильным знаком?

Проверил, да.

> Теоретически при длине круговой последовательности 100 и exclude регионе 10..90 start может уменьшиться на 20 от 10 и стать 90, а end увеличиться на 20 от 90 и стать равным 10 и ты будешь искать в регионе: 90...10 длиной 20 символов что совсем не соответствует начальным 10..90 заданным пользователем.

Следующий if вроде как раз для этого. Или я чето не так понял?

2024-08-27 06:50 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +int getRightCutLength(const SEnzymeData& enzyme) {
я добавил комментарии к переменным, но мне кажется названия методов самодостаточные

2024-08-28 02:22 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +                if (excludeRegion.endPos() + rightExtension > seqLength) {
Для примера с моими цифрами  твой код
``` excludeRegion.length = isCircular ? excludeRegion.endPos() + rightExtension - seqLength : seqLength - excludeRegion.startPos;```

Выдаст:
excludedRegion.length = 90 + 20 - 100 = 10

2024-08-28 02:23 UTC, yalgaer commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +                if (excludeRegion.length > seqLength) {
Какой смысл продолжать искать в excluded region если он покрывает 100% последовательности?

2024-08-28 09:26 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +                if (excludeRegion.length > seqLength) {
Останавливаем поиск конкретного энзима и пишем инфо.

2024-08-28 09:26 UTC, rasputinkirill commented on src/plugins/enzymes/src/FindEnzymesTask.cpp
> +                if (excludeRegion.endPos() + rightExtension > seqLength) {
Перепутал длину и конечную позицию.

2024-08-28 20:03 UTC, yalgaer commented
Замечаний нет, апрув после тестов

2024-08-30 09:05 UTC, yalgaer approved these changes

2024-08-30 09:54 UTC, merged