UGENE-7005. Make MA editor minimum font size be aware about current U…
ugeneunipro/ugene pull request #199
Opened 2021-01-17 21:37 UTC by yalgaer

2021-01-18 07:10 UTC, atiunov submitted a review, later dismissed

2021-01-19 14:43 UTC, atiunov requested changes
Add a test for MCA Editor.

2021-01-20 04:53 UTC, yalgaer commented
> Add a test for MCA Editor.

Added

2021-01-20 08:50 UTC, atiunov approved these changes

2021-01-20 23:26 UTC, merged