UGENE-6942. GUI tests for "Variant calling..." main menu item
ugeneunipro/ugene pull request #210
Opened 2021-01-29 10:51 UTC by EvelinaBiserova

2021-02-01 03:27 UTC, DmitriiSukhomlinov approved these changes, later dismissed

2021-02-01 06:50 UTC, yalgaer requested changes

2021-02-01 06:50 UTC, yalgaer commented on src/plugins/GUITestBase/src/GUITestBasePlugin.cpp
> +    REGISTER_TEST_TL(GUITest_common_scenarios_NIAID_pipelines::test_0007, minutes(7), labels({Cistrome, Linux, Windows, MacOS}));
nit: a better solution would be using a test data that can fit Nightly tests requirements. Not a blocker so.

2021-02-01 06:50 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/NIAID_pipelines/GTTestsNiaidPipelines.cpp
> +    bool b = out.removeOne("chrM.sam.bam.sorted.bam") && out.removeOne("variations.vcf");
Why removeOnce but not a simple .contains() ?

2021-02-02 08:13 UTC, EvelinaBiserova commented
Tests pass, comments corrected

2021-02-02 08:34 UTC, yalgaer approved these changes

2021-02-02 10:17 UTC, merged