UGENE-7003. Invalid Python module validation in Windows 10
ugeneunipro/ugene pull request #213
Opened 2021-01-31 11:26 UTC by EvelinaBiserova

Changed Python module validation message

2021-02-01 03:36 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/python/PythonSupport.cpp
> +    const QString pythonVersionRegexpStr = "(\\d+.\\d+.\\d+)";
`static const QString PYTHON_VERSION_REGEXP = "(\\d+.\\d+.\\d+)";`

2021-02-01 03:36 UTC, DmitriiSukhomlinov submitted a review, later dismissed

2021-02-01 07:03 UTC, yalgaer requested changes
This change can be tested with GUI tests
1) Add an executable file to the SVN or create inside of the test. (I would prefer adding to the SVN a file like 'dumb-script.sh/cmd' that can be used to test different external tools
2) In the test ensure that 'UGENE_EXTERNAL_TOOLS_VALIDATION_BY_PATH_ONLY' is not set to "1"
3) Add the 'dumb.sh' as a Python executable.
4) Check that validation fails.

2021-02-02 08:31 UTC, yalgaer reviewed
Everything is OK, please show that the test runs correctly in the Teamcity and I will approve.

+ Looks like you need to merge with master. The h/cpp file with regression test was added in a parallel PR.

2021-02-02 08:31 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +            #ifdef Q_OS_WIN
nit: there is a more readatable API:  toolPath+=isOsWindows()?"a":"b"

2021-02-03 05:08 UTC, yalgaer requested changes

2021-02-03 05:08 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    CHECK_SET_ERR(qgetenv("UGENE_EXTERNAL_TOOLS_VALIDATION_BY_PATH_ONLY") != "1",
You need to reset the variable in the test if it was set externally:
qputenv("UGENE_EXTERNAL_TOOLS_VALIDATION_BY_PATH_ONLY", "0");

2021-02-10 10:33 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +                              GTGlobals::UseMouse);
Offset

2021-02-13 09:39 UTC, EvelinaBiserova commented
@yalgaer, @atiunov anyone want to approve me?

2021-02-13 18:41 UTC, yalgaer submitted a review, later dismissed

2021-02-15 05:31 UTC, yalgaer approved these changes

2021-02-16 03:08 UTC, merged