UGENE-5450 Problem building tree from sample alignment on Windows
ugeneunipro/ugene pull request #247
Opened 2021-02-18 06:12 UTC by rasputinkirill

2021-02-19 04:05 UTC, EvelinaBiserova approved these changes, later dismissed

2021-02-19 04:33 UTC, yalgaer requested changes
This scenario can be covered by UI test.

2021-02-19 04:33 UTC, yalgaer commented on src/corelibs/U2View/src/phyltree/CreatePhyTreeDialogController.cpp
> +    if (FileAndDirectoryUtils::isDirectoryWritable(QFileInfo(msaObject->getDocument()->getURLString()).dir().path())) {
Please cache "msaObject->getDocument()->getURLString()" into a local variable to make code more readable

2021-02-19 07:37 UTC, EvelinaBiserova commented on src/corelibs/U2View/src/phyltree/CreatePhyTreeDialogController.cpp
> +        urlStr = msaObject->getDocument()->getURLString();
Please replace with cached variable `msaObjUrlString`

2021-02-19 08:48 UTC, EvelinaBiserova submitted a review, later dismissed

2021-02-24 06:57 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/phyltree/CreatePhyTreeDialogController.cpp
> +        urlStr = GUrlUtils::getDefaultDataPath() + "/" + msaObject->getGObjectName();
I suggest write a message to log in this case, for example:

`coreLog.details(tr("You have no write access to the \"%1\" directory, the result will be written to \"%2\".").arg(urlStr).arg(path));`

2021-02-24 06:58 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/phyltree/CreatePhyTreeDialogController.cpp
> +        urlStr = GUrlUtils::getDefaultDataPath() + "/" + msaObject->getGObjectName();
Also I think it's better to save result to "data/samples/Newick", not just "data"

2021-02-24 06:59 UTC, DmitriiSukhomlinov requested changes
See comments

2021-02-25 05:40 UTC, EvelinaBiserova reviewed
Please, run GUI Nightly Ubuntu test

2021-03-02 01:24 UTC, yalgaer requested changes

2021-03-02 01:24 UTC, yalgaer commented on src/plugins/GUITestBase/src/GUITestBasePlugin.cpp
> +    REGISTER_TEST_ONLY_WINDOWS(GUITest_regression_scenarios::test_5450);
Why do you register this test on Windows only? Could you please add it to all nightly builds?

Everything else looks good.

2021-03-02 04:08 UTC, EvelinaBiserova approved these changes

2021-03-03 05:41 UTC, closed without merging

2021-03-03 05:41 UTC, rasputinkirill commented
For now this bug isn't reproducable