UGENE-7080. Update CMake build files
ugeneunipro/ugene pull request #260
Opened 2021-02-25 23:49 UTC by yalgaer

2021-02-26 05:34 UTC, EvelinaBiserova commented on CMakeLists.txt
>  add_subdirectory(src/libs_3rdparty/zlib)
Where is qscore?

2021-02-26 06:21 UTC, yalgaer commented on CMakeLists.txt
>  add_subdirectory(src/libs_3rdparty/zlib)
Fixed. Thank you!

2021-02-27 06:56 UTC, EvelinaBiserova approved these changes

2021-03-01 12:03 UTC, DmitriiSukhomlinov requested changes
It's not possible to build UGENE with CMake on Windows now - CMakeList.txt files are configured incorrectly for this OS. Do you want to fix it in this issue of create another one?

2021-03-01 20:46 UTC, yalgaer commented
> It's not possible to build UGENE with CMake on Windows now - CMakeList.txt files are configured incorrectly for this OS. Do you want to fix it in this issue of create another one?

You are right I have never tested Windows so far. I will return to Windows it later, once I will be fully satisfied with the Linux support

2021-03-02 06:09 UTC, merged