UGENE-7116. Unignore GUITest_common_scenarios_shared_db_wd_run_workflow_gui_test_0003 test
ugeneunipro/ugene pull request #303
Opened 2021-03-23 07:59 UTC by EvelinaBiserova

2021-03-23 14:49 UTC, yalgaer requested changes

2021-03-23 14:49 UTC, yalgaer commented on src/ugene_version.pri
> +UGENE_VER_MAJOR=39
This file should not be changed - looks like it is some merge issue.

The patch is is good, I will approve it once you remove this file from the patch.

2021-03-24 05:53 UTC, DmitriiSukhomlinov approved these changes

2021-03-24 06:23 UTC, yalgaer approved these changes

2021-03-24 07:14 UTC, merged