UGENE-6170 Correct names of document formats in two workflow elements
ugeneunipro/ugene pull request #326
Opened 2021-04-05 06:44 UTC by rasputinkirill

2021-04-05 10:23 UTC, DmitriiSukhomlinov approved these changes, later dismissed

2021-04-05 14:48 UTC, yalgaer commented
Looks good to me. Will approve after nightly tests are finished.

2021-04-07 05:56 UTC, smlnkcv reviewed
The "Filter BAM/SAM files" element's';
 It wasn't mentioned in the original issue, but change "Output format" attribute visible value in the same way: format names should be used instead if format IDs.
Actually bam/sam  instead BAM/SAM.

2021-04-08 00:44 UTC, yalgaer commented
Some nightly tests failed with this patch.

2021-04-14 00:14 UTC, yalgaer requested changes

2021-04-14 00:14 UTC, yalgaer commented on src/plugins/workflow_designer/src/library/ConvertFilesFormatWorker.cpp
> +                result[AppContext::getDocumentFormatRegistry()->getFormatById(fid)->getFormatName()] = false;
Dirty code that will be hard to debug. Could you please cache the value into a local var.
Same for all other files in the PR where you use this long expressions.

2021-04-14 00:14 UTC, yalgaer commented on src/plugins/workflow_designer/src/library/ConvertFilesFormatWorker.cpp
> +    for (const QString &formatId : AppContext::getDocumentFormatRegistry()->getRegisteredFormats()) {
Add qAsConst

2021-04-14 00:14 UTC, yalgaer commented on src/plugins/workflow_designer/src/library/FilterBamWorker.cpp
> +            for (const QString &formatId : AppContext::getDocumentFormatRegistry()->getRegisteredFormats()) {
qAsConst

2021-04-14 00:14 UTC, yalgaer commented on src/plugins/workflow_designer/src/library/FilterBamWorker.h
> +    QMap<QString, QString> formatNameIdAssociation;
Please document the field

2021-04-15 23:32 UTC, yalgaer approved these changes

2021-04-16 08:26 UTC, merged