UGENE-4985. Wrong error message is shown when trying to open deleted file
ugeneunipro/ugene pull request #333
Opened 2021-04-08 04:38 UTC by EvelinaBiserova

https://ugene.dev/tracker/browse/UGENE-4985

2021-04-08 05:29 UTC, yalgaer requested changes

2021-04-08 05:29 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_4001_5000.cpp
> +    QFile file(testDir + "_common_data/scenarios/sandbox/A.fa");
Use 1 liner like: Use IOAdapterUtils::writeTextFile(sandBoxDir + "test_6707/file.txt", "Hello!");

2021-04-08 05:29 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_4001_5000.cpp
> +    GTUtilsTaskTreeView::waitTaskFinished(os);
Check that something is changed: an object view is opened or project tree has the document.

2021-04-08 05:29 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_4001_5000.cpp
> +    dialog->button(QMessageBox::Ok)->click();
Can we use: GTUtilsDialog::waitForDialog(os, new MessageBoxDialogFiller(os, QMessageBox::Ok, "text")); here?
If will fail if there is not message box with the expected text.

2021-04-08 05:33 UTC, yalgaer commented
The fix is good, only GUI test can be shortened by using correct utility methods.

2021-04-08 05:57 UTC, smlnkcv reviewed
Add please Russian translation for error message

2021-04-09 16:07 UTC, yalgaer approved these changes

2021-04-10 09:27 UTC, merged