UGENE-7247. Application unexpectedly closed after saving Workflow properties
ugeneunipro/ugene pull request #415
Opened 2021-06-23 10:12 UTC by EvelinaBiserova

https://ugene.dev/tracker/browse/UGENE-7247

2021-06-24 01:13 UTC, yalgaer requested changes

2021-06-24 01:13 UTC, yalgaer commented on src/corelibs/U2Designer/src/wizard/WizardController.cpp
> +WizardController::WizardController(std::shared_ptr<Schema> s, const Wizard *w)
This code does not compile
I would suggest:
1) Use QT variants of the pointers. They have no cross platform/compiler issues.
2) When use std always use std prefix (see move())
3) For any non-primitive type method parameters (even shared structures) use (const Type&).

2021-06-24 04:29 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Designer/src/wizard/WizardController.cpp
> +    : QObject(), schema(move(s)), wizard(w), runAfterApply(false) {
This thing looks a bit strange (I mean, `std::move`) - a bit over-designed or like you don't get the idea of the move semantic. 

It's difficult to explain why it's not really correct, I've tied to text a good comment, but it was very large and complicated in result. The main idea is: do not use `std::move` in this context, just replace your argument `std::shared_ptr<Schema> s` with `const std::shared_ptr<Schema>& s` (and it's better to use `QSharedPointer`)

2021-06-24 04:29 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Lang/src/support/WorkflowIOTasks.cpp
> +      url(u), schema(move(s)), meta(m) {
The same

2021-06-24 04:30 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Lang/src/tasks/SchemaEstimationTask.cpp
> +    : Task(tr("Workflow estimation task"), TaskFlag_None), schema(move(_schema)), meta(_meta) {
The same

2021-06-24 04:30 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Lang/src/tasks/SchemaEstimationTask.cpp
> +    : engine(_engine), schema(move(_schema)) {
The same

2021-06-24 04:31 UTC, DmitriiSukhomlinov requested changes
Use Qt smart pointers and get rid of the move semantic features - it this context it's excessively

2021-06-27 15:19 UTC, yalgaer approved these changes

2021-06-30 10:27 UTC, DmitriiSukhomlinov approved these changes

2021-06-30 11:34 UTC, merged