UGENE-7325. Make the "PCR primer design" tab visible for DNA sequence only
ugeneunipro/ugene pull request #443
Opened 2021-06-30 10:01 UTC by EvelinaBiserova

Tab is invisible to RNA, Amino, raw alphabets.

2021-07-02 08:49 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Gui/src/options_panel/OPWidgetFactory.h
> +
Remove the empty line

2021-07-02 09:03 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +GUI_TEST_CLASS_DEFINITION(test_7325) {
Don't remove this test, but, take an account, that this feature doesn't need cuz it's not finished yet

2021-07-02 09:06 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/PCRPrimerDesignForDNAAssemblyOPWidget.cpp
> +static void makeGroupboxTittleGrayIfDisable(QGroupBox *const gb) {
This function is cut off from everything, It's better to move it to either the `PCRPrimerDesignForDNAAssemblyOPWidget` class or the anonimus namespace. But, as far is this function is used in the only one function, you can just simply define it as lambda.

2021-07-02 09:38 UTC, DmitriiSukhomlinov requested changes
**Scenario:**

1. Open the "ex.fa"file, which is attached to the issue ([link](https://ugene.dev/tracker/secure/attachment/19951/ex.fa)).
2. Open the "PCR primer design"tab.
Expected: the tab is disabled.
3. Change focus to the first sequence
Expected: the tab has become enabled.
4. Click any "Select manually" button and start selecting on the Zoom view of the first sequence.
Expected: the corresponding fields are being changed.
Current: the corresponding fields aren't changed

Also see minor comments

2021-07-06 06:17 UTC, EvelinaBiserova commented
https://github.com/ugeneunipro/ugene/blob/9e5015a6e82696f0f62691f3eff6ba7986094d6f/src/plugins/pcr_primer_design_for_dna_assembly/src/PCRPrimerDesignForDNAAssemblyOPWidget.cpp#L407
This is context dependent. I guess it may happen that while the task is being executed, context may change. I could dispel doubts, but I don't know how to start PCR Primer Design task.

2021-07-06 08:33 UTC, DmitriiSukhomlinov commented
OK, merge it now, I'll report the other issue if some bags will be found

2021-07-06 08:33 UTC, DmitriiSukhomlinov approved these changes

2021-07-06 08:47 UTC, merged