UGENE-7348. Create notification report
ugeneunipro/ugene pull request #479
Opened 2021-07-25 11:29 UTC by EvelinaBiserova

What if backbone is empty?

2021-07-26 09:00 UTC, DmitriiSukhomlinov commented
![Screen Shot 2021-07-26 at 3 59 32 PM](https://user-images.githubusercontent.com/26257527/126962831-9388592a-fd0f-4299-88df-3a3965170e41.png)

There is a too smal font on macOS, please, increase the font size

2021-07-26 09:27 UTC, DmitriiSukhomlinov requested changes
Everything is good, but fix the font size

2021-07-26 09:27 UTC, DmitriiSukhomlinov commented
@yalgaer please review

2021-07-26 10:35 UTC, EvelinaBiserova commented
I will increase font size, but I want to note that on Windows the picture is different, and font I configured looks larger. ![image](https://user-images.githubusercontent.com/39720063/126975517-fa138566-fbda-4829-875a-ba753eb13819.png)

2021-07-26 10:47 UTC, DmitriiSukhomlinov commented
> I will increase font size, but I want to note that on Windows the picture is different, and font I configured looks larger. 

I don't think it's an unsolvable problem, look, for example, at the Sanger report for Windows:
![image](https://user-images.githubusercontent.com/26257527/126976927-23fd1d37-2efa-4523-a1ca-cac448fc014d.png)

and for macOS:
![Screen Shot 2021-07-26 at 5 42 53 PM](https://user-images.githubusercontent.com/26257527/126977089-952ed935-ff17-4509-866c-0405f29c9cb0.png)

Font sizes are pretty the same on both pictures.

2021-07-28 08:20 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +    auto getPairReport = [&](U2Region forward, U2Region reverse, const QString &primerName) -> QString {
I think, it's better to create a separate function - this is too much code for lambda

2021-07-28 08:21 UTC, DmitriiSukhomlinov requested changes
Minor comment

2021-07-30 03:42 UTC, DmitriiSukhomlinov approved these changes

2021-08-02 05:50 UTC, merged