UGENE-7375. Check user forward and reverse primers.
ugeneunipro/ugene pull request #525
Opened 2021-08-14 16:08 UTC by EvelinaBiserova

Added user primers to report.

2021-08-17 05:24 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +        report_ += getForwardPrimerReportResult(backboneSequence, settings.forwardUserPrimer);
Maybe I didn't mention it, but the backbone sequence shouldn't be added to user primers

2021-08-17 05:26 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +                                          {Seq::OtherSeq, tr("Other sequences")} };
`Other sequences in PCR reaction`

2021-08-17 05:26 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +                        "<th>Other sequences</th>"
`Other sequences in PCR reaction`

2021-08-17 05:27 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +    QString report_ = tr("<br><h3>Unwanted connections user primers</h3>");
`Unwanted connections of user primers`

2021-08-17 05:29 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +                                          {Seq::ReverseUser, tr("User reverse primer")},
`Forward user primer` and `Reverse user primer`

2021-08-17 05:29 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +                        "<th>User forward</th>"
The same as [here](https://github.com/ugeneunipro/ugene/pull/525/files#r690046092)

2021-08-17 05:37 UTC, DmitriiSukhomlinov requested changes
Some general comments because I couldn't find the certain lines where they should be placed:
1. I don't have any comments against the general table you have made (with + and -) despite the fact it wasn't described in the issue, but you should add a legend or a description.
2. You shouldn't search hetero-dimers between the same sequences. I mean, that you have searched hetero-dimers between "User forward primer" and "User forward primer" (the same about reverse). 
![image](https://user-images.githubusercontent.com/26257527/129669425-aec66f12-954c-4da2-8256-019972770a75.png)

2021-08-18 08:50 UTC, DmitriiSukhomlinov commented
> Some general comments because I couldn't find the certain lines where they should be placed:
> 
> 1. I don't have any comments against the general table you have made (with + and -) despite the fact it wasn't described in the issue, but you should add a legend or a description.
> 2. You shouldn't search hetero-dimers between the same sequences. I mean, that you have searched hetero-dimers between "User forward primer" and "User forward primer" (the same about reverse).
>    ![image](https://user-images.githubusercontent.com/26257527/129669425-aec66f12-954c-4da2-8256-019972770a75.png)
> 3. Also make it ""Forward user" and "Reverse user" for both lines
>    ![image](https://user-images.githubusercontent.com/26257527/129669639-0150b30f-1dd5-4dde-86f9-9f8fe4c4223e.png)

2)  isn't fixed

2021-08-18 08:51 UTC, DmitriiSukhomlinov commented on src/plugins/pcr_primer_design_for_dna_assembly/src/tasks/PCRPrimerDesignForDNAAssemblyTask.cpp
> +                                          {Seq::RevComplSeq, tr("Reverse complement sequence")},
`Reverse complementary sequence`

2021-08-18 08:51 UTC, DmitriiSukhomlinov requested changes
2) and a  minor comment

2021-08-18 09:00 UTC, smlnkcv approved these changes

2021-08-20 06:28 UTC, closed without merging

2021-12-27 10:42 UTC, EvelinaBiserova commented
#538