Logging and counter for UGENE crash report №24291
ugeneunipro/ugene pull request #584
Opened 2021-09-24 01:55 UTC by rasputinkirill

2021-09-27 05:37 UTC, DmitriiSukhomlinov approved these changes, later dismissed

2021-09-27 07:31 UTC, yalgaer requested changes
See comments

2021-09-27 07:31 UTC, yalgaer commented on src/corelibs/U2Lang/src/support/WorkflowDebugMessageParser.cpp
> +                coreLog.trace(QObject::tr("WorkflowDebugMessageParser.cpp:64 'key' = %1").arg(key));
nit: 
1) tr is not needed in trace() like this
2) use `__LINE__` when you need line number. Or remove the line number: the message is already unique for devs.

2021-09-27 07:31 UTC, yalgaer commented on src/plugins/workflow_designer/src/WorkflowViewController.cpp
> +        GCOUNTER(cvar, "Worklow started with enabled debugger");
Call GCounter::increment() directly. See the code above,

2021-10-11 14:57 UTC, yalgaer approved these changes

2021-10-12 00:46 UTC, merged