UGENE-6696 Remove BLAST, leave only BLAST+
ugeneunipro/ugene pull request #60
Opened 2020-02-07 09:16 UTC by rasputinkirill

2020-02-17 11:49 UTC, atiunov requested changes
Also items related to BLAST should be remove from ToolsMenu class.

2020-02-17 11:49 UTC, atiunov commented on data/cmdline/gene-by-gene.uwl
> -            }
The aliases with descriptions should be restored.

2020-02-17 11:49 UTC, atiunov commented on data/workflow_samples/Scenarios/gene_by_gene_report.uwl
> +wizard {
Restore the indentation.

2020-02-17 11:49 UTC, atiunov commented on src/plugins/external_tool_support/src/blast_plus/FormatDBSupport.cpp
>      //Check that formatDB or makeblastdb and tempory folder path defined
Remove formatDB mentioning from the comment. Also fix a typo in word "temporary".

2020-02-26 07:00 UTC, atiunov requested changes

2020-02-26 07:00 UTC, atiunov commented on data/cmdline/gene-by-gene.uwl
> +                description:"Path of BLAST DB";
"Path to BLAST DB"

2020-02-26 07:00 UTC, atiunov commented on data/cmdline/gene-by-gene.uwl
> +                description:"Type of BLAST output file (using 'XML (-outfmt 7)' by default)";
The default value is 5.

2020-02-26 07:28 UTC, DmitriiSukhomlinov approved these changes

2020-02-26 09:58 UTC, atiunov requested changes

2020-02-26 09:58 UTC, atiunov commented on data/cmdline/gene-by-gene.uwl
> +                description:"Path of BLAST+ DB";
"Path to BLAST+ DB"

2020-02-26 10:01 UTC, atiunov approved these changes

2020-02-26 10:02 UTC, merged