UGENE-3200 Project opens on project closing
ugeneunipro/ugene pull request #617
Opened 2021-11-10 08:29 UTC by rasputinkirill

Modified GUI test preforms absolutely identical check.

2021-11-12 18:34 UTC, yalgaer requested changes
Please remove "TODO", run GUI tests and I will approve

2021-11-12 18:34 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_3001_4000.cpp
>      // TODO: add this check after UGENE-3200 fix
Remove TODO?

2021-11-26 19:57 UTC, yalgaer requested changes
I will approve only after GUI/XML  run

2021-11-30 05:23 UTC, DmitriiSukhomlinov approved these changes

2021-12-02 02:05 UTC, yalgaer approved these changes

2021-12-02 04:49 UTC, merged