UGENE-6689 Row drag and drop action should be treated as a single action in the Alignment Editor
ugeneunipro/ugene pull request #63
Opened 2020-02-12 06:59 UTC by rasputinkirill

2020-02-13 05:59 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_msa/MaEditorNameList.cpp
> +    changeTracker->startTracking(os);
But where's **finishTracking()**?

2020-02-13 06:00 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_msa/MaEditorNameList.cpp
> +        changeTracker = new MsaEditorUserModStepController(editor->getMaObject()->getEntityRef());
You need to free the memory in the destructor

2020-02-13 06:05 UTC, DmitriiSukhomlinov requested changes

2020-02-13 06:05 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_msa/MaEditorNameList.cpp
> +    changeTracker->startTracking(os);
Where's **finish Tracking**?

2020-02-13 06:05 UTC, DmitriiSukhomlinov commented on src/corelibs/U2View/src/ov_msa/MaEditorNameList.cpp
> +        changeTracker = new MsaEditorUserModStepController(editor->getMaObject()->getEntityRef());
You need to free the memory in the destructor

2020-02-17 12:05 UTC, atiunov approved these changes

2020-02-17 12:58 UTC, merged