UGENE-7471 Add the Use ambiguous bases checkbox to In silico PCR
ugeneunipro/ugene pull request #631
Opened 2021-11-22 12:42 UTC by DmitriiSukhomlinov

2021-11-22 23:03 UTC, yalgaer requested changes
Minor comments only. 
The only blocker is that the test does not wait until workflow is finished.

2021-11-22 23:03 UTC, yalgaer commented on src/plugins/GUITestBase/src/GTUtilsPcr.cpp
> +    auto checkBox = dynamic_cast<QCheckBox*>(GTWidget::findWidget(os, "useAmbiguousBasesCheckBox"));
use GTWidget::findCheckBox  or check for null the result of 'dynamic_cast'

2021-11-22 23:03 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +        void run(HI::GUITestOpStatus& os) {
add override

2021-11-22 23:03 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
wait until workflow is finished.

2021-11-22 23:03 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
wait until workflow is finished

2021-11-23 03:39 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/GTUtilsPcr.cpp
> +    auto checkBox = dynamic_cast<QCheckBox*>(GTWidget::findWidget(os, "useAmbiguousBasesCheckBox"));
OK

2021-11-23 03:39 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +        void run(HI::GUITestOpStatus& os) {
OK

2021-11-23 03:41 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
I have waiting one line above

2021-11-23 03:41 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
Same

2021-11-23 03:47 UTC, DmitriiSukhomlinov commented
See comments, tests have been passed

2021-11-23 07:10 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
You need to wait after you run the workflow (first start, next wait for the workflow to finish), not before.

2021-11-23 07:10 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
Same

2021-11-23 07:12 UTC, yalgaer requested changes
Only 1 issue left and without it the test may be flaky: wait until workflow is finished before checking results.

2021-11-24 13:22 UTC, smlnkcv approved these changes, later dismissed

2021-11-29 04:59 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
OK

2021-11-29 04:59 UTC, DmitriiSukhomlinov commented on src/plugins/GUITestBase/src/tests/common_scenarios/pcr/GTTestsInSilicoPcr.cpp
> +    GTUtilsWorkflowDesigner::runWorkflow(os);
OK

2021-11-29 07:49 UTC, yalgaer approved these changes

2021-11-30 05:10 UTC, merged