UGENE-7161 Assert in "Find Groups of annotated regions" dialog
ugeneunipro/ugene pull request #707
Opened 2022-01-14 02:57 UTC by rasputinkirill

2022-01-14 03:42 UTC, yalgaer requested changes
Please check the comments

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +            : PopupChooser(os, QStringList()), pos(_pos) {
nit: use {} instead of QStringList()

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +        virtual void run() override {
nit: do not repeat 'virtual' with 'override'

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +            GTMouseDriver::release();
Remove this release. Independent press/release events must be used with extra care because they may have cross test issues

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +        virtual void run() override {
remove 'virtual'

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +            CHECK_SET_ERR(plusButton, "First plus toolbutton is NULL");
plusButton is never null

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +            QWidget *dialog = QApplication::activeModalWidget();
use GTWidget: getActveModalWidget(os) that is never null

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    QToolBar *toolbar = GTToolbar::getToolbar(os, "mwtoolbar_activemdi");
nit: use auto - do not repeat the type twice

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    CHECK_SET_ERR(toolbar, "Toolbar is NULL");
toolbar is never null

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    QWidget *farButton = GTToolbar::getWidgetForActionTooltip(os, toolbar, "Find annotated regions");
use auto + farButton is never null

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/GUITestBase/src/tests/regression_scenarios/GTTestsRegressionScenarios_7001_8000.cpp
> +    class CustomFiller : public FindAnnotationCollocationsDialogFiller {
Give the class a meaningful name

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/annotator/src/CollocationsSearchAlgorithm.cpp
> +            CHECK(res.length > 0);
this won't build

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/annotator/src/CollocationsSearchAlgorithm.cpp
> +            CHECK(res.length > 0);
Do you really want to return here and skip all other 'items'?

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/annotator/src/CollocationsSearchAlgorithm.cpp
> +        CHECK(nextI > i, );
Same here: what about other items?

2022-01-14 03:42 UTC, yalgaer commented on src/plugins/annotator/src/CollocationsSearchAlgorithm.cpp
> +            CHECK(searchRegion.contains(r), );
Do you really want to return here?

2022-01-14 07:16 UTC, smlnkcv reviewed
Works well, no assert

2022-01-16 07:49 UTC, rasputinkirill commented
About CHECKs, I've just replaced all asserts with them. Because after introduce SAFW_POINT and CHECK we try to get rid with asserts. This file is small, there is no tasks, there is only 'silent' algorithm and there are not so many asserts, so i decided to replace them with CHECKS. 
Do you think it is better to return asserts back?

2022-01-16 18:18 UTC, yalgaer commented
>  Do you think it is better to return asserts back?

Assertions (aka SAFE_POINTS) are not the same as CHECKS
CHECK is an expected situation. It is a 1-line helper that replaces 3 boilerplate if () {} lines
SAFE_POINT (assert) is a bug in the UGENE

The good solution is to replace asserts with SAFE_POINTS and fix the related bugs.
I think you are aware that with CHECKs you only hide the bugs and interrupt the computation (items in the rest of the list are not processed at all)

2022-01-18 16:00 UTC, yalgaer reviewed
This fix looks much better than before. Lets wait until tests before approval.

2022-01-18 16:00 UTC, yalgaer commented on src/plugins/annotator/src/CollocationsSearchAlgorithm.cpp
> +            SAFE_POINT(searchRegion.contains(r), "Items to search in contains nested regions", );
nit: the change the comment to the opposite: item region is not in the search region.

2022-01-18 16:00 UTC, yalgaer commented on src/plugins/annotator/src/CollocationsSearchAlgorithm.cpp
> +            SAFE_POINT(searchRegion.contains(r), "Items to search in contains nested regions", );
same here: change message to the opposite

2022-01-22 01:16 UTC, yalgaer approved these changes

2022-01-22 07:29 UTC, merged