UGENE-5640 Strict consensus algorithm draws an empty space instead of gap if a threshold is too low
ugeneunipro/ugene pull request #797
Opened 2022-03-11 12:19 UTC by DmitriiSukhomlinov

2022-03-13 18:49 UTC, yalgaer requested changes
Please fix the xml test

2022-03-13 18:49 UTC, yalgaer commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmStrict.cpp
> +    double cntToUseGap = double(currentThreshold) / 100.0 * nSeq;
Cast to double is not needed.

2022-03-14 06:44 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Algorithm/src/util_msa_consensus/MSAConsensusAlgorithmStrict.cpp
> +    double cntToUseGap = double(currentThreshold) / 100.0 * nSeq;
OK

2022-03-14 07:23 UTC, DmitriiSukhomlinov commented
I checked an XML test. The result has been changed a bit. This has happened because since I removed the `int` rounding numbers became more accurate. For example, it was a comprising before the fix:
```
int cntToUseGap = int(currentThreshold / 100.0 * nSeq); // 12
int topFreq = freqsByChar[topChar]; // 12
char res = topFreq < cntToUseGap ? U2Msa::GAP_CHAR : (char)topChar; // 12 < 12 => false => (char)topChar
```

But, after the fix it was turned into a:
```
double cntToUseGap = currentThreshold / 100.0 * nSeq; //12.6
double topFreq = freqsByChar[topChar]; // 12.0
char res = topFreq < cntToUseGap ? U2Msa::GAP_CHAR : (char)topChar; // 12.0 < 12.6 => true => U2Msa::GAP_CHAR
```

2022-03-15 07:24 UTC, yalgaer approved these changes

2022-03-15 17:33 UTC, merged