UGENE-7572 QT error in log after cancelling PHY tree creation.
ugeneunipro/ugene pull request #801
Opened 2022-03-16 08:04 UTC by rasputinkirill

2022-03-21 17:45 UTC, yalgaer reviewed
Looks good please fix all builds and run GUI tests.

2022-03-22 04:55 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/ExternalToolRunTask.cpp
> +                algoLog.info(tr("Unable to cancel tool %1 for 10 seconds. Stop it manually by your OS task manager.").arg(toolName));
Wait a bit, you can try to kill it by yourself, just by using [QProcess::kill()](https://doc.qt.io/qt-5/qprocess.html#kill). I'm sure you should try to do it and if you failed, then you text this message to user

2022-03-22 04:56 UTC, DmitriiSukhomlinov requested changes
See the comment

2022-03-23 04:23 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/ExternalToolRunTask.cpp
> +            if (externalToolProcess->state() == QProcess::Running) {
Check here the return value of `waitForFinished()`, not the state

2022-03-23 04:30 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/ExternalToolRunTask.cpp
> +            if (externalToolProcess->state() == QProcess::Running) {
Also, you should check `externalToolProcess->exitStatus()`

2022-03-23 04:31 UTC, DmitriiSukhomlinov commented on src/corelibs/U2Core/src/tasks/ExternalToolRunTask.cpp
> +            externalToolProcess->waitForFinished(10000);
The same checks

2022-03-23 04:31 UTC, DmitriiSukhomlinov requested changes
See comments

2022-03-24 04:03 UTC, DmitriiSukhomlinov approved these changes

2022-03-30 00:12 UTC, yalgaer approved these changes

2022-03-30 00:19 UTC, merged