UGENE-7584 Spidey alignment fails if delete created annotation until …
ugeneunipro/ugene pull request #825
Opened 2022-04-06 08:30 UTC by DmitriiSukhomlinov

…process is finished

2022-04-06 15:50 UTC, yalgaer requested changes
We should avoid showing dialogs/message boxes from within TaskScheduler callbacks: such dialogs stop the event loop - it means that no other tasks are processed while the dialog is shown at all - all tasks are blocked.

Even worse - this may lead to a dead-locks: when a task is waited to be finished inside of the event loop created by a the dialog started in prepare/report/onSubtaskFinished etc..

An acceptable simple solution might be either canceling the task completely or creating a new annotation table with an auto-generated name.

More complex option is to handle the task results outside of the TaskScheduler callbacks: wait for the task to finish and run results processing code (with dialogs) later.

2022-04-08 10:54 UTC, DmitriiSukhomlinov commented
> We should avoid showing dialogs/message boxes from within TaskScheduler callbacks: such dialogs stop the event loop - it means that no other tasks are processed while the dialog is shown at all - all tasks are blocked.
> 
> Even worse - this may lead to a dead-locks: when a task is waited to be finished inside of the event loop created by a the dialog started in prepare/report/onSubtaskFinished etc..
> 
> An acceptable simple solution might be either canceling the task completely or creating a new annotation table with an auto-generated name.
> 
> More complex option is to handle the task results outside of the TaskScheduler callbacks: wait for the task to finish and run results processing code (with dialogs) later.

I agree, fixed

2022-04-09 03:48 UTC, yalgaer requested changes
Minor issues only. Overall the solution is correct.

2022-04-09 03:48 UTC, yalgaer commented on src/plugins_3rdparty/primer3/src/primer3_core/primer3.h
> -  double pair_quality;
Please remove unrelated changes.

2022-04-09 03:48 UTC, yalgaer commented on src/plugins/external_tool_support/src/spidey/SpideySupportTask.cpp
> +            auto documentFilePath = GUrlUtils::getDefaultDataPath() + "/MyDocument.gb";
Please roll the result file name or we can overwrite user data.

2022-04-11 03:38 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/spidey/SpideySupportTask.cpp
> +            auto documentFilePath = GUrlUtils::getDefaultDataPath() + "/MyDocument.gb";
You won't override the user data in any case - even if you write to the existed "MyDocument.gb" and it has an annotation with the same name. There is a point, that you create the same document as a default one.

2022-04-11 03:40 UTC, DmitriiSukhomlinov commented on src/plugins_3rdparty/primer3/src/primer3_core/primer3.h
> -  double pair_quality;
Fixed

2022-04-11 23:04 UTC, yalgaer commented on src/plugins/external_tool_support/src/spidey/SpideySupportTask.cpp
> +            auto documentFilePath = GUrlUtils::getDefaultDataPath() + "/MyDocument.gb";
This is how I see the problem: 

1. You have an existing document that is not added to the project: /var/MyDocument.gb
2. You create the same in-memory document with a new data and add it to the project as 'loaded': /var/MyDocument.gb

What will happen next? 
I bet the newly created document will override the old one and this means a data loss for a user?

2022-04-11 23:04 UTC, yalgaer requested changes
Please check the comment about the document overwrite

2022-04-12 08:39 UTC, DmitriiSukhomlinov commented on src/plugins/external_tool_support/src/spidey/SpideySupportTask.cpp
> +            auto documentFilePath = GUrlUtils::getDefaultDataPath() + "/MyDocument.gb";
Fixed

2022-04-12 23:08 UTC, yalgaer reviewed
Good, will approve after GUI tests.

2022-04-13 10:37 UTC, DmitriiSukhomlinov commented
@yalgaer all tests have passed

2022-04-13 22:14 UTC, yalgaer approved these changes

2022-04-14 03:29 UTC, merged