Multiline view of the MSA editor - UGENE-7042 (epic UGENE-7031)
ugeneunipro/ugene pull request #917
Opened 2022-08-04 08:40 UTC by ichebyki

Stash all commits related to UGENE-7042
See also pull request #831

2022-08-10 22:33 UTC, yalgaer requested changes
See comments: same as in the previous PR (not fixed).
q:
Could you please work with GIT so the older commits keep the original modification dates?
It will simplify reviews a lot.

2022-08-10 22:33 UTC, yalgaer commented on src/corelibs/U2View/src/ov_mca/McaEditorWgt.cpp
> +    connect(refArea, SIGNAL(si_selectionChanged()), statusBar, SLOT(sl_updateStatusBar()));
Use function references for signal/slot connection for all changed cases. This will ensure we have no bugs during the compile time

2022-08-10 22:33 UTC, yalgaer commented on src/corelibs/U2View/src/ov_mca/McaEditor.h
> +    MaEditorWgt* getMaEditorWgt(uint index = 0) const override {
Please replace all uints for indexes to ints in the code. This should be as simple as 'replace-all' in the editor.

2022-09-04 23:17 UTC, yalgaer commented
Closing as inactive. Please re-open when work is resumed.

2022-09-04 23:17 UTC, closed without merging

2022-10-18 07:45 UTC, ichebyki commented
Created new PR #1004, as new branch ugene-7042.11 was created
All commits were stashed to the new one
This PR is closed